### ISSUE TITLE
New forum location

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#1]
I am giving serious consideration to this being the new forum location for CSLA .NET.

Try it out and let me know what you think.

**Comment by rockfordlhotka** [comment]
You can reach the forum administrators by mentioning @MarimerLLC/forum-admins in a post.

**Comment by rockfordlhotka** [comment]
The related thread in the "old forum" is here: http://forums.lhotka.net/forums/t/12897.aspx

**Comment by bboney** [comment]
Rocky,
I like it.  Let's give it a try.
Thanks!
