### ISSUE TITLE
Generic interface in DAL layer for all BO.

### ISSUE THREAD

**Issue by lmsantin** [MarimerLLC/cslaforum#10]
Has somebody tried to use a generic interface in DAL layer for all BO?

```
/// <summary>
/// Interface to be implemented by any business object.
/// </summary>
/// <typeparam name="D">Dto object</typeparam>
/// <typeparam name="I">Info dto object</typeparam>
/// <typeparam name="C">List criteria</typeparam>
public interface IBusinessObjectDal<D, I, C>
{
    List<I> FetchList(C criteria);
    D Fetch(Guid id);
    void Insert(D dto);
    void Update(D dto);
    void Delete(Guid id);
}
```

**Comment by rockfordlhotka** [comment]
At one point I had a sample that showed how to use a custom implementation of IDataReader to do the fetch part of the process. If you can define an interface that'll work universally there's no reason not to do so - other than that any abstraction adds performance overhead.

**Comment by rockfordlhotka** [comment]
Come to think of it, I'm pretty sure that IDataReader sample is included in the code that comes with the _Using CSLA 4: Data Access_ book.

**Comment by lmsantin** [comment]
Rocky we use to have an interface for each object, now I am thinking on having a generic one for all objects.
I use to have this in the DAL for each BO:

	/// <summary>
	/// 
	/// </summary>
	public interface ICategoryDal
	{
		List<CategoryInfoDto> FetchList();
		CategoryDto Fetch(Guid id);
		void Insert(CategoryDto dto);
		void Update(CategoryDto dto);
		void Delete(Guid id);
	}

then in dataportal:

 dalManager.GetProvider< GlobalPortal.Dal.Categories.ICategoryDal >()

If I use the generic interface then I don't need to define one interface for each BO and the change will be in the dataportal:

dalManager.GetProvider< IBusinessObjectDal< CategoryDto, CategoryInfoDto, CategoryInfoCriteria >>("CategoryDal")

You can see the GetProvider has a parameter to receive the DalEf class name because now I can not get it from the Interface type name using " string.Format(TypeMask, typeof(T).Name.Substring(1)); "
