### ISSUE TITLE
Chained business rules & AffectedProperties

### ISSUE THREAD

**Issue by ajj3085** [MarimerLLC/cslaforum#101]
I know when you chain business rules you need to have the outer rule merge its input properties with the inner rules.  Just wondering if the same is try for AffectProperties if both rules have affected properties (each rule affects different properties though).

**Comment by ajj3085** [comment]
To answer my own question, yes, you need to merge AffectedProperties as well.

**Comment by fujiiface** [comment]
@ajj7060 Curious about this; did you have to also remove duplicates from `AffectedProperties`?  The `IsNew` rule within the `2.05 Gateway Rules - ChainedContext` project in the `RuleTutorial` sample solution does not remove duplicates.  It does show merging the `AffectedProperties`, though.

**Comment by jonnybee** [comment]
There is no need to remove duplicates from AffectedProperties. 

The rule engine aggregates AffectedProperties and does a Distinct on the list before returning values.

**Comment by fujiiface** [comment]
Thanks @jonnybee!
