### ISSUE TITLE
override OnSaved - set newObject not working

### ISSUE THREAD

**Issue by swegele** [MarimerLLC/cslaforum#104]
I had assumed this would work:
override the OnSaved Method on my business object where I can change "newObject" to be a newly created one.  But no matter what I still get the original object that was saved and isNew = false;  
So if user calls myObject = myObject.Save()  I want them to get a new one that is freshly created.  This way they can never get ahold of an existing db record for editing.  Its like not allowing transaction edits...only creates.

Here is what I had.

        protected override void OnSaved(BatchTransfer newObject, Exception e, object userState)
        {
            if (e != null)
                base.OnSaved(newObject, e, userState);
            else
            {
                newObject = BatchTransfer.Create();
                base.OnSaved(newObject, e, userState);
            }
        }

Any pointers?  I looked at overriding SaveAsync and my head hurts :-)

**Comment by jonnybee** [comment]
Or consider to change to ObjectFactory. 

Then it is your DAL code that decides on whether to call MarkOld or not and you may even always return a new empty object.

**Comment by swegele** [comment]
@jonnybee  
regarding A - I use Encapsulated Implementation so ObjectFactory is out.
regarding B - I don't know how do override SaveAsync in a way to hand back a new object!  How would you do that?  Since it gives back a Task I didn't know what to do.

**Comment by jonnybee** [comment]
You could still use an ObjectFactory for just that oibject and call into the DataPortal_XYZ method in the business obejct class. 

An override of the SaveAsync would be like this:

      protected override Task<Root> SaveAsync(bool forceUpdate, object userState, bool isSync)
      {
          var root =  base.SaveAsync(forceUpdate, userState, isSync).Result;
          return Task.FromResult(new Root());
      }

**Comment by swegele** [comment]
@jonnybee - so if I am understanding that right, you are basically handing back a Task but it will have the status of "done" or "finished" or whatever?  I guess that makes sense.  That is simpler for me than the ObjectFactory approach.  Even Rocky said in his book that the OF approach downside was an increase in complexity.  I like simple :-)

**Comment by swegele** [comment]
@jonnybee - just tried it and viola!  works beautifully.  Its like a transaction object that should only allow saves of isNew=True.  I handled it previously by not implementing the DataPortal_Update method but that was clunky because it gave the user the impression that they could edit it and they didn't find out until save failed.  This way they never get into that situation.  Thank you!!
