### ISSUE TITLE
WCF configuration

### ISSUE THREAD

**Issue by chatzikk** [MarimerLLC/cslaforum#105]
I am developing a windows form application using CSLA 4.6.200 and I am trying to host the data portal in IIS. I want to use basicHttpBinding. I have created app.config and web.config according to the Data Portal e-book. When I start the application I get the following error:
---------------------------
 Content Type application/soap+xml; charset=utf-8 was not supported by service http://www.xxxxxx.gr/IISHost/wcfportal.svc.  The client and service bindings may be mismatched.
------------------------------------
I would appreciate any help.

**Comment by rockfordlhotka** [comment]
After the book was published the behavior of the client-side data portal was changed to simplify use in the most common scenario. If you set the data portal's DataPortalUrl value then app.config is totally ignored.

As a result, if you want to use app.config settings you must _only_ set the DataPortalProxy value, and then configure your endpoint using the name `WcfDataPortal` (unless you override that name via code).

**Comment by chatzikk** [comment]
Thank you very much for your reply but as this is the first time I implement a configuration like this it is difficult for me to understand the settings I have to include in app.config. The app.config file has the following entries (following the IISHost example):

  <appSettings>
    <add key="CslaPropertyChangedMode" value="Windows" />
    <add key="CslaDataPortalProxy" value="Csla.DataPortalClient.WcfProxy, Csla" />
    <add key="CslaDataPortalUrl" value="http://www.xxxxxxxx.gr:21647/IISHost/wcfportal.svc"/>
  </appSettings>
  <system.serviceModel>
    <client>
      <endpoint name="WcfDataPortal" address="http:/www.xxxxx.gr:21647/IISHost/wcfportal.svc" binding= "basicHttpBinding"  contract="Csla.Server.Hosts.IWcfPortal"/>
    </client>

I would appreciate if you could mention the changes I have to do.

**Comment by chatzikk** [comment]
I just realized that the part of the app.config file is not appearing in my comment. That is why I repeat my previous comment.
   

 \<appSettings>
   \<add key="CslaPropertyChangedMode" value="Windows" />
    \<add key="DalManagerType" value="Atlantis.DataAccess.SQL.DalManager,Atlantis.DataAccess.SQL" />
    \<add key="CslaDataPortalProxy" value="Csla.DataPortalClient.WcfProxy, Csla" />
    \<add key="CslaDataPortalUrl" value="http://www.xxxxxxxx.gr:21647/IISHost/wcfportal.svc"/>
  \</appSettings>

  \<system.serviceModel>
 \<client>
    \<endpoint name="WcfDataPortal" address="http://www.xxxxxxxx.gr:21647/IISHost/wcfportal.svc" binding= "basicHttpBinding"  contract="Csla.Server.Hosts.IWcfPortal"/>
    \</client>
  \</system.serviceModel>

I hope that you could mention the changes I have to do.

**Comment by jonnybee** [comment]
Please read Rocky message!!!!

> If you set the data portal's DataPortalUrl value then app.config is totally ignored.
> 
> As a result, if you want to use app.config settings you must only set the DataPortalProxy value, and then configure your endpoint using the name WcfDataPortal (unless you override that name via code).

So the first thing to do is to remove the setting CslaDataPortalUrl from your app.config!!!

Then - and only then - will CSLA use your configuration for WcfDataPortal.

**Comment by chatzikk** [comment]
It is working now. Thank you very much for your help
