### ISSUE TITLE
Recursive Rule Question

### ISSUE THREAD

**Issue by tsvideo** [MarimerLLC/cslaforum#106]
So guy’s i hope anyone can help me before i go to the bridge ;-)

In our Module to edit the part list of our Rack constructions i have the Problem, that if the user after adding a new assembly (ChildObject a) and at first enter data in the  quantity column the row disappears to Nirwana.

The Object Graph is:

ObjectGraph	Amount (Menge)	Amount Total (MengeGesamt)
HeaderObject		
     ChildObject (a)	5	5
          ChildObject (a.1)	2	10
          ChildObject (a.2)	1	5
     ChildObject (b)	1	1
          ChildObject (b.1)	1	1

CSLA Version is 4.5.601, And we also use Telerik RadTreeListView.
I Don’t know if it is my Code, CSLA or Telerik.

On the Property ‚Amount‘ there is a Rule to Calculate the ‚Amount Total‘, also for the Childs.
If i Add the Positionen Property to the AffectedProperties the Row Disappears, but if i not add the Positionen Property to the AffectedProperties it’s Calculates correct, but the UI (RadTreeListView (Grid)) doesn’t Refresh.

I tried this three variations of the Rule:

First mixed (Target / Property) approach:

private class CalculateMengeGesamtRule : Csla.Rules.BusinessRule
{
    public CalculateMengeGesamtRule(IPropertyInfo mengeProperty)
        : base(mengeProperty)
    {
        AffectedProperties.Add(PositionenProperty);
        AffectedProperties.Add(MengeGesamtProperty);
    }
 
    protected override void Execute(RuleContext context)
    {
        try
        {
            var target = (KonstAuftragPositionChild)context.Target;
            decimal mengeGesamt = target.Menge;
 
            // Rückgabe der tatsächlichen Menge innerhalb des Baumes oberhalb
            if ((target.Parent != null) && (target.Parent.GetType() == typeof(KonstAuftragPositionChildList)))
            {
                var parentList = (KonstAuftragPositionChildList)target.Parent;
 
                if ((parentList.Parent != null) && (parentList.Parent.GetType() == typeof(KonstAuftragPositionChild)))
                {
                    mengeGesamt = target.Menge * ((KonstAuftragPositionChild)parentList.Parent).MengeGesamt;
                }
            }
 
            if (target.MengeGesamt != mengeGesamt)
            {
                LoadProperty(target, KonstAuftragPositionChild.MengeGesamtProperty, mengeGesamt);
                target.MarkDirty();
            }
 
            //Baum unterhalb aktualisieren
            foreach (var position in target.Positionen)
            {
                //position.BusinessRules.CheckRules(MengeProperty);
                position.SetMengeGesamt(mengeGesamt);
            }
 
            context.AddOutValue(MengeGesamtProperty, mengeGesamt);
 
        }
        catch (Exception e)
        {
            throw new Exception(string.Format("Fehler in CalculateMengeGesamt: {0}", e.Message), e);
        }
    }
}
 
Second mixed (Target / Property) approach:

private class CalculateMengeGesamtRule : Csla.Rules.BusinessRule
{
    IPropertyInfo PositionenProperty;
 
    public CalculateMengeGesamtRule(IPropertyInfo mengeProperty, IPropertyInfo positionenProperty) : base(mengeProperty)
    {
        InputProperties = new List<IPropertyInfo>();
        InputProperties.Add(mengeProperty);
        InputProperties.Add(positionenProperty);
 
        PrimaryProperty = mengeProperty;
        PositionenProperty = positionenProperty;
 
        //AffectedProperties.Add(PositionenProperty);
        AffectedProperties.Add(MengeGesamtProperty);
 
    }
 
    protected override void Execute(RuleContext context)
    {
        try
        {
            decimal menge = (decimal)context.InputPropertyValues[PrimaryProperty]; ;
            decimal mengeGesamt = menge;
 
            KonstAuftragPositionChildList positionen = null;
            if (context.InputPropertyValues[PositionenProperty] != null)
            {
                positionen = (KonstAuftragPositionChildList)context.InputPropertyValues[PositionenProperty];
            }
 
            var target = (KonstAuftragPositionChild)context.Target;
            // Rückgabe der tatsächlichen Menge innerhalb des Baumes oberhalb
            if ((target.Parent != null) && (target.Parent.GetType() == typeof(KonstAuftragPositionChildList)))
            {
                var parentList = (KonstAuftragPositionChildList)target.Parent;
 
                if ((parentList.Parent != null) && (parentList.Parent.GetType() == typeof(KonstAuftragPositionChild)))
                {
                    var parentPosition = (KonstAuftragPositionChild)parentList.Parent;
                    decimal parentPositionMengeGesamt = (decimal)ReadProperty(parentPosition, KonstAuftragPositionChild.MengeGesamtProperty);
                    mengeGesamt = menge * parentPositionMengeGesamt;
                }
            }
 
            context.AddOutValue(MengeGesamtProperty, mengeGesamt);
 
            if (positionen != null)
            {
                //Baum unterhalb aktualisieren
                foreach (var position in positionen)
                {
                    //position.BusinessRules.CheckRules(KonstAuftragPositionChild.MengeProperty);
                    position.SetMengeGesamt(mengeGesamt);
                }
 
                //context.AddOutValue(PositionenProperty, positionen);
            }
        }
        catch (Exception e)
        {
            throw new Exception(string.Format("Fehler in CalculateMengeGesamt: {0}", e.Message), e);
        }
    }
}
 
Only Target Variation:

private class CalculateMengeGesamtRule : Csla.Rules.BusinessRule
{
    public CalculateMengeGesamtRule(IPropertyInfo mengeProperty) : base(mengeProperty)
    {
        PrimaryProperty = mengeProperty;
 
        AffectedProperties.Add(PositionenProperty);
        AffectedProperties.Add(MengeGesamtProperty);
    }
 
    protected override void Execute(RuleContext context)
    {
        try
        {
            var target = (KonstAuftragPositionChild)context.Target;
            decimal menge = (decimal)ReadProperty(target, KonstAuftragPositionChild.MengeProperty);
            decimal mengeGesamt = menge;
            var positionen = (KonstAuftragPositionChildList)ReadProperty(target, KonstAuftragPositionChild.PositionenProperty);
 
 
            // Rückgabe der tatsächlichen Menge innerhalb des Baumes oberhalb
            if ((target.Parent != null) && (target.Parent.GetType() == typeof(KonstAuftragPositionChildList)))
            {
                var parentList = (KonstAuftragPositionChildList)target.Parent;
 
                if ((parentList.Parent != null) && (parentList.Parent.GetType() == typeof(KonstAuftragPositionChild)))
                {
                    var parentPosition = (KonstAuftragPositionChild)parentList.Parent;
                    decimal parentPositionMengeGesamt = (decimal)ReadProperty(parentPosition, KonstAuftragPositionChild.MengeGesamtProperty);
                    mengeGesamt = menge * parentPositionMengeGesamt;
                }
            }
 
            LoadProperty(target, KonstAuftragPositionChild.MengeGesamtProperty, mengeGesamt);
 
            //Baum unterhalb aktualisieren
            foreach (var position in positionen)
            {
                position.BusinessRules.CheckRules(KonstAuftragPositionChild.MengeProperty);
            }
 
        }
        catch (Exception e)
        {
            throw new Exception(string.Format("Fehler in CalculateMengeGesamt: {0}", e.Message), e);
        }
    }
}
 
 
 

If Anyone could Help me, i would be very happy !

[CSLA Rule Question.docx](https://github.com/MarimerLLC/cslaforum/files/48749/CSLA.Rule.Question.docx)

**Comment by jonnybee** [comment]
Hi Thilo, 

I would split this into several rules so that the PropertyChanged event goes in the correct sequence. 

I would override ChildChanged on the "grandparent" to to do recalculation on that parent as a separate rule on that object. 

Then simplify the rule to just calculate the sum on the actual object. 

Last - I would override PropertyHasChanged on the actual object and after call to base.PropertyHasChanged (that also makes PropertyChanged events) loop throug the child list and call CheckRules on the MengeProperty. 

I would add this to code in separate steps so that it would be easier to identify which code has a problem - ie introduces these issues. 

As your rule(s) works now you will get PropertyChanged on the child objects before the actual object. This may or may not be problem - I am not familiar with the Telerik UI controls.

**Comment by tsvideo** [comment]
Hi Jonny,
thank you for your Suggestion, i will try it.
Thilo

**Comment by tsvideo** [comment]
Hi Jonny,
your Suggestion solved my Problem. At this Point i can't say what the Problem realy was.
The Simplifying and spliting of the Code works fine. One Problem that i still have is that the changing of MengeGesamt in the Rule doesn't fire the PropertyChanged in the associated child. So i catch this in the OnChildChanged of the grandparent, or did you that mean with your second sentence ?
I had still another Rule with the Problem, but with your Suggestion i solved this too.

So, the way to the Bridge and jump off is unneeded. I'm happy, my Family ist happy and the Users ... ? I don't know ;-)

Thilo

**Comment by jonnybee** [comment]
Hmm, on which associated child do you not get PropertyChanged? 

> Last - I would override PropertyHasChanged on the actual object and after call to base.PropertyHasChanged (that also makes PropertyChanged events) loop throug the child list and call CheckRules on the MengeProperty

Actually - what you should is call <child>.PropertyHasChanged(childType.MengeProperty). That method is proptected (IIRC) so you should create a 
custom methods that does this, ex

    public void RecalcMenge()
    {
    	PropertyHasChanged(MengeProperty);
    }
    
and call thus method from the list when you iterate the children. 

PropertyHasChanged will both run the rules for the given property and raise PropertyChanged events as per config.  

The challenge here is that PropertyChanged will trigger a new hildChanged on the list so you may need to shortcircuit or disable list events somehow.

**Comment by tsvideo** [comment]
On the Child where the Property Menge is changed from the user and the MengeGesamt is recalculated from the rule.

My Rule:
        private class CalculateMengeGesamtRule : Csla.Rules.BusinessRule
        {
            public CalculateMengeGesamtRule(IPropertyInfo mengeProperty) : base(mengeProperty)
            {
                InputProperties = new List<IPropertyInfo>();

                InputProperties.Add(mengeProperty);
                PrimaryProperty = mengeProperty;

                AffectedProperties.Add(MengeGesamtProperty);
            }

            protected override void Execute(RuleContext context)
            {
                try
                {
                    var target = (KonstAuftragPositionChild)context.Target;
                    decimal menge = (decimal)context.InputPropertyValues[PrimaryProperty];
                    decimal mengeGesamt = menge;


                    // Rückgabe der tatsächlichen Menge innerhalb des Baumes oberhalb
                    if ((target.Parent != null) && (target.Parent.GetType() == typeof(KonstAuftragPositionChildList)))
                    {
                        var parentList = (KonstAuftragPositionChildList)target.Parent;

                        if ((parentList.Parent != null) && (parentList.Parent.GetType() == typeof(KonstAuftragPositionChild)))
                        {
                            var parentPosition = (KonstAuftragPositionChild)parentList.Parent;
                            decimal parentPositionMengeGesamt = (decimal)ReadProperty(parentPosition, KonstAuftragPositionChild.MengeGesamtProperty);
                            mengeGesamt = menge * parentPositionMengeGesamt;
                        }
                    }

                    context.AddOutValue(MengeGesamtProperty, mengeGesamt);
                }
                catch (Exception e)
                {
                    throw new Exception(string.Format("Fehler in CalculateMengeGesamt: {0}", e.Message), e);
                }
            }
        }

My PropertyHasChanged:
        protected override void PropertyHasChanged(IPropertyInfo property)
        {
            base.PropertyHasChanged(property);

            if (property == MengeProperty)
            {
                foreach (var position in Positionen)
                {
                    position.CheckPropertyRules(MengeProperty);
                }
            }
        }

My OnChildChanged:
        protected override void OnChildChanged(Csla.Core.ChildChangedEventArgs e)
        {
            base.OnChildChanged(e);

            if (e.PropertyChangedArgs != null && !string.IsNullOrEmpty(e.PropertyChangedArgs.PropertyName) && !e.PropertyChangedArgs.PropertyName.StartsWith("Is"))
            {
                switch (e.PropertyChangedArgs.PropertyName)
                {
                    case "ArtikelNr":
                        OnPropertyChanged("Positionen");
                        break;
                    case "Positionen":
                    case "Farbe":
                        BusinessRules.CheckRules(PositionenProperty);
                        OnPropertyChanged("Positionen");
                        break;
                    case "MengeGesamt":
                        var childPosition = (KonstAuftragPositionChild)e.ChildObject;
                        foreach (var position in childPosition.Positionen)
                        {
                            position.CheckPropertyRules(MengeProperty);
                        }
                        break;
                    case "GewichtGesamt":
                        BusinessRules.CheckRules(MengeProperty);
                        OnPropertyChanged("Gewicht");
                        OnPropertyChanged("GewichtGesamt");
                        break;
                    case "OberflaecheGesamt":
                        BusinessRules.CheckRules(MengeProperty);
                        OnPropertyChanged("Oberflaeche");
                        OnPropertyChanged("OberflaecheGesamt");
                        break;
                }
            }
        }

**Comment by tsvideo** [comment]
The originally Problem was the OnPropertyChanged("Positionen") in the OnChildChanged Event.
