### ISSUE TITLE
How to implement containment?

### ISSUE THREAD

**Issue by lmsantin** [MarimerLLC/cslaforum#107]
I have a class A and a class B, both inherit from BusinessBase.

Class B has a Contained property of type A.
Class B has another property declared as RelationshipTypes.Child and this property is an editable list.

When I call the FieldManager.UpdateChildren(this), the dataportal tries to update the property declared as RelationshipTypes.Child and the Contained property too.

Why the dataportal tries to update the Contained property if it is not declared as RelationshipTypes.Child?

Why the Contained property is considered a child?

How can I implement containment?

**Comment by jonnybee** [comment]
For child properties the default is RelationshipTypes.Child. However as you can see in the code for UpdateChildren the RelationshipTypes flag is not checked.  

There is 2 possible options. This is the code for UpdateChildren: 

    public void UpdateChildren(params object[] parameters)
    {
      foreach (var item in _fieldData)
      {
        if (item != null)
        {
          object obj = item.Value;
          if (obj is IEditableBusinessObject || obj is IEditableCollection)
            Csla.DataPortal.UpdateChild(obj, parameters);
        }
      }
    }

Option A: 
Only callUpdateChild insted af UpdateChildren: 
 
	DataPortal.UpdateChild(PropertyB)

Option B: 
Make PropertyA a managed property but with a private backing field. This way the object is not added to FieldData and UpdateChildren will not find it. 
 
**Option B is the ONLY recommended way for implementing Inter-graph references and Using references. **

You need to have the reference stored in a priivate backing field so that you add 
[NotUndoable] and/or [NonSerialized] to the private field.

This is also described in detail in the "Using CSLA 4 Creating Business Objects" ebook.

**Comment by lmsantin** [comment]
Thank you JonnyBee for your response. I thought that FieldManager.UpdateChildren() will only update objects declared with RelationshipTypes.Child.

Are CSLA team planning to include a RelationshipTypes flag checking inside the FieldManager.UpdateChildren() method in future versions?

**Comment by jonnybee** [comment]
There is no item for this in the current issues list so it is not on the roadmap right now. 

It has been disussed earlier but there is some heave work to do that includes adding a new _fieldDataX in FieldManager for objects that should not be serialized (like to support NotSerializable and NotUndoable) and heavy testing. 

So option B is the recommended way to implement InterGraph and Using referenced.

**Comment by ajj3085** [comment]
@jonnybee Just want to clarify something. You said above that the default relationship type for child objects is child.  Does that mean that even if you don't specify the relationship type in RegisterProperty will still figure out that T is a Csla child?

**Comment by lmsantin** [comment]
Hello ajj3085:
Whether or not you specify the RelationshipTypes.Child in RegisterProperty that property will be updated when the FieldManager.UpdateChildren() is called if the property is an IEditableBusinessObject or IEditableCollection.

The RelationshipTypes.Child is used "is used to specify that a property value represents a reference to a child object".

"The CSLA .NET framework uses this relationship type information to understand that this is a child reference, so it can automatically handle a number of scenarios around n-level undo and object persistence on your behalf."

Page 26
Using CSLA 4: Creating Business Objects
Rev 1.1

**Comment by ajj3085** [comment]
@lmsantin Yes, that's what you stated in the first post.  My question to Jonny is whether it's actually necessary to specify the relationship type in the RegisterProperty call or if Csla will figure it out automatically based on T and set RelationshipType appropriately.  I had thought you had to always explicitly set it or it would be incorrect, but if Csla can figure it out that's one less thing I need to tell people they need to do.  ☺

Apologies for hijacking your thread, but when I saw Jonny's response it got me thinking about it.

**Comment by jonnybee** [comment]
Well, it is inconsistent in the sense that RelationshipTypes.None is the actual default but RelationshipTypes.Child is never checked or used inside CSLA. 

So the default is actually that an property that contains a business object (list or single) is an owning reference. 

I believe (IIRC) that RelationshipTypes.Child was intended to identify a child reference - but it is not used and kept for backward compatibility.

**Comment by ajj3085** [comment]
@jonnybee Great, thanks for the info.  I'll pass it along to my team.  Maybe an Obsolete attribute could be slapped in the Child value to communicate that.

**Comment by lmsantin** [comment]
@ajj3085 no problem, your comments are welcome.
