### ISSUE TITLE
Child objects related to logged in user

### ISSUE THREAD

**Issue by ipankiv** [MarimerLLC/cslaforum#109]
Hi all.
I'm completely new to CLSA.NET and I have simple question related to data fetching.
Imagine that I have 2 different users with the same role, let it be "student" role.
Each student have some related data, for example lessons schedule.

What is correct way to restrict one student not to see other student schedule?
I want to use authorization rules, but I don't know correct way to implement them.

Also I see two possible options here.
One is to store info about logged in user in Csla.ApplicationContext.User (I mean store more than username) and in Schedule->DataPortal_Fetch code something like this

Dal.SelectSchedules((CustomIdentityWithID)Csla.ApplicationContext.User).UserID);

Another option is to create "LoggedInStudent" business object with child "Schedules" object.
That "LoggedInStudent" will handle all ID stuff and will populate "Schedules" in correct way.

Second options seems more elegant to me, but it will get more different with another roles.
For example if I have not only "Student" role, then I should created "LoggedInAnotherRole" and that another "LoggedInAnotherRole" may have different interface than "LoggedInStudent".

So the main question is
"What is correct way to restrict one user not to get data related to another user?"

**Comment by jonnybee** [comment]
You do not want to use AuthorizationRules for this scenario. 

Static (root level) AuthorizationRules is typically used to determine if a user is allowed to Create/Fetch/Update/Delete a certain type. 

Property level AuthorizationRules is used to determine is a user is allowed to view or edit a property value or execute a method. 

Here you should make sure to fill the criteria object by some custom logic or do the necessary lookup in your data access (like - from a given username - find the userid - and use this in further data access).

**Comment by ipankiv** [comment]
Thank you for your answer.
So basically I should make decision about what to get in "Schedules" business object.

For example
[Serializable]
public class Schedules : BusinessBindingListBase<Schedules, Schedule>
{
    public static Schedules GetAll()
    {
        if(Csla.ApplicationContext.User.IsInRole("Student"))
        {
              //handle student
              var studentId = GetIdByUserName(Csla.ApplicationContext.User.Name);
              return DataPortal.Fetch<Schedules>(studentId);
        }
        else
        {
              //handle others
              //...
        }
    }
    
    private void DataPortal_Fetch(int studentID)
    {
       var Schedules = DALSchedules.SelectAllByStudent(studentID);
       foreach (var item in Schedules)
       {
           Add(DataPortal.FetchChild<Schedule>(item));
       }
    }
}

Then if I login in as studentA and call Schedules.GetAll() I will get the schedules only for studentA, if I login as studentB then only for studentB.

My doubts about this approach is "handle others" section. It may be very complicated if I have a lot of roles.

So is this normal in CSLA world, or maybe I misunderstood your answer?

**Comment by jonnybee** [comment]
You should ask yourself whether this is the same object not. 
Does it follow the Single Responsibility Pattern? 
Will it be the same validation / authorization rules? 

You could have a 
ScheduleList              - Only available for users with role Student
TeacherScheduleList - Only available for users with role Teacher 

This will match well with the authz rule system - you would still need to have the IDs as parameteres. 

Note: You may also consider to look into having different criteria objects and separate DataPortal_XYZ methods with different objects as parameters.

**Comment by ipankiv** [comment]
Thank you for your answers!
