### ISSUE TITLE
Reloading a Lazy-Loaded Property

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/cslaforum#114]
Let's say I have a property called `Description` that is `string`-based. It's read-only, and based off a LINQ query on a list. This is "old" code in that it doesn't use the `PropertyInfo<>` backing fields, and that's what I'm updating it to. So what it currently looks like is this:

```
public string Description
{
    get { return someList.FirstOrDefault(...).Description; }
}
```

Now, I could make that a lazy-loaded property, but the problem is that the query is based on a property value on the object (a status enumeration) that can change. So if that changes, it'll affect the `Description` value.

So what I want is a lazy-loaded property so that I don't do the calculation if no one ever accesses the property getter, but if the dependent property changes, the `Func` that the lazy-loaded property is based on will change.

Anyone have any ideas on how to do this?

**Comment by rockfordlhotka** [comment]
Have another `private bool` property that indicates whether the dependent property has changed, and set that property value from a rule associated with the dependent property?

**Comment by jonnybee** [comment]
Well - it could be done by a PropertyRule that has  
- CanRunInCheckRules
- CanRunAsAffectedProperty
- CanRunOnServer

all set to false.

Or - you could just override PropertyHasChanged and reset the flag there.
