### ISSUE TITLE
Localization of BusinessRules Messages

### ISSUE THREAD

**Issue by rubenrovira** [MarimerLLC/cslaforum#117]
Hi, I am using CSLA 4.6 and WinForms and I have a problem with Localization of the BusinessRules MessageText.

The UI is ready to switch between en-US (english) and es-AR (spanish) language at any time.

If having the UI CurrentCulture = en-US I create a new business Object X, all it messagetext where "loaded" in english
After that, if UI CurrentCulture is changed to es-AR and then, I create a new business object of the same class (X), the messagetext remains in english but if I try to create another business object of class Y not used before, the messagetext will be loaded in spanish

Its like there is a cache of business object mesaggetext and I could not find where this cache is placed.

Is there any way to clear all those messages when the user change the UI language in order to load all of them again from the correct resources file?

regards

**Comment by rockfordlhotka** [comment]
Are you having trouble with the message text, or with the property name?

The property name is cached and there's an existing issue to look at a resolution to this problem: https://github.com/MarimerLLC/csla/issues/344

But the message text for rules is contained in your rule implementation. As a result, when you set the error result in your rule you should use a resource manager to get the value from your resx file(s).

**Comment by rubenrovira** [comment]
The problem is in the MessageText, I will try to explain better myself

In the BO, I add a rule this way

BusinessRules.AddRule(new LessThan(DateFromProperty, DateToProperty) { MessageDelegate = () => Resources.LessThanMessage});

I have two resources files, One called Resources.resx and another Resources.es-AR.resx

Both of them define the entry LessThanMessage

The first time I create the BO in the UI.WinForms using English, I got the message from the Resources.resx, but if then I changed the UI CurrentCulture to Spanish and try to create the same BO, I got the MessageTexts in English too.

The resources files are OK, because if I try the same first in Spanish and then switch to English I got always the messagetext in spanish.

**Comment by rubenrovira** [comment]
If you want Rocky, I could attach a little sample app in order to be more clear in my explanation

**Comment by rockfordlhotka** [comment]
That would be helpful, thank you.

**Comment by jonnybee** [comment]
I wrote a test app myself and everything works as expected. I do not get the behavior that you describe. So please post a sample app to demonstrate this.

**Comment by rubenrovira** [comment]
Hi Rocky / Jonnybee! Thanks about you messages

Sorry about closing and reopen the thread, it was my mistake!

I am attaching a little project were I reproduce the problem I am having with messagetext localization

Please, change the extension from PNG to ZIP. I could not upload the file as ZIP so I decided to change it extension to PNG.

I used VS2012 and CSLA 4.6 to develop it

In order to run the test app, just click on Step 1 and Step 2 without close the main form. Check the error messages in the Child form. I added a messagebox in the AddBusinessRules method in order to show that this method is executed just the first time I created the BO. As in this method are the messagetext definition, I supposed that there is the cause of the no translation issue

Sorry about my english

best regards


![localizationtest](https://cloud.githubusercontent.com/assets/13245594/12217064/5971ae9c-b6d3-11e5-86c9-8c901a33cd53.png)

**Comment by jonnybee** [comment]
I don't think you should set Resource.Culture - especially in AddBusinessRules method which is only called once per type. Resources should be fetched as per the CurrentThread.CurrentUICulture.

I made some changes and it works just as I expected. Se my attached file and rename from png to zip.

![localizationtest](https://cloud.githubusercontent.com/assets/3512406/12217871/9355d22e-b70e-11e5-8ed7-0eb73fed9021.png)

**Comment by jonnybee** [comment]
You have a logical error in your code here.
The ctor where you create the BO instance (and validation is called) is executed before  the Load event where you set the Resources.Culture. 

When you set the Resources.Culture your code actually override the culture to use. 
Normally the CurrentThread.CurrentUICulture is used to select the localized resource.

	public partial class BOForm : Form
    {
        public BOForm()
        {
            InitializeComponent();
            bOBindingSource.DataSource = BO.New();
        }

        private void BOForm_Load(object sender, EventArgs e)
        {
            Resources.Culture = System.Threading.Thread.CurrentThread.CurrentCulture;

            label1.Text = Resources.CodeLabel;
            label2.Text = Resources.NameLabel;
        }
    }

So the second time you call the form is shows the correct resources texts for broken rules.

My recommendation is to not set the Resources.Culture and only set cultures on the CurrentThread.

**Comment by rubenrovira** [comment]
Thanks Jonnybee!

Following your tips I can put my code to work. I really appreciate your explanation and the time you expend to help to me.

Just one more thing. You encourage me to consider to use the builtin translation in Windows Forms Designer. As far as I know, that create a resource file per form but as in my solution I have many forms that use similar text to translate (Code, Name, Address, Phone, Email, etc), I found it a little repetitive.

**Comment by jonnybee** [comment]
There is several issues: 
a) languages have different number of words - one word in one language may have several words (ie require more than one translation)  in another language based on context.
b) some languages are more verbose then others and once translated the label/control may not be large enough to display it and so the controls size must also be changed. 
c) some languages are right to left, most are left to right. 

If you do not need it for the languages you must support then fine - but if you should need it be aware that many control properties are "localizable" and can be adjusted in the WinForms Designer.

**Comment by rubenrovira** [comment]
You are right! It is really better to have all those properties localizable.

I will close the issue. Thanks again Jonnybee!!
