### ISSUE TITLE
Updating CSLA license

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#122]
I am strongly considering switching CSLA from its current open source (but one-off) license to a standard OSS license ~~such as MS-PL~~ such as MIT.

I do not believe this will impact anyone except in a positive way.

The new license will grant at least as many rights to you as the current license. The primary difference is that the current license includes a clause restricting you from taking CSLA and repackaging it into a "CSLA competitor". 

I think the odds of anyone doing that today are small, and I think the value to everyone of using a standard OSS license outweighs the minor protections my existing license provides me.

It is also important to understand that this new license will affect the version where I make the change and into the future. So there will be _absolutely zero_ impact on any existing versions of CSLA - they will continue to be available under the existing license. 

To get the new license people will need to upgrade to the new version of CSLA, and to avoid the new license people will just need to never upgrade to a newer version of CSLA.

**Comment by scottt732** [comment]
Out of curiosity, why are you leaning towards MS-PL as opposed to Apache 2.0 or MIT?

**Comment by rockfordlhotka** [comment]
Apache 2.0 is also in consideration. I do want to retain attribution in the license - call me vain :)

**Comment by rockfordlhotka** [comment]
Digging further, the MIT license also requires attribution, so that might be the best option - thanks for the input @scottt732 .

**Comment by rockfordlhotka** [comment]
For reference: http://opensource.org/licenses/MIT

**Comment by justinmchase** [comment]
:+1: MIT for being refreshingly simple.

**Comment by tfreitasleal** [comment]
CslaContrib will also use the MIT license?

**Comment by rockfordlhotka** [comment]
Not necessarily, what do you think ?

**Comment by tfreitasleal** [comment]
I think I should have checked what's the actual CslaContrib license before making comments about the subject. It turns out that CslaContrib project is using the MIT license since 10-06-2015.

**Comment by GillesBer** [comment]
Using a standard license would ease further adoptions. MIT is good to be well recognized and simple/short.

**Comment by ajj3085** [comment]
I think MIT is the way to go, personally.

**Comment by rockfordlhotka** [comment]
I updated the OP to reflect that MIT is the likely candidate at this point.

**Comment by rockfordlhotka** [comment]
I'm hearing only positives on this, so I'll be changing the license to MIT.
