### ISSUE TITLE
Business object inheritance

### ISSUE THREAD

**Issue by ConstantinPatak** [MarimerLLC/cslaforum#134]
Hello,

I am having a class with name BaseBO that inherits from the BusinessBase<T> and another class with name DerivedBO that I want to derive from the BaseBO class. My questions are the following:
1) How do I register the properties from the DerivedBO?
2) Is there something that I might be concerned of? Do I have to abandon this design?

Thanks in advanced

**Comment by jonnybee** [comment]
1. Same way as you register properties in your BusinessObject
2. Be aware of a the coupling you get as changes in base classes _may_ affect the derived BO (think trying to add a property with the same name a derived class) and also might break the single rsponsibility pattern. IIRC: you can only register rules/affected properties(input properties on properties that is registered within the SAME class. 

For my preference - I prefer to add methods, overloads and f.ex logging / DI in the base class. And try to avoid defining BO properties in base class.

**Comment by ConstantinPatak** [comment]
Hi Jonny,

Thanks for your response. I tried to register the properties with different approaches and I failed. In more detail, lets say that the DerivedBO need to extend the BaseBO class by adding the Name property:
1) Tried to use the: public static readonly PropertyInfo<string> NameProperty = RegisterProperty<string>(c => c.Name); But because the BaseBO inherits from the BusinessBase<BaseBO> the lambda expression could not recognize the Name property.
2) Tried to use: public static readonly PropertyInfo<string> NameProperty = RegisterProperty<string>(NameProperty); But this approach throws an exception.
3) Tried to use: public static readonly PropertyInfo<string> NameProperty = RegisterProperty<string>(typeof(DerivedBO), NameProperty); But this approach doesn't register my property.

Can you give an example of the approach you suggest?

Thanks

**Comment by jonnybee** [comment]
All your base classes must be generic classes. Only the "last" level can be non-generic. 


    [Serializable]
    public class BaseBO<T> : BusinessBase<T> where T:BaseBO<T>
    {
        public static readonly IPropertyInfo Name1Property 
            = RegisterProperty<string>(c => c.Name1);

        public string Name1
        {
           get { return GetProperty<string>(Name1Property); } 
           set { SetProperty<string>(Name1Property, value);}
        }
    }

    [Serializable]
    public class DerivedBO<T> : BaseBO<T> where T : DerivedBO<T>
    {
        public static readonly IPropertyInfo Name2Property
            = RegisterProperty<string>(c => c.Name2);

        public string Name2
        {
            get { return GetProperty<string>(Name2Property); }
            set { SetProperty<string>(Name2Property, value); }
        }
    }

    [Serializable]
    public class MyBO : DerivedBO<MyBO>
    {
        public static readonly IPropertyInfo Name3Property
            = RegisterProperty<string>(c => c.Name3);

        public string Name3
        {
            get { return GetProperty<string>(Name3Property); }
            set { SetProperty<string>(Name3Property, value); }
        }
    }

**Comment by ConstantinPatak** [comment]
Is there a way to make the DerivedBO class to derive from the MyBO directly and also be able to register the DerivedBO properties, because what I am trying to achieve is to create a List<MyBO> and be able to add both MyBO and DerivedBO instances by using polymorphism.

**Comment by jonnybee** [comment]
The short answer is No. 

You may have the each object in the list implement an Interface and use the properties from that interface in f.ex a grid. 

Look at the \Samples\NET\cs\Polymorphism sample for Csla.

**Comment by ConstantinPatak** [comment]
Thanks Jonny

**Comment by JasonBock** [comment]
Is this what you're looking for?

http://dotnetbyexample.blogspot.com/2010/08/fixing-clsa-property-registration.html

Regards,
Jason

**Comment by jonnybee** [comment]
The post from 2010 shows an alternate way for registering properties when the base class is a non-generic class. I prefer to keep the base classes as generic base classes.

**Comment by ConstantinPatak** [comment]
Thanks Jason it was exactly what I was looking for and it works.
