### ISSUE TITLE
Required property conditional on another property not null.

### ISSUE THREAD

**Issue by jchabot1979** [MarimerLLC/cslaforum#14]
How to set a Required Rules conditionnal on another property? I want the RequiredRule to Raised the ValidateOnDataError on my control only when another Property is not null. 

Thanks a lot.

**Comment by jonnybee** [comment]
For this example say Property1 is required only when Property2 is not null. 

There is 2 parts involved:


1. tell rule engine to rerun rules for Property1 when Property2 is changed
2. make the validation for Property1 check if Property2 is not null before Reuired rule is executed

a: Add a Dependencies rule like this

    BusinessRules.AddRule(new DependencyRule(Property2PropertyInfo, Property1PropertyInfo);

b: I prefer to use a ShortCircuiting rule to just stop rule engine from advancing to next for these types of rules. This is easily done by using the RulePriority to control the sequence of rules for the given property. You could also create a Gateway rule that wraps the RequiredRule. 

    public class StopIfInputPropertyIsNull : PropertyRule
    {
        private readonly IPropertyInfo _dependentProperty;

        public StopIfInputPropertyIsNull(IPropertyInfo primaryProperty, IPropertyInfo dependentProperty)
            : base(primaryProperty)
        {
            _dependentProperty = dependentProperty;
            InputProperties.Add(dependentProperty);
        }


        protected override void Execute(RuleContext context)
        {
            var value = context.InputPropertyValues[_dependentProperty];
            if (value == null)  // shortcircuit when Property2 is null
            {
                // true tells rule engin to stop and run next rules for this property
                context.AddSuccessResult(true);  
            }
        }
    }

usage: 

    BusinessRules.AddRule(new StopIfInputPropertyIsNull(Property1PropertyInfo, Property2PropertyInfo) { Priority = -1});
    BusinessRules.AddRule(new Required(Property1PropertyInfo);

The default value for Priority is 0. The rule engine will execute rules per property in ascending order.  

I also recomment to look at the various rules in the $\Samples\NET\cs\RuleTutorial sample.
