### ISSUE TITLE
Clarification of business rule calculation design

### ISSUE THREAD

**Issue by hurcane** [MarimerLLC/cslaforum#144]
I have read some conflicting information regarding business rules that do calculations, and am looking for some input into a specific situation I am dealing with. I am still in the concept research phase for the current version of CSLA. I have used CSLA 3.0 (no managed properties) extensively in previous projects.

The user is recording shipping information for an order. When the freight terms are collect, we need to retrieve the recipient's account number, which needs to know the "carrier" and the "recipient".

The "carrier" is semi-transparent to the user. They are selecting from a list of shipping methods (UPS next day air, UPS ground, FedEx ground, Joe's Trucking Company, etc.).

In the Using CSLA book on creating business objects, page 89 of revision 1.1 has an example of a calculated business rule where the Value1 and Value2 properties are added to calculate a total in the Value3 property. The example mentions implies associating the business rule with Value1 as the primary property. 

Our particular use case, when we try to apply it using the example from the book, has caused much debate on our team. One of the problems we have been struggling with is the relationship of the ship method to the carrier. We want to set the recipient's account number when the ship method changes, but not if the old and new ship methods are for the same carrier.

We have also had debates about the primary properties for the rule. Do we assign it to each property that is mutable (recipient, ship method, terms), or should it be assigned to the result property (account number), and let dependencies govern running the rule? If we use the result property, how do we deal with the scenario where the ship method changes, but we don't really want to execute the account number calculation if the related carrier hasn't changed.

In searches of the old and current forums, I have found a couple more statements about design that seemed relevant. Unfortunately, I didn't save the links when I found them, and now I am having trouble finding them again. Hopefully, I will paraphrase them properly without misconstruing their intent.

I read a statement by Jonny Bekkum that mentions that calculation rules should be associated with the calculated value. I read a statement by Rocky that business objects should have the properties they need to do their work, and should not necessarily be just based on what the UI will look like.

Considering these two statements, I am considering the following design:
- _Properties needed for the business user:_ Recipient, Freight terms, Shipping method, Collect account
- _Properties needed only for internal use:_ Freight carrier

I would use two calculation rules:
- SetCarrierFromShipMethod
  - PrimaryProperty: Freight carrier
  - InputProperties: Shipping method
- SetCollectFreightAccount
  - PrimaryProperty: Collect account
  - InputProperties: Recipient, Freight terms, Freight Carrier

When the shipping method is changed, it will set the carrier. If the carrier changes, it will trigger setting the collect account. I am assuming that the carrier property is smart enough to detect that the value is not really changing. If that assumption is false, then I could add the Carrier to the input properties and use to conditionally add the output value.

To sum everything up...

Does this design fit with the way business rules are meant to work? What other considerations might I be overlooking?

Where can one find more information about designing rules for the real world? I am usually pretty good at Google-Binging for information, but this has been a difficult quest.

**Comment by jonnybee** [comment]
Would you be able to post a sample project to highlight the issues? 

I reccomend to read my blogposts on the rule engine:
https://jonnybekkum.wordpress.com/2011/08/29/csla-4-2-rules-update/ 
https://jonnybekkum.wordpress.com/2012/11/07/csla-4-5-ruleengine-update/
https://jonnybekkum.wordpress.com/category/csla/business-rules/

**Comment by jonnybee** [comment]
The key issues to have in mind is:
I default mode the rule engine will check rules when a property value is changed using this semantic:  

1. first check rules where property == rule.PrimaryProperty
- then cascade and recheck rules for (aggregate of AffectedProperties + rules where PrimaryProperty is an InputProperty). These rules are only checked and nor further cascade is done!! There is no check for whether the property value in affected properties was actually changed. 


- For async rules triggered in first run the affected properties will be rerun without cascade.
- For async rues triggered in second run there is no extra validation (or cascade) of affected properties. 

In advanced mode (CascadeOnDirtyProperties) the rule execution will cascade down as long as the property values is changed. This may cause infinite loop and exceptions.

For async rules I prefer to inherit from PropertyRule as this allows me to control when the rule engine is allowed to execute the rule by setting these properties: 

- CanRunInCheckRules	       
- CanRunAsAffectedProperty	      
- CanRunOnServer
