### ISSUE TITLE
[Question] - ObjectFactory and child collections

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/cslaforum#146]
It has been a long time since I have worked with CSLA, and I have managed to confuse myself trying to implement the `ObjectFactory` approach.

I have a root business object, which has a child collection (`BusinessListBase`) exposed as a property.

The [ObjectFactory] attribute is applied to the root business object, and I have implemented a fetch method on the object factory, which not only creates the root, but also is responsible for creating the child list etc.

That has all been working fine, until I started binding the child list (via the property on the root business object) to a UI, and attempting to "Add New Item" to the list.

When I call `RootBo.ChildListProperty.AddNew()` to add a new child item to the list, this throws a `TargetInvocationException`

It seems in my child list, I need to override `AddNewCore()` and create the new business object instance.

This is where I am confused, in order to create a new item to add to the list, let's say there are some default values required from the server, so basically I need to defer to `DataPortal.Create()` right?

```
 protected override ChildListItem AddNewCore()
        {
            //base.AddNewCore();
            var child = Csla.DataPortal.Create<ChildListItem>();
            return child;
        }

```

However, there is no `ObjectFactory` attribute on `ChildListItem` so how will the `DataPortal` know which method to invoke on the server?

The guidance I have seen says that you shouldn't be creating individual `ObjectFactory`'s for child objects, therefore I am guessing perhaps I need to still add the `ObjectFactory` attribute to the Child object, but pointing at the root object factory?

```
  [ObjectFactory(typeof(MyRootObjectFactory))]
```

But in that instance, as the `Create()` method doesn't take any arguments, how can a single `ObjectFactory` have multiple `Create` methods, that just differ by return type? It can't!

So at the moment, I am left with the conclusion that creating individual `ObjectFactory` for child objects is necessary!

Guidance appreciated!

Cheers

**Comment by jonnybee** [comment]
I you need to go to the server for default values the you must handle this similar to LazyLoadedChild objects. Meaning:
- Add ObjectFactory attribute to the child class
- override AddNewCore
- And use DataPortal.Create<ChildListItem> in AddNewCore
As it is only the "root" dataportal calls that will be transferred to the server in N-Tier configuration.

**Comment by dazinator** [comment]
@jonnybee Thanks, that's what I have done for the time being, glad to see that this is the correct route to take.
Many Thanks.
