### ISSUE TITLE
Async Business Rules firing in DataPortal_Fetch

### ISSUE THREAD

**Issue by bradtwurst** [MarimerLLC/cslaforum#148]
Good day.

I am using csla 4.6.2 in a wpf-based application communicating with a wcf-based data portal on a server.

I have an issue with a business object throwing an exception during the DataPortal fetch operation.

The business object has the following code:
```C#
        public static BizObject Get(string fileName)
        {
            var t = DataPortal.Fetch<BizObject>(fileName);
            return t;
        }

        [RunLocal]
        protected override void DataPortal_Fetch(string fileName)
        {
            var reportDOC = XDocument.Load(fileName);
            LoadCriteriaXElement(report); // <-- this method sets the properties in the B.O. from the xDoc (including MyBizProperty)
        }

       protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
            BusinessRules.AddRule(new MyBizRule(MyBizProperty));
        }
```

The business rule object: 
```C#
public class BizRule : Csla.Rules.BusinessRule 
{ 
  public BizRule(Csla.Core.IPropertyInfo primaryProperty) 
    : base(primaryProperty) 
  { 
    InputProperties.Add(primaryProperty); 
    IsAsync = true; 
  }

  protected async override void Execute(Csla.Rules.RuleContext context) 
  { 
     var cmd = new CheckEntryCommand();
     cmd.CheckValue =  (string)context.InputPropertyValues[PrimaryProperty];
     cmd.ReturnValue = "";
     cmd = await DataPortal.ExecuteAsync<CheckEntryCommand>(cmd);
     if (cmd.ReturnValue.IsBlank())
     {
         context.AddErrorResult("Invalid Entry");
     } 
     else 
    {
         context.AddOutValue(OutputProperty, cmd.ReturnValue);
    }
    context.Complete(); 
  }
```

the CheckEntry Command object performs a database query and returns a corresponding value.

The DataPortal_Fetch method is tagged RunLocal as we need to retrieve the file from the local (client) machine.

The problem that I am having is that the Get static method in the business object is receiving a InvalidOperationException with the message "IsBusy == true".

This is what I've tracked down so far.

- The DataPortal_Fetch is being called during the DataPortal.Fetch operation (inside SimpleDataPortal.cs)
- The DataPortal_Fetch sets properties which cause the above async business rule to fire (inside BusinessRules.cs)
- The BusinessRules.cs  performs a .Execute(context) on the rule.  There is no 'await' on this Execute call
- Since there is no 'await' on the execute call, the execution of the SimpleDataPortal.Fetch method does not wait inside the DataPortal_Fetch b.o. method (obj.CallMethodTryAsync("DataPortal_Fetch" ...)
- The very next thing that occurs in the Fetch method is to checks the IsBusy (which is true because the async business rule is still running on the Server data portal and has not yet returned it's result back to the client) and causes the exception above to be thrown.

Any suggestion on what we should do to deal with this issue?

Our current idea is to Bypass Property Checks on the Fetch and then call the businessrules.checkrules manually after the fetch is complete.  Is there a better way of dealing with this situation?

Sorry for the long post, but it's been a Monday...

Thanks,
James

**Comment by rockfordlhotka** [comment]
The `DP_Fetch` method is marked with `RunLocal` so it is running on the WPF client, not on the app server. It is a sync method, so the "server-side" data portal will call it synchronously.

This can get complex very fast if you are calling the "client-side" data portal asynchronously, but the "server-side" parts are synchronous and/or if your synchronous "server-side" code makes async calls.

The Microsoft async/await implementation is really designed to work where an entire call chain is either sync or async. Mixing the two is very problematic.

The data portal does some clever things to mitigate these issues when making calls to an actual remote app server - primarily because I can rely on the underlying WCF or Http technologies to shield us from some of the issues.

But in your case the call is entirely local, so you should be either entirely sync or entirely async to avoid issues.

**Comment by rockfordlhotka** [comment]
Another possibility that I've considered is to create a more "complete" local data portal implementation.

The problem could be mitigated if the local data portal completely emulated a remote app server - switching the call to another AppDomain and another thread. The overhead would become fairly comparable to doing an actual remote app server call (minus only the network latency), but it would provide identical semantics to a real remote app server.

Thus far I've chosen to keep the local data portal more optimized (much lower overhead), but with these async/await limitations where not all combinations of sync/async callers/implementations can be supported.

**Comment by jonnybee** [comment]
Do you want to allow the async rule to run in the DataPortal_XYZ methods and in CheckRules? Or only when the PrimaryProperty is changed? 

If you inherit from PropertyRule you get 3 new properties that you can use to tell the rule engine when it is allowed to execute the rule:

- CanRunInCheckRules
- CanRunAsAffectedProperty
- CanRunOnServer

See also: https://jonnybekkum.wordpress.com/2011/08/29/csla-4-2-rules-update/

**Comment by bradtwurst** [comment]
Thanks for the info (sorry for delay in following up...)

At the root of the issue was the fact that our business rule base class was running an async rule inside logic that was already running async, and in our case, the async was not really needed nor desired.

We've addressed the situation in our code.
