### ISSUE TITLE
Csla and TestProjects

### ISSUE THREAD

**Issue by wwimmo-row** [MarimerLLC/cslaforum#151]
In my WPF application, I want to test the business layer with a Microsoft test project.
Therefore, I do not have a UI-layer with XAML-components but test-classes.
When starting the tests, CSLA 4.5.700.0 is initialized as well.

Because a project-reference exists to  "Csla.Xaml.dll"  the Csla.ApplicationContext uses the Csla.Xaml.ApplicationContextManager.
On other code locations, a similar decision is taken by using  "System.Windows.Application.Current != null".

Results:
**********

1. I get the expectecd "Csla.Xaml.ApplicationContextManager"
    because the reference to Csla.Xaml exists in my test project

2. I do not get the same type of principal as in my XAML application
    "System.Security.Principal.WindowsPrincipal" instead of "Csla.Security.UnauthenticatedPrincipal"
    In app.config, I set <add key="CslaAuthentication" value="Csla"/> 
    I  know that I can modify this principal-type after CSLA initialisation)

3.  Currently, in the test projet  I get a Serialization exception when using an authorized DataPortal 
    "The type is not resolved for member "Csla.Security.UnauthenticatedPrincipal,Csla, 
     Version=4.5.700.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30".
     Exactly the same code works perfectly well in my XAML-application without serialization
     problems, so I assume another initialization problem with CSLA

Question
************
Why exist different mechanisms to decide XAML/NotXAML and how do I have to modify the CSLA settings correctly for my test project?

**Comment by wwimmo-row** [comment]
Because we use WPF-clients only, I deactivated the tests on "System.Windows.Application.Current"
in the file "Csla.Xaml.ApplicationContextManager"
-> the principal is set as expected
-> the serialization problem disappeared
    (the serialization seems to use the internal variable "_principal" and 
     because the variable was not set correctly, the serialization aborted)

**Comment by streagan123** [comment]
We had something similiar.  I ended up putting in a hack that gets it to work for now until I get a better solution.

Basically, I put a copy of Csla.dll in the following location:
c:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions

It's not a great solution, but it got me working until I decide how else I would like to address it.

Not sure if it will help, but it might.
