### ISSUE TITLE
How CSLA's ApplicationContext.User works?

### ISSUE THREAD

**Issue by bhargavgaglani** [MarimerLLC/cslaforum#159]
I am using CSLA in my project. After authentication we are setting principle object in ApplicationContext.User and using in throughout application to obtain logged in user's details. . But I found that it is static class and static variable. So how it is working internally (for multiple logged in users at a time)?

**Comment by jonnybee** [comment]
Internally the ApplicationContext class uses an IContextManager to store the current principal. 

By default the Csla.ApplicationContext.ApplicationContextManager is used and the current user is  stored in Thread.CurrentPrincipal

If Csla.Web.dll is present the Csla.Web.ApplicationContextManager is used and 
- HttpContext.Current != null then current user it is stored in HttpContext.Current.User 
- HttpContext.Current = null then current user is stored in Thread.CurrentPrincipal

If Csla.Xaml.dll is present the Csla.Xaml.ApplicationContextManager is used and 
- System.Windows.Application != null then current user it is stored in static member variable 
- System.Windows.Application = null then current user is stored in Thread.CurrentPrincipal

**Comment by bhargavgaglani** [comment]
Thanks. That helps!
