### ISSUE TITLE
Aah! There y'all are!

### ISSUE THREAD

**Issue by javed007** [MarimerLLC/cslaforum#17]
Took some work, but finally found this place.  No questions - just wanted to get re-acquainted.  They had me change my old name (jav) to javed007. Well they didn't make me choose 007, that was my idea.

**Comment by rockfordlhotka** [comment]
I'm glad you found us :)

**Comment by rockfordlhotka** [comment]
You say it took some work though - is there something I could do to make it easier for people to find this new forum location?

**Comment by javed007** [comment]
Hi,
I had gone to the old forum after a few weeks, and not seeing any messages for so long had me very worried for some time. Then Remembering your posts about GitHub, I went back and saw the GitHub link in your last note.
I think it would be a good idea to post something with the title, "We have moved" and provide the link in there.
Javed

**Comment by rockfordlhotka** [comment]
![newforum](https://cloud.githubusercontent.com/assets/2333134/8578785/66e2b7b8-2576-11e5-8326-95f701435897.jpg)

**Comment by javed007** [comment]
Wow! I guess I got so fixated on the date of each posting and the fact that my last post was in the same location it was weeks ago that I didn't quite read the topic.  How interesting.

**Comment by rockfordlhotka** [comment]
As long as you are here everything is all good :smile:

**Comment by rxelizondo** [comment]
I have a favorite shortcut on my browser that points to "http://forums.lhotka.net/forums/". I have used that link for a long time and when I click on it I don't see the moved to GitHub announcement. This is what I see:

![cslaforum](https://cloud.githubusercontent.com/assets/13452107/8826094/977ce500-3049-11e5-9ce5-7b3184ddbea3.png)

If I do a Google search for "CSLA.net forums", the first link on the list is a link pointing to "http://forums.lhotka.net/forums/" which does not show the announcement.

Perhaps you should reroute all calls to the old forums to a page with a big announcement about the move. From there, people can click a link to come here or a link to go to the old forum.

I hope you are feeling much better now, have a great day.

Thanks.

**Comment by MarkOverstreet** [comment]
I agree
