### ISSUE TITLE
Multiplatform Strategies

### ISSUE THREAD

**Issue by gravidThoughts** [MarimerLLC/cslaforum#187]
Per Rocky in an old forum post about smart clients in a multi platform world.

>This is a problem with any distributed service-based solution where you can't control client-side deployment. In other words, the problem isn't unique to CSLA.
>The typical solution is to develop your server code/deployment such that you can run multiple versions of the service at the same time, retiring older versions of the service as your user base ultimately updates to the current client app version.
>The most common way to do this is to embed the version number into the URL for the service endpoint, and the easiest thing is to host each endpoint in its own AppDomain (web site). Each client app will talk to the URL corresponding to that client's version.
>This is easy to do with the data portal, just like with any other service endpoint, and addresses this issue pretty effectively.`

I have a few questions.

Is the story with business apps for these platforms still ugly? If I want to distribute a business app  across android/apple/windows for a single company, am I still in a situation where I cannot control the client roll out across all platforms like I could with a Click Once application in Windows?

If it is still ugly, I was thinking a potentially easier strategy to enforce compatibility would be to distribute a backwards compatible client that can `activate` new features when the new version of the data portal gets pushed to production. The new portal would be pushed once the client was available on all platforms, and could force anyone not updated to get the update.

Is that completely insane? Anyone ever had a similar thought and fleshed it out? 

I suppose you would still run in to a different set of PITA compatibility issues, just no longer in maintaining a data layer across multiple versions of a data portal.

Thanks,
Matthew

**Comment by rockfordlhotka** [comment]
The problem remains, at least as long as you are using a public store where Apple/Google/Microsoft control the client rollout schedule.

However, the problem can be addressed by using a URL-based naming scheme for your dataportal endpoint that includes the version. Generally you need to keep at most n-1 endpoints alive - the current version and one older, and then only for perhaps a couple weeks while the apps get updated in the stores and on user devices.

**Comment by gravidThoughts** [comment]
Thanks Rocky.

In your opinion, is the toolset for implementing a private distribution viable? If so, can I safely assume that it is more cost effective to go the private distribution route as opposed to maintaining two data portals?

**Comment by rockfordlhotka** [comment]
I'm not sure I can answer that, as the schemes/costs/etc. for Apple, Google, and Microsoft are different. You'll need to research their corporate store options to see if they'll meet your needs.

**Comment by gravidThoughts** [comment]
Thanks!
