### ISSUE TITLE
Validation Rule for more than one Business Properties

### ISSUE THREAD

**Issue by RaviPatelTheOne** [MarimerLLC/cslaforum#190]
We have two properties in Business class. Both are dependent on each other. Like, City Code and City Name. 
Now, we have business validation that if Code and Name is set then first validate whether code is exists. If Code not exists then validate Name is exists. But before these validation, We need to check some primary validation like Max length and others. Once all these validations pass then only fire custom business rules for both properties. Facing issue like if we define validation rule for Code and Name is not valid (Like MAX length) then also custom rule for code is fire. 

Please suggest how to create custom rule which depends on two properties and only fire once after validating basic rules like require and max length. 
Thanks in advance @rockfordlhotka , @jonnybee , @JasonBock

**Comment by jonnybee** [comment]
Which version of CSLA.NET are you using and what type of UI? 

Generally, first start by reading these 2 blogposts:
https://jonnybekkum.wordpress.com/2011/08/29/csla-4-2-rules-update/   and 
https://jonnybekkum.wordpress.com/category/csla/business-rules/  

Basically the rule engine in CSLA will process rules on a per-property basis and for each property rules is processed 

- by Priority in ascending order. 
- All rules with Priority equal or below (bo).BusinessRules.ProcessThroughPriority (deafule = 0) will be called, unless yor code explicitly set stopProcessing to True. 
- Rules with Priority above (bo).BusinessRules.ProcessThroughPriority is only called if none of the provious rules has an Error result or stopProcessing is set to True. 

In a rich client (WinForms, WPF, Silverlight, Mobile) the rules when the property is updated with a new value as the user navigates from property to property. In a web application the rules will be called from the custom CslaModelBinder when all properties has ben set from the input - similar to BusinessRules.CheckRules. 

Rules may also tell the rule engine of when the can be executed. Easiest way is to inherit from PropertyRule base class and set: 

- CanRunInCheckRules
- CanRunAsAffectedProperty
- CanRunOnServer

For a description of these see: 
https://jonnybekkum.wordpress.com/2011/08/29/csla-4-2-rules-update/     

So what it boils to to as my recommendation for a rich client (WPF, WinForms, Silverlight) is: 
CodeProperty: 

-  RequiredRule with Priority = 0
-  MaxLengthRule with Priority = 0
-  LookupCityNameByCode with Priority = 10 and with all CanRun.... properties = false. 

And similar for NameProperty. 
         
This way the LookupXYZ rule is onle ever called when the previous rules have passed with Error level and only after the user has edited a property value.
