### ISSUE TITLE
Move cslacontrib to github?

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#2]
@jonnybee I wonder if we should move cslacontrib from codeplex to GitHub?

If we move it to GitHub it would be listed along with CSLA itself, and so I think it would be easier to find.

Thoughts?

**Comment by rockfordlhotka** [comment]
I did the take liberty of setting up an empty repo here in case we do think it is a good idea (you can probably tell what I think :) )

**Comment by jonnybee** [comment]
I've had the same thought for some time so I totally agree.

**Comment by rockfordlhotka** [comment]
I grabbed the files from codeplex (trunk) and uploaded them into the GitHub repo, so that's a starting point anyway.

https://github.com/MarimerLLC/cslacontrib/issues/1

**Comment by rockfordlhotka** [comment]
As you noted via email, it would be better to let you do the import from codeplex :)

**Comment by rockfordlhotka** [comment]
![new skitch](https://cloud.githubusercontent.com/assets/2333134/8051339/d8849226-0e40-11e5-9a55-b575b81c301a.jpg)
Oops, or not - doesn't support direct import from codeplex :(

**Comment by rockfordlhotka** [comment]
@jonnybee , I'll let you do whatever you'd like - perhaps try svn2git - that's how I got a fair amount of the CSLA .NET project history into GitHub originally.

**Comment by rockfordlhotka** [comment]
I tried the TFS import option too, and couldn't get that to work either - though I suspect that feature exists primarily to support codeplex migrations?

**Comment by rockfordlhotka** [comment]
I also tried the TortoiseGit feature to clone a git repo from an svn server and that failed.

So @jonnybee for my part I'm giving up - if you can figure out a way to get the history ported over that's great, otherwise I figure people who need the history can look at the codeplex site.

**Comment by jonnybee** [comment]
Hi Rocky,

I'm giving git-tf a try now.
https://gittf.codeplex.com/
http://www.microsoft.com/en-us/download/details.aspx?id=30474

Running now on my computer as I write,

/Jonny

2015-06-09 17:45 GMT+02:00 Rockford Lhotka <notifications@github.com>:

**Comment by rockfordlhotka** [comment]
I didn't mention that I tried svn2git too, but without success - so I hope this git-tf tool works better.

**Comment by rockfordlhotka** [comment]
@jonnybee -  I'm glad git-tf works, that's excellent.

I have deleted and recreated the cslacontrib repo so you can push the code without all the tags, and hopefully we're all set.

**Comment by jonnybee** [comment]
Hi Rocky,

I have removed all ..svnbridge files and folders from the repo.
Then pushed the repo to https://github.com/MarimerLLC/cslacontrib

So we should be good to go.

There is a bit of cleanup that should be done to the solutions and projects.
So I am stil wondering on whether it would be best to just import the code
without history and cleanup assemblies so we have a smaller and cleaner
repo.

/Jonny

2015-06-10 0:48 GMT+02:00 Rockford Lhotka <notifications@github.com>:

**Comment by rockfordlhotka** [comment]
I think there's probably value in the history - I'd recommend doing the cleanup against the new GitHub repo now that it is here.

**Comment by rockfordlhotka** [comment]
Just a quick link to the work item for migrating the code.
https://github.com/MarimerLLC/cslacontrib/issues/1
