### ISSUE TITLE
.Net 4.62

### ISSUE THREAD

**Issue by joemorin73** [MarimerLLC/cslaforum#20]
Will there be any issues with .Net 4.62 when it's released?

**Comment by rockfordlhotka** [comment]
I have a prerelease of CSLA version 4.6 in NuGet now, and plan to have another updated prerelease online in the next couple days. (watch https://github.com/MarimerLLC/csla/releases)

I am reasonably confident that version CSLA 4.5 will work in .NET 4.6, but when Windows 10 launches I'll have CSLA 4.6 online with explicit .NET 4.6 support.

**Comment by joemorin73** [comment]
Excellent.  We have a window for a framework upgrade and just needed to check it off the list. ;)
