### ISSUE TITLE
Why do I get a "operation argument types should be serializable" warning?

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslaforum#204]
As far as I can see, the criteria argument is serializable.

![operation argument types should be serializable](https://cloud.githubusercontent.com/assets/3586655/15986600/93b6efa0-3003-11e6-9290-cbd55324eb4b.png)

**Comment by rockfordlhotka** [comment]
I think @jasonbock recently fixed a bug with how the analyzer determined whether a type is serializable.

**Comment by tfreitasleal** [comment]
You are referring to Fixes serialization check (#593)
You are right, it was fixed after 4.6.400 was released.

**Comment by finnmich** [comment]
I get this warning after upgrading from 4.6.300 to 4.6.401.
Some examples: 
private void DataPortal_Fetch(SingleCriteria<string> criteria)
and
private void DataPortal_Fetch(UsernameCriteria criteria)

**Comment by rockfordlhotka** [comment]
See my answer in #212

**Comment by jmarquesh** [comment]
I'm getting the same warning with an int parameter. I'm using version 4.8.1.

![image](https://user-images.githubusercontent.com/5407014/49332269-422e2080-f578-11e8-94b3-3e1821aef37c.png)

**Comment by rockfordlhotka** [comment]
This is a known issue https://github.com/MarimerLLC/csla/issues/623

**Comment by jmarquesh** [comment]
Oh sorry, I read that one, but I thought it only applied to objects, not primitive types. Thanks.
