### ISSUE TITLE
ViewModelBase OnRefreshing fires once while OnRefreshed fires 3 times

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslaforum#205]
Hi Rocky,

According to the method's documentation
`Method called after a refresh operation has completed and before the model is updated (when successful).`

In fact, it's called only on
`private void QueryCompleted(object sender, EventArgs e)`
just before the Model is set.

OTOH OnRefreshed is called always after the try/catch block, except on the method
`private void QueryCompleted(object sender, EventArgs e)`
where it's called inside the try stanza.

**Comment by rockfordlhotka** [comment]
What do we think is the correct behavior?

**Comment by tfreitasleal** [comment]
I think that every time you call OnRefreshed, you should have called previously OnRefreshing, that is, before the Model is refreshed
I was/am using those overrides to detach/attach event handlers that were referencing the Model and causing memory leaks.

**Comment by rockfordlhotka** [comment]
I think the better answer is to override `OnModelChanged`. I don't really recall the reasoning behind the events existing, but to hook/unhook events the override is the better answer.

```csharp
        protected override void OnModelChanged(ModelType oldValue, ModelType newValue)
        {
        }
```

**Comment by tfreitasleal** [comment]
Overriding `OnModelChanged` should work.
