### ISSUE TITLE
Change tracking on view models

### ISSUE THREAD

**Issue by dpakpaul** [MarimerLLC/cslaforum#208]
I'm brand new to CSLA and I'm trying to evaluate whether CSLA will work for the UWP app I'm building. I saw the UWP sample and wanted to try out a simple use case - I want to populate a view model and assign some initial values to it. Then when trying to save, check if any of the vm props bound to the view have changed and if so, proceed to save. 

The view model looks like this - 

   [Serializable()]
    public class TestVm : BusinessBase<TestVm>
    {
 
        public static readonly PropertyInfo<string> FirstNameProperty =
            RegisterProperty<string>(c => c.FirstName);

        public string FirstName
        {
            get { return GetProperty(FirstNameProperty); }
            set { SetProperty(FirstNameProperty, value); }
        }

        public static readonly PropertyInfo<string> LastNameProperty =
            RegisterProperty<string>(c => c.LastName);

        public string LastName
        {
            get { return GetProperty(LastNameProperty); }
            set { SetProperty(LastNameProperty, value); }
        }

      
        public void SaveAllChanges()
        {
            // Also tried IsDirty
            if (this.IsSelfDirty)
            {
               // do somethign
            }
            
        }
    }

All I did in the page OnLoaded was to create the view model class and assign it to the DataContext. I didn't even do an initial set of the properties. But IsDirty and IsSelfDirty are both true . Seems like IsDirty should automatically be set to true only via the SetProperty() when the value has changed from an old val to a new val ? I must be missing something .

**Comment by jonnybee** [comment]
Does your code call DataPortal.Create<TestVm>() to get a new instance? Often this code is added as a public static factory New method on the class. 
   
    public static Root NewTestVm()
    {
      return DataPortal.Create<TestVm>();
    }

The base class has a DataPortal_Create method that will be called and this method calls MarkClean() to mark the object as Not Dirty.

**Comment by dpakpaul** [comment]
Thanks. I tried that , but it still shows as dirty. But , at this point, let me dig into the csla code itself and understand what the data portal does so that I have a better perspective on different elements involved. I appreciate the pointer in the right direction.

**Comment by rockfordlhotka** [comment]
The definition of "dirty" from the framework's perspective is that we have a reasonable expectation that the field values in the object are different from those in the database.

All new objects can be assumed to be dirty, because the object is new so there is _no_ database representation - hence the values must be different.

You can override `IsDirty` to alter this behavior, just be aware that the data portal won't even try to save an object if it isn't dirty, so your new objects will never be persisted unless they are marked dirty in some other manner.
