### ISSUE TITLE
"operation argument types should be serializable" warning? (re-open of issue 204)

### ISSUE THREAD

**Issue by finnmich** [MarimerLLC/cslaforum#212]
I get this warning after upgrading from 4.6.300 to 4.6.401.
Some examples: 
private void DataPortal_Fetch(SingleCriteria criteria)
and
private void DataPortal_Fetch(UsernameCriteria criteria)

**Comment by rockfordlhotka** [comment]
One of the new analyzers checks to make sure parameters to DataPortal.XYZ methods are serializable. Unfortunately there's a bug in the .401 implementation that doesn't properly determine whether some types are serializable.

This will be fixed in .500

**Comment by tfreitasleal** [comment]
I had the same problem with a SafeDataReader.
