### ISSUE TITLE
CSLA for pure Mono

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslaforum#223]
There is a solution csla.mono.sln but it doesn't even load its projects.
What's the state of the art? Is someone looking at it?

**Comment by rockfordlhotka** [comment]
@jonnybee did a mono port a long time ago (years), but it has obviously fallen into disrepair, primarily due to lack of demand. To highlight that point, you are the first person to look at it in years.

At least for me, the priority of the mono solution will climb very rapidly once mono runs on webassembly, but that probably won't be for another year or so is what I'm hearing. However, the ability to run CSLA "natively" in any modern browser is _extremely_ compelling, so you can bet I'll be all over that!! 😈 

Do you have a pressing or particular need for CSLA on mono?

**Comment by tfreitasleal** [comment]
I think the demand for Mono will grow slowly at first. One of the reasons is everybody is focusing on mobile Mono. Visual Studio has no support to target plain Mono, be it desktop or web applications. I won't comment about WebAssembly but I think Mono demand will increase sharply once System.Web and WCF are ported and that should happen [soon enough](http://www.mono-project.com/docs/about-mono/compatibility/).

It's my first approach to Mono. I have a test project I want to port. So, no, I don't have a pressing need. But anyway I'll try to make the solution build. If I do, I'll make write and issue, make a pull request, the lot.

**Comment by tfreitasleal** [comment]
The trouble is the lack of NuGet target for pure Mono. Check the [documentation](https://docs.nuget.org/create/targetframeworks)

**Comment by rockfordlhotka** [comment]
I don't think the nuget thing is a huge deal, as mono appears to fit in at netstandard 1.4.

In CSLA 4.6.500 I am supporting netstandard 1.5 because that's where reflection quit being such a horrific problem, but all the code still exists in the codebase that would allow support as far back as netstandard 1.3 or maybe even earlier.

I just didn't see the value in it, because CSLA already has direct assemblies that support every platform for netstandard 1.1-4 (except mono I guess). So when I went to add support for .NET Core I felt it was easiest to target netstandard 1.5 and just move forward from there.

**Comment by tfreitasleal** [comment]
The point isn't only how to build and target the libraries but also about how to consume them. Xamarin Studio (aka MonoDevelop) must recognize this target.

**Comment by tfreitasleal** [comment]
As expected, the application crashes and the offending line is
`using (var ctx = ConnectionManager<SqlConnection>.GetManager(Database.MyConnection, false))`

**Comment by tfreitasleal** [comment]
This was published today at Xamarin blogs. It looks like I asked the question a few days ahead of time.
[.NET Standard Library Support for Xamarin](https://blog.xamarin.com/net-standard-library-support-for-xamarin/)

**Comment by rockfordlhotka** [comment]
Sort of - though that doesn't solve the problem that pure mono has no nuget target, nor does it appear in the .NET Standard Library matrix so it isn't clear what version of netstandard (if any) is supported by mono.

**Comment by tfreitasleal** [comment]
It's listed as **Mono /Xamarin Platforms** but i don't understand the symbols on that line. So you are right, it doesn't really solve the problem.

This problem concerns not only CSLA-Core but also CSLA-WindowsForms as Mono's Windows Forms implementation isn't exactly the same as .NET implementation.

I don't understand why Mono/Xamarin/NuGet (well, they are all Microsoft, aren't they?) don't address the issue. In the mean time, we could releasse CSLA-Core-mono, CSLA-WindowsForms-mono, etc

**Comment by tfreitasleal** [comment]
On second thoughts, a NuGet target is useless, unless VS/Xamarin Studio have a matching project target.

**Comment by rockfordlhotka** [comment]
Miguel's comment (via email) is correct - we'd need to add a whole new NuGet package for mono.

Right now, for example, `CSLA-Core` is the single base for everything - it has all the platforms. And then `CSLA-WPF` has the support for WPF and a dependency on `CSLA-Core`.

What we'd have to do for mono is add a `CSLA-mono` package to NuGet that contains the Csla.dll targeting mono.

This is not a problem from my perspective.

It sounds like supporting the Windows Forms port to mono is not a good idea, since the mono team doesn't support that technology. Perhaps it would be better to support their GtkSharp UI technology instead?

**Comment by tfreitasleal** [comment]
I agree on Csla-mono matter. On top of that. we must support ASP.NET on Mono and also some desktop UI technology.
After Miguel's answer, about Windows.Forms ("Windows.Forms is not actively maintained by the Mono team"), I'm looking into Gtk#.

**Comment by tfreitasleal** [comment]
Let me investigate a bit more this issue. Mono environment isn't easy to work with and I might be doing something wrong. Also there was a reflection issue that was fixed on the latest release I downloaded a while ago. On the other hand, the exception occurs on the DataPortal_Execute() method so reflection worked as it should up to this point.

**Comment by tfreitasleal** [comment]
Windows Forms is unusable on Mono. I'm testing a console application. It looks like it runs. I found a few issues:
- allowed connection string format
- Thread.CurrentThread.CurrentUICulture is set to InvariantLanguage when you start the application
- can not handle SqlDbType.Timestamp

and I feel there are a lot more to come. So far no issue is due to Csla code.

Xamarin Studio sometimes behaves normally and allows debugging sometimes it doesn't. I can't understand why, so I'm back to command line days...

**Comment by jonnybee** [comment]
The databinding implementation i Mono / Windows Forms is also lacking when I was testing it.

**Comment by tfreitasleal** [comment]
According to my first readings about GTK#, there is no databinding at all. Databinding is on [future plans](http://www.mono-project.com/docs/gui/gtksharp/plan/#future-plans). The source code at [GitHub](https://github.com/mono/gtk-sharp) shows no signs of databinding.

We must understand how far in the futura are those plans.

If there is no Databinding, I don't see how can we improve igtk-sharp in order to use it with Csla.

**Comment by tfreitasleal** [comment]
I found problems with the SafeDataReader. The only way to get past the DataPortal_Fecth, was to use an SqlDataReader instead of a SafeDataReader. The SafeDataReader is an important utility class but it's not the core of Csla.

I was using a project not so simple and this makes tests more difficult. I need to use a project far more simpler but I can't do it now. BTW my project uses sync DataPortal and factory methods. Async methods need to be tested.

For the record, I'd say that it looks like Csla runs on Mono without  major problems. As there are at least a few problems, some serious testing is needed.

**Comment by rockfordlhotka** [comment]
It is probably possible to figure out the offending code in `SafeDataReader` and to fix it with a `MONO` compiler directive.

**Comment by tfreitasleal** [comment]
Again, there is nothing wrong with Csla on Mono. The database was using `DateTime2` on the `CreateDate` and `ChangeDate`. It seems [SQL server reports this column as string in the legacy protocol version which mono implements](http://stackoverflow.com/questions/25577219/asp-net-mvc4-razor-on-mono-ef-6-datetime-crash).

**Comment by tfreitasleal** [comment]
I must add a note about how I did Mono tests.

Xamarin Studio allows you to set breakpoints like VS. Before debuging a solution, XS re-compiles the solution targetting for Mono. This process may be a problem on itself (complaints about embeding resources, unable to make folders, etc). XS debuging, behaviour is quite different from VS. If I believe everything XS said... First of all, when exceptions are raised by external assemblies, it should break the debug. Well, it doesn't. Second, it reports strange things like
`Method 'GetOrdinal' not found in type 'System.Data.IDataReader'.`
`Method 'GetDateTime' not found in type 'System.Data.IDataReader'.`
I found it rather odd and confirmed  the source code does implement the referred methods. As expected, they do exist and it looks like they are a direct copy their .NET counterpart as available on the ReferenceSources library. Xamarin Studio was reporting false issues so I had to give up using it.
This isn't a problem since there is binary compatibility: assemblies should run unchanged on Mono and .NET. The Mono specific compile process exists just for debugging purposes..

Atfer I decided to forget about XS, my problem was I could no longer debug the code. I had to insert Console.WriteLine statements in the relevant parts of Csla code, compile on VS and run on Mono command line. This method told me where the problems were. After that, I changed whatever was need to workaround the issues and everything was fine. As the last step, I build specific samples to illustrate each problem. Those samples are very small, they don't depend on CSLA and served to submit the issues on [bugzilla.xamarin](https://bugzilla.xamarin.com/)

**Comment by tfreitasleal** [comment]
In order to find a suitable desktop environment to build applications that run everywhere, there are some requisites that must be observed:
- run everywhere
- support DataBinding (and MVVM scenarios)
- include designer support

After some research, some messing around with VirtualBox and some testing, I reached some conclusions:

[System.Windos.Forms] (https://github.com/mono/mono/tree/master/mcs/class/System.Windows.Forms)
Mono port
- 2.0 API is not supported at this time
- still in beta state
- not actively maintained

[Gtk#] (https://github.com/mono/gtk-sharp)
Mono/.NET binding to the cross platform Gtk+ GUI toolkit
- no DataBinding

[XWT] (https://github.com/mono/xwt)
A cross-platform UI toolkit for creating desktop applications with .NET and Mono
- Mono Open Source
- no DataBinding (except for WPF backend)
- UI abstraction using different backends according to platform

[Eto] (https://github.com/picoe/Eto)
Cross platform GUI framework for desktop and mobile applications in .NET
- 3rd party Open Source
- includes DataBinding
- Supports MVVM scenarios
- no designer
- UI abstraction using different backends according to platform

[Avalonia] (https://github.com/AvaloniaUI/Avalonia)
Multi-platform .NET UI framework (formerly known as Perspex)
- 3rd party Open Source
- includes DataBinding
- Supports MVVM scenarios
- XAML - uses VS/XS/MonoDevelop designer
- looks promising but still in Alpha state (test applications run on Windows and Linux)

I also found some paid soluions that I didn't test.

**Comment by tfreitasleal** [comment]
A small correction, Although Avalonia, uses XAML, Xamarin Studio and MonoDevelop don't design their XAML. VisualStudio built in designer shows the objects but the toolbox is empty. There is an [AvalonStudio project ](https://github.com/VitalElement/AvalonStudio) that is made using Avalonia and intends to be a studio for Avalonia, but is a WIP.

**Comment by tfreitasleal** [comment]
I'm doing some tests on Eto. I'll report back.
