### ISSUE TITLE
Possible analyzer bug:  PropertyInfos must be readonly for BB but not CommandBase

### ISSUE THREAD

**Issue by ajj3085** [MarimerLLC/cslaforum#231]
I'm using Csla 4.6.401, .Net 4.6.  I copied and pasted a PropertyInfo declaration from a CommandBase class to a BusinessBase.  I then had an error in my solution when I ddin't before, because the PropertyInfo field was public static but not readonly.  I added the readonly, and the project was fine, but in checking the CommandBase, all of the readonly modifiers were missing.

**Comment by rockfordlhotka** [comment]
This sounds like a bug - @JasonBock ?

**Comment by JasonBock** [comment]
@ajj3085 can you post a gist or a code sample here?

**Comment by ajj3085** [comment]
Just create a new blank class library project (.Net 4.6.1), and Csla via nuget, then paste this into the Class1.cs file:

```
using System;
using Csla;

namespace ClassLibrary1 {
	[Serializable]
	public class CommandObj : CommandBase<CommandObj> {
		public static PropertyInfo<string> TextProperty = RegisterProperty<string>(x => x.Text);

		public string Text {
			get { return ReadProperty(TextProperty); }
			private set { LoadProperty(TextProperty, value); }
		}
	}

	[Serializable]
	public class BusinessObj : BusinessBase<BusinessObj> {
		public static PropertyInfo<string> TextProperty = RegisterProperty<string>(x => x.Text);

		public string Text {
			get { return ReadProperty(TextProperty); }
			private set { LoadProperty(TextProperty, value); }
		}
	}
}
```

There will be an error for the TextProperty declaration because it's not readonly, but nothing for the command's TextProperty.

**Comment by JasonBock** [comment]
OK, I'll write up a bug on the CSLA site.
