### ISSUE TITLE
WinForms not finding WcfMobilPortal

### ISSUE THREAD

**Issue by Brannos1970** [MarimerLLC/cslaforum#248]
I build the web services just like the sample and it is up and running. The problem I have is that the Winforms app cannot access the web service.

I check the app.config and it looks like it is correct:
<add key="CslaDataPortalUrl" value="http://localhost:51222/WcfMobilePortal.svc" />

But I get this error: {"There was no endpoint listening at http://localhost:51222/WcfMobilePortal.svc that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details."}

Any suggestions as to what I may have missed?

Thanks

**Comment by jonnybee** [comment]
Is your solution configured with multiple startup projects? Could simply be that the server project is just not started for debugging with the WinForms app.

**Comment by Brannos1970** [comment]
It is configured with multiple startup projects. I did double check the web.config bindings to ensure they are correct and I think they are:

<service name="Csla.Server.Hosts.WcfPortal" behaviorConfiguration="returnFaults">
        <endpoint binding="wsHttpBinding" bindingConfiguration="wsHttpBinding_IWcfPortal" contract="Csla.Server.Hosts.IWcfPortal" />
      </service>
      <service name="Csla.Server.Hosts.Mobile.WcfPortal" behaviorConfiguration="returnFaults">
        <endpoint binding="basicHttpBinding" bindingConfiguration="basicHttpBinding_IWcfPortal" contract="Csla.Server.Hosts.Mobile.IWcfPortal" />
      </service>
    </services>

But I am wondering if I should modify them with the "name" attribute.

**Comment by Brannos1970** [comment]
I figured it out. The sample is missing some part and have some areas with different service names. Once I added a WcfPortal.svc and pointed everything correctly to it all is working.
