### ISSUE TITLE
Csla.ApplicationContext.User.Identity is null outside of the global.asax file

### ISSUE THREAD

**Issue by JustinBourlier** [MarimerLLC/cslaforum#251]
For some reason, the Csla.ApplicationContext.User.Identity is null in other pages.  I have my Login call in  the Global.asax.cs file in Session_Start like so, and this works just fine.  However, when accessing the object in other pages, it's null.  I'm utilizing ASP.NET 4.5.1 Web Forms.  

**I added this to web.config:**
  <appSettings>
    <add key="CslaAuthentication" value="Custom" />
  </appSettings> 

**Here is the global.asax piece, which works just fine, I can read the identity object.**  
protected void Session_Start(object sender, EventArgs e)
        {
#if DEBUG
            HttpContext.Current.Request.ServerVariables["HTTP_CSWFCEMPLID"] = "1330810";
            HttpContext.Current.Request.ServerVariables["HTTP_GROUPS"] = "DTCA_TIG_SIS_CCAM_ADMIN^DTCA_TIG_SIS_CCAM_ANALYTICS";
            HttpContext.Current.Request.ServerVariables["HTTP_CSSN"] = "Bourlier";
            HttpContext.Current.Request.ServerVariables["HTTP_CSGIVENNAME"] = "Justin";
#endif
            CustomPrincipal.Login();
            if (Csla.ApplicationContext.User.Identity.IsAuthenticated)
            {
                //JAB: example to show how to read logged in user, remove this before deploy
                string fullName = (Csla.ApplicationContext.User.Identity as CustomIdentity).FullName;
                long employeeId = (Csla.ApplicationContext.User.Identity as CustomIdentity).EmployeeId;
            }
        }

**Here is my CustomIdentity and CustomPrincipal classes**
using System.Web;
using Csla;
using Csla.Security;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CCAM.Business.Entities
{
    [Serializable]
    public class CustomPrincipal : CslaPrincipal
    {
        private CustomPrincipal(CustomIdentity identity) : base(identity) { }

        public static void Login() {
            var identity = CustomIdentity.GetCustomIdentity(); 
            Csla.ApplicationContext.User = new CustomPrincipal(identity); 
        }

        public static void Logout() { 
            Csla.ApplicationContext.User = new UnauthenticatedPrincipal(); 
        }
    }

    [Serializable]
    public class CustomIdentity : CslaIdentityBase<CustomIdentity>
    {
        public static readonly PropertyInfo<string> FullNameProperty = RegisterProperty<string>(c => c.FullName); 
        
        public string FullName 
        { 
            get { return GetProperty(FullNameProperty); } 
            private set { LoadProperty(FullNameProperty, value); } 
        }

        public static readonly PropertyInfo<long> EmployeeIdProperty = RegisterProperty<long>(c => c.EmployeeId);

        public long EmployeeId
        {
            get { return GetProperty(EmployeeIdProperty); }
            private set { LoadProperty(EmployeeIdProperty, value); }
        }

        public static CustomIdentity GetCustomIdentity() 
        { 
            return DataPortal.Fetch<CustomIdentity>(); 
        } 

        private void DataPortal_Fetch()
        {
            AuthenticationType = "Custom";
            IsAuthenticated = true;

            EmployeeId = Convert.ToInt64(HttpContext.Current.Request.ServerVariables["HTTP_CSWFCEMPLID"]);
            string lastName = HttpContext.Current.Request.ServerVariables["HTTP_CSSN"];
            string firstName = HttpContext.Current.Request.ServerVariables["HTTP_CSGIVENNAME"];
            FullName = firstName + " " + lastName;
            Name = firstName;

            IList<string> groups = ((string)HttpContext.Current.Request.ServerVariables["HTTP_GROUPS"]).Split('^');
            if (!User.Exists(new UserCriteria(EmployeeId)))
            {
                //see if they have access by checking if they are a member of any of the groups
                if (!Employee.Exists(new EmployeeCriteria(EmployeeId)) || groups.Count == 0)
                {
                    IsAuthenticated = false;
                    return;
                }

                Employee thisUser = Employee.GetByEmployeeID(EmployeeId);
                if (thisUser.Active == false)
                {
                    IsAuthenticated = false;
                    return;
                }

                //Add new user
                User newUser = User.NewUser();
                newUser.EmployeeID = EmployeeId;
                newUser.FirstName = thisUser.FirstName;
                newUser.LastName = thisUser.LastName;
                newUser.Active = thisUser.Active;
                newUser.CreatedOn = DateTime.Now;
                newUser.CreatedBy = -1;
                newUser.Save();
            }

            var user = User.GetByEmployeeID(EmployeeId);

            if (IsAuthenticated)
            {
                if (user.FirstName != firstName)
                    user.FirstName = firstName;
                if (user.LastName != lastName)
                    user.LastName = lastName;

                //check that their assigned groups match what's in database
                foreach (var group in groups)
                {
                    bool found = false;
                    foreach (var dbGroup in user.EmployeeUserToGroups.Clone())
                    {
                        if (group == dbGroup.GroupName)
                        {
                            found = true;
                            break;
                        }
                    }

                    if (!found)
                    {
                        if (!Group.Exists(new GroupCriteria(group)))
                        {
                            //New Group came in that starts with DTCA_TIG_SIS_CCAM* filter
                            Group newGroup = Group.NewGroup();
                            newGroup.GroupName = group;
                            newGroup.Description = "Admin To Update";
                            newGroup.CreatedOn = DateTime.Now;

                            //System User
                            newGroup.CreatedBy = -1;
                            newGroup.Active = true;
                            newGroup.Save();
                        }
                        UserToGroup userToGroup = UserToGroup.NewUserToGroup();
                        userToGroup.GroupName = group;
                        userToGroup.EmployeeID = EmployeeId;
                        userToGroup.CreatedBy = -1;
                        userToGroup.CreatedOn = DateTime.Now;
                        user.EmployeeUserToGroups.Add(userToGroup);
                    }
                }

                //reverse of loop above, check that their db groups match what's in their header variable
                foreach (var dbGroup in user.EmployeeUserToGroups.Clone())
                {
                    bool found = false;
                    foreach (var group in groups)
                    {
                        if (group == dbGroup.GroupName)
                        {
                            found = true;
                            break;
                        }
                    }

                    //remove them from their relationship
                    if (!found)
                        user.EmployeeUserToGroups.Remove(dbGroup.GroupName, EmployeeId);
                }
                user.Save();

                Roles = new Csla.Core.MobileList<string>(groups);
            }
        }
    }
}

**Comment by jonnybee** [comment]
Is Csla.Web.dll referenced in your project and present in your bin folder?

**Comment by JustinBourlier** [comment]
Oops, I guess I opened up 2 threads somehow by accident.  This issue has been resolved / closed here:
https://github.com/MarimerLLC/cslaforum/issues/252#issuecomment-250319057
