### ISSUE TITLE
Csla.ApplicationContext.User.Identity is null outside of the global.asax file

### ISSUE THREAD

**Issue by JustinBourlier** [MarimerLLC/cslaforum#252]
For some reason, the Csla.ApplicationContext.User.Identity is null in other pages.  I have my Login call in  the Global.asax.cs file in Session_Start like so, and this works just fine.  However, when accessing the object in other pages, it's null.  I'm utilizing ASP.NET 4.5.1 Web Forms.  

**I added this to web.config:**
```
  <appSettings>
    <add key="CslaAuthentication" value="Custom" />
  </appSettings> 
```

**Here is the global.asax piece, which works just fine, I can read the identity object.**  
```
protected void Session_Start(object sender, EventArgs e)
        {
#if DEBUG
            HttpContext.Current.Request.ServerVariables["HTTP_CSWFCEMPLID"] = "1330810";
            HttpContext.Current.Request.ServerVariables["HTTP_GROUPS"] = "DTCA_TIG_SIS_CCAM_ADMIN^DTCA_TIG_SIS_CCAM_ANALYTICS";
            HttpContext.Current.Request.ServerVariables["HTTP_CSSN"] = "Bourlier";
            HttpContext.Current.Request.ServerVariables["HTTP_CSGIVENNAME"] = "Justin";
#endif
            CustomPrincipal.Login();
            if (Csla.ApplicationContext.User.Identity.IsAuthenticated)
            {
                //JAB: example to show how to read logged in user, remove this before deploy
                string fullName = (Csla.ApplicationContext.User.Identity as CustomIdentity).FullName;
                long employeeId = (Csla.ApplicationContext.User.Identity as CustomIdentity).EmployeeId;
            }
        }

```

**Here is my CustomIdentity and CustomPrincipal classes**
```
using System.Web;
using Csla;
using Csla.Security;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CCAM.Business.Entities
{
    [Serializable]
    public class CustomPrincipal : CslaPrincipal
    {
        private CustomPrincipal(CustomIdentity identity) : base(identity) { }

        public static void Login() {
            var identity = CustomIdentity.GetCustomIdentity(); 
            Csla.ApplicationContext.User = new CustomPrincipal(identity); 
        }

        public static void Logout() { 
            Csla.ApplicationContext.User = new UnauthenticatedPrincipal(); 
        }
    }

    [Serializable]
    public class CustomIdentity : CslaIdentityBase<CustomIdentity>
    {
        public static readonly PropertyInfo<string> FullNameProperty = RegisterProperty<string>(c => c.FullName); 
        
        public string FullName 
        { 
            get { return GetProperty(FullNameProperty); } 
            private set { LoadProperty(FullNameProperty, value); } 
        }

        public static readonly PropertyInfo<long> EmployeeIdProperty = RegisterProperty<long>(c => c.EmployeeId);

        public long EmployeeId
        {
            get { return GetProperty(EmployeeIdProperty); }
            private set { LoadProperty(EmployeeIdProperty, value); }
        }

        public static CustomIdentity GetCustomIdentity() 
        { 
            return DataPortal.Fetch<CustomIdentity>(); 
        } 

        private void DataPortal_Fetch()
        {
            AuthenticationType = "Custom";
            IsAuthenticated = true;

            EmployeeId = Convert.ToInt64(HttpContext.Current.Request.ServerVariables["HTTP_CSWFCEMPLID"]);
            string lastName = HttpContext.Current.Request.ServerVariables["HTTP_CSSN"];
            string firstName = HttpContext.Current.Request.ServerVariables["HTTP_CSGIVENNAME"];
            FullName = firstName + " " + lastName;
            Name = firstName;

            IList<string> groups = ((string)HttpContext.Current.Request.ServerVariables["HTTP_GROUPS"]).Split('^');
            if (!User.Exists(new UserCriteria(EmployeeId)))
            {
                //see if they have access by checking if they are a member of any of the groups
                if (!Employee.Exists(new EmployeeCriteria(EmployeeId)) || groups.Count == 0)
                {
                    IsAuthenticated = false;
                    return;
                }

                Employee thisUser = Employee.GetByEmployeeID(EmployeeId);
                if (thisUser.Active == false)
                {
                    IsAuthenticated = false;
                    return;
                }

                //Add new user
                User newUser = User.NewUser();
                newUser.EmployeeID = EmployeeId;
                newUser.FirstName = thisUser.FirstName;
                newUser.LastName = thisUser.LastName;
                newUser.Active = thisUser.Active;
                newUser.CreatedOn = DateTime.Now;
                newUser.CreatedBy = -1;
                newUser.Save();
            }

            var user = User.GetByEmployeeID(EmployeeId);

            if (IsAuthenticated)
            {
                if (user.FirstName != firstName)
                    user.FirstName = firstName;
                if (user.LastName != lastName)
                    user.LastName = lastName;

                //check that their assigned groups match what's in database
                foreach (var group in groups)
                {
                    bool found = false;
                    foreach (var dbGroup in user.EmployeeUserToGroups.Clone())
                    {
                        if (group == dbGroup.GroupName)
                        {
                            found = true;
                            break;
                        }
                    }

                    if (!found)
                    {
                        if (!Group.Exists(new GroupCriteria(group)))
                        {
                            //New Group came in that starts with DTCA_TIG_SIS_CCAM* filter
                            Group newGroup = Group.NewGroup();
                            newGroup.GroupName = group;
                            newGroup.Description = "Admin To Update";
                            newGroup.CreatedOn = DateTime.Now;

                            //System User
                            newGroup.CreatedBy = -1;
                            newGroup.Active = true;
                            newGroup.Save();
                        }
                        UserToGroup userToGroup = UserToGroup.NewUserToGroup();
                        userToGroup.GroupName = group;
                        userToGroup.EmployeeID = EmployeeId;
                        userToGroup.CreatedBy = -1;
                        userToGroup.CreatedOn = DateTime.Now;
                        user.EmployeeUserToGroups.Add(userToGroup);
                    }
                }

                //reverse of loop above, check that their db groups match what's in their header variable
                foreach (var dbGroup in user.EmployeeUserToGroups.Clone())
                {
                    bool found = false;
                    foreach (var group in groups)
                    {
                        if (group == dbGroup.GroupName)
                        {
                            found = true;
                            break;
                        }
                    }

                    //remove them from their relationship
                    if (!found)
                        user.EmployeeUserToGroups.Remove(dbGroup.GroupName, EmployeeId);
                }
                user.Save();

                Roles = new Csla.Core.MobileList<string>(groups);
            }
        }
    }
}

```

**Comment by rockfordlhotka** [comment]
Web servers have no memory - each client request gets a blank new workspace. However, ASP.NET does track your session as you note.

The start method for the session runs once at the start of the session. But it doesn't run at the start of each client request, and at the start of each client request you are in a blank workspace.

So what you must do is set the principal object at the start of each client request, otherwise the value will be blank (blank workspace remember).

**Comment by JustinBourlier** [comment]
Ahh that makes sense, guess I was hoping somewhere under the hood this got cached away.  Thank you for the quick reply, I'm enjoying working with the framework.

**Comment by JustinBourlier** [comment]
In case anyone else runs into this, the method in the Global.asax you want to use to set this object is: 
Application_AcquireRequestState

**Comment by fujiiface** [comment]
@JustinBourlier @rockfordlhotka For a while now, I've had a similar issue except I think mine deals with the fact that I am using a custom HTTP Handler to check `Csla.ApplicationContext.User` to see if the user is authenticated, and if so, are they allowed to download specific files.  I have been using `Application_AcquireRequestState` like Justin mentioned but users will still lose application context once in a while.  To resolve the issue, the user has to log back in and go back to the link.

Is there another part of **Global.asax** that needs to have the principal set?  Here's my `Application_AcquireRequestState`:

    protected void Application_AcquireRequestState(object sender, EventArgs e)
    {
        var identity = HttpContext.Current.User.Identity;
        if (identity.IsAuthenticated)
        {
            CustomPrincipal.Load(identity.Name);
        }
    }

Also, stepping through the code, I notice that `Application_AcquireRequestState` is called every time a Business Object is accessed on the page.  Maybe this requires some changes in the code to do less object calls but I am getting a lot of calls (15+).

**Comment by JustinBourlier** [comment]
Fuji, dunno if you are still working on this.  But those calls might be due to the requests to all the resources in your application.   I did something like this to improve performance and reduce the number of times I'm setting the principal.

        protected void Application_AcquireRequestState(object sender, EventArgs e)
        {
            if (HttpContext.Current != null)
            {
                if (HttpContext.Current.Request.Url.AbsoluteUri.Contains(".js") ||
                    HttpContext.Current.Request.Url.AbsoluteUri.Contains(".css") ||
                    HttpContext.Current.Request.Url.AbsoluteUri.Contains(".png") ||
                    HttpContext.Current.Request.Url.AbsoluteUri.Contains(".axd") ||
                    HttpContext.Current.Request.Url.AbsoluteUri.Contains(".asmx") ||
                    HttpContext.Current.Request.Url.AbsoluteUri.Contains(".ico"))
                    return;
            }
            HttpCookie authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];

            if (authCookie != null)
            {
                CustomPrincipal.SetContextUsingCookie(authCookie);
            }
        }

**Comment by fujiiface** [comment]
Hi @JustinBourlier,

Thanks for the suggestion.  I didn't think it would be related to those resources and testing the code shows me that it, indeed, is not.  I get one `CustomPrincipal.SetContextUsingCookie(authoCookie)` call per business object retrieval.  In other words, if I have three dropdowns and they all make their own database call, each one calls the `CustomPrincipal` function.  I am rewriting a Web Forms application to MVC so I can make some optimizations to reduce the amount of those calls but, in those cases where I can't, it's still calling multiple times.

Since moving to MVC I haven't had to use the custom HTTP handler so I haven't seen users losing context for attachment downloading anymore.  Once in a while I see users making unauthorized calls but this could be related to session timeout.  I've been skeptical since the download problem existed for a long time.
