### ISSUE TITLE
Possible bug when specifying DataPortalProxyFactory via config?

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/cslaforum#255]
I think I found a bug trying to specify a custom IDataPortalProxyFactory implementation via the configuration file.

Create a solution named `DataPortalProxyFactoryBug`  Run the below code, and it should work.  Add the following to the programs app.config, 

```
<appSettings>
	<add key="CslaDataPortalProxyFactory" value="DataPortalProxyFactoryBug.Program.MyDataPortalProxyFactory, DataPortalProxyFactoryBug"/>
</appSettings>

```

and you'll get an ArguementNullException:  Value cannot be null:  Parameter name: key

```
   at Csla.DataPortal`1.Update(T obj)
   at DataPortalProxyFactoryBug.Program.BusinessObject.SayHelloCommand() in c:\sandbox\DataPortalProxyFactoryBug\DataPortalProxyFactoryBug\DataPortalProxyFactoryBug\Program.cs:line 21
   at DataPortalProxyFactoryBug.Program.Main(String[] args) in c:\sandbox\DataPortalProxyFactoryBug\DataPortalProxyFactoryBug\DataPortalProxyFactoryBug\Program.cs:line 13
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Csla;
using Csla.Core;
using Csla.DataPortalClient;

namespace DataPortalProxyFactoryBug {
	internal class Program {
		private static void Main(string[] args) {
			Console.WriteLine(BusinessObject.SayHelloCommand());

			Console.ReadLine();
		}

		[Serializable]
		public sealed class BusinessObject : CommandBase<BusinessObject> {
			public static string SayHelloCommand() {
				return DataPortal.Execute(new BusinessObject()).SayHello;
			}

			public static readonly PropertyInfo<string> SayHelloProperty = RegisterProperty<string>(x => x.SayHello);
			public string SayHello {
				get { return ReadProperty(SayHelloProperty); }
				private set { LoadProperty(SayHelloProperty, value); }
			}

			protected override void DataPortal_Execute() {
				SayHello = "Hi!";
			}
		}

		public sealed class MyDataPortalProxyFactory : IDataPortalProxyFactory {
			public IDataPortalProxy Create(Type objectType) {
				return new LocalProxy();
			}

			public void ResetProxyType() { }
		}
	}
}

```

Any ideas?  This is in the latest version 4.6.401, targeting .Net 4.0 full profile.

Thanks

**Comment by jonnybee** [comment]
I think it is a fairly odd case where you put the DataPortalProxyFactory as an inner class of Program (or any other class). If you move MyDataPortalProxyFactory to be outside Program class your code runs just fine, . 

So this will run fine:

    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine(BusinessObject.SayHelloCommand());

            Console.ReadLine();
        }

        [Serializable]
        public sealed class BusinessObject : CommandBase<BusinessObject>
        {
            public static string SayHelloCommand()
            {
                return DataPortal.Execute(new BusinessObject()).SayHello;
            }

            public static readonly PropertyInfo<string> SayHelloProperty = RegisterProperty<string>(x => x.SayHello);
            public string SayHello
            {
                get { return ReadProperty(SayHelloProperty); }
                private set { LoadProperty(SayHelloProperty, value); }
            }

            protected override void DataPortal_Execute()
            {
                SayHello = "Hi!";
            }
        }
    }


    public sealed class MyDataPortalProxyFactory : IDataPortalProxyFactory
    {
        public IDataPortalProxy Create(Type objectType)
        {
            return new LocalProxy();
        }

        public void ResetProxyType() { }
    }

**Comment by ajj7060** [comment]
Hmm, well the nesting has nothing to do with it, but apparently I made the same mistake in both instances, which was incorrectly specifying the type.  I'll open a separate issue about that.  Thanks for looking at this.
