### ISSUE TITLE
"operation argument types should be serializable" warning on SingleCriteria<>

### ISSUE THREAD

**Issue by finnmich** [MarimerLLC/cslaforum#259]
I still get a "operation argument types should be serializable" on my DataPortal_Fetch methods after upgrading to 4.6.500.
This is the same as in #212 and #204 

Example code that gives me a warning:
`private void DataPortal_Fetch(SingleCriteria<int> criteria){
}`

**Comment by rockfordlhotka** [comment]
Thank you for the info - @JasonBock can you see what's up with this?

**Comment by lgJohnMilazzo** [comment]
I'm getting them as well.  (4.6.500)

**Comment by jonnybee** [comment]
Why do you still use SingleCriteria? 

See: [http://forums.lhotka.net/forums/p/9295/44176.aspx](http://forums.lhotka.net/forums/p/9295/44176.aspx) 

> You can pass any single serializable value as a parameter to Create, Fetch or Delete. So SingleCriteria is now useless, since you can just pass a single value.

**Comment by finnmich** [comment]
@jonnybee Thanks for the info! I'll have to do a huge refactoring job to remove all the uses of SingleCriteria, but it might be worth it :)
But it still shouldn't cause a compiler warning to use it though. (Or if it's obsolete, maybe the framework should display that as a warning?)

**Comment by rockfordlhotka** [comment]
Yes, there's clearly an issue here. Hopefully @jasonbock can take a look at some point.

**Comment by JasonBock** [comment]
My initial test shows that I do not get a warning for a method that has `SingleCriteria<>`:

![image](https://cloud.githubusercontent.com/assets/904213/19692875/37b2bf20-9a9f-11e6-8326-abb68d7dfdda.png)

Note that I have no squiggle for the argument that is defined with `SingleCriteria<int>`.

I'll keep digging....

**Comment by JasonBock** [comment]
A unit test is failing, so there's something going on....still digging....

**Comment by JasonBock** [comment]
So for some reason, when I run my VSIX, I don't see the problem, but a unit test will fail. And others are seeing this give a warning. I have no idea what is going on at this point :(

**Comment by JasonBock** [comment]
OK, I still haven't solved it, but the reason I don't see it when I launch the analyzers project as a VSIX is that it can actually analyze the source for `SingleCriteria<>`. If I make it a `List<>`, which is serializable because it's marked with the attribute, I do see the warning. So now I have a repeatable case that I can try and figure out how to make it work.

The key problem is trying to get a list of attributes from a type when you don't have source code, I think. So....I'll keep digging.

**Comment by lgJohnMilazzo** [comment]
Wish I could help, but thanks to @jonnybee I refactored out all of my SingleCriteria<>.    :)

**Comment by JasonBock** [comment]
As a side note, yes, `SingleCriteria<>` should be deprecated at least. But I still have an issue with my analyzer independent of this particular type...

**Comment by JasonBock** [comment]
So, some rather unfortunate news :(

This won't be fixed until the 2.1 version of the Compiler API. This talks about this issue in detail: https://github.com/dotnet/roslyn/issues/3898

So, until then, there really is no way to fix this problem :(

cc @rockfordlhotka

**Comment by rockfordlhotka** [comment]
I've added an issue regarding `SingleCriteria`: https://github.com/MarimerLLC/csla/issues/656

**Comment by JasonBock** [comment]
At this point, I'm going to close this and put the issue tracking on https://github.com/MarimerLLC/csla/issues/623, and reopen that one.
