### ISSUE TITLE
Csla.PropertyLoadException

### ISSUE THREAD

**Issue by javed007** [MarimerLLC/cslaforum#26]
Working in WPF, I am getting a baffling error that I never saw in SL.
I have a large object tree. The root object reads all the data from the database, and then calls a method  (SetParentAndModel), on each child. Child simply set the Model value to the object it receives.  This process goes down through the entire tree. Has worked like a charm in SL for > 2 years.
 
6 weeks ago, while converting to WPF, I ran into an error while the object tree was loading.  
Error : Items collection must be empty before using ItemsSource.
One or two of the objects have child collections, and it turned out that those collections were causing the error. After struggling with it for days, I dismantled much of the code, and while playing with it, just like that - for some reason, the error disappeared.  To this day, I have no idea why.  So much so that I have basically put everything almost (but not completely) back to how it was and everything has worked fine. 

Today, decided to include one last object that also has a single collection, and started getting the same error. Finally I decided to populate the object field by field from the object received from the parent. Everything went smoothly until I got to the child collection, and no matter what I did, I could not get rid of the error. After trying everything, I decided to separately create instance of the collection and then set the collection in the object to this new instance.  That is when I got the error Csla.PropertyLoadException.

It just so happened that while typing this message, and going back and meddling with the code, one time when I ran the application, the error simply did not come up. At first I thought I might have commented out some lines, but no.  I have put everything back, except that I instantiate the object and set each of its fields separately from the object sent by the parent (I was doing exactly that for about an hour and the error was still there). But now no error.  I have no idea why the error has stopped. I have checked under the table, behind the cabinet - I see no ghosts, no goblins, nothing.

Since I had started typing this message, I thought I might as well finish.  Perhaps more experienced people may have an explanation. 

Javed

**Comment by rockfordlhotka** [comment]
I don't know what's going on specifically, but I can tell you that the implementation of data binding in WPF is quite different in many ways from Silverlight (or Windows Forms). So perhaps you are hitting some timing issue within how WPF is binding your objects or something?

**Comment by javed007** [comment]
Thank you.
The good thing is that the issue has corrected itself. As long as it doesn't come back just as mysteriously, I am happy.
Javed
