### ISSUE TITLE
WP 8.1 still supported?

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/cslaforum#261]
I'm creating a sample application to explore how to incorporate Xamarin into our build process.

As far of this, I've created a business library and have started to add Csla (4.6.500) to all the projects; this was fine for Csla-Core, but when I try to add Csla-WindowsPhone I get an error which suggests that package hasn't been updated since Csla 4.5.

```
PM> install-package Csla-WindowsPhone

Attempting to gather dependency information for package 'Csla-WindowsPhone.4.5.701' with respect to project 'TeamCityXamarinTest.WinPhone', targeting 'WindowsPhoneApp,Version=v8.1'
Gathering dependency information took 202.79 ms
Attempting to resolve dependencies for package 'Csla-WindowsPhone.4.5.701' with DependencyBehavior 'Lowest'
install-package : Unable to resolve dependencies. 'CSLA-Core 4.6.500' is not compatible with 'CSLA-WindowsPhone 4.5.701 constraint: CSLA-Core (= 4.5.701)'.
At line:1 char:1
+ install-package Csla-WindowsPhone
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Time Elapsed: 00:00:00.6338891

```

The web page still says WinRT and WinRT Phone are still supported, which I thought was WP8.1.  The WP8.1 project was created when I added the xamarin shared code projects via the templates that come with the latest Xamarin.

Do I need this package, and if so, any chance to get it updated?  If I don't, what Csla packages should I be using for the various Xamarin UI projects?

**Comment by ajj7060** [comment]
Oh, nevermind, I think I want the Csla-WindowsPhoneWinRT package.

**Comment by rockfordlhotka** [comment]
That is correct.
