### ISSUE TITLE
Is it possible to turn off serialization?

### ISSUE THREAD

**Issue by aramka** [MarimerLLC/cslaforum#262]
I thought I remember reading somewhere that its possible to turnoff the serialization.

Is this the case? If so how?

Im not interested in N-tier configuration provided by CSLA. The business object does not need to be mobile.

**Comment by jonnybee** [comment]
Wee, you cannot turn off serialization but you may configure your app as en edge application, IE: an app that only use a local dataportal and does not serialize objects to another computer/process. 

The default behavior for editable objects is to make a clone of itself before calling save on that object. This is to keep the original object with a correct state - in the event that save fails and the transaction was rolled back. This is an option that you may disable (AutoCloneOnUpdate).

**Comment by aramka** [comment]
Thank you for your reply. Which of the E-books should I consult to configure my app as an edge application? Or is there other documentation I can consult?

**Comment by aramka** [comment]
Setting AutoCloneOnUpdate to false accomplished what I was looking for. The actual setting is

<appSettings> <add key="CslaAutoCloneOnUpdate" value="false" /> </appSettings>

Also, I found mention of this setting, how it works, and drawbacks of setting it to false in the

Serialization and AutoCloneOnUpdate

chapter of the

UsingCsla4-04-DataPortal

ebook.

Thank You for your help.
