### ISSUE TITLE
How to retrieve ID - MVVM? 

### ISSUE THREAD

**Issue by dglasses** [MarimerLLC/cslaforum#266]
Hello

How to I get the Id of new object created?

I save a model via DataPortal_Insert...which call web api...I get the id in DataPotal_Insert, but not viewmodel in WPF application.

Which event I need to use to get the id?

Thanks

**Comment by rockfordlhotka** [comment]
Make sure you are using the result of the Save method. That is a new instance of your object with the updated values. This is covered in the 'Using CLSA 4' eBook.
