### ISSUE TITLE
Missing reference to Csla?

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/cslaforum#267]
We currently have a WinForms app, and have just moved to .Net 4.6.2.  We're also going to be creating mobile applications using Xamarin Forms, the latest version.  To that end, we've changed our business library to be a shared solution and created a NET46 project (two actually, one for the WinForms client, and one for the data portal server which runs under Asp.Net).  

For Xamarin, I'm trying to determine how to support the business code on the various mobile applications, which are iOS, Android, and WP8.1.  I'm trying to keep the number of projects as small as possible, but at the very least I think I'll need a business rule project specifically for WP8.1, since it only supports NetStandard 1.2.  I've also tried creating a NetStandard 1.5 library for both iOS and Android, and I can reference everything fine, but when I compile both iOS and Android say I'm missing a reference to Csla-Core, even though they do have them.

My repo solution can be found here:  https://github.com/ajj7060/CslaMissingReference

It seems like this should work, but when I look at the Csla reference in the Xamarin projects, they are using Csla from MonoAndroid10 and MonoIOS10, not the NetStandard1.5, which I'm thinking is the cause of the compiler's confusion.  

Any ideas?  Do I just need to suck it up and create Android and IOS specific projects for the business code as well?

**Comment by rockfordlhotka** [comment]
The CSLA 4.6.500 support for netstandard is at version 1.6. Nothing supports 1.5. I don't think there's any official support by Xamarin for netstandard is there? Maybe 1.4 or something old?

CSLA has support for PCL Profile111 (starting I think in CSLA 4.6.400), and _that_ is what Xamarin uses for its PCL scenarios.

**Comment by ajj7060** [comment]
Thanks @rockfordlhotka .  I ended up doing a PCL with profile 151; that seems to work.  

The NuGet package for Csla includes a netstandard1.5 folder for version 4.6.500.  Should that be 1.6?

**Comment by rockfordlhotka** [comment]
Yes, I think so.
