### ISSUE TITLE
Porting the DalEf layer to .NET Core

### ISSUE THREAD

**Issue by lmsantin** [MarimerLLC/cslaforum#268]
Hello:

Has anybody ported the DalEf to .NET Core?
I created a project and referenced the NETStandard.Library 1.6 but I could not reference any CSLA-EFx.
I tried with a different project and referenced the NETStandard.Library 1.5.0-rc2-24027 and I couldn't reference any CSLA-EF.
Is it possible to create an edmx in .NET Core?

Thanks.

**Comment by jonnybee** [comment]
EF Core is Code-First only and there is no edmx support in EF Core. 

So to port DalEf to .NET Core (and EF Core) the easiest part i probably to generate code-first model from the database and then do whatever rework to match with the old edmx model.   

And Csla does not (yet) provide an Csla.EF7.Netstandard 1.6.
The name should probably be changed to Csla.EFCore1rather than EF7 as Microsoft renamed it to EFCore which is now out in version 1.0. And EfCore 1.1 is available in preview now.

**Comment by lmsantin** [comment]
@jonnybee after reading your response and taking into consideration how new are .NET Core and VS 2015 Tooling (this one is being released as a preview), I am concerned about the stability I have a question.
Would you use CSLA 4.6.500 and .NET Core for a web app that is supposed to be live in one year, or use CSLA 4.6.500 with .NET 4.6?

I would like to read @rockfordlhotka opinion too.
Thanks for your time.

**Comment by jonnybee** [comment]
You are probably aware that both ASP.NET Core and EFCore runtime is available for both DOTNETCORE 1.0 and .NET 4.5.1 and higher. You could even use ASP.NET Core on .NET framework with EF6 and CSLA for .NET.

Also ASP.NET Core will always run in Kestrel - whether you use DOTNETCORE or .NET framework. 

Yes, there is a lack in the tooling bits and the documentation could be better too. If you go the ASP.NET Core route then be sure to set aside extra time for research and knowledge building. There is also quite many NuGet packages that are just getting available on the platform or may not be ported yet (or ever).  

So I would look at how much is already invested in an application framework and infrastructure as well as developer knowledge combined with the project timeframe. It is a lot more to this than just selecting which CSLA version to use.

**Comment by lmsantin** [comment]
Thank you @jonnybee 
I won't port to .NET Core what we have made till now. It would be better that we keep our class library CSLA 4.6.500 with .NET 4.6 to meet our deadlines.
IMO, .NET Core environment (platform, tooling, NuGet packages, documentation, etc) is not as mature and stable as needed right now.

**Comment by rockfordlhotka** [comment]
I do think the future of .NET is based on .NET Core. But using it today will measure your patience and requires that you accept some serious risk - in particular risk in terms of change management as Microsoft figures out the platform and related tooling over the next 1-2 years.
So there's no one answer - you need to determine how much time/money you are willing to spend overcoming those challenges vs the benefits you hope to gain.

What are the benefits? Potentially being "future ready" or whatever. Also being able to run on Linux servers, and therefore Docker on Linux. I think that's about it. Oh, and it may look good on your resume - that is also true 😄

**Comment by lmsantin** [comment]
Thank you @rockfordlhotka for your opinion and your time. I agree with you and @jonnybee 
I'll close this issue.
