### ISSUE TITLE
Different scenario using LazyGetProperty, a Func<X, Y> valueGenerator is needed.

### ISSUE THREAD

**Issue by lmsantin** [MarimerLLC/cslaforum#269]
There are some issues about the LazyGetProperty method #239, [https://github.com/MarimerLLC/csla/issues/363](url) and [https://github.com/MarimerLLC/csla/issues/447](url). I had a different scenario, I needed a different valueGenerator function because I need to pass an object (criteria) to it.

Maybe in CSLA futures versions a solution for this could be included c.c @rockfordlhotka 
Some additions are needed in the client-side DataPortal and overloads to LazyGetProperty and related methods.

I solved it doing the following:

To generate a value, I need to use DataPortal.CreateChild<T>(object criteria). I could not use the current LazyGetProperty method because it is expecting a function like Func<P> valueGenerator and there is no parameter to pass a criteria.

Fortunately, I have an abstraction between BusinessBase class and my BO, so I overloaded the LazyGetProperty in my abstracted class:

```
 protected P LazyGetProperty<T1, P>(PropertyInfo<P> property, T1 criteria, Func<T1, P> valueGenerator)
 {
   if (!(FieldManager.FieldExists(property)))
    {
     var result = valueGenerator(criteria);
     LoadProperty(property, result);
    }
    return GetProperty<P>(property);
 }
```
I need a DataPortal Create method  which accepts a generic criteria so I created a static class called DataPortalExtensions and put the following method inside it:

```
public static TResult Create<T1, TResult>(T1 criteria)
 {
   return DataPortal.Create<TResult>(criteria);
 }
```
Finally I could defined the lazy property inside my class:
```
public static readonly PropertyInfo<MyList> ItemsProperty = RegisterProperty<MyList>(c => c.Items, RelationshipTypes.Child | RelationshipTypes.LazyLoad);
public MyList Items
 {
   get
    {
      return LazyGetProperty(ItemsProperty, Criteria, DataPortalExtensions.Create<Criteria, MyList>)
    }
   private set { LoadProperty(ItemsProperty, value); }
 }
```

Hope this help.

**Comment by rockfordlhotka** [comment]
Nice solution!

**Comment by lmsantin** [comment]
Thank you @rockfordlhotka
