### ISSUE TITLE
GetBrokenRules & Attributes

### ISSUE THREAD

**Issue by dglasses** [MarimerLLC/cslaforum#270]
Hello

I have required attribute on a column of a model. 

I am overriding AddBusinessRules method and adding a custom rule. When I call Mode.Save in my viewmodel and get the list of broken rules, I don't get required attribute as a broken rule, only the custom rule is listed.

But, If I remove the override or AddBusinessRules, I get the required attribute as broken rule.

Is it by design or I am missing something?

Thanks

**Comment by lmsantin** [comment]
Are calling the AddBusinessRules method in your base class?

```
        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
            //your rules here
        }
```

**Comment by dglasses** [comment]
Yes.

**Comment by lmsantin** [comment]
Are you calling the base class DataPortal_Create method when you create your object?

```
        protected override void DataPortal_Create()
        {
            using (BypassPropertyChecks)
            {

            }
            base.DataPortal_Create();
        }
```

**Comment by dglasses** [comment]
No, I was not calling base.DataPortal_Create(). I added it and I still do not get the required column attributes using GetBrokenRules() method.

**Comment by lmsantin** [comment]
Let's debug your code:

```
        protected override void DataPortal_Create()
        {
            using (BypassPropertyChecks)
            {

            }
            base.DataPortal_Create();
            //Add the following line an set a breakpoint on it
           var myObject = this;
        }
```
When you get to the breakpoint, check "myObject", it should have all the rules broken.
The rules will be broken till you assign a valid value to the property.

**Comment by dglasses** [comment]
Is it protected override or private void?

**Comment by dglasses** [comment]
I only get those broken rules which I added in AddBusinessRules, the Required attributes are not listed in the collection.

**Comment by lmsantin** [comment]
Could you put one required property here?

**Comment by dglasses** [comment]
[Column]
[Required]
public string Fax { get; set; }

**Comment by lmsantin** [comment]
-In your DataPortal_Create(), check the value myObject.Fax before exiting that method.
-Check the Mode.Fax value before call Mode.Save

**Comment by jonnybee** [comment]
This may be the behavior of the custom rule and caused by the custom rule making a short circuit of the rule processing. 

Could you post the custom rule here?

**Comment by dglasses** [comment]
internal class ValidOrder:BusinessRule
	{
		protected override void Execute(RuleContext context)
		{
			//TODO: these rules are fictitious and they are subject to further developments.
			var target = (Order)context.Target;

			if(string.Equals(target.Code,target.Description,StringComparison.CurrentCultureIgnoreCase))
			{
				context.AddErrorResult("Example:code and description cannot be the same!");
			}
		}
	}

**Comment by dglasses** [comment]
The value of fax is null in the DataPortal_Create and before the Model.save

**Comment by jonnybee** [comment]
So, the custom rule is an object rule?

If so it will only be executed when you call BusinessRules.CheckRules or BusinessRules.CheckObjectRules. It will not be executed when the property is changed as the Required rule will be.

**Comment by lmsantin** [comment]
I see, the property is working fine. Fax is a string so it's null in the Create and before calling Save because you haven't assign a value to it.

Is your custom rule a per-type rule?

**Comment by jonnybee** [comment]
Could you post a small sample project that show your issue? 

That would make it a lot easier to locate the problem.

**Comment by dglasses** [comment]
Hello Jonnybee

1. Not sure what you mean by CSLA style managed properties ( I added GetProperty(FaxProperty) and SetProperty(FaxProperty, value). Still did get see the failed rule in collection returned by GetBrokenRules method.

2. The ux is very simple. 
     a. WPF (prisim module) has order control and orderviewmodel. 
     b. Order control has save button.
     c. When save button is called
             I call BeginRefresh(callback => Models.Order.CreateNewOrder(callback))
     d. Then, I call Model.ApplyEdit and check if Model.IsValid and call Model.Save
     c. If Model is not valid. Following code:
            var brokenRules = Model.GetBrokenRules();

If I remove protected override void AddBusinessRules(), then I can see the properties marked with "Required" attribute in the collection returned GetBrokenRules(). But, as soon as I add AddBusinessRules method, I do not see the properties marked with "Required" attribute.

**Comment by dglasses** [comment]
Hello Everyone

I was able to resolve the. I did not realize that the custom rule was being added to a new ruleset and I was not changing the ruleset back to default.

Thanks
