### ISSUE TITLE
Adding common rule outside of class that inherits BusinessBase

### ISSUE THREAD

**Issue by JustinBourlier** [MarimerLLC/cslaforum#272]
I noticed that you can add IAuthorizationRules outside of the class, by doing Csla.Rules.BusinessRules.AddRule(typeof(T), New.Csla.Rules.CommonRules.IsInRole... etc)

However, is there anyway I can add IBusinessRules (such as .Required) in this same manner?  And if not, why not?  

In particular, I was hoping to store all of my rules in the database, and hydrate my Business Assembly on Application_Start or whenever rules are updated.

Thanks in advance,
Justin

**Comment by jonnybee** [comment]
Authorization rules for static DataPortal (type rules) must be added before the first object is created. That is the reason this is possible. 

Business rules on the hand is typically per-property rules and must have a reference to the static PropertyInfo objekt. Be aware that AddBusinessRules will only be called once per object type. The Cala rule engine should be considered static typed and each rule be viewed as a single instance.  There is no per-instance rules nor is there any provision for changing the rules once they have been initialized for a given object type! 

You could store rules in a database and initialize in AddBusinessRules for the given type. 

But if you need to "rehydrate" rules and have a very dynamic rule set (or per-instance rule) then you should probably use another external rule engine to be called from an object level business rule. You could still set messages on individual properties.

**Comment by JustinBourlier** [comment]
Okay that sort of makes sense.  So basically if I exposed the BusinessRules object utilized by my entity (by using a public wrapper), then I should be able to add these types of IBusinessRules outside of the class itself, and they will persist indefinitely or however long the AppDomain is running.   Am I understanding this correctly, that IBusinessRules won't have to be added every time the entity is instantiated?

**Comment by jonnybee** [comment]
The BusinessRules registry is quite encapsulated. I'm don't think you can register rules on outside of the class by just exposing the IBusinessRules. Look at the base class constructor that calls AddBusinessRules. 

IE: The constructor will call AddBusinessRules when no rules is registered for the given type in BusinessRuleManager. 

Look at Csla.Rules.BusinessRuleManager class. Most methods and properties are internal and not accessible for your code.

**Comment by JustinBourlier** [comment]
Thanks for your help, I was able to add these outside of the class.  In short, I created a function AddRules(IBusinessRule rule) in my business class.   Then in global.asax, I looped through the assembly, instantiating each business object, and adding the rule through my wrapper.  

To my amazement, that rule still persisted when newing up the object on other pages in the app.

**Comment by rockfordlhotka** [comment]
The rules are initialized one time per AppDomain, so they should survive until you web site is reset for any reason.

**Comment by JustinBourlier** [comment]
That's awesome, thank you both for the quick responses.  Really digging this framework.
