### ISSUE TITLE
HttpProxy not availble for WP8.1?

### ISSUE THREAD

**Issue by ajj7060** [MarimerLLC/cslaforum#275]
Still working on getting our Xamarin project going.  One thing I saw was that Csla seems to only have LocalProxy available if you're targeting Windows Phone 8.1.  Shouldn't HttpProxy be available here?  If not, what proxy should work if we need a remote data portal (which we do)?

**Comment by rockfordlhotka** [comment]
I think there's an open issue dealing with the fact that WcfProxy isn't on Xamarin at the moment. I _thought_ HttpProxy existed across all the platforms, but perhaps it somehow ended up excluded from WP8.1.

Would you open an issue to re-add it to that platform? Thank you.

**Comment by ajj7060** [comment]
@rockfordlhotka I've added the issue; thanks!

**Comment by ajj7060** [comment]
WP8.1 isn't going to be around much longer.
