### ISSUE TITLE
DataFieldManager throws and Exception when attempting to render a "Microsoft.Reporting.WinForms.LocalReport"

### ISSUE THREAD

**Issue by b1tburn3r** [MarimerLLC/cslaforum#28]
While having a custom IIdentity that is implemented using a Csla.ReadOnlyBase set in Csla.ApplicationContext.User, then attempting to render a LocalReport using the Local reporting services engine, we get the following exception.  

{"Failed to load expression host assembly. Details: Attempt by method 'Csla.Core.FieldManager.FieldDataManager.ForceStaticFieldInit(System.Type)' to access field 'Csla.ReadOnlyBase`1<SSRSClientCSLAIdentityBug.TestIdentity>.CS$<>9__CachedAnonymousMethodDelegate5' failed."}

The problem happens during the LocalReport.Render() call - it looks like the FieldDataManager is attempting to read an anonymous delegate using reflection.  (I stepped into the CSLA code to the exact place where it occurs (FieldDataManager.cs Line 967).

I should also mention that this issue does not happen in version 4.6.* beta.

**Comment by b1tburn3r** [comment]
FWIW: I have a small console app solution (less than 100 lines of code) with the correct NuGet Packages installed for the report render stuff from Microsoft that reproduces this issue.

**Comment by rockfordlhotka** [comment]
I'm totally unfamiliar with this reporting technology. It is something built into Windows Forms?

**Comment by jonnybee** [comment]
There's a lot of posts in the old forum about ReportViewer:
http://forums.lhotka.net/search/SearchResults.aspx?q=reportviewer 

I know there has been many difficulties - inlcluding IIRC that ReportViewer runs as a separate process under WindowsIndetity when run on a client computer. There is lots of information on the Microsoft forums as well on how to pass a CustomIdentity to ReportViewer,

**Comment by b1tburn3r** [comment]
This is not the report viewer control, it is a Local reporting engine that renders RDLC files (as opposed to Rdl which Ssrs uses).  I am fairly new to it as well and was introduced to it by another consultant at our company (they are using it on their project).   I have a console application solution with about 100 lines of code that has the Client Side Reporting engine installed from NuGet if you would like to see the jist of what we sre doing (Just rendering an RDLC file in the LocalReport class).  When I stepped through the CSLA code, there appeared to be an extra property getting added to our identity class that was not in our code which the FieldDataManager was throwing an exception on when trying to read it during the LocalReport.Render() call. (i didn't go deeper than that to see how or why this new field was added). This happened on our identity class at my current client so I wrote a bare bones example to demonstrate what is happening so I can safely share it if you are interested in seeing it.

**Comment by b1tburn3r** [comment]
I got it working...

So thinking about this after my last reply right before my drive into work, johnnybee got me thinking - maybe it's some kind of Code Access permissions issue where the client reporting engine is trying to access the "CS$<>9__CachedAnonymousMethodDelegate5" of ReadOnlyBase<T> but is restricting access to that anonymous delegate field in ReadOnlyBase<T>.  

So I snagged the code from FieldDataManager in the ForceStaticFieldInit(Type) call and ran it inline after I set the principal in my ApplicationContext to see if I could run the same code outside of the LocalReport.Render() call (just to see if it would throw the same exception).  Low and behold it allowed me to do it (I was suspecting that it would otherwise other people would have ran into this a long time ago).

Poking around inside the LocalReport class I found a method called SetBasePermissionsForSandboxAppDomain(System.Security.PermissionSet).  the PermissionSet constructor takes an enum of "PermissionState" which has an option for "Unrestricted".  Setting this before calling Render on the LocalReport allows the FieldDataManager to call fields[0].GetValue(null) on the "CS$<>9__CachedAnonymousMethodDelegate5" field when it comes up.

FWIW:  When I ran the same sample application while referencing the CSLA 4.6 beta - the problem went away (and this anonymous delegate method was not in the field list for ReadOnlyBase<T> which is why I brought it up - I assumed something was taken out in 4.6 that made this field in ReadOnlyBase<T> unnecessary).

**Comment by jonnybee** [comment]
Actually: You are using the Report Viewer and this is owned by the SqlServer team. 
You are just using this fr rendering reports locally - but it is still the ReportViewer control.

**Comment by b1tburn3r** [comment]
I am sorry, I'll admit that I don't know anything about SSRS or the Report Viewer as I have never worked with either before - (the project this is being used on is not my team so I am coming in blind from that perspective as well).  To clarify what I meant, when I said they were not using the Report Viewer - I meant they were not using the Report Viewer UI component.  Yes, as a whole they are using the Report Viewer Libraries.

Thanks for your help! :-)
