### ISSUE TITLE
Use CSLA for auditing?

### ISSUE THREAD

**Issue by PeterConchaR** [MarimerLLC/cslaforum#287]
Hello community,
We have CSLA v2.0.50727, and they are asking me to take an audit check. So I would like to know if:
- ¿Can I know With CSLA what properties of my object have changed?
- ¿What recommendations do I have for mapping table names and fields in my database, with the values and names of my properties?, We intended to use custom annotations on properties; Although we are investigating how.

The purpose is to be able to save in a table that values changed of a certain field and table. Example.

Audit_table
Audit_id
Field_name
value
Table_name
Row_id

**Comment by rockfordlhotka** [comment]
You control the persistence of data in your database, not CSLA. So yes, you can do this by adding the necessary code in your data access layer.

**Comment by jonnybee** [comment]
SqlServer offers sthis out of the box.

You can also build this in the data access layer with f.ex. Entity Framework. 

CSLA is not an ORM. It is for business objects. CSLA 2.0 is a long way back and I assume the app hasn't been updated in a while.
