### ISSUE TITLE
Execute not getting called consistently in AuthorizationRule

### ISSUE THREAD

**Issue by JustinBourlier** [MarimerLLC/cslaforum#289]
I'm kind of pulling my hair out on this one, but quite frequently, my AuthorizationRule class isn't being called.  I have base.CacheResult = false;

Any reason why this can happen?  It's not consistent, sometimes it calls it, sometimes it won't.  My control is in a telerik RadWindow, dunno if that would make any difference.

Breakpoint is hitting HasPermission line, but "Execute" method isn't being called.

My HasPermission call:
Csla.Rules.BusinessRules.HasPermission(AuthorizationActions.EditObject, businessObject.GetType())
`
public class SummaryTopicAuthorization : AuthorizationRule
    {
        private AuthorizationActions _action;
        private IPropertyInfo _property;
        public SummaryTopicAuthorization(AuthorizationActions action, IPropertyInfo property) : base(action, property)
        {
            base.CacheResult = false;
            _action = action;
            _property = property;
        }

        public SummaryTopicAuthorization(AuthorizationActions action)
            : base(action)
        {
            base.CacheResult = false;
            _action = action;
        }

        protected override void Execute(AuthorizationContext context)
        {
            var summaryTopic = context.Target as CCAM.Business.SummaryTopic;

            if (_action == AuthorizationActions.WriteProperty)
                ExecuteWritePropertyAuthorization(context, summaryTopic);
            if (_action == AuthorizationActions.EditObject)
                ExecuteEditAuthorization(context, summaryTopic);
        }

        private void ExecuteEditAuthorization(AuthorizationContext context, Business.SummaryTopic summaryTopic)
        {
            var user = Csla.ApplicationContext.User;
            var userIdentity = user.Identity as CustomIdentity;

            if (summaryTopic != null)
            {
                if ((user.IsInRole("Relationship Manager") || user.IsInRole("LOB Manager")) && 
                    userIdentity.IsInLob(summaryTopic.SummaryMember.Cohort.BusinessGroup) &&
                    summaryTopic.SummaryMember.SummaryStatusID != (int)Constants.SummaryStatus.Complete)
                    context.HasPermission = true;

                if (user.IsInRole("COG Manager") || user.IsInRole("Reviewer") &&
                    summaryTopic.SummaryMember.SummaryStatusID != (int)Constants.SummaryStatus.Complete)
                    context.HasPermission = true;
            }
        }

        private void ExecuteWritePropertyAuthorization(AuthorizationContext context, Business.SummaryTopic summaryTopic)
        {
            var user = Csla.ApplicationContext.User;
            var userIdentity = user.Identity as CustomIdentity;

            if (summaryTopic.SummaryMember != null)
            {
                if (_property == Csla.Core.FieldManager.PropertyInfoManager.GetRegisteredProperty(summaryTopic.GetType(), "LOBResponse"))
                {
                    if ((user.IsInRole("LOB Manager") || user.IsInRole("Relationship Manager")) &&
                        userIdentity.IsInLob(summaryTopic.SummaryMember.Cohort.BusinessGroup) &&
                        summaryTopic.SummaryMember.SummaryStatusID == (int)Constants.SummaryStatus.InReview)
                    {
                        context.HasPermission = true;
                    }

                    if (user.IsInRole("COG Manager") || user.IsInRole("Reviewer"))
                        context.HasPermission = true;
                }
            }
        }
    }
`

**Comment by JustinBourlier** [comment]
Still totally stuck on this.  On initial load / checking, the Execute method calls.  After that, it doesn't get called, even tho I'm calling HasPermission.   Also, on the initial call, it always returns false (as expected) because my object is null.  However, once it stops calling Execute it suddently magically returns true when I call HasPermission.  I put a breakpoint everywhere on context.HasPermission=true, which never gets hit.

Still stumped.

**Comment by jonnybee** [comment]
There are 2 different levels of Authorization rules. 

EditObject, CreateObject, DeleteObject is only enforced by the DataPortal _before_ the objects are created and these are checked by the static BusinessRules.HasPermission methods. The result of these authorization rules are never cached. The target object is always null. 

WriteProperty, ReadProperty and Execute method are checked by SetProperty/GetProperty and CanExecuteMethod and use the instance property BusinessRules.HasPermission methods. The result of the authorization rule is cached when CacheResult = true. Target object is supplied as the actual BO instance. 

And there is one more restriction. There can only be one - 1 authorization rule per Type, AuthorizationAction and PropertyInfo/MethodInfo.  You might be able to register more than one AuthorizationRule but the rule engine will only call one rule (uses First() verb on rule collection).

**Comment by JustinBourlier** [comment]
**EditObject, CreateObject, DeleteObject is only enforced by the DataPortal before the objects are created and these are checked by the static BusinessRules.HasPermission methods. The result of these authorization rules are never cached. The target object is always null.**

So how come when I call: Csla.Rules.BusinessRules.HasPermission(AuthorizationActions.EditObject, typeof(CCAM.Business.SummaryTopic))  the Execute method isn't always hit in SummaryTopicAuthorization class?  

I added the rule like this in the public static void AddObjectAuthorizationRules() method
            Csla.Rules.BusinessRules.AddRule(typeof(SummaryTopic), new CCAM.Business.Rules.Summary.SummaryTopicAuthorization(AuthorizationActions.EditObject));

**Comment by jonnybee** [comment]
Do you use RuleSets? 

All the static HasPermission comes into this actual method: 

    private static bool HasPermission(AuthorizationActions action, object obj, Type objType, string ruleSet)
    {

      if (action == AuthorizationActions.ReadProperty ||
          action == AuthorizationActions.WriteProperty ||
          action == AuthorizationActions.ExecuteMethod)
        throw new ArgumentOutOfRangeException("action");

      bool result = true;
      var rule =
        AuthorizationRuleManager.GetRulesForType(objType, ruleSet).Rules.FirstOrDefault(c => c.Element == null && c.Action == action);
      if (rule != null)
      {
        var context = new AuthorizationContext { Rule = rule, Target = obj, TargetType = objType };
        rule.Execute(context);
        result = context.HasPermission;
      }
      return result;
    }

And there is absolutely no caching here.

**Comment by JustinBourlier** [comment]
I do use rulesets on other object types, but not on this one.

This is the authorization rules I have added to it.  From looking at that code there, it looks at only rulesets by type, so no, there are no rulesets on this type.  :
            Csla.Rules.BusinessRules.AddRule(typeof(SummaryTopic), new CCAM.Business.Rules.Summary.SummaryTopicAuthorization(AuthorizationActions.EditObject));
            Csla.Rules.BusinessRules.AddRule(typeof(SummaryTopic), new CCAM.Business.Rules.Summary.SummaryTopicAuthorization(AuthorizationActions.WriteProperty, _lOBResponseProperty));

**Comment by JustinBourlier** [comment]
The really baffling part to this, is that function returns true!  Yet I put a breakpoint on context.HasPermission = true, and that's never touched.   

My first pass on .HasPermission (when the object is null) hits it, but subsequent checks when the object is not null, don't hit it.

**Comment by JustinBourlier** [comment]
You were right, the RuleSet was throwing things off.  I'm a little bit confused as to why it would tho.  Here is the code that was causing the issues.  As you can see, the object type here is "Cohort", and the rule it's running is "SummaryAuthorization" which is different than SummaryTopicAuthorization which was not getting hit.  Is it because these objects are linked in this way -> cohortObj.Summary.SummaryTopic which is causing the Cohort ruleset to override the SummaryTopic ruleset?

`            Csla.ApplicationContext.RuleSet = Rules.RuleSet.Summary;
            Csla.Rules.BusinessRules.AddRule(typeof(Cohort), new CCAM.Business.Rules.Summary.SummaryAuthorization(AuthorizationActions.EditObject));`

**Comment by JustinBourlier** [comment]
Yup, I'm back to being dumbfounded, ,but atleast I know which lines are causing the issue.  I checked Csla.ApplicationContext.RuleSet, and it's returning default after retrieving my SummaryTopic object (which is what I would expect), yet it still bypasses that Execute function if I leave those lines in the previous comment in the code.

**Comment by jonnybee** [comment]
IIRC the Csla.ApplicationContext.RuleSet is to support a multi-tenant environment so that the app can be configured with different sets for all types on a per tenant basis. When you set a new ruleset name her it affects ALL the static HasPermission calls for ALL types. 

Then there is the possibility of having different RuleSets on the BusinessRules that are called via the BusinessRules instance property in the BOs. These methods use the BusinesssRules.RuleSet to select the rules. 

I have never needed to change the static Csla.ApplicationContext.RuleSet in my apps (just left it at default) but I have used the instance BusinessRules.RuleSet to have different sets of BusinessRules and AuthorizationRules that can be selected (ie set BusinessRules.RuleSet in either DataPortal_Create or DataPortal_Fetch).

Also - if there is no AuthorizationRule for the given type type and AuthorizationAction the default value  is true.

**Comment by JustinBourlier** [comment]
Ohhhhhhhh, thank you so much for the explanation.  I was definitely using it all wrong.  It's basically like an HttpContext then, in that manner.
