### ISSUE TITLE
Business Rules and PropertyChanged event

### ISSUE THREAD

**Issue by bradtwurst** [MarimerLLC/cslaforum#292]
I have a business rule where a property is being calculated based upon the value of other properties.

The business rule fires properly and the property changes, but I don't get a PropertyChanged event fired for the calculated property.

The business rule is using AddOutValue(calcPropInfo, value) to update the calculated value and the value changes from its previous value.

In winforms using the DataBindings, the value is updated on the screen.
In wpf using PropertyChanged, the value is not updated as the event is not fired.

I assume that I am missing something simple, but I just am not seeing it.

Any help is greatly appreciated.

**Comment by jonnybee** [comment]
Which version of CSLA do you use? 

Check the CSLA PropertyChangedMode in your config file. It should NOT be Windows for a WPF application.

**Comment by bradtwurst** [comment]
Thanks for the feedback.

The underlying situation was that we needed to use CascadeOnDirtyProperties to deal with multiple levels of rules and that CascadeOnDirtyProperties is an instance flag.
