### ISSUE TITLE
RelationshipTypes Enum

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#297]
Hi All,
In the samples projects I can't seem to find a child reference  with RelationshipTypes enum, is this no longer recommended ?

Thanks

**Comment by tfreitasleal** [comment]
Because of CslaGenFork code generation, a few years ago I checked CSLA's source code and found out RelationshipTypes.Child is never used. I just re-checked and it's not used.
I guess it's like those database engines that store the foreign key but do nothing about...

**Comment by Chicagoan2016** [comment]
Thanks for your reply, Should we use the RelationshipTypes enum or is it optional?

Regards

**Comment by tfreitasleal** [comment]
You should use RelationshipTypes LazyLoad and PrivateField. None is set by default on PropertyInfo

`// Default value is ManagedField`
`private RelationshipTypes _relationshipType = RelationshipTypes.None;`

Child is completely useless.

**Comment by rockfordlhotka** [comment]
As I recall, we thought we needed that enum and it ended up in the design, but in the end it wasn't necessary. It is probably something we should remove from the codebase.

**Comment by Chicagoan2016** [comment]
Thank you all for your help
