### ISSUE TITLE
overloading Dataportal_Insert and Update

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#299]
Hi All, 
I know we can overload Dataportal_Create and Dataportal_Fetch methods ( seen them in samples code) but could we overload Dataport_Insert and update methods? will we need to override Save method in our classes to that?

Thanks

**Comment by jonnybee** [comment]
No - you cannot not overload the DataPortal_Insert or DataPortal_Update. 

A BO should be Autonomous and contain all the values that is required for saving. 

Some alternatives: 

1. You could add extra properties to the BO 
2. You could create a CommandObject that hold extra properties/object as well as the actual BO.
3. You can add extra objects to ApplicationContext.XYZ_Context and these will also move over to the server
4. ApplicationContext.User (principal object) is also transferred as context

Theis is the signature for IDataPortalServer:

    Task<DataPortalResult> Create(Type objectType, object criteria, DataPortalContext context, bool isSync);
    Task<DataPortalResult> Fetch(Type objectType, object criteria, DataPortalContext context, bool isSync);
    Task<DataPortalResult> Update(object obj, DataPortalContext context, bool isSync);
    Task<DataPortalResult> Delete(Type objectType, object criteria, DataPortalContext context, bool isSync);

and as you can see there is no criteria object in Update method.

**Comment by Chicagoan2016** [comment]
Thank you Jonny,
I like the idea of CommandObject if need arizes to call different stored procs for inserts or updates.
