### ISSUE TITLE
The case of the ApplicationContext.ClientContext disappearance 

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#3]
Moving this thread to GitHub. Original is here: http://forums.lhotka.net/forums/t/12029.aspx

**Comment by jteneglio** [comment]
That's not what I'm doing here, this object in particular is both a root and a child but in different circumstances.  In the one I showed here I believe it is a Root , but I doubt that this is related to the issue of the context being lost????

**Comment by rockfordlhotka** [comment]
I'm trying to understand exactly what you are doing so I can create a simple repro of the scenario.

**Comment by jteneglio** [comment]
I was thinking of reproducing it in a smaller app so it would be easy to debug... but didn't have the time yet :-D but i'm getting there

**Comment by rockfordlhotka** [comment]
ok, that would be very helpful in trying to solve the problem

**Comment by jteneglio** [comment]
In CSLA does every call coming from the WinRT to the server a new thread?

**Comment by jteneglio** [comment]
I'm using pretty much the code in The Using CSLA Data Portal Configuration book, Page 94 and up
I've added some Debug Lines and these troubles me (maybe I'm wrong but ), the number at the end of each debug lines are Thread.CurrentThread.ManagedThreadId

2015-06-15 07:03:12.940 Authorize FirstRun In 33           <--- Authorise the first time from UI
2015-06-15 07:03:12.941 CustomePrincipal Load In 33   <--- Load principal
2015-06-15 07:03:12.942 Authorize Else In 33                <-- this is the else of the authorize code?? 
2015-06-15 07:03:12.943 Authorize Else Out 33             <-- Out of the else ???
2015-06-15 07:03:12.944 CustomIdentity LoadUserData in 33 
2015-06-15 07:03:12.959 CustomIdentity LoadUserData Out 33
2015-06-15 07:03:12.960 CustomePrincipal Load Out 33     <-- Finish the load of the principal
DBQueryStop 06/15/2015 11:03:13.226  GenericCount    <-- Continue with our code
2015-06-15 07:03:13.230 Authorize FirstRun Out 33       <-- Finish the authorize code
Microsoft.WindowsAzure.ServiceRuntime Verbose: 500 : Role instance status check starting
Microsoft.WindowsAzure.ServiceRuntime Verbose: 502 : Role instance status check succeeded: Ready
2015-06-15 07:03:21.974 Authorize FirstRun In 18
2015-06-15 07:03:21.974 CustomePrincipal Load In 18
2015-06-15 07:03:21.975 Authorize Else In 18
2015-06-15 07:03:21.975 Authorize Else Out 18
2015-06-15 07:03:21.976 CustomIdentity LoadUserData in 18
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/1273337584/ROOT-1-130788827683073723): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. 
2015-06-15 07:03:21.989 CustomIdentity LoadUserData Out 18
----------------------
---- CONTEXT LOST ----
----------------------
2015-06-15 07:03:21.991 CustomePrincipal Load Out 18
The thread 0x300 has exited with code 0 (0x0).
The thread 0x2938 has exited with code 259 (0x103).
The thread 0x5288 has exited with code 259 (0x103).
The thread 0x7348 has exited with code 259 (0x103).
The thread 0x5374 has exited with code 259 (0x103).
The thread 0xa88 has exited with code 259 (0x103).
The thread 0x4264 has exited with code 259 (0x103).
The thread 0x4644 has exited with code 259 (0x103).
The thread 0x27a8 has exited with code 259 (0x103).
The thread 0x318c has exited with code 259 (0x103).
The thread 0x710c has exited with code 259 (0x103).
The thread 0x6d44 has exited with code 259 (0x103).
The thread 0x4a94 has exited with code 0 (0x0).
Microsoft.WindowsAzure.ServiceRuntime Verbose: 500 : Role instance status check starting
Microsoft.WindowsAzure.ServiceRuntime Verbose: 502 : Role instance status check succeeded: Ready
2015-06-15 07:04:37.134 Authorize FirstRun Out 18

**Comment by rockfordlhotka** [comment]
ASP.NET (that's what's hosting the data portal on the server) handles each client request separately. It uses a thread pool to handle the requests, so it reuses threads all the time, but if more than one client request occurs at the same time then yes, they'll be in different threads.

**Comment by halloween8** [comment]
I've build a sample app that replicate the issue i'm having but i cannot add it, cant I send it to you, Rockford?

**Comment by rockfordlhotka** [comment]
Put it in onedrive/dropbox/google drive/box/etc. and post a link?

**Comment by jteneglio** [comment]
https://onedrive.live.com/?id=F07DB383718C20E5%21139&cid=F07DB383718C20E5&group=0

CSLATestApp.zip

Here is the project  I've build that replicates the issue. This project includes a windows azure backend and a Windows 8 front end.  You need to start the azure backend first then the front end, In the front end there is 3 buttons, one to login, and 2 others, to replicate the issue, click on the button on the left, then right, then left again.  If my conditional break point stayed with the project it should stop in the AuthorizeDataPortal.Authorize on any of those lines, "never" the same one

 var userID = ApplicationContext.ClientContext["UserId"];
 var userUID = ApplicationContext.ClientContext["UserUID"];
 var employeeUID = ApplicationContext.ClientContext["EmployeeUID"];
 var languageCode = ApplicationContext.ClientContext["LanguageCode"];
 var workingDate = ApplicationContext.ClientContext["WorkingDate"];
 var otherData = ApplicationContext.ClientContext["SomeOther"];
 var another = ApplicationContext.ClientContext["Another"];
 var lastOne = ApplicationContext.ClientContext["LastOne"];

Thanks for looking at it.

**Comment by jteneglio** [comment]
Any luck replicating?

**Comment by rockfordlhotka** [comment]
I think the business rule idea is a red herring. I put a breakpoint in the rule and it is never executed.

**Comment by rockfordlhotka** [comment]
Your breakpoint didn't make it to me, and I don't see what's failing for you. I put a couple lines at the very top of the Authorize() method
```
      var tmp = Csla.ApplicationContext.LocalContext["FirstRun"];
      var tmpuser = ApplicationContext.ClientContext["UserId"];
```
And those two fields seem to be containing the correct values as I click the buttons.

**Comment by jteneglio** [comment]
Indeed the business rule is not the problem, I've put a conditional break point with this in it

Csla.ApplicationContext.ClientContext.Count == 0 

on line 44 through 51 in AuthorizeDataPortal

And sometimes it stops on the second, some times on the third....

**Comment by rockfordlhotka** [comment]
So you are saying that some code is running _during_ the Authorize() call that is clearing the context?

**Comment by jteneglio** [comment]
It would seem yes

**Comment by jteneglio** [comment]
Hard issue or is it me :-)

**Comment by fmongeau** [comment]
Hi there Rocky. Jean works with me. This is a rather big thing for us. You could say that we "bet the company" on CSLA (perhaps more than the Company :) I've been a fan of CSLA for more than a decade but this is our first app on the WIndows8/Modern/WinRT pltform. This is a multi-user app that has difficulties being multi-users.
Any help would be much appreciated. Is there any clarification or anything else I (or Jean) can do to help you help us? Thank you very much.
PS. We met in Vegas last year. I do remember you, but I understand if you don't remember me ;) Cheers!

**Comment by jonnybee** [comment]
Hi, 

I have been able to reproduce the issue and after hours of debugging and instrumenting the code I believe I have found the underlying issue and fix. Email is sent to Rocky. 

The issue is caused by the MobileRequestProcessor on the server side that does not set ExecutionLocation to Server. 

If you have the source code available you may make the change youselves to verify that this solves your issue: 
Change this method in Csla.Server.Hosts.Mobile.MobileRequestProcessor: 

	private void SetContext(IMobileRequest request)
	{
	  // JOB Add this line to set the ExecutionLocation
	  ApplicationContext.SetExecutionLocation(ApplicationContext.ExecutionLocations.Server);
	  ApplicationContext.SetContext(request.ClientContext, request.GlobalContext);
	  if (ApplicationContext.AuthenticationType != "Windows")
	ApplicationContext.User = request.Principal;
	  SetClientCultures(request);
	}

**Comment by fmongeau** [comment]
Thank you so much!!!!!!  We'll let you know soon!

**Comment by jteneglio** [comment]
A BIG THANKS to you Jonny, i tried the patch you just post and it seem to have fix it. NICE!!!!stop
