### ISSUE TITLE
Basic business rule - AffectedProperties

### ISSUE THREAD

**Issue by JustinBourlier** [MarimerLLC/cslaforum#305]
Straight from the book: The AddOutValue method can also be used to change other property values. In that case you must add those properties to the **AffectedProperties** list in the rule’s constructor. I’ll discuss the AffectedProperties list later in this chapter.

So why do I get this error?
Error	20	Property or indexer 'Csla.Rules.BusinessRule.AffectedProperties' cannot be assigned to -- it is read only

I simply want to set a boolean property to true if a property changes.  Here is my rule class.
`    public class SendResponseDueNotification : Csla.Rules.BusinessRule
    {
        public SendResponseDueNotification(IPropertyInfo primaryProperty, IPropertyInfo sendNotificationProperty) 
            : base(primaryProperty)
        {
            InputProperties = new List<IPropertyInfo> { PrimaryProperty };
            AffectedProperties = new List<IPropertyInfo> { sendNotificationProperty };
        }

        protected override void Execute(Csla.Rules.RuleContext context)
        {
            context.AddOutValue(AffectedProperties[0], true);
        }
    }`

**Comment by JustinBourlier** [comment]
Nevermind, I eventually found a post that showed just adding it to the collection.  The books could use an example of this since it's different than the examples of how primary properties are set.

For any other newbies, here's my first non authorization type of business rule (untested).  Essentially I want to set a flag that indicates I can send a notification if they change a date on one of my properties.

`   
 public class SendResponseDueNotification : Csla.Rules.BusinessRule
    {
        public SendResponseDueNotification(IPropertyInfo dueDateProperty, IPropertyInfo sendNotificationProperty)
            : base(dueDateProperty)
        {
            InputProperties = new List<IPropertyInfo> { dueDateProperty };
            AffectedProperties.Add(sendNotificationProperty);
        }

        protected override void Execute(Csla.Rules.RuleContext context)
        {
            if (!(context.Target as BusinessBase).IsNew)
            {
                var dueDate = (DateTime)context.InputPropertyValues[PrimaryProperty];
                if (dueDate != DateTime.MinValue)
                    context.AddOutValue(AffectedProperties[0], true);
            }
        }
    }
`

**Comment by jonnybee** [comment]
There is a lot of useful sample rules in the csla/Samples/NET/cs/RuleTutorial/ solution.

**Comment by JustinBourlier** [comment]
thanks Johnny.  Sure wish my work would let me install vs2015 already so I could open these solutions in something other than a texteditor!  ha.

**Comment by tfreitasleal** [comment]
Hi Justin,

RuleTutorial is a VS2012 solution aas are most of the samples.

**Comment by JustinBourlier** [comment]
Can you point me to that version download?  The one I downloaded was vs2015.  Tried installing targeting pack for 2013 but no dice.
