### ISSUE TITLE
Implementation of DynamicListBase versus DynamicBindingListBase

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslaforum#307]
`DynamicListBase<T>where T : IEditableBusinessObject, IUndoableObject, ISavable, IMobileObject, IBusinessObject`

`DynamicBindingListBase<T> where T : IEditableBusinessObject, IUndoableObject, ISavable, IBusinessObject`

On `DynamicBindingListBase`, the type `T` doesn't have to implement `IMobileObject.`
Is this correct? If so, why the difference?

**Comment by rockfordlhotka** [comment]
`DynamicBindingListBase` is only useful for Windows Forms apps, and I think the assumption was that if you were still using Windows Forms that you probably weren't using modern serialization techniques.

So that's probably a bug/oversight in reality.

**Comment by tfreitasleal** [comment]
I remember to change ProjectTracker  - and **ProjectTracker.Ui.WinForms** - so it uses 
`<add key="CslaDataPortalProxy" value="Csla.DataPortalClient.MobileProxy, Csla"/>`
`<add key="CslaDataPortalUrl" value="http://localhost:11170/WcfMobilePortal.svc"/>`

Shall I raise an issue and submit a PR?

**Comment by rockfordlhotka** [comment]
Yes, please.

**Comment by tfreitasleal** [comment]
Done.
