### ISSUE TITLE
Problem saving an object having Stream type property

### ISSUE THREAD

**Issue by ashishaon** [MarimerLLC/cslaforum#315]
Hi,
I have an object which has a property of Stream type. When I try to save the object we see that as soon as the call reach to the server, the value of Stream property gets null. I have below query:
Can we use Stream type property, keeping in mind its Serialization-Deserialization compatibility in CSLA?

Thanks

**Comment by jonnybee** [comment]
Stream is not a valid datatype that can be serialized to/from a server.
