### ISSUE TITLE
Is VB6 code supported along with .NEt 4.5 by CSLA 4.5

### ISSUE THREAD

**Issue by ramanbansalfis** [MarimerLLC/cslaforum#316]
Hi, My application is a mix of VB6 dll and .Net 4.5 dll. Now I am upgrading to CSLA 4.5 from 3.6. Will VB6 code be supported by 4.5. Please clarify

**Comment by jonnybee** [comment]
CSLA 4.5 (or 3.6 for that matters) has no dependencies to VB6 or support of VB6. It is only your .NET code that may have a dependency of VB6 dlls. I assume that your app is running on .NET Full Framework and CSLA 4.5 support .NET Framework 4.0 and newer.

**Comment by ramanbansalfis** [comment]
Thanks Jonny. This is what I was expecting. My VB6 dll is related to .Net only.
