### ISSUE TITLE
Windows 8 (WinRT) support

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#318]
**PLEASE PROVIDE YOUR FEEDBACK**

It looks like WinRT may not be supported in Visual Studio 2017 - which wouldn't be surprising given how old Windows 8 is, and how its market share has shrunk since Windows 10 has been out.

I'm working on the next CSLA release (4.6.600), and given that my intent is to at least create the .NET Core support using VS2017, I'm considering dropping WinRT support.

That would include these two platforms:

* Windows 8 WinRT
* Windows Phone 8 WinRT

Obviously there'll be continued support for:

* Xamarin iOS
* Xamarin Android
* Xamarin Forms (iOS, Android, UWP)
* Windows 10 UWP (PC, mobile, Hololens, Xbox)
* ASP.NET (full .NET)
* WPF (on all OS versions where you can use WPF)
* Windows Forms (on all OS versions where you can use WinForms)
* Console apps

And new support for:

* .NET Core (Windows, MacOS, Linux)
* ASP.NET Core

Any major objection to dropping WinRT?

**Comment by tonydrake** [comment]
Assuming that windows10Cloud will be based on W10 UWP.

**Comment by rockfordlhotka** [comment]
I'm pretty sure that's true @tonydrake, because if their new OS was somehow based on 3+ year old WinRT they'd still be supporting it in VS2017.

**Comment by tfreitasleal** [comment]
I guess the silence means no objection.

**Comment by fujiiface** [comment]
I have no objection.

**Comment by jonnybee** [comment]
No objection.

**Comment by russblair** [comment]
No objection.

**Comment by MarceloJGaray** [comment]
No objection.

**Comment by IvanKujundzic** [comment]
That's fine with me.  I'm excited about this release and looking forward to using the Core MVC.

**Comment by ajj7060** [comment]
I didn't see Windows Phone 8.1 on the list anywhere?  Would dropping WinRT also include dropping WP 8.1?  We are just starting rebuilding our mobile app with Xamarin, but are unsure if we would need to support WP8.1 at this point, but our current mobile app does support WP8.1.

**Comment by rockfordlhotka** [comment]
@ajj7060 Windows Phone 8.1 is a WinRT thing. Windows 10 Mobile is UWP.

Obviously CSLA 4.6.500 will continue to support WinRT (Win8 and WP8.1). 

The VS2017 solution I'm working against now no longer includes any WinRT projects, because they aren't supported in the new tooling. (or maybe they are if I install the WinRT SDK?)

**Comment by ajj7060** [comment]
I think we'd actually like to not support 8.1 at this point too, and this would be good argument not to.  Its more important to use to keep up on the latest Csla versions (and other dependencies).
