### ISSUE TITLE
How to test if one particular business rule is broken ( has AddErrorResult)

### ISSUE THREAD

**Issue by swegele** [MarimerLLC/cslaforum#322]
Given a string property "LabType" and a rule "IsLabTypeValidRule" pointed to the property info "LabTypePropertyInfo".  

I would like to add a boolean property on the business object that will report true if the rule is returning as broken (context.AddErrorResult...)

I don't remember having seen any examples of how to ask a business rule if it is reporting broken.

Thanks,

Sean

**Comment by jonnybee** [comment]
You need inspect the BusinessRules.BrokenRules, f.ex: 

      var ruleName = new MaxLength(NameProperty, 10).RuleName;

      var nameMaxLengthBroken = BusinessRules.GetBrokenRules()
            .Where(p => p.Property == NameProperty.Name)
            .Any(p => p.RuleName == ruleName);

If there is only one rule for a given property you could also just check for any broken rules on that property. You may also consider to check for Severity == RuleSeverity.Error.

**Comment by swegele** [comment]
Perfect.  I haven't ever dug into how the URI is formatted and I figured it was searchable from outside but didn't know how.

Thanks @jonnybee
