### ISSUE TITLE
safedatareader returns wrong values

### ISSUE THREAD

**Issue by philadefenderrob** [MarimerLLC/cslaforum#323]
I have a stored procedure that always returns a 0 or a 1 for a particular column ("ClosedCases"). It works correctly. However, when using SafeDataReader as follows, the returned value is not always correct. (note that it never returns some value other than 0 or 1)

Private Sub Map(ByVal reader As SafeDataReader)
            Using (BypassPropertyChecks) ...

LoadProperty(_hasClosedCaseData, Convert.ToBoolean(reader.Item("ClosedCases")))

Using the Immediate Window, the value for reader.Item("ClosedCases") does not always agree with the value returned from the stored proc.

**Comment by jonnybee** [comment]
I checked the latest code and Csla 3.8.4 code for SafeDatareader and there is no method .Item("fieldname") in SafeDataReader. Which version of Csla do you use? 

That may not necessarily be caused by SafeDataReader returning a wrong value. 
Convert.ToBoolean(val) will convert any numeric value that is not 0 to true. 

Example: 

    Convert.ToBoolean(1);       // returns true
    Convert.ToBoolean(0);       // returns false 
    Convert.ToBoolean(100);     // returns true 
    Convert.ToBoolean(02);	    // returns true 
    Convert.ToBoolean(11);	    // returns true 
    Convert.ToBoolean(11.3);     // returns true 
    Convert.ToBoolean(-11.3);    // returns true `

You must also make sure that the column name is unique. SqlServer/DataReader does not require fields to be unique in a select statement or reader.. 

If you are using SafeDataReader you should rather use 

    reader.GetBoolean("ClosedCases"); 

The actual code in SafeDataReader is: 

    public bool GetBoolean(string name)
    {
      return GetBoolean(_dataReader.GetOrdinal(name));
    }

    public virtual bool GetBoolean(int i)
    {
      if (_dataReader.IsDBNull(i))
        return false;
      else
        return _dataReader.GetBoolean(i);
    }

and these are just wrapper metods over the standard DataReader in .NET so I doubt this returns the wrong value. You should inspect your own code. Maybe the field _hasClosedCaseData is modified somewhere in your code?

**Comment by philadefenderrob** [comment]
Hi, and thanks for your quick response. We are using CSLA 4.3.13. The only values being returned for the unique column named "ClosedCases" by the stored procedure are integers values: 0 or 1.  This only appears to be an issue when the stored proc returns a 0 -> the reader.Item("ClosedCases") will sometimes read it as a 0 and sometimes as a 1. Note that I am inspecting it before the value is loaded into the _hasClosedCaseData property:

?reader.Item("ClosedCases")
1 {Integer}
    Integer: 1      *(should be 0)*

I have already tried to use GetBoolean in the way you mentioned above, but I get an InvalidCastException when I do:

A first chance exception of type 'System.InvalidCastException' occurred in System.Data.dll
{"Specified cast is not valid."}
    _className: Nothing
    _COMPlusExceptionCode: -532462766
    _data: {System.Collections.ListDictionaryInternal}
    _dynamicMethods: Nothing
    _exceptionMethod: {Boolean get_Boolean()}
    _exceptionMethodString: Nothing
    _helpURL: Nothing
    _HResult: -2147467262
    _innerException: Nothing
    _ipForWatsonBuckets: 1479989521
    _message: "Specified cast is not valid."
    _remoteStackIndex: 0
    _remoteStackTraceString: Nothing
    _safeSerializationManager: {System.Runtime.Serialization.SafeSerializationManager}
    _source: "System.Data"
    _stackTrace: {SByte()}
    _stackTraceString: Nothing
    _watsonBuckets: Nothing
    _xcode: -532462766
    _xptrs: 0
    Data: {System.Collections.ListDictionaryInternal}
    HelpLink: Nothing
    HResult: -2147467262
    InnerException: Nothing
    IPForWatsonBuckets: 1479989521
    IsTransient: False
    Message: "Specified cast is not valid."
    RemoteStackTrace: Nothing
    s_EDILock: {Object}
    Source: "System.Data"
    StackTrace: "   at System.Data.SqlClient.SqlBuffer.get_Boolean()     at System.Data.SqlClient.SqlDataReader.GetBoolean(Int32 i)     at Csla.Data.SafeDataReader.GetBoolean(Int32 i)     at Csla.Data.SafeDataReader.GetBoolean(String name)"
    TargetSite: {Boolean get_Boolean()}
    WatsonBuckets: Nothing

Thanks for your advice!

**Comment by philadefenderrob** [comment]
Sorry - didn't mean to close - please see last comment. Thanks!

**Comment by jonnybee** [comment]
That is because reader.GetBoolean (or actuall C#) get an exception on 
   return   (bool) int32value;

My recommendation is to explicitly cast the values to bit (as this is translated to boolen in DataReader)

    var conn = new SqlConnection(@"Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=Northwnd;Integrated Security=True");
    var cmd = new SqlCommand("select cast(1 as bit) as bool1, cast(0 as bit) as bool2");
    cmd.Connection = conn;
    conn.Open();
    var reader = new SafeDataReader(cmd.ExecuteReader());
    reader.Read();
    reader.GetBoolean("bool1").Dump();
    reader.GetBoolean("bool2").Dump();

You can run this code in LinqPAD amd the output is True and False.

**Comment by jonnybee** [comment]
Or you could just use

      reader.GetInt32("ClosedCases") == 1

**Comment by philadefenderrob** [comment]
Thanks - tried both suggestions, but neither work. This is really a head-scratcher...

**Comment by jonnybee** [comment]
In that case 

1. Make sure to inspect the entire resultset that is returned.  Use Linqpad og SqlServer Management Studie  to exeute the same SQL and dump everyting out. 
2. Inspect your code to verify that there is nothing else that modifies the value.

**Comment by philadefenderrob** [comment]
This appears to be a data issue. I'm sorry to have taken your time, and appreciate all your help.

Thanks again.
