### ISSUE TITLE
LoadProperty vs. BypassPropertyChecks

### ISSUE THREAD

**Issue by tsvideo** [MarimerLLC/cslaforum#33]
Hello !
What is for performance better in a Fetch / Load Routine ?
Load each Property with LoadProperty(.....)
or Set using (BypassPropertyChecks) and load each Property with this.MyProperty = ... ?
Also for a Write Routine
Use ReadProperty or Get Every Property by using (BypassPropertyChecks) ?
Thank you for an answer!
Thilo

**Comment by jonnybee** [comment]
Should be the same as SetProperty will perform as LoadProperty when inside BypassPropertyCheck.

**Comment by tsvideo** [comment]
OK Jonny, Thank you !
