### ISSUE TITLE
Analyzers: Enforce Assumptions for Rule Attributes

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/cslaforum#332]
When I was doing a talk on CSLA this past week, I started to wonder if something like this would make sense:
```
[Required]
public int Id
{
	get { ... }
	set { ... }
}
```
How could a value type be "required"? There's no way to determine if it's been set or not.

Similarly:
```
[StringLength(1000)]
public int Data
{
	get { ... }
	set { ... }
}
```
Wouldn't `StringLength` only make sense on a `string`-based property?

My point is, I wonder how many analyzer rules should be created for the rule attributes. Thoughts?

**Comment by rockfordlhotka** [comment]
Those come from Microsoft though - `System.ComponentModel.DataAnnotations' - so while I agree that having some analyzers would be really nice, I think they should go along with the DataAnnotations assembly (now package in .NET Core?).

**Comment by jonnybee** [comment]
Do many developers use DataAnnotations in their BOs? 

And shouldn't this be provided by Microsoft?

**Comment by ajj7060** [comment]
I agree that these should come from MS, not be part of Csla.  We do use DAs in our BOs as well.

**Comment by JasonBock** [comment]
"Do devs use DataAnnotations?" - I used to, but very recently I've started to move away from them because I like to be consistent, and having two ways of adding rules (attributes and `AddBusinessRules()`) seems klunky.

"Should these come from MS?" - Probably, but I wouldn't hold my breath waiting to see if they ever add them :).

**Comment by fujiiface** [comment]
I use DataAnnotations on properties for `[Display(Name = "Friendly Name")]` and inconsistently on controller/action methods (I know 👎 )

**Comment by JasonBock** [comment]
If the consensus is that we think either the analyzers for something like should come from MS (which I personally think will never happen), or that there's not a lot of value investing time into creating analyzers for these attributes, let's close this. Otherwise, I can start coming up with a couple of analyzer rules around them.

**Comment by rockfordlhotka** [comment]
I agree that Microsoft will likely never write these analyzers. But I'm also sure that they don't belong in CSLA, so I'll close this issue.
