### ISSUE TITLE
Resolving dependencies on CSLA server

### ISSUE THREAD

**Issue by vsinghal7** [MarimerLLC/cslaforum#335]
I have a web application in which consists of a client (UI), WEBAPI serverr and a CSLA/Application server.

There is a scenario  where I need to send values (which is saved in the WEBAPI autofac scope) from WebAPI to Application/CSLA server.

What is the most generic way to achieve that.

Thanks in Advance !!

Vinod

**Comment by rockfordlhotka** [comment]
Are you using the CSLA data portal to communicate from the web API server to the app server?

**Comment by vsinghal7** [comment]
Hi Rocky,

Yes, I am using CSLA data portal.

Thanks
Vinod

**Comment by rockfordlhotka** [comment]
The easiest way to flow "out of band" state from the client (your web API server) to the app server is by using `Csla.ApplicationContext.ClientContext`. This is a dictionary of serializable values that is automatically transferred over the data portal on each call.

**Comment by vsinghal7** [comment]
Hi Rocky,

Thanks for the solution, I have implemented the same and it works.
