### ISSUE TITLE
Creating Criteria

### ISSUE THREAD

**Issue by ashishaon** [MarimerLLC/cslaforum#345]
Hi, 
I want to give myself clarity about creating criteria class and instantiating it. 

For simple criteria we can simply use int, char, string etc which simplifies life. But for complex one, we need to create a class and pass its instance as criteria. Now my queries are:

Which is the best way of creating criteria structure:	
->Create a simple C# class.
->Create a class which have attributes of CriteriaBase.

Other question is, if we create CriteriaBase class, then what will be best way to instantiate:
->By using new keyword
->Using DP_Create of Criteria class.

Thanks

**Comment by jonnybee** [comment]
The critera class must/should be serializable by the builtin serializers in CSLA (ie: support MobileFormatter) and the simplest way to do this is to inherit from CriteriaBase. 

Use a ctor or the default ctor and set the properties on the instance. You should never call any DataPortal methods to get an instance.

**Comment by ashishaon** [comment]
Got clear idea on my point. Thanks
