### ISSUE TITLE
"List item must be marked as a child object" exception happens when deserializing

### ISSUE THREAD

**Issue by Arash-Sabet** [MarimerLLC/cslaforum#347]
Hello -
I have an object derived from BusinessBase with two list objects both derived from BusinessListBase. I am able to serialize the object to json by Newtonsoft successfully but when trying to deserialize it using Newtonsoft, the code throws the exception in the subject line. I could not find a CSLA-based solution for this issue but I implemented a workaround by employing a DTO object to serialize and deserialize through it. What's the other more concrete way (if any) to avoid getting the exception in the subject line? Thanks.

**Comment by rockfordlhotka** [comment]
I've never tried using Json.net to serialize a CSLA object graph.

Only full-fidelity serialization can be used to properly serialize a graph; things like XmlSerializer and JsonSerializer _will not work_.

I am reasonably certain the Json.net has advanced options to act like the BinaryFormatter or NetDataContractSerializer, and if configure Json.net to do full-fidelity serialization then it should work - but again, not something I've tested.

If your intent is to serialize the object graph for external clients - in other words you want to send the byte stream to a non-CSLA consumer, then you should read this: https://github.com/MarimerLLC/csla/wiki/JSON-Services

**Comment by Arash-Sabet** [comment]
Thanks Rocky for the tip. Full-fidelity works in my work context. I should have thought about it!
