### ISSUE TITLE
MVVM/WPF Validation Rule problem when creating new business object

### ISSUE THREAD

**Issue by xuanhnvt** [MarimerLLC/cslaforum#349]
Hi Rocky,

I'm new of CSLA Framework. I am using it to implement business layer for my MVVM/WPF application. Now, I have a problem with validation rule. I had object Area, and its properties are Code, Name, Description then I added rule **Required** to Code and Name. I binded the view model of Area object in Popup Window for editting. ViewModel code is show as below:
`public AreaViewModel(IMessageBoxService messageBoxService, IAreaManager manager) : base(messageBoxService)
        {
            // do initialization
            try
            {
                if (manager == null)
                {
                    throw new ArgumentNullException("manager");
                }

                _areaManager = manager;
               // Area constructor do nothing
                this.Item = new Area();
                this.DisplayName = "Create Area";

                // start edit item
                this.EditItemCommand.Execute(null);
            }
            catch (Exception ex)
            {
                this.MessageBoxService.ShowError(this.GetType().FullName + System.Reflection.MethodBase.GetCurrentMethod().Name + ": " + ex.Message);
            }

        }`
I expected popup will show broken rule message for Code and Name properties. Unfortunately, it didn't. 
Can you help me solve this problem? Thank you!

**Comment by ajj7060** [comment]
Area is a `Csla.BusinessBase<T>`?  If so, you can't new it up via the ctor.  You'll need to create a static factory method in area like this:

``public static Task<Area> NewAreaAsync() {
    return DataPortal.CreateAsync<Area>();
}``

It doesn't need to be async if you're doing WPF, although its probably the recommended approach since you have to do async in mobile (like Xamarin).   Also, it doesn't have to be a static factory method, if you want to unit test for example.  You could have an AreaFactory which has an instance method that calls the DataPortal.CreateAsync.

**Comment by xuanhnvt** [comment]
For some reason, my all business object are from Csla.Core.BusinessBase. I also had my own object factories. I will add a method like you show me. Thank you.

**Comment by ajj7060** [comment]
@xuanhnvt That's a bit odd; you'd normally inherit `BusinessBase<T>`, unless there was a specific case where you didn't or couldn't use the behavior defined there.

Regardless though to get instances of Csla objects you normally call `DataPortal.Create<T>` or `DataPortal.Fetch<T>` (or their async equivalents).  `CommandBase<T>` and `CriteriaBase<T>` are exceptions, but with commands normally the static factory method will call new (not code outside the class) and `CriteriaBase<T>` are not normally publically visible.

**Comment by xuanhnvt** [comment]
@ajj7060 I tried to replace my own business base class with generic BusinessBase<T> before, but it was difficult to make it work with existing derived objects I had. So I decided to inherit Csla.Core.BusinessBase. I see it's a bit odd, too.
Anyway, I solved my problem, thank you for your detailed answer, it give me useful information.

But could I have one more question here?
As you know, BusinessBase has property IsSavable, I bind it with property IsEnabled of button Save, for enabling user to save data or not. When I edit an object, change something, button Save is enabled, but when I change object back to old data like data in database, button Save is still enabled. In this case, I would like button Save is disabled, because I don't want to save unchanged data.
Do Csla framework have any method to notify all properties of object be unchanged while editting object?

**Comment by jonnybee** [comment]
Read this blog post from Jason Bock - creating custom field data.
http://www.jasonbock.net/News/Item/9cc70d85-bef3-4e2b-9a68-3ba82615f8a3   

Managed properties will normally not store the "original" value so when an object is marked as changed it will still be changed even if the values are "edited" back to the same as original values. So you need to create/configure a custom FieldData that stores the original value and override some methods from the business base class to determine if the object is dirty or not.

**Comment by xuanhnvt** [comment]
@jonnybee It works. Thank you so much.
