### ISSUE TITLE
N-Level Undo Problem: Child List Object just can undo one time.

### ISSUE THREAD

**Issue by xuanhnvt** [MarimerLLC/cslaforum#355]
Hi,

I have an object graph like below:

Product (inherit from BusinessBase<Product >)
      |--- Product Information (code, name, description, ...)
      |--- RecipeItemList (inherit from BusinessListBase<RecipeItemList , RecipeItem>)

I bind Product object with View (WPF Window) that show product info and list view of recipe items. When I edit product, add some recipe items into list (original list is empty), I try CancelEdit(), object undo correctly. I edit second time, I call BeginEdit() then modify product again, and cancel edit, this time recipe  item list can not undo. I try to fix the problem but can not. Could you help me find the reason? Please refer my below code:

**Product Class**
public class Product : IdCodeNameBaseObject<Product>
{
	...
	public static readonly PropertyInfo<RecipeItemList> RecipesProperty = RegisterProperty<RecipeItemList>(p => p.Recipes);
	public RecipeItemList Recipes
	{
		get
		{
			if (!FieldManager.FieldExists(RecipesProperty))
			{
				LoadProperty(RecipesProperty, DataPortal.CreateChild<RecipeItemList>());
				OnPropertyChanged(RecipesProperty);
			}
			return GetProperty(RecipesProperty);
		}
	}
	...
}

**Method to add RecipeItem**
private void ExecuteAddRecipeItemCommand(Material material)
{
	try
	{
		if (material == null)
			throw new ArgumentNullException("material");
		RecipeItem newRecipeItem = this.Item.Recipes.AddNew();
		if (this.Item.Recipes.Count == 0)
			newRecipeItem.Sequence = 0;
		else
			newRecipeItem.Sequence = (byte)(this.Item.Recipes.Max(o => o.Sequence) + 1);
		newRecipeItem.ProductId = this.Item.Id;
		newRecipeItem.MaterialId = material.Id;
		newRecipeItem.UsedAmount = 1;
		newRecipeItem.MaterialInfo = _materialManager.GetById(material.Id);
	}
	catch (Exception ex)
	{
		this.MessageBoxService.ShowError(this.GetType().FullName + System.Reflection.MethodBase.GetCurrentMethod().Name + ": " + ex.Message);
	}
}

**Comment by jonnybee** [comment]
It is impossible to tell from this code. You do not show how it is handled with BeginEdit/CancelEdit/EndEdit. 

Could you make a simple solution that shows your issue and share this with us? Preferrably in you own github repository.

**Comment by xuanhnvt** [comment]
@jonnybee Thanks for your response.

I made a simple solution (acctually it is a part of my entire software). I attach it below. Let me explain you something about it.

I use MVVM Cinch framework for UI, Csla for Business Objects, Mock some data for test and use AutoMapper to map BO and data entity.
This solution will show list of Products, each Product have one recipe including list of Materials (I called recipe items as above and this list can be empty). It enable user to create new, edit, and delete Product. When user create or edit product, it will show ProductPopup window for editing Product and its recipe. This window have button Save and Cancel (for undo testing).

I would like talk about Cancel button. This is my issue.
- When ProductPop show, I called Product.BeginEdit() in constructors of my own view model (ItemViewModel file).
- Then I start editing product, add material into recipe. I try pressing Cancel (it will call Product.CancelEdit() and Product.BeginEdit()), undo work correctly. Product and recipe list return to original data.
- Then I edit again, press Cancel. This time, undo can not work, recipe list not return to original list.

Please refer to below files in solution. Maybe they relate to my issue.
- ProductRepository.cs: get business object from mock data (using AutoMapper inside)
- ProductManager.cs: busisness logic service implementation
- ItemViewModel.cs: base ViewModel inherit from Cinch framework
- ProductViewModel.cs: inherit from ItemViewModel and I bind it with ProductPopup.

[XRMS.zip](https://github.com/MarimerLLC/cslaforum/files/988588/XRMS.zip)

**Comment by jonnybee** [comment]
You should change your code to use ISupportUndo rather than IEditableObject. 

                (_item as ISupportUndo).BeginEdit();

and 

                (_item as ISupportUndo).CancelEdit();
                (_item as ISupportUndo).BeginEdit();

and then your code will work as expected. 

IEditableObject has a very specific implementation that will only edit/undo the properties of the "object" whereas ISupportUndo will make a snapshot of the graph (object + children + grandschildren etc).

**Comment by xuanhnvt** [comment]
@jonnybee Thank you. I fixed it already.

I have one more issue with property IsDirty of each item of child list. I create new column of ListView and bind IsDirty with this column (for purpose, notify user which item has change). When I edit value of item, column IsDirty of this item change to "true", but when I edit back to original data, column IsDirty remain "true" even though value of IsDirty property is false.

Continue with my above project, in ProductPopup window, I create 2 button "+", "-" for modifying amount of each material of recipe list and add column IsDirty for checking state of IsDirty property.

Could you help me find out the reason? Please refer to link of project. Thank you again.

http://www.mediafire.com/file/lpao1w49dib41am/XRMS.zip

**Comment by jonnybee** [comment]
Read this post by Jason Bock [Creating Custom FieldData Classes in CSLA](http://www.jasonbock.net/News/Item/9cc70d85-bef3-4e2b-9a68-3ba82615f8a3)
