### ISSUE TITLE
Result in Command

### ISSUE THREAD

**Issue by ashishaon** [MarimerLLC/cslaforum#356]
I have a small query related to Command BO. In Command we use Result for:

- To Know whether execution completed successfully.

- Or, Set Result any value which is outcome of execution.

As per my understanding I thing second option is most suitable, still I want to clarify.

Thanks

**Comment by rockfordlhotka** [comment]
Either way is fine really.

The point of a _command_ object is that it represents some server-side operation.

If your goal is to retrieve a value then you should use a _read-only_ object.

However, it is certainly true that some server-side operations, as a side-effect, do return a value. And in that case it is perfectly find to return values as properties of a command object.

**Comment by ashishaon** [comment]
Got my answer. Thanks Rocky
