### ISSUE TITLE
CSLA Command objects

### ISSUE THREAD

**Issue by vsinghal7** [MarimerLLC/cslaforum#359]
Hi,

Just a general query.

Is it recommendable to use Command object for making DAL calls directly. Dal operation will be calling stored procedures , these SP's are for updating values in DB.

Thanks
Vinod

**Comment by jonnybee** [comment]
That depends on the context of when those stored procedures should be called. 

If it is in context of a Save operation on a BO then it should be done from within that Save operation. 
If it is a "standalone" operation then use a CommandObject.

**Comment by vsinghal7** [comment]
Thanks Jonny !!!!
