### ISSUE TITLE
WcfPortal, Client criteria reset at Serverside and List returned initialized on Clientside with empty childs.

### ISSUE THREAD

**Issue by AsadCheema** [MarimerLLC/cslaforum#36]
Hi All, i thing i am missing some configuration step, here are step to pull data:

Step1:
In WinRT App setup,
Using Csla 4.5.7 with Windows 8.1 Store App , App.xaml.cs OnLaunched event has
Csla.ApplicationContext.DataPortalProxy = typeof(Csla.DataPortalClient.WcfProxy).AssemblyQualifiedName;
Csla.ApplicationContext.DataPortalUrlString = "http://localhost/WcfAppServer/MobilePortal.svc";

 Step2:
 Xaml page call GetItemsInfoListAsync(1, 5)

Step3:
Bussines.Lib.WinRT passes pageIdx=1 and pgSize=5 to FilterCriteria object and calls DataPortal as
await DataPortal.FetchAsync<ItemsInfoList>(new FilterCriteria("ALL", pageIdx, pageSize, ItemImage.ItemImageCategory.Thumbnail));

Step4:
When call receives at DataPortal_Fetch(FilterCriteria criteria), the criteria object does not have (pgIdx=1,pgSize=5), instead it is initialized to default values (pgIdx=1,pgSize=20), and instantiate the List with 20 childen in it and return the result back.

Step5:
On WinRT side received a list of 20 items, but all those child are initialized to default/empty properties, even though the list returned by WcfPortal was with actual 20 items initialised with db-values. Somewhere data got lost and a list got initialized with some default empty items in it.

So my issue are, when i passed (pgIdx=1,pgSize=5) in criteria, this criteria does not reached to server side, instead a default criteria object with (pgIdx=1, pgSize=20) passed down to server side DataPortal_Fetch method. Even though the List with 20 items returned back from server side =, when it reached on client side, a list of 20 items received, but all those 20 items initialized with default/empty properties. I don't know what am i missing in configuration?

Asad.

**Comment by jonnybee** [comment]
Can you post a sample app that show this problem/issues? 

Have you made sure to have the exact same names on both namespace, classes and assemblies/dll's in both WinRT and .NET! These must match for serialization to work properly!

**Comment by AsadCheema** [comment]
Ok, i tested the App, now i can successfully get ItemDtl using its ID, but still list where i am passing filterCriteria is still not serializing to ServerSide and the collection created on ServerSide is not serializing to Client. But unable attach VS2013 solution. In old forum one can attach zip file.

Asad.

**Comment by halloween8** [comment]
As someone told me 

Put it in onedrive/dropbox/google drive/box/etc. and post a link?

**Comment by rockfordlhotka** [comment]
That, or push it into your own GitHub repository and post a link here.

**Comment by jonnybee** [comment]
The issue at hand here is simple. 

You must use managed properties in all your objects - including Criteria objects and read only objects. 

So f.ex the Criteria object should be defined as:

	private class FilterCriteria : CriteriaBase<FilterCriteria>
    {
        public static readonly PropertyInfo<string> ItemIDProperty = RegisterProperty<string>(c => c.ItemID);
        public string ItemID
        {
            get { return ReadProperty(ItemIDProperty); }
            private set { LoadProperty(ItemIDProperty, value); }
        }

        public static readonly PropertyInfo<string> ItemTypeIDProperty = RegisterProperty<string>(c => c.ItemTypeID);
        public string ItemTypeID
        {
            get { return ReadProperty(ItemTypeIDProperty); }
            private set { LoadProperty(ItemTypeIDProperty, value); }
        }

		// And so on for other properties 

The same goes for your items object, this will NOT work:  

    [Serializable()]
    public partial class ItemInfo : ReadOnlyBase<ItemInfo>
    {
      public string ItemID { get; private set; }
      public string ItemCode { get; private set; }
    
Properties must be defined as managed properties:
 
    [Serializable()]
    public partial class ItemInfo : ReadOnlyBase<ItemInfo>
    {
      public static readonly PropertyInfo<string> ItemIDProperty = RegisterProperty<string>(c => c.ItemID);
      public string ItemID
      {
          get { return ReadProperty(ItemIDProperty); }
          private set { LoadProperty(ItemIDProperty, value); }
      }

      public static readonly PropertyInfo<string> ItemCodeProperty = RegisterProperty<string>(c => c.ItemCode);
      public string ItemCode
      {
          get { return ReadProperty(ItemCodeProperty); }
          private set { LoadProperty(ItemCodeProperty, value); }

**Comment by AsadCheema** [comment]
Thank you Jonny for the quick response, really appreciate this. Will try to fix the BOs and test it again.

Regards.

**Comment by jonnybee** [comment]
You _can_ make your code work but this requires extra code to handle serialization and deserialization so the general recommendation is to use "managed backing fields". This is documented in the "Using CSLA 4 - Creating Business Objects" ebook Chapter 1.

**Comment by jonnybee** [comment]
Your code would work in .NET when using one of the builtin binary formatters but these are not available on WinRT or Windows Phone. This is why CSLA has a builtin MobileFormatter that knows how to handle "CSLA managed properties" - but this does not handle the simple properties that you have used here.

**Comment by AsadCheema** [comment]
Thank you Jonny, yes i converted the test app accordingly and it is now serializing both ways. Now i had another issue on hand, we are using Csla since last 10 years and started from v2.0 and then updated our dlls as Csla moved towards v3.8. So all our classes are in hybrid type of property definitions. I don't know is there an easy way to convert all properties to "Csla managed properties". It is around thousands of lines of code.
Regards.

**Comment by jonnybee** [comment]
Well, there is quite a number of challenges. 

1. Property declarations and serialization 
2. Business rules (validation, authentication, async)

You can get quite far with Structural Search and Replace in R# when updating the property declarations anjd business rules. Be prepared to learn SSR! 
Also see: http://blog.jetbrains.com/dotnet/2010/04/07/introducing-resharper-50-structural-search-and-replace/ and the sample catalog of patterns. 

I would also take a close look at Csla.Validation if you have many of the old style rules from 3.6.x to 3,8.x. Csla.Validation adds support for most of the old style validation rules (static methods) but not for async rules or authentication rules. These should be in the new style  for 4.x (as classes).
Also see my blogpost: https://jonnybekkum.wordpress.com/2013/10/07/csla-validationthe-new-nuget-package-in-csla-net-4-5-40/

You could maybe write your own in VS2015 but I have not ventured into this so I have no experience whatsoever on that. 

The other road to look at is adding OnGetState/OnSetState methods to add serialization of fields.
