### ISSUE TITLE
TransactionManager vs ConnectionManager

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#362]
I am a little confused about the difference between the two. we are using DB transactions inside our stored procs (sql server) should we use ConnectionManager or TransactionManger?

Thanks for your help

**Comment by jonnybee** [comment]
Hi, 

ConnectionManager: Provides an automated way to reuse open database connections within the context of a single data portal operation.

TransactionManager:  Provides an automated way to reuse open database connections and associated ADO.NET transactions within the context of a single data portal operation.

So it really depends on whether you need to use ADO.NET Database Transactions (ie transactions that span multiple stored procedures/sql statements) or if it is sufficient to have only transaction inside your procedures. .

**Comment by ajj7060** [comment]
Also, I would think that for most people using TransactionScope has largely replaced using TransactionManager.

**Comment by Chicagoan2016** [comment]
Thank you
@jonnybee we have transactions inside storedprocs, what is your recommendation?

kind regards

**Comment by jonnybee** [comment]
Use ConnectionManager
