### ISSUE TITLE
Csla.ApplicationContext.User in ProjectTracker WinForms UI

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/cslaforum#369]
Hi Rocky et al

I have been trying to implement a user login similar to the ProjectTracker sample. However, the `User` is being reset to a `GenericIdentity` virtually straight after the user is first authenticated. Then I noticed this actually happens in the ProjectTracker sample, too. I added a tool strip button to `MainForm` which simply does

```
private void DumpUserIdentity(object sender, EventArgs e)
{
    System.Diagnostics.Debug.WriteLine(Csla.ApplicationContext.User.Identity);
}
```
The output is `System.Security.Principal.GenericIdentity`

Is there a way to fix this? This is a bit of showstopper for me currently.

Thanks
Michael

**Comment by jonnybee** [comment]
See: https://github.com/MarimerLLC/csla/issues/701

**Comment by rockfordlhotka** [comment]
Also, if you look at `Samples\ProjectTracker` in master right now, I have a temporary workaround with a custom application context provider that resolves the issue. It is an easy workaround - add that one class, and one line of code as the app starts so CSLA uses that custom provider.

**Comment by michaelcsikos** [comment]
Thanks Jonny and Rocky. The `ApplicationContextManager` is working fine.
