### ISSUE TITLE
How can you test rule RunMode = RunModes.DenyOnServerSidePortal

### ISSUE THREAD

**Issue by halloween8** [MarimerLLC/cslaforum#37]
I have a rule that is defined
RunMode = RunModes.DenyOnServerSidePortal
or
this.CanRunOnServer = false; (with CommonBusinessRule)

And I want to test the fact that it runs on the client and not on the server, is it possible to test that?

**Comment by rockfordlhotka** [comment]
Csla.ApplicationContext has properties you can use to determine the physical and logical execution location of your code.

Logical location refers to the fact that CSLA is location transparent, so even in a 1-tier physical deployment your code is logically on the 'client' or 'server' even if it is always physically on the same machine.

Physical location is a good-faith attempt by CSLA to determine if your code has physically moved to a different machine. So in normal 2-tier or 3-tier deployments this will tell you if your code is running on a physical server or not.

More details are in the *Using CSLA 4* ebook.

**Comment by jonnybee** [comment]
Why do you want to test something that is part of the framework? 

 

What it means is that the RuleEngine will exclude the rule from being run when on the logical server side. 

 

I would simply test that the flag is set as per expected on the rule. 

 

/jonny

**Comment by halloween8** [comment]
Rocky 

Right, Can you set this (Csla.ApplicationContext.ExecutionLocation) somehow, in a test ???

**Comment by ajj3085** [comment]
If you're unit testing the rule class in isolation, I don't think that the flag that the code is running on the server should ever be set.  Are you testing the rule directly or by interacting with the business object which uses the rule?

**Comment by halloween8** [comment]
the latter, i'm trying to test the object in both environments.

**Comment by jonnybee** [comment]
Q: Do you want to test that the Rule is configured correctly or do you want to test the CSLA Rule Engine? 

If you want to test the rule then just verify that the flag is set. 

The latter requires a "dummy" entity object that you call DataPortal.Fetch/DataPortal.Create on and in the data access calls BusinessRules.CheckRules(). You could create a dummy rule that just sets another property and verify whether that property has a defined value or not (ie: has ruile been called or not). The RuleEngine has a predictable behavior and if one rule works then the others will also have the same behavior.

**Comment by ajj3085** [comment]
Alternately instead of a dummy object, if you're using dependency injection with Csla, you can create an interface which wraps the static properties you need and just provide a mock object.  One approach to DI with Csla is here: http://magenic.com/Blog/Post/43/Abstractions-in-CSLA

**Comment by jonnybee** [comment]
Or:
Call DataPortal.Create on Your BO (and data Access should call base.DataPortal_Create which does  BusinessRules.CheckRules() on the logical serverside). This <rule>,Execute Method should not be called.
 
On the returned Object call <bo>,BusinessRules.CheckRules() and the <rule>.Execute Method should now be called.

**Comment by halloween8** [comment]
Right I like this. Thanks
