### ISSUE TITLE
Analyzer Idea: Enforce Calling a "AddXYZ" Method in a Rule

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/cslaforum#373]
Today at a client we were talking about implementing business rules, and we started to wonder....would there ever be a reason in a rule to *not* call at least one of the following methods:

* `AddErrorResult`
* `AddWarningResult` 
* `AddInformationResult` 
* `AddSuccessResult` 

It would seem odd to have a rule that doesn't do some kind of `Add...()` call, but there may be valid reasons that I'm not seeing. One counter to this is a dev to just uses the `Target` property on the `context` and gets/sets properties that way (via `ReadProperty` and `LoadProperty`).

Discuss (please :) )

**Comment by jonnybee** [comment]
Yes, there is several reasons:

1. AddSuccessResult is added by the rule engine as default if a sync rule hasn't added a result.
2. A Calculation/ToUpper/ToLower rule would only call context.AddOutValue
   See RuleTutorial\TransformationRules\CalcSum.cs and ToUpper.cs
3. An async lookup rule would call AddOutValue (and call context.Complete) 
   See: RuleTutorial\AsyncLookupRule\Rules\AsyncLookupCustomer.cs
4. A Gateway rule would typically only check for some conditions to call an inner rule (and take advantage og the RuleEngine to add SucessResult when not set). 
   See: RuleTutorial\GatewayRules\Rules\CanWrite.cs
5. Both Csla standard rules and custom rules may only call context.Results.Add(..) to make a more flexible rule that could f.ex have a property to determine severity when rule is broken. 
   See: RuleTutorial\CompareFieldsRules\Rules\GreaterThan.cs and 
          Csla\Rules\CommonRules.cs - Required and MaxLength rule 
6. A Dependency rule would only set InputProperties and/or AffectedProperties (and have no implementation of Execute)
   See: RuleTutorial\AddonPropertyRules\Rules\DependencyFrom.cs 
7. A rule may only interact with the context.Target object to do property changes. 

So there is several resonable condintions for when a Rule would not call any of the AddXYZ methods. 

My vote is NO to this analyzer.

**Comment by jonnybee** [comment]
RuleTutorial solution is located in Csla\Samples\Net\cs\RuleTutorial folder.

**Comment by JasonBock** [comment]
That's good to know. This is why I always propose the idea first :). So I'm fine with closing it out.
