### ISSUE TITLE
Async DB methods

### ISSUE THREAD

**Issue by gem4511** [MarimerLLC/cslaforum#379]

**Comment by gem4511** [comment]
Finally faced with the need to use async DB with Csla, I'm trying to get my head around how.  I have the ebook series, and am examining Project Tracker code.  I can't seem to clear the fog.

My application has long been running fine on .Net and on OSX via Mono, using Windows.Forms.  A port to Android and iOS tablets is necessary.  Since modifying the Windows.Forms code-behind code to accommodate the Xamarin.Forms-generated version of the UI was fairly simple to do, re-implementing the UI to Xaml is not a priority.  Getting the database operations to work, of course, is.

 All will be well going forward if I can just figure out how to replace the following snippets with the async equivalents:

ClientList class (a ReadOnlyListBase):

        public static ClientList GetClientList(  )
        {
                return DataPortal.Fetch<ClientList>(  );
        }

        private void DataPortal_Fetch(  )
        {
        RaiseListChangedEvents = false;
        string query =
                "SELECT OBID,Title,Version " +
                "FROM client " +
                "ORDER BY Title";
        conn.Open(  );
        cm = new FbCommand( query, conn );      			
        dr = cm.ExecuteReader(  );			

        IsReadOnly = false;          		
        while ( dr.Read(  )  )
        {
                ClientInfo info = new ClientInfo( dr );
                Add( info );
        }
        IsReadOnly = true;
        RaiseListChangedEvents = true;
        dr.Close(  );
        conn.Close(  );
        }

MainForm (a Windows.Forms Form):

        ClientListbindingSource.DataSource = ClientList.GetClientList(  );

In looking at the GetExistingProject example on page 56 of the WPF and Silverlight ebook, I can't seem to fathom how to formulate the callback thing so I can bind a retrieved ClientList to my form.
GetExistingProject( ) is void and here I sit, stumped.

Any help converting this to async would be most appreciated, and would clear away the mental logjam.

Thanks
GEM

**Comment by rockfordlhotka** [comment]
Unfortunately the book predates the addition of the async/await keyword in .NET, and of course in CSLA.

I have a blog post about using [async/await in the data portal](http://www.lhotka.net/weblog/CSLADataPortalChangesInVersion45.aspx), and I suspect that'll help you quite a lot.

**Comment by gem4511** [comment]
Thanks Rocky.  I've made some progress by reacting to your blog info.
