### ISSUE TITLE
Editable ChildList question

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#384]
On P-60 in Data Access book we have
"If properties are required in addition to the list of child objects, you should create an editable parent object that contains the collection, along with those other properties and their rules."

In the context of Project Tracker's "Edit Project" user scenario, if we need properties for the "Resources" child collection do we have to code an additional object that will be parent of Resources collection but a child of ProjectEdit.cs? or the above statement (on p-60) is only true for root list objects?

kind regards

**Comment by jonnybee** [comment]
A list has no support for managed properties, business rules etc. It is a list that maintain a "shadow" list of deleted objects. This is the same whether it is a child or grandchild. 

In the case of ProjectEdit you would have to determine whether the additional properties belong to the existing parent object (ProjectEdit) or to a separate layer. 

EditableRootList is a root list object. If you need parent properties then use another stereotype.

**Comment by Chicagoan2016** [comment]
Thank you Jonny,
you are right! an EditableRoolList won't be a 'root' if I needed a parent object : )
