### ISSUE TITLE
Custom Business Rule

### ISSUE THREAD

**Issue by fujiiface** [MarimerLLC/cslaforum#386]
Hi all,

Have what I think is a weird issue going on with a custom business rule.  I have two generic business rules that deal with strings.  One is the `ToUpper `sample that is found within the Using CSLA 4 02-Objects ebook (page 108).  The other is based on the `ToUpper `sample and called `NullToEmptyString `which checks for a null string field (from the database) and replaces it with an empty string.

The issue occurs when I am saving a child object to my parent.  If I run the code without debugging I get a broken rule related to the property that is null when it should be an empty string.  However, if I step through the code and take my time, the `NullToEmptyString `rule executes properly and the parent object becomes valid...child object is saved as expected.

I mention the `ToUpper `rule because if I test the rules out, `ToUpper `works without any issues.  After the child object is added to the parent the lower case properties are uppercased, as expected.  Any insight is appreciated.

Code is below.

## ToUpper Rule
```
/// <summary>
/// Uppercases any string value
/// </summary>
/// <remarks>
/// Reusable custom CSLA business rule example from the Using CSLA 4 eBooks (UsingCsla4-02-Objects.pdf; page 108)
/// </remarks>
public class ToUpper : Csla.Rules.BusinessRule
{
    public ToUpper(Csla.Core.IPropertyInfo primaryProperty)
        : base(primaryProperty)
    {
        InputProperties = new List<Csla.Core.IPropertyInfo> { PrimaryProperty };
    }

    protected override void Execute(Csla.Rules.RuleContext context)
    {
        var input = context.InputPropertyValues[PrimaryProperty].ToString();
        if (!string.IsNullOrEmpty(input))
        {
            context.AddOutValue(PrimaryProperty, input.ToUpper());
        }
    }
}
```

## NullToEmptyString Rule
```
/// <summary>
/// Checks the property for a null value and replaces it with an empty string if the value is null
/// </summary>
public class NullToEmptyString : Csla.Rules.BusinessRule
{
    public NullToEmptyString(Csla.Core.IPropertyInfo primaryProperty)
        : base(primaryProperty)
    {
        InputProperties = new List<Csla.Core.IPropertyInfo> { PrimaryProperty };
    }

    protected override void Execute(Csla.Rules.RuleContext context)
    {
        var input = context.InputPropertyValues[PrimaryProperty];
        if (input == null)
        {
            context.AddOutValue(PrimaryProperty, string.Empty);
        }
    }
}
```

## Parent Object AddBusinessRules
```
protected override void AddBusinessRules()
{
    base.AddBusinessRules();

    //code omitted

    #region Custom Business Rules

    //Custom Business rules
    BusinessRules.AddRule(new Library.Rules.ToUpper(LastNameProperty));
    BusinessRules.AddRule(new Library.Rules.ToUpper(FirstNameProperty));
    BusinessRules.AddRule(new Library.Rules.ToUpper(RequestedByProperty));
    
    BusinessRules.AddRule(new Library.Rules.NullToEmptyString(LatestWorkLocationProperty));
}
```

## Code-behind child and parent save
```
if (attachment.IsValid)
{
    _obj.Attachments.AddTo(attachment);
    _obj = _obj.Save();
}
```

**Comment by jonnybee** [comment]
There is no way to tell any issues from this code. 
Could you post a working sample that reproduces the issue for us?

**Comment by fujiiface** [comment]
Jonny,

I've put a sample together (attached) but, in doing so, it seems I have found where the issue is.  I have a RegEx business rule that ensures the `LatestWorkLocationProperty` only contains alphanumeric characters and spaces.  In my previously posted **code-behind child and parent save** sample, I am not calling `_obj.IsValid` so the object's business rules are not checked again.  _**This is causing the validation error.**_

This issue leads me to a different question now.  **Is it required to override the `IsValid` property?**  When I first learned CSLA from another developer and the CodeSmith templates we were provided, the `IsValid` property was overridden.  If my business objects do not override the `IsValid` property, my validation rules are not checked again and my save operation fails.  If I do override `IsValid` then the save operation succeeds.

The `IsValid` overrides just call `BusinessRules.CheckRules()` and return true/false depending on the `GetBrokenRules().Count` value.  I've messed around with this most of the day and do not see another way around this but I'm probably doing something wrong.

[sample.zip](https://github.com/MarimerLLC/cslaforum/files/1137283/sample.zip)

**Comment by jonnybee** [comment]
I think that is a unnecessary override of IsValid and may slow down your application. 

You _should_ call 

     BusinessRules.CheckRules();
     MarkOld();

at the end of DataPortal_Fetch to make sure that the object is validated and start off with the correct state. From then on the rules will be checked as each property is updated in the UI or when model is updated (f.ex using CslaModelBinder in MVC). This will make sure the objects are in the correct state at any time - and there is no need to override IsValid (to force a check of all business rules). Especially in a rich client (WinForms, Xaml) this override would slow down the user experience as IsValid may be called many times by the UI. 

If you override DataPortal_Create in your code to set default values you should always call 

    base.DataPortal_Create()

at the end of the overridden method. 

    protected virtual void DataPortal_Create()
    {
      BusinessRules.CheckRules();
    }

**Comment by ajj7060** [comment]
@jonnybee Is the MarkOld required?  I believe the dataportal will call that for you, although I can't remember if its before or after you enter the DP_F method.  I seem to recall it was changed to do it before.

**Comment by tfreitasleal** [comment]
Hi all,

If I remember correctly, if I MarkOld(), the object becames old and thus IsSavable returns false.
Considering you just ran business transformation rules, some properties are changed and the object no longer matches what is saved on the database. This might be the correct action considering:

1. if you change the object, the saved version will included the changes made when fetching the object;

2. if you don't change the object, the fetch changes won't be saved but it doesn't matter because they will run the next time you fecth the object.

**Comment by rockfordlhotka** [comment]
@ajj7060 we did change it to call `MarkOld` prior to invoking your `DP_Fetch` code, which is why you need to use `BypassPropertyChecks` in your code when loading values.

This change was made so it would be possible for people to ensure their object loaded with `IsDirty` as `true` if they desired, even though I think it is normally better if it is `false`.

**Comment by fujiiface** [comment]
Thanks @jonnybee.  I will mess around with this some more to avoid overriding IsValid.  The "many times" behavior you mentioned is, in fact, what I have seen at times.  It hasn't been too bad on my performance but it should be addressed since more people will be using this application.

@tfreitasleal: that sounds like behavior I want :+1: 

@rockfordlhotka so calling `MarkOld();` after the `DP_Fetch` and `BypassPropertyChecks` should be standard unless I need to ensure my object is savable every time I retrieve it, regardless of whether or not the object has actually had a property change?

**Comment by rockfordlhotka** [comment]
My recommendation is to _not_ call `MarkOld`, but instead to use `BypassPropertyChecks` when loading values into your object.

The data portal already called `MarkOld` before invoking your `DP_Fetch` method, you shouldn't need to call it again unless you accidentally (or intentionally) change the object's state while loading the instance with data from the DAL. Normally this would be an accident - aka bug - and is something you'd catch as part of your automated testing.

**Comment by fujiiface** [comment]
Gotcha.  Thanks @rockfordlhotka!

**Comment by ajj7060** [comment]
@tfreitasleal In addition to what Rocky wrote, I'd say generally, IMO, that its a bug for a just-fetched object to be dirty.  There typically isn't a reason to change the object on fetch.  For performance reasons I prefer to write the fetch queries to lookup data needed instead of letting rules run to do the lookups, and calculates I'd think shouldn't change what was loaded.  I normally code lookup rules / calculations to set CanRunOnServer = false.  So CheckRules then only does validation.  So omitting the MarkOld call usually clues me in on something that isn't setup correctly.

**Comment by Chicagoan2016** [comment]
Thanks for the explanation @rockfordlhotka , I have a use case where I need to get data from a csv file, run business/validation rules and then send the data to a SQL database.
