### ISSUE TITLE
Create multi level hierarchy in CSLA

### ISSUE THREAD

**Issue by PraveenKadali** [MarimerLLC/cslaforum#391]
I am trying to implement multi level hierarchy. and my classes are like below
Collection
 [Serializable()]
    public class MaterialList : BusinessBindingListBase<MaterialList, Material>, IBusinessObjectList<MaterialList>
    {
 MaterialParent _params;

        internal MaterialParent LoadParent
        {
            get { return _params; }
            set { _params = value; }
        }
     private MaterialList()
        {
            base.AllowEdit = true;
            base.AllowNew = true;
            base.AllowRemove = true;
        }
 public static MaterialList NewMaterialList(Material material)
        {
            return DataPortal.CreateChild<MaterialList>(material);
        }
private void Child_Create(Material parentMaterial)
        {
            _params = new MaterialParent(parentMaterial);
        }
}
 [Serializable()]
        internal class MaterialParent
        {
            private Material _parent;

            public Material Parent
            {
                get { return _parent; }
                set { _parent = value; }
            }

            public MaterialParent(Material demand)
            {
                _parent = demand;
            }

        }
base class
 [Serializable()]
    public class Material : UpdateableBusinessBase<Material>
    {
       private Material()
        {
            MarkAsChild();
        }
 private static PropertyInfo<MaterialList> ChildMaterialListProperty = RegisterProperty<MaterialList>(p => p.ChildMaterialList);
        public MaterialList ChildMaterialList
        {
            get
            {
                if (!(FieldManager.FieldExists(ChildMaterialListProperty)))
                {
                    if (this.IsNew)
                        LoadProperty(ChildMaterialListProperty, MaterialList.NewMaterialList(this));
                }
                return GetProperty(ChildMaterialListProperty);
            }
            set
            { SetProperty(ChildMaterialListProperty, value); }
        }
     }
**When I tried to update the value of one of the properties, I got the below error
An exception of type 'Csla.PropertyLoadException' occurred in Csla.dll but was not handled in user code

Additional information: Property load or set failed for property MyProperty (The list must be an IBindingList to AddNew.)**

Has anyone ran into this issue before?  Or Is it possible to have multi level hierarchy in CSLA?

**Comment by jonnybee** [comment]
Yes, it is possible to have multi-level hierarchy in CSLA. 

Seems like you have a couple of issues. 

1. You should not create a _parent field in your list 
2. Use a generic base class like BusinessBase<T> for your Material class 

Could be other issues with your object structure as well as UpdateableBusinessBase is not a class in CSLA.

**Comment by PraveenKadali** [comment]
Thank yo for your response Jonny
I tried by removing the parent field from the list but still got the same error.
The UpdateableBusinessBase is just an abstract class that is inheriting BusinessBase

Do you have any sample code by chance that I can use as a reference to troubleshoot my issue?

**Comment by jonnybee** [comment]
You should use generic base classes. Ex: 

    [Serializable()]
    public abstract class UpdateableBusinessBase<T> : BusinessBase<T> where T : UpdateableBusinessBase<T>

and 

    [Serializable()]
    public class Material : UpdateableBusinessBase<Material>

Can post a complete solution that show the issue you have?

**Comment by PraveenKadali** [comment]
I am using Infragistics grid view control and I think the control is not working well with multi level hierarchical csla objects. 
If I bind the data to Windows Forms DataGridView, it is getting updated with out any errors. 
I will post the question to Infragistics support team.

Thank you for your help.
