### ISSUE TITLE
Business Rule issue (async/sync)

### ISSUE THREAD

**Issue by sylum** [MarimerLLC/cslaforum#401]
Hi Folks,

I'm working on an API REST project and I’m facing a business rule issue.

Actually, all controllers use aync operations with csla objects (BusinessBase).
Some of those objects have business rules (async as well) attached to their properties.
When I made a put/post request to controller (for create/update a record), I have got the following error:

_An asynchronous module or handler completed while an asynchronous operation was still pending._

It’s seems the controller return the answer before the async rule return the result. The keyword wait is well present, below a sample of the business rule.

```
 public class IsAutorizeToCustomer : Csla.Rules.BusinessRule
        {
            public IsAutorizeToCustomer(Csla.Core.IPropertyInfo primaryProperty)
                : base(primaryProperty)
            {
               IsAsync = true;
                InputProperties = new List<Csla.Core.IPropertyInfo>();
                InputProperties.Add(primaryProperty);              
            }

            protected async override void Execute(Csla.Rules.RuleContext context)
            {         
                int customerId = (int)context.InputPropertyValues[CustomerIdProperty];
                var cmd = new CustomerExistCommand(new CustomerExistCommand.Criteria() { Id = customerId });
                var result =  (await DataPortal.ExecuteAsync(cmd)).IsExists;
                if (result) context.AddErrorResult(string.Format("the field {0} is incorrect.", CustomerIdProperty.FriendlyName));
                context.Complete();
            }
        }
```

So i have tried to change the business async rule to a sync rule like below but now i get this exception : _System.NotSupportedException : 'isSync == true'_

```
public class IsAutorizeToCustomer : Csla.Rules.BusinessRule
        {
            public IsAutorizeToCustomer(Csla.Core.IPropertyInfo primaryProperty)
                : base(primaryProperty)
            {
               //IsAsync = true;
                InputProperties = new List<Csla.Core.IPropertyInfo>();
                InputProperties.Add(primaryProperty);      
            }

            protected async override void Execute(Csla.Rules.RuleContext context)
            {     
                int customerId = (int)context.InputPropertyValues[CustomerIdProperty];
                var cmd = new CustomerExistCommand(new CustomerExistCommand.Criteria() { Id = customerId });
                var result =  DataPortal.Execute(cmd)).IsExists;
                if (result) context.AddErrorResult(string.Format("the field {0} is incorrect.", CustomerIdProperty.FriendlyName));
                context.Complete();
            }
        }
```
does someone have an idea about it?

Cedric

**Comment by rockfordlhotka** [comment]
The thing is, you need to make sure your service method (the top-level code hosted by ASP.NET) doesn't complete until all the business rules are finished.

You can tell when all async rules are complete by listening for the `ValidationComplete` event on your object.

You can await an event using techniques in this SO thread:
https://stackoverflow.com/questions/12858501/is-it-possible-to-await-an-event-instead-of-another-async-method

**Comment by sylum** [comment]
Hi Rocky, 

With your advice and the post below from JonnyBee, I'm be able to manage the async rules.

[http://forums.lhotka.net/forums/p/12148/56247.aspx](http://forums.lhotka.net/forums/p/12148/56247.aspx)

```
public async void CheckAllRulesAndWaitForAllRulesToComplete()
{
  var tcs = new TaskCompletionSource<bool>();
  // declare event handler
  EventHandler eh = (sender, e) => tcs.SetResult(true);
  // attach to validation complete event
  ValidationComplete += eh;
  // call check rules 
  BusinessRules.CheckRules();
  // wait for tcs to set result (ValidationComplete)
  await tcs.Task;
  // unsubscripbe from event
  ValidationComplete -= eh;
}
```
You save my day. Thanks a lot both of you.

Cedric
