### ISSUE TITLE
Move Serializable attribute to System namespace

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#41]
**Please provide your feedback on this idea**

I am considering a change that I *think* shouldn't break anyone, but which would clean up the way people implement x-plat classes in CSLA.

https://github.com/MarimerLLC/csla/issues/407

Basically today to create an x-plat class you need this:

```c#
using System;
using Csla.Serialization;

[Serializable]
public class Foo : BusinessBase<Foo>
```
With the proposed change you would not need the `using Csla.Serialization` statement:
```c#
using System;

[Serializable]
public class Foo : BusinessBase<Foo>
```
Obviously that's a source of bugs and is just one less thing to deal with. Perhaps more importantly, in VS15 with shared projects and the way the code editor greys out `using` statements it often looks like `using Csla.Serialization` isn't required, when in reality it is required - just on some other platform.

**Comment by ajj3085** [comment]
I think that makes sense; The Csla attribute is meant to cover the platforms which don't have System.SerializableAttribute, correct?  So this change would make that fact transparent.
