### ISSUE TITLE
ApplicationContext change

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#417]
I am looking at making a change to the way the default ApplicationContext is managed - specifically for the `User` property, and local/client/global context dictionaries.

I've actually implemented the change, and would appreciate any feedback folks have on it.

https://github.com/MarimerLLC/csla/issues/729#issuecomment-327609037

This is a breaking change, but I _think_ only for people who've been working around the fact that context didn't automatically flow to worker threads. Now (in .NET 4.6 and higher) context _will_ automatically flow to worker threads.

**Comment by tfreitasleal** [comment]
Why only on .NET 4.6 or higher?

**Comment by rockfordlhotka** [comment]
Because `AsyncLocal` doesn't exist on .NET 4 or 4.5.
