### ISSUE TITLE
ClaimsPrincipal vs IPrincipal in netstandard2.0

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#422]
I just blogged about a conundrum we're facing while implementing support for ASP.NET Core 2.0. Specifically that ASP.NET Core (unlike all other .NET versions and platforms) requires the use of `ClaimsPrincipal` instead of `IPrincipal` for user identity.

http://www.lhotka.net/weblog/IsIPrincipalDead.aspx

Looking for people's thoughts on this matter.

**Comment by rockfordlhotka** [comment]
Microsoft has made it pretty clear that `ClaimsPrincipal` is the future (.NET 4.5 and higher). Of course `ClaimsPrincipal` implements `IPrincipal`, so technically that type remains valid, but more and more it isn't enough to just implement `IPrincipal`, you need to subclass `ClaimsPrincipal`.

What's really unfortunate is that `ClaimsPrincipal` and `ClaimsIdentity` don't have their own interfaces - so you _must_ subclass their concrete type. That's not so easy for CSLA, because I need those types to also implement `IMobileObject` so they can be serialized by MobileFormatter. It just means I need to figure out how to get/set all the values from `ClaimsPrincipal` and `ClaimsIdentity` during serialization - and they don't directly allow that to occur.

I'm not 100% sure this is a solvable issue... At least not without reflecting against private members of `ClaimsPrincipal` and `ClaimsIdentity` anyway...

**Comment by mj1856** [comment]
Hi Rocky.  I left some suggestions for you in the blog post comments, but Disqus somehow marked it as spam, so not showing currently...  Anyway, I'll repaste it here:

> All of the built-in principal classes (`WindowsPrincipal`, `GenericPrincipal`, `RolePrincipal`) are based on `ClaimsPrincipal`, which implements `IPrincipal`. So if you directly implement `IPrincipal`, then you have no claims support, so you don't get to work in environments that need claims, like ASP.Net Core. Since it seems like CSLA should play in lots of environments, I wouldn't recommend a sweeping change, but rather a targeted one.
>
> Glancing at the CSLA source code, I'd start in `Csla.Web.ApplicationContextMananger.SetUser`, and instead of casting I would take in a `ClaimsPrincipal`. Then work backwards through the breaking changes until you get to a point where the code is used by things other than ASP.Net, and do the cast there. You could even trap it and throw a better exception message if you want, like "Only `ClaimsPrincipal` based principals can be used in ASP.NET Core"... etc.
Then, I'd also go to `Csla.Security.CslaPrincipal` and anywhere else you may be implementing `IPrincipal` yourself, and update those to be based on `ClaimsPrincipal`.
>
> Everything else, leave at `IPrincipal`.
> 
> Hope that helps. ;)

**Comment by rockfordlhotka** [comment]
Thank you for reposting @mj1856 - I don't know why it disappeared from Disqus...

**Comment by rockfordlhotka** [comment]
The fact that `ClaimsPrincipal` and `ClaimsIdentity` are _concrete types_ instead of interfaces - that's really the painful part of this!

**Comment by mj1856** [comment]
I guess I'm not fully following (sorry, I'm not actively using CSLA), but say it did affect your WinForms users.  Would it matter?  I mean, if their principle is a `WindowsPrincipal`, then they already are compatible with `ClaimsPrincipal`, It's only any custom principals created directly from `IPrincipal`, such as your `CslaPrincipal` that would matter, and if you base that on `ClaimsPrincipal` then you're covered there too, right?

**Comment by rockfordlhotka** [comment]
People often use custom principal objects with CSLA, allowing client-side identities to flow to app servers (independent from windows identities). For example, if you build an app that is a shared kiosk on a manufacturing floor you don't have users log in/out of Windows, you just have them log in/out of your app.

So people who've created custom principal/identity types will need to alter their types to subclass ClaimsPrincipal and ClaimsIdentity.

Which wouldn't be such a big deal if they could just implement a new interface - but Microsoft decided to force us all to use their concrete types. That's a much bigger change obviously - inheritance is the tightest form of coupling you can achieve...

**Comment by mj1856** [comment]
So, I've been digging trying to find some guidance for you, and came up with a few things.

1. [What's New in Windows Identity Foundation 4.5](https://docs.microsoft.com/en-us/dotnet/framework/security/whats-new-in-wif) describes the introduction of `ClaimsPrincipal` as it describes WIF being integrated with .NET Framework 4.5, around 2012.  So, this isn't a new thing.

2. [This blog post](https://dotnetcodr.com/2013/02/14/introduction-to-claims-based-security-in-net4-5-with-c-part-2-the-new-inheritance-model/) from 2013 (by @andras-nemes) describes some of the effects, and includes this bit of advice:
    > ... if you plan to build your own Identity and Principal objects then you should not implement IIdentity and IPrincipal but derive from ClaimsPrincipal and ClaimsIdentity instead.

3. aspnet/mvc#5532 calls out `HttpContext.User` returning `ClaimsPrincipal` instead of `IPrincipal`, with the same concerns you have here about custom principals.  Maybe you could chime in there, and/or open a new issue and reference that one.

Sorry I can't be more helpful than that.  Good luck!

**Comment by ajj7060** [comment]
We use custom principal / identity classes too (in WinForms, Asp.Net, and Xamarin), but we subclass them from CslaPrincipal/CslaIdentity.  If those suddenly inherited ClaimsPrincipal/ClaimsIdentity, I don't think that would cause us any issue.  Wouldn't most that need a custom principal do that as well? It seems that's easier to do than implement IMobileObject on your own.

I guess it depends on how many Csla users completely rolled their own IPrincipal/IIdentity implementations without subclassing anything.  

The MobileFormatter issue is understandable; maybe though there needs to be an IPrincipalSerializer interface, and the prin/ident just need to be serialized differently based on what is supported for the platform.  

Personally, if its clear Claims are the future, I'd rather bit the bullet now rather than continue to put it off.

**Comment by tfreitasleal** [comment]
@ajj7060 Agree. The sooner the better.

**Comment by rockfordlhotka** [comment]
I think I'll make the switch explicit though, by adding `CslaClaimsPrincipal` and `CslaClaimsIdentity` types (if I can figure out the serialization).

This would allow people to opt-in to the new types, and also provides some type naming clarity that I think has value.

**Comment by rockfordlhotka** [comment]
Serializing and deserializing the values in these two Microsoft types is non-trivial. Some of the values transport relatively easily, others are very much not easy.

Also, as I'm doing this, it is hard to envision how to automate serialization of custom subclasses. So I have a question for folks like @ajj7060.

When you subclass `CslaIdentity`, are you adding extra properties and values? If you transitioned to a `ClaimsIdentity`, which is already very extensible, would you even need to create your own subclass? Or could you use a `ClaimsIdentity` as-is, using its existing `Properties` dictionary to store your custom values?

**Comment by tfreitasleal** [comment]
I don't know Claims. In one application I subclass `CslaIdentity` and add extra properties: an `int UserID` and a `MobileList<string> Groups`. These are used for autorization purposes. Using a dictionary migh prove inadequate, if it slows down the application (unlikely).

**Comment by rockfordlhotka** [comment]
The [ClaimsIdentity](https://msdn.microsoft.com/en-us/library/system.security.claims.claimsidentity(v=vs.110).aspx) type is basically an `IIdentity` with some extra properties, most notably a list of `Claim` objects.

The `ClaimsPrincipal` type also has a `Claims` property, that is an aggregate of all the claims from all (yes, there can be more than one) identity objects associated with the principal. Microsoft obviously recommends using this aggregate property for all autho checks.

Each [Claim](https://msdn.microsoft.com/en-us/library/system.security.claims.claim(v=vs.110).aspx) is basically a glorified name/value construct. So whatever custom values you might have been adding as a custom property to your identity could now be a `Claim`.

Beyond that, each `Claim` has a whole bunch of other data, including _its own_ dictionary of arbitrary name/value pairs. I guess in case you'd rather have a single claim with lots of data rather than a bunch of individual claims or something? I don't claim to understand (pun intended! 😄 ).

**The reason I'm asking** is because _if_ I can figure out the serialization/deserialization, it will be just for the CSLA types, not for subclasses. You'll still be able to create a subclass, but you'll have to override the `OnGetState` and `OnSetState` methods yourself and add in your own custom values.

**Comment by rockfordlhotka** [comment]
I just created a PR so it is easier to see what I'm doing - this way you can easily see the new CSLA claims principal/identity types. All the serialization is in the principal type, because I can only "deserialize" `ClaimsIdentity` via their constructor.

In fact, as I type this I realize that I don't really need a _Csla_ClaimsIdentity at all, because I'm really just tearing apart Microsoft's type and putting it back together again. Hmmmm....

**Comment by ajj7060** [comment]
@rockfordlhotka Yes, I've added custom properties to the identity, like UserId was used in many places for populating LastUpdatedBy data in the DB when the user modified data.  I had some other data too.  But I think each property would just become a Claim.  That matches up with my knowledge of the SAML SSO standard, which IIRC includes the idea of claims and as you said they are just key/value pairs.  I think there were certain well-known claims like email, firstname.  I could easily see that working.

At my current company, we do add properties, but the identity actually defers to another class named Session, which stores all the permissions and user information.  So our custom Identity just has a private field for the Session instance, and we just set it once during the login process, and Identity asks Session everything.  The only actual Csla property is the session key, as Session only goes from server to client on logon.  The session key goes from client to server so we can location the user's session to prevent lots of extra data (and we don't trust the client).  But again, I see no reason the session key wouldn't just be a Claim.  As long as it goes back to the server somehow, its workable.

I do like the idea of a new CslaClaimPrincipal class.  That seems like a good compromise to keep from breaking everyone as they migrate.

**Comment by ajj7060** [comment]
Glancing at the ClaimIdentity documentation, and perhaps being a bit naive, but perhaps MobileFormatter could special case ClaimsPrincipal/ClaimsIdentity and call their WriteTo to get a binary representation of the objects, and stuff that data into the stream.

**Comment by rockfordlhotka** [comment]
Did you see a way to use that binary data to rehydrate an instance of the object though? There's a constructor for it in UWP, but I don't see it on the other (more modern) platforms.

**Comment by ajj7060** [comment]
Hmm, I didn't look at the documentation that closely, so its possible the ctor you need doesn't exist.  That would be a bummer.

**Comment by oising** [comment]
@rockfordlhotka I don't know if this is helpful or not, but I bodged something similar a few years ago using CustomReflectionContext to dynamically add new properties/attributes to types/instances of concrete/sealed classes I couldn't extend, in order to prevent making extensive changes to a plugin system.

**Comment by JohnWigger** [comment]
@rockfordlhotka,  I tried out the CslaClaimsIdentity serialization support in the beta and it worked well.  However,  I also tried to write code that did this: Csla.ApplicationContext.User = new Csla.Security.UnauthenticatedPrincipal();
Unfortunately, I get the exception in the below code in ApplicationContextManager.cs.  


System.InvalidCastException: 'Unable to cast object of type 'Csla.Security.UnauthenticatedPrincipal' to type 'System.Security.Claims.ClaimsPrincipal'.'

public void SetUser(System.Security.Principal.IPrincipal principal)
    {
      HttpContext.User = (ClaimsPrincipal)principal;
    }

**Comment by dazinator** [comment]
@rockfordlhotka think this can now be closed?
