### ISSUE TITLE
Quick obsolete SingleCriteria question

### ISSUE THREAD

**Issue by fujiiface** [MarimerLLC/cslaforum#424]
After updating CSLA a few months ago I started getting the analyzer warning `'Csla.SingleCriteria<DMS.Library.Entities.LetterList, int>' is obsolete: 'Use custom class derived from CriteriaBase e.g. ProjectCriteria : CriteriaBase<ProjectCriteria> instead.'`

I've been resolving these as I go through code by replacing the criteria parameters with just the single parameter.  In the the example code above, I use a plain old `int` parameter.  Should I be replacing these with custom derived criteria classes instead?  It seems like overkill for a single parameter.

**Comment by Chicagoan2016** [comment]
@fujiiface , 
this is strange, I coding an object as i write this, I am using an int as a criteria and VS 2017 is building the project without any errors.

**Comment by fujiiface** [comment]
@Chicagoan2016 I am getting a warning about it, not an error.  My project continues to build and deploy.  I am just curious as to whether I should be creating a criteria class for a single int parameter or is it alright to just pass the integer.  Creating the criteria class seems like overkill to me unless it is required for serialization.

**Comment by rockfordlhotka** [comment]
You can just pass the `int` - that's why the old type is obsolete - a long time ago CSLA was enhanced to allow single primitive values to just flow through the data portal without being wrapped in an extra type.

**Comment by fujiiface** [comment]
Thanks @rockfordlhotka!
