### ISSUE TITLE
Use CslaPrincipal without inheriting? (public constructor)

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/cslaforum#427]
I have been trying to solve a problem with VSTO add-ins and `SerializationException` for `UnauthenticatedPrincipal` and my custom principal inheriting from `CslaPrincipal`. (See [here](https://github.com/MarimerLLC/cslaforum/issues/411).)

So far the only reliable solution seems to be installing _Csla.dll_ in the GAC. I will also need to install one of my own assemblies in the GAC, where my custom principal class is declared. However, if `CslaPrincipal` had a public constructor, I could use that without inheriting, and then I would only need to add _Csla.dll_ to the GAC. Any thoughts?

**Comment by michaelcsikos** [comment]
I will probably make a new assembly just for the custom principal to go in the GAC.

```
[Serializable]
public class OperatorPrincipal
    : CslaPrincipal
{
    protected OperatorPrincipal(IIdentity identity)
        : base(identity)
    {
    }
}
```

**Comment by ajj7060** [comment]
I've been watching that thread; its too bad the cheesy config section workaround didn't solve it.  I had a similar problem in my unit tests, but the cheesy workaround fixed it for me.  

There's a thread (https://github.com/MarimerLLC/cslaforum/issues/422) on creating a CslaClaimsPrincipal.  Maybe Rocky and include a public ctor on that one although that wouldn't help you now.

Probably stuck just putting things in the GAC for now though.

**Comment by michaelcsikos** [comment]
I made a tiny new DLL and signed it with a strong name so it can go in the GAC.

And, of course, I had to make an InstallShield Limited Edition project because [it's the only official way](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-install-an-assembly-into-the-gac) to add assemblies to the GAC. So far, so good. Client is happy, and so am I.
