### ISSUE TITLE
Can authorization rules be invoked on a child object?

### ISSUE THREAD

**Issue by rodneyworkman291** [MarimerLLC/cslaforum#428]
I have a EditableChild object for addresses.  I only want the address to be editable for some flavors of address but not all addresses.  I wrote a custom authorization rule but I have realized that its never enforced/invoked.  Just for grins I also tried to use the CommonRules IsInRole() but that was also not enforced.  

Then I found a comment from Jonny Bekkum in the older forums that said For child objects you need to enforce the rule in your own code (authz rules is only enforced by the "root" DataPortal).  

I have attempted to enforce the child object authorization rules by calling this.CheckObjectRules(); but this does not seem to enforce or invoke the rules either.  Can authorization rules be invoked on a child object?

Rodney Workman

**Comment by rodneyworkman291** [comment]
I gave up trying to make the Child Object read only.  I implemented a property level rule instead and just applied to all properties in the child object.  This solution worked for me.  Would still be interested in learning how others solved this type of problem.

**Comment by jonnybee** [comment]
I'd rather just overload the CanWriteProperty method on the child object to
return false when the object is readonly.

1. There can only be one-1 authz rule per type, action and method/property
(so I can still add authz rules)
2. Any new properties added to the object later on will also be made
readonly.


2017-09-15 23:34 GMT+02:00 Rodney <notifications@github.com>:
