### ISSUE TITLE
Speedup EditableRootList

### ISSUE THREAD

**Issue by tsvideo** [MarimerLLC/cslaforum#43]
Hi!
I have an EditableRootList with about 1500 ChildObjects in it.
The call of Child_Upate() takes more than 30 seconds of time.
Even if i had only one Child to Change (Checked in Update from the Childs)
Any Suggestions ?
Thank you for an answer !
Thilo

We are using CSLA Version 4.5.601

**Comment by jonnybee** [comment]
Do you use a remote DataPortal or SimplePortal (local)? 

My first reaction is that your model should be redesigned. Why load 1500 child object if the user only want to edit one object? 

For an alternate solution look at the DiffGram sample in the Samples folder. 
See also: http://forums.lhotka.net/forums/t/7511.aspx

**Comment by tsvideo** [comment]
Hello Jonny,
thats a good idea only to send a List with the changed objects !
That is for me possible.
My Tests are with a local Portal, but the production Environment is remote.
The List is filled with 'production orders' for the overview of our current Rack production.
Every assembly unit has an production order. The Users can decide to start a single production order or all production order for the whole client Order.
CSLA is the base for our own ERP-System.
