### ISSUE TITLE
ErrorProvider and ReadWriteAuthorization extenders not working on child object

### ISSUE THREAD

**Issue by rodneyworkman291** [MarimerLLC/cslaforum#430]
I have a EditableRootObject who has a Editable Child object.  

In my windows form app my form is using the ErrorProvider and ReadWriteAuthorization extenders.
On my controls in the form I have set the ApplyAuthorization on ReadWriteAuthorization to true for each control.

There are times when fields in my child object are not editable.  I know from unit testing when I call the childs CanWriteProperty it is editable and not editable at the correct times.  

On the child object I have used several data annotations to apply basic rules such as to denote required fields and string length and so on.

On my form, my save icon is tied to the root objects IsSavable property.  I know when my child is valid and when it is not. As I comply with the rules the forms save button becomes enabled.  So I know the root object is paying attention to the child objects IsSavable/IsValid properties.  

The ErrorProvider works as expected on controls that are bound in the root object but it has no effect on bound controls that are bound to the roots child object.  In other words I do not see the error icon when I should.

In the same way the ReadWriteAuthorization extender enables and disables controls that are bound to the root object but has no effect on the controls bound to the roots child object.

**Comment by tfreitasleal** [comment]
Hi Rodney,

Are you calling
`BusinessRules.CheckRules();`
on the DataPortal_XYZ methods of the cild object?

**Comment by rodneyworkman291** [comment]
Tiago thank you for your suggestion.

Yes.  I verified I am calling **base.Child_Create()** and I know the base Child_Create() is calling BusinessRules.CheckRules() just as you have suggested.  I have evidence that the rules are in fact working in unit test as well as from the UI.  I know they work from the UI because when I test rootObject.IsSavable() and rootObject.IsValid() and even when I examine the broken rules collection these all show when the validation rules are in fact broken and when they are not broken. The problem I am facing is the client UI, via the ErrorProvider extender, is not showing validation issues to the user for items that are in the child object however the ErrorProvider is showing validation issues for items in the root object.  

In the same manner the ReadWriteAuthorization extender is not manipulating the controls for controls bound to properties in the child object.  I have child business properties that when I call CanWriteProperty from my unit test correctly shows true/false in the correct situation.  From my UI, although the UI control was not marked readonly, and the user attempts to change a value whose CanWriteProperty returns false, the system throws an error on the set of that property.  That error is expected and is not what I am asking for help with.  I can write my own code to disable a UI control based on testing each properties CanWriteProperty however, its my belief that someone has already done that in the ReadWriteAuthorization extender.  

I feel like its maybe an issue with that BindingSourceHelper can help me with so I am currently studying Lhotka's chapter on data binding from the Expect C 2008 book.

**Comment by jonnybee** [comment]
The ErrorProvider has a property for DataSource. Thai should be th BindingSource and you must add a separate ErrorProvider for the ChildBindingSource. 

IIRC the same goes for ReadWriteAuthorization.

**Comment by rodneyworkman291** [comment]
Thanks jonnybee that tip helped.  I was not using a ChildBindingSource as I tried to bind everything to the rootBindingSource.  After creating the ChildBindingSource it all worked as expected.
