### ISSUE TITLE
ConnectionManager<>.GetManager

### ISSUE THREAD

**Issue by CrossSlide** [MarimerLLC/cslaforum#439]
Hi,
In the documentation examples I see the hard coded "LocalDB" used with GetManager(). Can't I pull the DB from a connection string in my App.config or am I missing something?

using (var ctx = ConnectionManager<SqlCeConnection>.GetManager("LocalDb"))

Thanks

**Comment by tfreitasleal** [comment]
Hi,
I can't find **LocalDB** on *.cs files but only on *..config files. What's sample you are referring to?

**Comment by rockfordlhotka** [comment]
@CrossSlide  could be referring to the samples from the _Using CSLA 4_ books?

In that case the `GetManager` method is described in the book about data access, including a description on how it interacts with your config file.

If you are referring to the `/Samples` folder, @tfreitasleal recently did a ton of updates on them, and can probably answer any questions you might have.

**Comment by CrossSlide** [comment]
Thanks guys, I think I figured it out. I used .Getmanger("MyDB") to grab my connection string and it seem to be working.

p.s. Yes I was referring to the CSLA 4 books.
