### ISSUE TITLE
Property Value Conversion Code

### ISSUE THREAD

**Issue by CrossSlide** [MarimerLLC/cslaforum#441]
I have some fields that I need to change based on some status values in my business object. It’s not simple conversion but doing some conditional formatting before the field value is returned. Is this a case where I need to use Manual Backing Fields?

**Comment by rockfordlhotka** [comment]
You should be able to do this in a business rule, assuming we're talking about a `string` property.

**Comment by fujiiface** [comment]
@CrossSlide Like Rocky said, if it is a string property this should be similar to the sample ToUpper rule found in the RuleTutorial project: https://github.com/MarimerLLC/csla/tree/master/Samples/NET/cs/RuleTutorial/TransformationRules

**Comment by CrossSlide** [comment]
Got it. Thanks @fujiiface  @rockfordlhotka
