### ISSUE TITLE
Upgrade CSLA-Core from 4.6.500 to 4.6.603 can't find Transactional attribute

### ISSUE THREAD

**Issue by toddhughes1** [MarimerLLC/cslaforum#448]
I'm trying to update my CSLA-Core nuget package from 4.6.500 to 4.6.603, but now I can't seem to find the TransactionalAttribute. (I must add that I'm trying to convert a project to a new .NETStandard project.)

I'm sure it's something simple. Did I miss a note or post somewhere? Did it move, or is it now obsolete?

**Comment by toddhughes1** [comment]
It's because the TransactionalAttribute isn't compiled into .NET Standard/Core. I had to examine the code base to figure this out.

**Comment by rockfordlhotka** [comment]
Ahh yes, that attribute is used to bring COM+ into play, and COM+ isn't supported in netstandard or .NET Core, only in full .NET.

**Comment by toddhughes1** [comment]
Is there somewhere on the forum that has a graph/checklist of which features are included/compiled in which build--that is, netstandard, .NET Core, and full .NET? 

I just had another instance of trying to convert an old project, only to find out that some types weren't in .NET Core. I think this would be very helpful for those assessing whether or not a project type conversion would be possible.
