### ISSUE TITLE
Readonly collection and asp.net dropdownlist

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#452]
Hi All,
conk me on the head but I can't seem to get asp.net dropdownlist working with Readonly collection list : )
it was working fine with NameValueList.
Regards

**Comment by Chicagoan2016** [comment]
Hit my head against the keyboard a couple of times and everything is fine : )

**Comment by rockfordlhotka** [comment]
(LOL)!
