### ISSUE TITLE
Help with CSLA-Core

### ISSUE THREAD

**Issue by rgsoft** [MarimerLLC/cslaforum#456]
I am re-writing a Silverlight application using ASP.net Core (Knockout, SQL backend).

I am having a problem trying to get CSLA to work.  Using VS2017 template Class Library (.net Core) I added CSLA-Core via Nuget (see images) but this causes SafeDataReader not to be recognised (see images)

What is the correct way/steps to add/set up CSLA-Core to be used in a ASP.net core app.?

All help very welcome - is there step-by-step guide or has anyone a sample template/app.

Thanks

![1](https://user-images.githubusercontent.com/13234412/32501010-c9114050-c3ce-11e7-8397-cdd8e8f3b7e2.png)

![2](https://user-images.githubusercontent.com/13234412/32501023-ce979a60-c3ce-11e7-803d-83444ee8c82d.png)

**Comment by JohnWigger** [comment]
@rgsoft ,  You chose a .NET Core class library.  If you instead choose a .NET Standard 2 class library as a template you will have access to SafeDataReader and most of the other things that you expect.

**Comment by rgsoft** [comment]
Thanks....I gave that a try...still same issue

1) .NET Standard 2 class library
2) Nuget CSLA-Core
3) Nuget Install-Package System.Data.SqlClient -Version 4.4.0

![3](https://user-images.githubusercontent.com/13234412/32599701-38a7c774-c535-11e7-8fe6-e6ac7ec0b3ef.png)

**Comment by JohnWigger** [comment]
In case anyone else identifies this as a problem, using the current baseline of 4.6.603, you will get this error. For the time being, you need to retrieve the prerelease beta version of this package, 4.7.100-beta17100905.
