### ISSUE TITLE
Odd XML Comment Issue

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/cslaforum#46]
I was looking at the Intellisense for `Save()`, and I noticed the docs didn't read very well. Here's a screen shot:

![csla xml comments](https://cloud.githubusercontent.com/assets/904213/9658380/7c008034-520e-11e5-8399-616d4b6295fc.png)

It seems like the `<see langword` stuff is being ignored:

```
/// If <see langword="true"/>, triggers overriding IsNew and IsDirty. 
/// If <see langword="false"/> then it is the same as calling Save().
```

This is in VS 2015. This may be something that CSLA is doing right and VS has a bug in it, but I thought I'd report it here first.

**Comment by ajj3085** [comment]
I'd actually file an issue for VS on this; IIRC, even MS' SandCastle project interprets the *langword* attribute correctly on a *see* element.

**Comment by JasonBock** [comment]
Appears this is done now.
