### ISSUE TITLE
Object not returned in DataPortalException

### ISSUE THREAD

**Issue by brinawebb** [MarimerLLC/cslaforum#472]
I'm using Csla 4.7.1 beta 17100905 with .NET Standard 2.0. I've created a library project with my business objects and am testing them directly in an MsTest project. My database is SQLite.

In my library I have a customer object that has a name property. This name has a unique constraint in the database, so if you try and save it, the database bubbles up a unique constraint exception and the save fails. When this happens (in the DataPortal_Insert and DataPortal_Update) I set a property (IsNameUnique = false), check business rules, and then throw the exception. Within the dataportal if I set a breakpoint, my object is now invalid and has a broken rule, and the IsNameUnique property is false.

A few problems I'm seeing:

1. When cust = cust.Save() is called and the failure occurs, cust.IsNameUnique is not false in the object that's returned. The property is the same as before it was called.
2. In my catch, the ex.BusinessObject of the DataPortalException is null. This also happens when I have no exception handling in my DataPortals

I've tried fiddling with these two properties in my app config file and they don't seem to do anything.
AutoCloneOnUpdate and DataPortalReturnObjectOnException

**Comment by jonnybee** [comment]
The proper way to handle this is to have a business rule that checks for uniqueness whenever Name property is changed and/or before you call Save. 

When a Save fails you could display the error mesage. But you should not continue using the possibly returned object. Take f.ex a Root object with new children and grandchildren. When Save fails some of the children may already be marked as "IsNew = false" while others are unchanged and still have IsNew = true (the same could also be said about Change tracking). The standard transaction handling is to roll back all changes and the only object to be in the correct state is the "original" on the client.

**Comment by brinawebb** [comment]
Thanks Jonnybee.

First issue, there is a bug here. DataPortalReturnObjectOnException is not being read from the config file in my unit tests.

Second issue:
<whenever name is changed> This would require me to hit the database (where the names are stored) every time the property changes, adding unwanted overhead in our case.

What I did was override the Save() method. 

        public virtual new Customer Save()
        {
            // This property isn't being read from the app.config, setting it here
            ApplicationContext.DataPortalReturnObjectOnException = true;

            try
            {
                return base.Save();
            }
            catch (DataPortalException ex)
            {
                return (Customer)ex.BusinessObject;
            }
        }

**Comment by rockfordlhotka** [comment]
@brinawebb would you please submit that bug as an issue in the csla repo here on GitHub?

**Comment by brinawebb** [comment]
Thanks Rocky. Was just about to submit and found that it exists. #465 Nice to know that Csla, .NET Standard, and SQLite is being used! Love that Xamarin Live was released today under VS 15.5, really a game changer.
