### ISSUE TITLE
DataPortal_Create and check rules

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslaforum#477]
Hi
I have an object with plenty od business rules like required, etc.
I was expecting the required fields to show the error mark as soon as the object is shown.
It turns out those rules are checked only after the first run of validation, meaning after the first change to a business property.

Advice (and even help) is required. TIA

**Comment by rockfordlhotka** [comment]
iirc, there's no automatic run of rules on a DP_Fetch, assuming that data from the database is valid. If that's not the case then you should add a call to CheckRules at the end of your DP_Fetch method.

**Comment by tfreitasleal** [comment]
Hi Rocky.

I know that. CslaGenFork as an option to generate `BusinessRules.CheckRules();` on _DataPortal_Fecth_.

But I'm asking about **DataPortal_Create**. Shouldn't it check rules by itself? Anyway, even if I force  `BusinessRules.CheckRules();`, no propertie are marked with the broken rules sign until I trigger validation, say type something on some text box and move to another text box.

So how do I force validation programmatically? I want the users to understand what are the required fields as soon as the new empty form shows on the screen.

**Comment by rockfordlhotka** [comment]
What's funny is that @JasonBock and I are having this discussion right now too 😄 

He refreshed my memory though. DP_Create doesn't check rules by default, you have to call `CheckRules` at the end of DP_Create if you want them checked.

**Comment by tfreitasleal** [comment]
My issue is more of a UI thing - I guess that's because I'm not using BindingSource but binding directly to business objects.

Debuggng DataPortal_Create shows that `base.DataPortal_Create()` does check business rules.
`BusinessRules.GetBrokenRules().Count` is zero before running base methods and shows the updated value after running it.

**Comment by tfreitasleal** [comment]
BTW the issue isn't related to binding source. The errorProvider.DataSourcemust be set **after** binding all properies to the model. Issue solved.
