### ISSUE TITLE
Manual Backing Field

### ISSUE THREAD

**Issue by CrossSlide** [MarimerLLC/cslaforum#479]
I need to capture a property value before it's changed and have added a line in the setter. I'm using a Manual backing field but VS IntelliSense is saying it's a Managed backing field and I should only use Get/Set/etc. 

Should I be doing this another way? Thanks

```
public static readonly PropertyInfo<int> CountProperty = RegisterProperty<int>(c => c.Count, RelationshipTypes.PrivateField);
private int _count = CountProperty.DefaultValue;
public int Count
{
    get { return GetProperty(CountProperty, _count); }
	set
	{
		SaveCount = _count; <<----------- Added ---------------
		SetProperty(CountProperty, ref _count, value);
	}
}
```

**Comment by jonnybee** [comment]
The analyzer flags this as an issue as the general  guidance is that you should not have any other code than GetProperty/SeProperty in the property declaration. What is the intended use of this property?

**Comment by CrossSlide** [comment]
I need to know what the original property value was before it was changed so I can adjust some other values after the property value has changed.

**Comment by CrossSlide** [comment]
I found a solution: OnPropertyChanging. Thanks!
