### ISSUE TITLE
Object caching is not working using CslaDataPortalProxy in WCF Service + MVC

### ISSUE THREAD

**Issue by RaviPatelTheOne** [MarimerLLC/cslaforum#482]
We are using 4-tier architecture for developing application using Silverlight and WCF portal. We have also added ObjectCaching (powered by cslacontrib) at WCF layer. So, when first call comes, it goes to cache layer using compress proxy. If object does not exist in cache, it goes to Business object to fetch data. We are able to call WCF service from Silver light application.

**SilverLight configuration config file:** 

```
<add key="CslaDataPortalUrl" value="http://localhost:22627/WcfPortal.svc" />
<add key="CslaObjectFactoryLoader" value="DataAccess.FactoryLoader, DataAccess" />
```

EndpointAddress address = new EndpointAddress(“http://localhost:22627/WcfPortal.svc”);
Csla.DataPortalClient.WcfProxy.DefaultUrl = address.ToString();

BasicHttpBinding httpbind = new BasicHttpBinding();
Csla.DataPortalClient.WcfProxy.DefaultBinding = httpbind;
Csla.DataPortal.ProxyTypeName = typeof(CompressedProxy<>).AssemblyQualifiedName;

**WCF configuration:**

```
<add key="CslaDataPortalProxy" value="CslaContrib.ObjectCaching.CacheDataPortal, CslaContrib" />
<add key="CachingProvider" value="CslaContrib.ObjectCaching.InMemoryCacheProvider, CslaContrib" />

```

**Now, we want to consume same WCF Service using MVC application. We have added following configuration in MVC project web.config and existing WCF Service.**

**MVC Project configuration:**
```
    <add key="CslaDataPortalUrl" value="http://localhost:22627/WcfPortal.svc" />
     <add key="CslaObjectFactoryLoader" value="DataAccess.FactoryLoader, DataAccess" />
```

**WCF configuration:**
Following two keys will be available in WCF configuration.

```
<add key="CslaDataPortalProxy" value="CslaContrib.ObjectCaching.CacheDataPortal, CslaContrib" />
<add key="CachingProvider" value="CslaContrib.ObjectCaching.InMemoryCacheProvider, CslaContrib" />
```
CompressedHost and Csla.Server.Hosts.Silverlight.IWcfPortal are removed from WCF service  as they are not required in MVC application.

When any method (Fetch or Update) is called from MVC controller, it directly calls business object factory method instead of calling CacheDataPortal.

Any suggestion to check why WCF service doesn't call Cache object proxy configured in web.config of WCF project. 

Please let us know if there any other setting need to configure when using WCF services from MVC while using cache factory method?

**Comment by jonnybee** [comment]
Are you using MVC Core or MVC 5? 

Please verify that the CacheDataPortal is the active/used one.

**Comment by RaviPatelTheOne** [comment]
We are using Asp.net MVC 5.
