### ISSUE TITLE
Support for Slack (collaboration)

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#49]
I've been playing with [Slack](https://slack.com/) for a while now and have a community set up that is tied to this GitHub forum.

One of the drawbacks to this forum is that there's no notification scheme - no way to know when someone has posted a new item or reply.

Slack is one way to solve this issue, because it echoes this forum, and Slack has mobile (and desktop) clients that support notifications.

If you are interested in helping me with the next stage of Slack experimentation I'll need your email address - sadly I need to manually add people to Slack unless they are part of my domain (and of course you aren't :smile:).

**Comment by rockfordlhotka** [comment]
The link to this forum's Slack is https://marimerllc.slack.com/

**Comment by ChristopherHlusak** [comment]
We use Slack where I work - it definitely is not a good replacement for "forums" in my opinion in that I haven't found it to be something easily searchable or siloed into individual thread topics; we've found it has certain use cases where it excels more than others - something like "release-day" chatter where it is a useful collaboration tool for something that we really don't need to go back and reference after the conversations have taken place.

I would like to be added; it would be interesting to see how multiple accounts work together if at all - chlusak at microedge dot com.

Thank you!

**Comment by hurcane** [comment]
One potential issue with Slack is that it has a limited search history in
the free product.

**Comment by rockfordlhotka** [comment]
I'm not suggesting we replace the forum with slack - just that slack is a way to get notifications about posts here in the forum.

Perhaps there are other ways to get notifications about posts in a GitHub issues list?

**Comment by ChristopherHlusak** [comment]
I'm confused - I get e-mails every time someone posts something in the forum... (your initial post came to my inbox which is what prompted me to come here).  Are you talking about something different?

**Comment by rockfordlhotka** [comment]
I get emails too - but I get a *lot* of emails so I have rules that route/suppress most of them.

I could probably tune my rules for this forum better. Mostly I guess I'm looking for an excuse to use Slack :smile:

**Comment by marjon** [comment]
Hi Rocky,

I would love to help you test Slack, please use john@kennison.com.au as the
email address.

John
