### ISSUE TITLE
Help with ICloneable

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslaforum#492]
Building a **WPF** library (CslaContrib) I found some issues with `ICloneable`.
Libraries should be as backward compatible as possible. The dependencies were all on 4.6.603 and I'm pushing them back down to 4.5.500. In the meanwhile, I stopped by at 4.6.100.

In 4.5.500 there is no `Csla.ICloneable` but only `System.ICloneable`
In 4.6.100 there are two `ICloneable` to chose from: the same `System.ICloneable` but also a short-living `Csla.ICloneable`.
I say short-living, because `Csla.ICloneable` no longer exists on 4.6.603

So what is this `Csla.ICloneable`? I think it was kind'a workaround for NS or .NET Core or Xamarin or whatever. Since it's a **WPF** library, I think I should always use `System.ICloneable`

@rockfordlhotka  please confirm that us«ng `System.ICloneable` is the correct action.

**Comment by rockfordlhotka** [comment]
I suspect that it was a temporary workaround to some version of netstandard or a PCL - as you suggest.

`System.ICloneable` is what you should use.

**Comment by tfreitasleal** [comment]
Thanks for the confirmation.
