### ISSUE TITLE
In memory Object has no DB Identity after Insert

### ISSUE THREAD

**Issue by Shawellaby** [MarimerLLC/cslaforum#494]
I've spent several years on the outskirts of CSLA working with it at a high-level and have recently started maintaining a legacy app that I've been requested to make what seems like a small change to. I have search the interest for a few days and re-read the Expert C# 2008 Business Objects book and feel while this is not necessarily a CSLA related issue someone here might be able to shed some light on my problem.

I am having a problem with some legacy code from around 2006 using the CSLA framework. A recent request has been made to provide the Database ID of a newly inserted House record to a LOG file when a record is created BEFORE returning back to the list of Houses. The ID is being created by the database (SQL Server 12.0.2000.8 in Azure) and stored on the Insert method below…our problem is the RecordNo field is not being updated after the Insert on the HouseRecord object in memory while the _HouseEditForm_ is open. The UniqueID (RecordNo) is available, from the same instance of the _HouseRecord_, when viewed on the HouseForm page after the _HouseEditForm_ is closed and we are returned to the _HouseForm_ page. Details of this process are below.

**NOTE: When I run this with a Local IIS RemotingHost (LocalProxy) on my machine the RecordNo is populated as I expect. The issue only occurs when a Server RemotingHost (RemoteProxy) is used.**

**For reference:**
CSLA Runtime Version: v2.0.50727
CSLA Version: 2.1.4.0
.Net Framework: 4.0

**RecordNo** (_recordNo) is defined on the HouseRecord : BusinessBase<HouseRecord> class as:

```
private Nullable<int> _recordNo;
[System.ComponentModel.DataObjectField(true, true)]
        public Nullable<int> RecordNo
        {
            get
            {
                return _recordNo;
            }
        }

``` 

When the application is launched _MainForm_ calls an abstract _FormControllerBase_ which is responsible for showing, adding, removing, and closing forms (WinParts) on the _MainForm_. _FormControllerBase_ is also responsible for defining all virtual and abstract methods. During the launch of the app the initial call to _FormControllerBase_ from _MainForm_ sets the _FormController_ property to a new instance of the _HouseController_ with a parameter of a new _HouseForm_. At this point _HouseForm_ is in charge and we continue below.

This should (to this point) appear fairly normal for a base class/mainform model.

_HouseForm_ calls out to _HouseController_ method to create a new _HouseManager_ to obtain a collection of _HouseRecords_

The collection _HouseRecords_ are bound to a DataGridView on the left of the _HouseForm_ and the user has the ability to click on any of them or use the mouse to navigate the cursor up or down in the list. There is an Event Handler that populates a view on the right side of _HouseForm_ that shows the properties and values for the currently highlighted item in the DataGridView.

_HouseController_ is in the main project.
_HouseManager_, _HouseRecord_ and _HouseRecords_ are inside a library in the RemotingHost.

When the user wishes to Edit one of these they click "Edit" on the _HouseMainForm_ and we go to a _HouseEditForm_ view with the editable details of the _HouseRecord_. 

When the user wishes to Create a new _HouseRecord_ the _HouseForm_ calls the _HouseController_ and adds a _HouseEditForm_ passing an argument of the HouseController.CreateNewRecord()

`_houseController.AddEditForm(new HouseEditForm((HouseRecord)_houseController.CreateNewRecord()));`

The CreateNewRecord method on the _HouseController_ actually creates a new _HouseRecord_. The _HouseRecord_  default method calls MarkAsChild(),MarkNew(), sets local properties to isInEdit to True, creates a local id (Guid.NewGuid()) and various other binding sources for dropdown lists. There is a field on _HouseRecord_ called _recordNo which will eventually store the UniqueID from the Database. It is this field that is the scope of this post. The new _HouseRecord_ is returned to the _HouseController_ which then calls the CSLA BeginEdit() method. The _HouseRecord_ is then added to the collection _HouseRecords_ on the _HouseManager_.

The user proceeds to populate the fields with data and when they are satisfied the Save button on the _HouseEditForm_ is clicked.

The Save method then calls the CheckRules() method on the _HouseRecord_ which simply calls the CSLA method ValidationRules.CheckRules(). Next we check the CSLA IsSavable flag on the _HouseRecord_ and if it is true a call to the HouseController.HouseManager.updateHouseRecord(_houseRecord)

The updateHouseRecord method has a local collection _updateHouseRecords for which the incoming _HouseRecord_ is added. A property "IsUpdate" on the _updateHouseRecords object is set to True, then the DataPortal.Update() method is called from the _HouseManager_:

`	_updateHouseRecords = DataPortal.Update(_updateHouseRecords);`

**The full Update method on the _HouseRecords_ class:**

```
[Transactional(TransactionalTypes.Manual)]
		    protected override void DataPortal_Update()
		    {
		      try
		      {
		        if (_isDelete == true)
		        {
		          foreach (HouseRecord obj in DeletedList)
		            obj.DeleteSelf();
		          // now that they are deleted, remove them from memory too
		          DeletedList.Clear();
		        }
		      }
		      catch (Exception e)
		      {
		        throw e;
		      }			
		      try
		      {
		        if (_isUpdate == true)
		        {
		          // add/update any current child objects
		          foreach (HouseRecord obj in this)
		          {
		            if (obj.IsNew)
		              obj.Insert();
		            else
		              obj.Update();
		          }
		        }
		      }
		      catch (Exception e)
		      {
		        throw e;
		      }
		
		      foreach (HouseRecord obj in this)
		      {
		        obj.MarkOld();
		        obj.ApplyEdit();
		       
		      }
		    }
```

Our isUpdate property evaluates to True, our IsNew property evaluates to True and the _HouseRecord_ Insert method is called.

The Insert method on _HouseRecord_ simply adds the properties to a sqlparameter collection and calls out to a stored procedure which returns an Identity.

 	

```
SqlParameter returnParam;

            using (SqlConnection cn = new SqlConnection(Database.NeighborhoodConnection(UserNeighborhood)))
            {
                cn.Open();
                using (SqlCommand cm = cn.CreateCommand())
                {
                    using (TransactionScope tr = new TransactionScope())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
			cm.CommandText = "InsertHouseRecord";
			cm.Parameters.Clear();
			cm.Parameters.AddWithValue("@Cost", Cost);
			........
			All other parameters omitted for brevity
			........
			returnParam = new SqlParameter("@RecordNumber", SqlDbType.Int);
                        returnParam.Direction = ParameterDirection.ReturnValue;
                        cm.Parameters.Add(returnParam);
                        cm.ExecuteNonQuery();
			_recordNo = (int)cm.Parameters["@RecordNumber"].Value;
		     }
		 }
	    }

```

**Stored procedure:**

```
ALTER PROCEDURE [dbo].[InsertHouseRecord]
	(
		@Cost money = NULL,
		........
		All other parameters omitted for brevity
		........
	)
AS
	INSERT INTO Houses (Cost, ...) 
	VALUES (@Cost, ...)
	
	RETURN SCOPE_IDENTITY()

```

**NOTE: I have tried both SCOPE_IDENTITY() and @@IDENTITY**

Thank you for taking the time to read this. If you have any questions or need clarification for anything I have been vague for please let me know.

**Comment by rockfordlhotka** [comment]
Without looking in depth through your code - this sounds very much like the simple/common case where the result of the `Save` method isn't being used to rebind the UI.

Starting around version 3.8 CSLA has consistent behavior for local and remote data portal proxies. Prior to that point we were "optimizing" local proxy by not cloning the object graph, but that led to a whole host of inconsistencies between the two experiences (like what you are seeing).

But all that aside, if you look at the code where the root business object is being saved, I bet you see something like this:

```
obj.Save();
```

When you should see something like this:

```
// unbind the UI
obj = obj.Save();
// rebind the UI
```

**Comment by Shawellaby** [comment]
Thank you for your time.

I understand what you are saying and I will take a look at this from another angle now.

I did want to comment that this isn't even a UI issue....as the RecordNo is never displayed on the Form it is saved from (HouseEditForm). I'm simply trying to read that property from the object after it is Inserted by the DataPortal and write the UniqueId to a log file while still on the HouseEditForm page. I know the object is being updated by the database as when I dismiss the HouseEditForm and see the data in the HouseForm DataGridView the RecordNo is there. The re-binding to the UI worked perfectly.

I don't know of a way to debug this since it works (there is no problems) with a LocalProxy and I cannot set a breakpoint in the RemoteProxy.

**Comment by rockfordlhotka** [comment]
The fact that it works with the local proxy, and you are probably running a version of CSLA prior to 3.8, is why I think the problem is that the result of the `Save` method is being ignored.

When you call `Save`, here's what happens:

1. The object graph is cloned to the app server
  1. The client-side object graph is essentially just garbage now - old data that is obsolete
1. On the app server, the object graph is saved to the db, and as part of that process your db-generated id value is put into the object graph
  1. The client-side object graph is unchanged
1. The server-side object graph is cloned back to the client and returned as a result of `Save`
  1. If you don't replace references to the old/obsolete client-side object graph with the result of `Save` then you can't see the changes made on the server

What I just described is for the remote portal (and _all_ portals in 3.8 and higher). But prior to 3.8 the local portal didn't do the cloning so you'd see the "server-side" changes in the original graph. The BIG problem with that, is that if the update failed part way through the db would roll back, but the object graph was left in an inconsistent/garbage state. That led to tons of bugs that people often didn't even know they had - nasty stuff - hence the change in later versions of the framework.

**Comment by Shawellaby** [comment]
Again, thank you for confirming this issue i'm having.
I am unable to compile and upgrade to 3.8 and since obj = obj.Save() isn't working what I settled on was using the GUID created on the "new" object as a parameter to trigger a "refresh" on the specific HouseRecord in the HouseRecords collection HouseManager.HouseRecords using a "GetItem(Guid id)" method. Not efficient but also not used that much, and it works.

I very much appreciate your time involved in responding (especially so quickly).
