### ISSUE TITLE
Take Newtonsoft.Json dependency?

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#515]
I am _very_ reluctant to take dependencies on anything not provided by Microsoft as part of .NET and their platforms.

However, Microsoft themselves have been taking the Newtonsoft.Json dependency very often of late, and there is some value in CSLA taking this dependency as well - specifically to eliminate a dependency on DataContractSerializer, which is problematic in wasm/Blazor at the moment.

I'm not sure about the broader consequences of taking a dependency on Newtonsoft.Json though, so I want to open this up for conversation.

1. Unlike most third-party components that may lack support or just disappear, this particular component has stood the test of time, and enjoys support from Microsoft within their own components/templates
1. There is no real equivalent to this component from Microsoft; they appear to have abdicated this functionality to Newtonsoft rather than trying to compete
1. Interestingly, Newtonsoft.Json not only does basic JSON serialization better than anyone, but they _also_ have options to do deep serialization as an alternative to BinaryFormatter or NetDataContractSerializer, but entirely cross-platform.

I welcome your thoughts on this idea.

**Comment by tfreitasleal** [comment]
On the comments to the .NET Blog [Introducing .NET Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/), Immo Landwerth from Microsoft clearly states

> Of course, this doesn’t mean we can’t or shouldn’t provide some built-in JSON support. We’ve talked with James about this in the past and I believe there is a lot of opportunity for us to collaborate with him on an even more performant way to provide JSON support in .NET. However, we’re very interested in doing this with him rather than just building “another” JSON.NET.

It looks like Microsoft isn't planning to use anything other than NewtonSoft.Json.

**Comment by hurcane** [comment]
I would venture to guess that many businesses have already taken a dependency on NewtonSoft.Json. I know that we have made that decision for our business.

**Comment by richard-chamberlain** [comment]
I think the dependency on DataContractSerializer is only for MobileList. I think the dependency can be removed by using a variation of the code used in MobileDictionary.

        private const string _valuePrefix = "v";

        protected virtual void OnGetState(SerializationInfo info)
        {
            info.AddValue("count", this.Count);
        }

        protected virtual void OnGetChildren(SerializationInfo info, MobileFormatter formatter)
        {
            bool mobileChildren = typeof(IMobileObject).IsAssignableFrom(typeof(T));
            int count = 0;
            foreach (T child in this)
            {
                if (mobileChildren)
                {
                    SerializationInfo si = formatter.SerializeObject(child);
                    info.AddChild(_valuePrefix + count, si.ReferenceId);
                }
                else
                {
                    info.AddValue(_valuePrefix + count, child);
                }
                count++;
            }
        }

        protected virtual void OnSetChildren(SerializationInfo info, MobileFormatter formatter)
        {
            bool mobileChildren = typeof(IMobileObject).IsAssignableFrom(typeof(T));
            int count = info.GetValue<int>("count");

            for (int index = 0; index < count; index++)
            {
                T value;
                if (mobileChildren)
                    value = (T)formatter.GetObject(info.Children[_valuePrefix + index].ReferenceId);
                else
                    value = info.GetValue<T>(_valuePrefix + index);

                Add(value);
            }
        }

**Comment by rockfordlhotka** [comment]
Nice observation @richard-chamberlain - much better than using DCS or Json.Net!
