### ISSUE TITLE
Property Get / Set code question

### ISSUE THREAD

**Issue by kaoskt** [MarimerLLC/cslaforum#516]
The code below is an extract from a business class we have used for some time. 
It is for a property which uses lazy loading to ensure that the return value is never null.

We recently updated to the CSLA 4.7.100 from 4.3 and now we see warning about this code section:
"Warning	CSLA0007	Properties that use managed backing fields should only use Get/Set/Read/Load methods and nothing else."

What are the issue with this code?
How should it refactored?

Code Exerpt
        public EmailMergeDocList EmailMergedDocs
        {
            get
            {
                if (ReadProperty(EmailMergedDocsProperty) == null)
                {
                    MyLoadProperty(EmailMergedDocsProperty, EmailMergeDocList.NewList());
                }
                return GetProperty(EmailMergedDocsProperty);
            }
            private set { MyLoadProperty(EmailMergedDocsProperty, value); }
        }
        public static readonly PropertyInfo<EmailMergeDocList> EmailMergedDocsProperty = RegisterProperty<EmailMergeDocList>(p => p.EmailMergedDocs, RelationshipTypes.Child | RelationshipTypes.LazyLoad);

**Comment by kaoskt** [comment]
Sorry, should add that MyLoadProperty() is a method we added which sets the property without affecting the IsDirty state of the object.

**Comment by rockfordlhotka** [comment]
There are methods to simplify lazy loading of your object.

```c#
      get { return LazyGetProperty<ProjectResources>(ResourcesProperty, async ()=> LoadPropertyAsync<ProjectResources>(ResourcesProperty, DataPortal.FetchAsync<ProjectResources>())); }
```

**Comment by kaoskt** [comment]
Thanks for that.
What about our requirement to never return null?

Btw, checking for null in the getter also allows us to null out the property at one place and allow lazy loading to populate it later when it is next referenced. Typically do a real data portal call (return something other than an empty list) in those cases.

I guess, I am trying to understand why the warning has been added & if we need to move away from our current getter pattern.

**Comment by kaoskt** [comment]
thanks again.
I should have looked at your reply a bit closer before my last reply.
