### ISSUE TITLE
Csla.DataPortalClient.MobileProxy question

### ISSUE THREAD

**Issue by kaoskt** [MarimerLLC/cslaforum#517]
Applies to CSLA v4.7.100, DotNet 4.6.1.

We are trying to make data portal calls using the mobile proxy for a Xamarin IOS client and are finding limitations. many we have worked around, but this one looks like a game breaker. Haven't got to trying DotNet Standard yet.

It appears the mobile proxy cannot handle non primitive parameters.
EG calling DataPortal_Fetch(MySearchCriteria cr_) fails when MySearchCriteria  is  a class, even if that class is serializable. Using int or string as the criteria works. However providing a single int or string doesn't give us the flexibility we need. Consider returning all the invoices for one client in the month of June.

Is there a way we can use user defined classes as parameters to the DataPortal calls, with the Mobile proxy?

**Comment by jonnybee** [comment]
Does MySearchCriteria inherit from CriteriaBase and use "mananged properties"? F.ex: 

    [Serializable]
    public class Criteria : CriteriaBase<Criteria>
    {
          public static readonly PropertyInfo<int> ProjectIdProperty = RegisterProperty<int>(c => c.ProjectId);
          public int ProjectId
          {
            get { return ReadProperty(ProjectIdProperty); }
            set { LoadProperty(ProjectIdProperty, value); }
        }
     }

**Comment by jonnybee** [comment]
Yes, your criteria classes and business classes must all derive from MobileeList/MobileObject in order to be serializable in the MobilePortal.

**Comment by jonnybee** [comment]
Plain classes with get/set properties will only work when using a built-in .NET BinarySerializer like DataContractSerializer or BinaryFormatter.

**Comment by kaoskt** [comment]
Thank you.
Looks like we have some refactoring to do.
