### ISSUE TITLE
Business rules with context.AddOutValue leaves object in dirty & savable state	

### ISSUE THREAD

**Issue by roberttor** [MarimerLLC/cslaforum#527]
Hello all,
Using Windows forms, c# and CSLA 4.7.100
I have several business rules that are only intendend to get additional/readonly information for a given object ID.
For example, a rule that given a customer ID property fills name, address, … properties using the context.AddOutValue.
The problem that I have is that only calling these rules the object is in dirty state, even if the outgoing information is stored in readonly properties.
Is there any way to fill the outgoing properties without leaving the object in dirty state?
Thanks a lot

Robert

**Comment by roberttor** [comment]
I add more information:
I usually call these rules both from the UI (client context after a property has been changed) as well  from de Data Portal (calling checkrules after loading the primary properties in dp_fetch).
I know that one solution would be to load all the properties in the fetch method, without the need of the rule, and use this rule only when the property is changed in the UI.
This approach works but it makes me to add joins in a lot of sql sentences only to get some basic information that is used very often by several objects. This is not very smart and difficults a lot the code maintenance.
I hope that someone can help me

**Comment by jonnybee** [comment]
When you use AddOutValue the property will always be marked as Dirty. 

The alternative is to use the LoadProperty method in BusinessRule baseclass to load values into the object without marking the field as Dirty. 

    protected void LoadProperty(object obj, Csla.Core.IPropertyInfo propertyInfo, object newValue)

**Comment by roberttor** [comment]
Thank you Jonny,

How can I know the object inside a uule shared by several object classes? Is it possible?

**Comment by jonnybee** [comment]
Use the parameter RuleContext.Target. 

For async rules you also need to set BusinessRule.ProvideTargetWhenAsync property to true.

**Comment by roberttor** [comment]
Hello again. 
Solved! Many thanks for your help!
