### ISSUE TITLE
csla syntax for methods

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#529]
I have a to write several methods in an Editable root object. I read the 'Creating business objects' book and on page 37 there is a discussion about csla methods, my methods will be called with parameters, if I use the provided snipped to generate the method it uses the first overload of RegisterMethod, Here is the code generated by the snippet.

```
   public static MethodInfo NameMethod = RegisterMethod(c => c.Name());
        public void Name()
        {
            // Check Authorization, trows UserNotAuthorizedException if not authorized
            CanExecuteMethod(NameMethod, true);

            // implementation goes here 

        }
```

If I want to add parameters to the method, what should I change in the lambda expression to the RegisterMethod()? any example will be appreciated.

Regards

**Comment by Chicagoan2016** [comment]
Thank you @jonnybee

**Comment by rockfordlhotka** [comment]
Dummy values.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka
