### ISSUE TITLE
How to run rule only when other properties have no broken rules?

### ISSUE THREAD

**Issue by hurcane** [MarimerLLC/cslaforum#539]
I am working on converting some CSLA 3.0-based code to version 4. I have an ugly process in the current code that I think could be handled more elegantly via the version 4 business rules, but I need some help with the techniques that I should use. One issue I am struggling with is validation-related and the other has to do with setting a related property's value.

I think all of my struggles are boiling down to the same question: How to manage the execution of a business rule so that it only executes when all of the input properties are valid?

Business class contains properties for City, State, and Zip code. These properties have some simple business rules for being required. The State has a simple external validation. My plan is to have the external validation run at priority 1 so it will only run once the state has been defined.

In our current code, the business rule to validate the city is setting different kinds of errors. If the state property is empty, it sets an error that the state needs to be filled in, and returns from the rule. It examines the broken rules collection for any broken rules related to the state. If it finds any, the error message is that the city is not valid because the state is not valid and returns from the rule. If those conditions didn't exit the rule, the external validation is executed.

I was presuming to have the external validation for the city also run at priority 1. How should I handle the condition that the state property is valid? Is there a better way than direct examination of the broken rules collection of the target?

Should these situations be broken up into more rules? One concern for the user experience is that city could have a broken rule saying the city is not part of the state (the external validation ran, but failed). If the state is cleared, the error message on the city changes from "not part of the state" to "state must be filled in". Ideally, the business rules would give the user the same experience.

The zip code property has logic similar to the city validation, but it requires both city and state to be valid.

The existing code also attempts to default the zip code. The property setters for the city and state call the same method. The method only changes the zip code value if both properties are valid. I am hopeful this could also be executed within the business rules framework.

That's my mess to deal with. I'm not looking for a complete solution. I am looking for guidance on the best organization of all of these conditions as CSLA 4 business rules.

**Comment by fujiiface** [comment]
This isn’t necessarily a solution but would it make sense to only have a rule on the Zipcode that goes out to the external validation and populates the city and state for you?  You could still have a Required rule for City and State but, unless I’m mistaken, if you know the Zipcode you should be able to get City and State.  I’m sure there are edge cases to my logic but I figured I would throw it out there.

**Comment by hurcane** [comment]
I’m working with existing business objects to be converted from a CSLA 3.0 framework to CSLA 4. I am rather limited in changing the user experience. In these cases, the data entry is being recorded from a live phone conversation, and the data entry needs to support entry in any order.

**Comment by tfreitasleal** [comment]
Usually when we say Business Rules in CSLA, we mean **Property** Business Rules.
There are also **Object** Business Rules. They run when the object is validated.

Have a look at [ObjectRules in CslaContrib](https://github.com/MarimerLLC/cslacontrib/tree/master/trunk/Source/CslaContrib.Net45/Rules/ObjectRules). The `CollectionPopulated` rule makes sure a child collection as at least one item.

**Comment by hurcane** [comment]
I think my problematic rule is a property rule. It runs in response to a property changing and affects another property. It's just that we want the rule to only run when all of the input properties are valid. 

For my zip code default rule, I was planning that the rule would be attached to each of the input properties, something like this example:

BusinessRules.AddRule(new DefaultZipCode(StateProperty, StateProperty, CityProperty, ZipProperty));
BusinessRules.AddRule(new DefaultZipCode(CityProperty, StateProperty, CityProperty, ZipProperty));

State and City are input properties. Zip is an affected property.

After sleeping on this, I think the way that I will do this is to use rule chaining with a gateway rule. The gateway rule will use context.Target, cast it to BusinessBase and use a Linq query to find if any of the input properties from the inner rule have an error in the broken rules collection. I think this gateway would be reusable in my class. I can use it as a gateway to the external validation and the zip code default rules.

**Comment by tfreitasleal** [comment]
> I was planning that the rule would be attached to each of the input properties

Sounds like the right way to do it.

> It's just that we want the rule to only run when all of the input properties are valid.

As I said before, it's up to your `Execute` code to decide when to do something. Your `Execute` code can start by checking if the object `IsValid`. If not, just do nothing. Otherwise do whatever you wan to do.

**Comment by hurcane** [comment]
> Your Execute code can start by checking if the object IsValid. If not, just do nothing. Otherwise do whatever you wan to do.

IsValid at the object level is too coarse. The object has other properties (e.g. required "contact name" property). Contact name can be blank, making the object be not valid, but I would still run the rule for the city and zip code as long the input properties have no broken rules.

There is definitely some difficulty communicating the needs of this business scenario because the term "valid" is overloaded. When I have said "properties are valid" and "city and state to be valid", that really means that there are no broken rules related to the specific properties. That is separate from the concept of the object being valid.

**Comment by ajj7060** [comment]
I think the proper way would be to have the rule that can run only if input properties aren't broken is to set its priority to 1 or higher.  IIRC, rules with priority zero or less always run, and then rules with priority higher than zero only run if there are no broken rules already.
