### ISSUE TITLE
Must be marked as Child 

### ISSUE THREAD

**Issue by CrossSlide** [MarimerLLC/cslaforum#543]
I have a BO that has a child collection that is bound to a GridControl and the data is retrieved without a problem. When I go to the bottom of the grid and add a new item the grid shows it’s in edit mode but as soon as I type a keystroke it bombs with “List item must be marked as a child object”.

I’ve tested my BO and I can add a new record without error, (var nw =BO.MyColl.AddNew(); nw.MyField = “test”; BO.Save()). During testing both the BO.MyColl.IsChild and nw.IsChild return true. So I think this proves my BO is setup correctly.

 Anyone know what I'm doing wrong? Thanks

`<DataGrid ItemsSource="{Binding Model.MyColl}" AutoGenerateColumns="False" >
	<DataGrid.Columns>
		<DataGridTextColumn Binding="{Binding MyField}"/>
	</DataGrid.Columns>
</DataGrid>
`

Error:
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
InvalidOperationException: List item must be marked as a child object

CSLA: v4.6
WPF MVVM: CSLA ViewModelBase

**Comment by CrossSlide** [comment]
SO
``

**Comment by CrossSlide** [comment]
Here is a test I've setup. Again the DataGrid crashes when I try to add a new child, “List item must be marked as a child object”. This is almost a direct copy of the OrderEdit class in the EncapsulatedInvoke example. I'm sure there is a very simple mistake I'm making but...


`    /// THE ROOT \\\
    public class aRootParent : BusinessBase<aRootParent>
    {
        public static readonly PropertyInfo<int> IdProperty = RegisterProperty<int>(c => c.Id);
        public int Id {...}

        public static ...(c => c.RootParentField);
        public string RootParentField {...}

        public static ...(c => c.ListOfChild, RelationshipTypes.Child);
        public aListChild ListOfChild {...}

        public static aRootParent NewRootParent()
        {
            return DataPortal.Create<aRootParent>();
        }

        [RunLocal]
        protected override void DataPortal_Create()
        {
            using (BypassPropertyChecks)
            {
                Id = -1;
            }
            ListOfChild = DataPortal.CreateChild<aListChild>();
            base.DataPortal_Create(); 
        }
    }

    /// THE LIST \\\
    public class aListChild : BusinessListBase<aListChild, aChild>
    {
        // Base handles creation...
    }
	
    /// THE CHILD \\\
    public class aChild : BusinessBase<aChild>
    {
        public static ...(c => c.Id);
        public int Id
        {...}

        public static ...(c => c.ChildField);
        public string ChildField
        {
            get { return GetProperty(ChildFieldProperty); }
            set { SetProperty(ChildFieldProperty, value); }
        }

        protected override void Child_Create()
        {
            using (BypassPropertyChecks)
            {
                Id = -1;
            }
            base.Child_Create();
        }
    }
	
	/// View \\\
	<DataGrid ItemsSource="{Binding Model.ListOfChild}" AutoGenerateColumns="False" >
		<DataGrid.Columns>
			<DataGridTextColumn Header="Child" Binding="{Binding Path=ChildField}"/>
		</DataGrid.Columns>
	</DataGrid>
`

**Comment by CrossSlide** [comment]
For future newbies there is no  add new concept in WPF...

**Comment by rockfordlhotka** [comment]
There is a workaround (typically) however, in that you can handle the UI control's event indicating that it would like to add a new item and then you can add it via `mycollection.AddNew()`. It is a bit messy, and it would be better if the WPF datagrid used the data binding interfaces properly...

**Comment by CrossSlide** [comment]
Thanks Rocky! @rockfordlhotka
