### ISSUE TITLE
ProjectTracker: Could not load file or assembly 'Csla, Version=4.7.101.0,

### ISSUE THREAD

**Issue by grahamblandford** [MarimerLLC/cslaforum#544]
Hi guys,

I'm trying to move forward on some ASP.NET MVC stuff using CSLA and after digging out the eBooks that I'd purchased some time agi for CSLA 4, I've downloaded the latest Project Tracker sample project, but I'm having issues running it.

After unloading the Xamarin-type projects that I don't need (yet) as they were giving me a bunch of errors, I'm left with 8 projects that all build fine, but as soon as I run it and what looks like the main form is presented, I get THIS error:

be = {"Could not load file or assembly 'Csla, Version=4.7.101.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"}

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Csla
  StackTrace:
   at Csla.DataPortalException.get_BusinessException()
   at WpfUI.ViewModels.ViewModel`1.OnError(Exception error) in C:\Users\Graham\Documents\Visual Studio 2017\csla-4.7.101\Samples\ProjectTracker\ProjectTracker.Ui.WPF\ViewModels\ViewModel.cs:line 31
   at Csla.Xaml.ViewModelBase`1.set_Error(Exception value)
   at Csla.Xaml.ViewModelBase`1.QueryCompleted(Object sender, EventArgs e)
   at Csla.DataPortal`1.OnFetchCompleted(DataPortalResult`1 e)
   at Csla.DataPortal`1.<BeginFetch>d__35.MoveNext()

I've updated all of the CSLA nuget packages to the same level, but no idea where this is coming from?!

Any help would be appreciated.

Thanks,
Graham

**Comment by rockfordlhotka** [comment]
You may need to change the data portal configuration to use your local web server instead of Azure. 

It is set to use Azure by default, but I've upgraded the Azure site to 4.7.200 already.

**Comment by grahamblandford** [comment]
Thanks Rocky. Never thought to give that a try. I’ll let you know. 

I’m guessing I could also update the Nuget packages and recompile to 4.7.200 to resolve it also(?)

Graham
