### ISSUE TITLE
CslaActionExtender

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#548]
I am working on a Winforms Application and thought of using CslaActionExtender conder, Although we have a very good example showing how to use CslaActionExtender cotnrol but the ProjectTracker doesn't use the CslaActionExtender, I wonder if there is a reason or CslaActionExtender is no longer needed?

Kind regards

**Comment by tfreitasleal** [comment]
Hi,

I'm sure @rockfordlhotka can explain his choices better than me but I would say Project Tracker intends to show how a CSLA application can be done, but also how CSLA works.

You may notice that Resource and Project classes aren't symmetrical, meaning they have different behaviours. I always thought they were different on purpose, so we can see different ways of doing it.

You may also notice that the BindUI/Rebind could be done in a completely different way, but the way it's done shows in detail how binding works.

CslaActionExtender is a great control that makes life a lot easier, by hiding the inner details of DataBinding. So it's not the best choice to show in detail how DataBinding works.

**Comment by Chicagoan2016** [comment]
Thank you @tfreitasleal
