### ISSUE TITLE
Required properties

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#562]
**Question**
I have a business object where almost every property is required. I have a couple of questions.
1) I have been using 'Csla.Rules.CommonRules.Required' for required properties but I was wondering  is there a better syntax to mark all properties as required? we could also use [Required] , just a thought : )

2) Should I give my 'Required' business rules a priority of -1? since no need to run any other business rules if the required properties are not there.

Kind Regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms, WPF,  MVC

**Comment by rockfordlhotka** [comment]
The attributes out of `DataAnnotations` are great! But they have a couple limitations you should be aware of.

1. They are a compile-time thing, so aren't good for multi-tenant configurable scenarios
1. They are per-property, so simplistic - but really convenient for the per-property scenario

**Comment by jonnybee** [comment]
Another limitation is translations in case your application has multi-lingual user interface. 
Csla Rules comes with resource files for translations. When using System.ComponentModel.DataAnnotations your code must specify the typeof Resource file and ResourceName to use to get translations.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka , Thank you @jonnybee
