### ISSUE TITLE
Business rule utilizing 'Exists' Command objects

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#563]
**Question**
In one of my use cases I make sure to alert the users if they are trying to insert existing data in the Database. I have written several Command objects that implements the 'exists' functionality. When I was coding  the business rule that utilize one of these command objects I thought may be we could have  a business rules where we pass the 'IDProperty' and the 'command' object to the business rule, that way one business rule will work with all the 'exists' command objects in the project.
Any thoughts?

kind regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms, WPF, MVC.

**Comment by rockfordlhotka** [comment]
I think that's fine, as long as you implement the DP_Execute method in a maintainable manner. It could easily become a big/fragile if..else or switch block, and that'd be ugly. But if you implement it using some sort of DAL factory model or provider model that seems pretty reasonable.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka
