### ISSUE TITLE
CSLA-ASPNETCORE-MVC(4.7.101) : Type.GetType - _dayType is null

### ISSUE THREAD

**Issue by jhuerta013** [MarimerLLC/cslaforum#566]
**Question**
How can I get the type on the Dal.DalFactory to find the type. Its always null.

**Version and Platform****Question**
Hello all,

I am trying to create my first project using CSLA-ASPNETCORE-MVC(4.7.101). When I get to the Dal.DalFactory method GetManager the Type.GetType fails. The _dayType is null. I've done some research and I know that with .NET Core assemblies are not loaded/found by default. Can anyone please provide help on what exactly I need to do. I have a full version of the  MVC5 4.6 sample working which I used as a reference. Any help or direction would be greatly appreciated.

Thank you.
  

**Version and Platform**
CSLA version: 4.7.101
OS: Windows
Platform: ASP.NET Core, MVC

CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
The most common issue is that the DLL isn't in the appropriate server-side directory - as in, the DLL to be dynamically loaded just isn't there on the server (deployment issue).

**Comment by Chicagoan2016** [comment]
Assuming you have two projects in your solution, YourProject.Dataaccess and YourProject.Dataaccess.Sql.
I had encountered similar errors in the past and the reason was, I didn't have a 'Reference' to YouProject.Dataaccess in YourProject.Dataaccess.Sql.

Kind Regards

**Comment by jhuerta013** [comment]
Hello,
Sorry for not clearing my setup.   I have 1 solution with 4 projects. 

Project.Dal - References (None)
Project.DalSQL - References (Project.Dal)
Project.Library - References (Project.Dal)
Project.MVC Core - References (Project.Library)

When I try to add the reference from Project.Dal to Project.DalSQL I get the "circular dependency" error. My understanding is that with standard .Net the Project.Dal.GetManager() would get the "_dalType = Type.GetType(dalTypeName);" assembly for the type via the ones that were loaded by the main web project but this is not the case with Core.

**Comment by rockfordlhotka** [comment]
References would normally be like this:

Dal-><none>
Library->Dal
DalSQL->Dal
MVC->Library, DalSQL, Dal

It is worth noting that `MVC` _only_ references `DalSQL` to get it deployed, not because it actually uses it directly. Technically `MVC` doesn't need to reference `Dal`, because `Dal` will come along for the ride with `Library`, but this makes it explicit that `Dal` needs to deploy on the server too.

**Comment by jhuerta013** [comment]
Wow! Thank you so much rocky. I cant believe it was that simple. Danget!!!!! and I just notice that my other MVC project also had the same references are you describe! One of those issues where I was over thinking it. 

Thanks again. Im off to the races!
