### ISSUE TITLE
Default value of CanRunAsAffectedProperty  in BusinessRule class

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#567]
What's the default value of CanRunAsAffectedProperty ?
Kind Regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms, WPF

**Comment by michaelcsikos** [comment]
I believe it's `true`. Have a look at the PropertyRule.cs file.

**Comment by jonnybee** [comment]
Yes, true is the default value.

      CanRunAsAffectedProperty = true;
      CanRunOnServer = true;
      CanRunInCheckRules = true;

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos , Thank you @jonnybee
