### ISSUE TITLE
Request to @jonnybee 

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#568]
Hi @jonnybee ,
Is there a way we could get PDF version of two of your blog posts please?

https://jonnybekkum.wordpress.com/2011/08/29/csla-4-2-rules-update/
https://jonnybekkum.wordpress.com/2012/11/07/csla-4-5-ruleengine-update/

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by michaelcsikos** [comment]
You could print them to PDF with Windows 10.

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos , you rock
