### ISSUE TITLE
Command object

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#569]
I have always used Command object by intializing it through its constructor. I was reading P70 of 'Creating Business objects' book and in Table 15--second item it states that we could also initialize a command object by setting its properties, I tried to do this today but couldn't get it working since we don't  create instance of a command object. We have one static method 'Execute' which calls DataPorta.Execute.
Any ideas

Kind Regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms, WPF

**Comment by michaelcsikos** [comment]
```
var cmd = new ExampleCommand(...);

// set cmd properties

cmd     = DataPortal.Execute(cmd);

// or

cmd     = await DataPortal.ExecuteAsync(cmd);
```

**Comment by Chicagoan2016** [comment]
@michaelcsikos , We usually implement the constructor private, I think public constructor was a requirement for Silverlight (if memory serves)

**Comment by michaelcsikos** [comment]
That was for business classes. For command classes just make the class a nested private class with a public constructor.

**Comment by Chicagoan2016** [comment]
@michaelcsikos , I code Command objects in separate files and under a folder 'Command objects' in Business Layer projects, I think your proposed solution might not work in this case

**Comment by michaelcsikos** [comment]
You can still nest the private command class inside another static class.

```
public static class MyCommands
{
    public static async Task<bool> DoExampleAsync(...)
    {
        var cmd = new ExampleCommand(...);

        cmd     = await DataPortal.ExecuteAsync(cmd);

        return cmd.Result;
    }
    [Serializable]
    private class ExampleCommand
        : CommandBase<ExampleCommand>
    {
        public bool Result { get; private set; }

        public ExampleCommand(...)
        {
        }

        protected override void DataPortal_Execute()
        {
            Result = ...
        }
    }
}
```

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos
