### ISSUE TITLE
Caching in NameValueClasses and ReadonlyList

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#571]
Hi All,
I use caching mechanism of using a static variable in my NameValue Classes and ReadonlyList classes as shown in ProjectTracker sample but I have noticed in a  Form (Winforms) which have 7,8 comboboxes with few hundred items each, that this mechanism is not making a big difference.
Should I move to System.Runtime.Caching ?

Kind Regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms, WPF

**Comment by michaelcsikos** [comment]
So you already have the list loaded, but the `ComboBox` is still slow to load? If this is the case, consider suspending the binding of the `ComboBox` while you set the `DataSource`.

I use the following extension method to make this easier. It works when binding to `Text` (i.e. `DropDown`) or `SelectedValue` (i.e. `DropDownList`).

If you're using an intermediate `BindingSource` for the `ComboBox.DataSource` pass that in, too.

```
public static void SuspendBindingsAndSetDataSource(this ComboBox comboBox, object dataSource)
{
    comboBox.SuspendBindingsAndSetDataSource(null, dataSource);
}

public static void SuspendBindingsAndSetDataSource(this ComboBox comboBox, BindingSource bindingSource, object dataSource)
{
    var bindText                   = comboBox.DataBindings["Text"];
    var bindSelectedValue          = comboBox.DataBindings["SelectedValue"];

    var oldTextUpdateMode          = DataSourceUpdateMode.Never;
    var oldSelectedValueUpdateMode = DataSourceUpdateMode.Never;

    if (bindText != null)
    {
        oldTextUpdateMode             = bindText.DataSourceUpdateMode;

        bindText.DataSourceUpdateMode = DataSourceUpdateMode.Never;
    }

    if (bindSelectedValue != null)
    {
        oldSelectedValueUpdateMode             = bindSelectedValue.DataSourceUpdateMode;

        bindSelectedValue.DataSourceUpdateMode = DataSourceUpdateMode.Never;
    }

    if (bindingSource != null)
    {
        bindingSource.RaiseListChangedEvents = false;
        bindingSource.DataSource             = dataSource;
        bindingSource.RaiseListChangedEvents = true;

        if (comboBox.DataSource != bindingSource)
            comboBox.DataSource = bindingSource;
        else
            bindingSource.ResetBindings(false);
    }
    else
    {
        comboBox.DataSource    = dataSource;
        comboBox.SelectedIndex = -1;
    }

    if (bindText != null)
    {
        bindText.DataSourceUpdateMode = oldTextUpdateMode;

        bindText.ReadValue();
    }

    if (bindSelectedValue != null)
    {
        bindSelectedValue.DataSourceUpdateMode = oldSelectedValueUpdateMode;

        bindSelectedValue.ReadValue();
    }
}
```

**Comment by tfreitasleal** [comment]
@michaelcsikos I think I will add this to the ComboBox extensions methods on https://github.com/tfreitasleal/CslaExtremeDemos

**Comment by michaelcsikos** [comment]
@tfreitasleal Cool ;-)

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos , @tfreitasleal I would like to see an example of its use : ), I know  I am lazy : )

**Comment by Chicagoan2016** [comment]
@michaelcsikos , I have been using this and I am not seeing any difference in performance, may be I am using it wrong? 

Regards

**Comment by michaelcsikos** [comment]
I can't remember the exact scenario that required this. When I tested it the other day it made no difference to the binding time, either, for simple scenarios. Sorry about that. If I remember why I made the extension I'll let you know.

**Comment by Chicagoan2016** [comment]
@michaelcsikos  Thank you
