### ISSUE TITLE
Rule chaining or Inheritance?

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#573]
Hi All,
I have a form where the value in a certain dropdown dictates which business rules should be added to the object, The properties of the business object and Dataacess pretty much stay the same.
I was wondering if I should use Rule Chaining to implement an outer rule that selects inner rules based on dropdown value but for some reason it doesn't sound like an elegant solution because the dropdown has over 15 values and there will be a big 'case' statement inside the outer rule, am I right?

Another option is to use inheritance where the base class is a concrete class with properties and dataportal_XYZ methods and the sub classes (chosen based on dropdown value) only overrides 'AddBusinessRules' method. This solution sounds elegant to me : ), I remember when I used to work on CSLA 1.xx,  Inheritance like this wasn't easy ( I am sure my skills were the reason).

Suggestions please?

kind regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by michaelcsikos** [comment]
Is the drop-down value bound to the business object? Or are you creating a new object after a button click?

**Comment by Chicagoan2016** [comment]
dropdown is populated from a readonly collection and 'value' of the dropdown reaonlycollection is a also a property in the main Business object which is of root stereotype.
I am a little rusty when it comes to databinding in Winforms, I took over this project after years of not working with Winforms so I am going to manually call the 'save' method after a button click.
I hope I explained it better : )

**Comment by jonnybee** [comment]
I think maybe creating different RuleSets would be e good solution for you. 
Remember each RuleSet must be a complete set of rules tor the type.

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos , Thank you @jonnybee , you guys are the best!

I was wondering what is our mentor (@rockfordlhotka )'s opinion about this ? : )  , of course if time permits.

kind regards

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos , Thank you @jonnybee
