### ISSUE TITLE
List of properties in a business objects

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#575]
Hi All,
I remember reading somewhere in CSLA books that because of 'Field Manager" in CSLA we can get a list of properties for a business object without using Reflection. Could someone please show me how to do this?

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by ajj7060** [comment]
FieldManager.GetRegisteredProperties()

**Comment by rockfordlhotka** [comment]
Or `Csla.Core.PropertyInfoManager.GetRegisteredProperties(obj)`

**Comment by Chicagoan2016** [comment]
Thank you @ajj7060 , Thank you @rockfordlhotka
