### ISSUE TITLE
custom base class for readonly child stereotype

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#578]
Hi All,
I created custom base class to inherit from, instead of inheriting from BusinessBase and I followed the pattern 
  public interface IChild : Csla.Core.IEditableBusinessObject, IMobileObject

For readonly child what should I do? should I inherit from Csla.Core.IReadOnlyObject and I MobileObject?

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by michaelcsikos** [comment]
Why not just inherit from `ReadOnlyBase<T>`?

**Comment by Chicagoan2016** [comment]
@michaelcsikos , you are right, I have actually inherited my Editable custom base class from 'BusinessBase' and there is interface with properties that I want to inherit in every editable object and my custom base class implements both BusinessBase and the custom interface ( The interface was suggested by @jonnybee )

Should I follow the same pattern because I do need some properties that I want to inherit in every readonly object?

Thanks

**Comment by michaelcsikos** [comment]
Yes, I would inherit from ReadOnlyBase<T> with your own interface and virtual or abstract methods/properties.
