### ISSUE TITLE
CommandBase serialisation of type object not supported

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/cslaforum#579]
**Question**
I am attempting to use a command which has a couple of parameters.  

``` csharp
        public static async Task CompleteVisitAsync(int visitId, int[] questionIds)
        {
            var command = new CompleteVisitCommand();
            command.VisitId = visitId;
            command.QuestionIds = questionIds;
            command = await DataPortal.ExecuteAsync<CompleteVisitCommand>(command);
        }

```

During `DataPortal.ExecuteAsync` I get this exception:

> Message: System.NotSupportedException : Serialization of type object is not supported.

Stack trace:

> at Csla.Serialization.Mobile.CslaBinaryWriter.Write(Object target, BinaryWriter writer)
   at Csla.Serialization.Mobile.CslaBinaryWriter.Write(Stream serializationStream, List`1 objectData)
   at Csla.Core.ObjectCloner.Clone(Object obj)
   at Csla.DataPortal`1.<DoUpdateAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.DataPortal`1.<ExecuteAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.DataPortal.<ExecuteAsync>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Foo.Business.CompleteVisitCommand.<CompleteVisitAsync>d__9.MoveNext() in C:\Users\Foo\Source\Repos\Foo\src\Foo.Business\CompleteVisitCommand.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foo.Business.VisitSummaryInfo.<CompleteAsync>d__14.MoveNext() in C:\Users\Foo\Source\Repos\Foo\src\Foo\VisitSummaryInfo.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
Result Message:	System.NotSupportedException : Serialization of type object is not supported.

Here is the command class:

```csharp

   [Serializable]
#pragma warning disable CSLA0003 // Find CSLA Business Objects That do not Have Public No-Arugment Constructors
    public class CompleteVisitCommand : CommandBase<CompleteVisitCommand>
#pragma warning restore CSLA0003 // Find CSLA Business Objects That do not Have Public No-Arugment Constructors
    {

        public CompleteVisitCommand()
        {

        }

        public static readonly PropertyInfo<int> VisitIdProperty = RegisterProperty<int>(c => c.VisitId);
        public int VisitId
        {
            get
            {
                return ReadProperty(VisitIdProperty);
            }
            private set
            {
                LoadProperty(VisitIdProperty, value);
            }
        }

        public static readonly PropertyInfo<int[]> QuestionIdsProperty = RegisterProperty<int[]>(c => c.QuestionIds);
        public int[] QuestionIds
        {
            get
            {
                return ReadProperty(QuestionIdsProperty);
            }
            private set
            {
                LoadProperty(QuestionIdsProperty, value);
            }
        }
      
        public static async Task CompleteVisitAsync(int visitId, int[] questionIds)
        {
            var command = new CompleteVisitCommand();
            command.VisitId = visitId;
            command.QuestionIds = questionIds;
            command = await DataPortal.ExecuteAsync<CompleteVisitCommand>(command);
        }

        protected new async Task DataPortal_Execute()
        {
            using (var dbContext = ReusableContext<IDatabase>.Get())
            {
                // do stuff
                await dbContext.Context.SaveChangesAsync();
            }

        }

    }

```

Notes:

- whether or not I have a public constructor doesn't seem to make a difference.
- If I use ordinary (non propertyinfo) properties, the command executes (this error goes away) but the property values are then lost. This is the case even I add a ` [RunLocal]` attribute above the  `DataPortal_Execute` method.

What am I missing here?

**Version and Platform**
CSLA version: 4.7.200-R18051402
OS: Android.
Platform: Xamarin

**Comment by dazinator** [comment]
It seems the problem is the `int[]`. If I remove that things work. I assume serialisation of int[] array is a known limitation of the serialiser or is this a bug?

**Comment by dazinator** [comment]
I was also under the impression that `RunLocal` avoided serialisation? SO I would have thought adding RunLocal would have worked around this..

**Comment by tfreitasleal** [comment]
> It seems the problem is the int[]. If I remove that things work. I assume serialisation of int array is a known limitation of the serialiser or is this a bug?

Csla serialization has its own rules. You can't use `type[`] nor `List<T>`; you must use `Csla.Core.MobileList<T>`

**Comment by ajj7060** [comment]
As far as the RunLocal, it used to be that the local data portal didn't serialize, however many people were caught by errors when they later tried to switch to a remote data portal as they did something improperly.  So the decision was made that local data portal calls also serialize the object, so that the behavior is consistent and these issues would always be exposed.

**Comment by dazinator** [comment]
Thanks for clarifications both!
Btw: PropertyInfo style with List<int> seems to work ok - maybe an enhancement was made. However i'll use mobilelist to be safe.

**Comment by lmsantin** [comment]
> > It seems the problem is the int[]. If I remove that things work. I assume serialisation of int array is a known limitation of the serialiser or is this a bug?
> 
> Csla serialization has its own rules. You can't use `type[`] nor `List<T>`; you must use `Csla.Core.MobileList<T>`

I'm having the same issue., I'm using CSLA.NET Core. My commandbase has a property and the type of that property is a class, it has the Serializable attribute.

Since the Serializable attribute is not working as in previous CSLA versions, how can I serialize that class?

**Comment by rockfordlhotka** [comment]
This is all dependent on the particular serializer you are using. CSLA now defaults to the `MobileFormatter`, which has some limitations, but some major advantages as well (in terms of resulting size of the serialized payload). One key reason this became the default is that other serializers weren't available across all platforms.

Starting in CSLA 4.9 you can choose the `BinaryFormatter` for all .NET implementations where that serializer exists. And fortunately it does exist in .NET Standard 2.0 (it didn't in the 1.x versions).

Still, my recommendation is to stick with `MobileFormatter` (the default).

The rules are a bit different - it can only serialize primitive types and objects that implement the CSLA `IMobileObject` interface. There are a number of base types in `Csla.Core` that do this for you, and all the CSLA base types that you normally use are subclasses of those.

**Comment by ronnymgm** [comment]
Hello @rockfordlhotka  you mentioned :
"Starting in CSLA 4.9 you can choose the BinaryFormatter for all .NET implementations where that serializer exists. And fortunately it does exist in .NET Standard 2.0 (it didn't in the 1.x versions)."

Does this mean can we configure the HttpProxy to use the traditional BinaryFormatter instead of the Mobile.
We have huge amounts of code in libraries not following the MobileFormatter rules for serialization.
And we would like if possible to use the http dataportal but with the traditional BinaryFormatter.
Migrating the code is hard because the error is just an "unable to serialize" error without any detail about the object.

Thanks for you feedback.

**Comment by angtianqiang** [comment]
@ronnymgm 
Has my library been successfully migrated? I am in the process of migration. I have encountered the problem that I cannot use BinaryFormatter

**Comment by KC7465128305** [comment]
Hi Rocky,

"The rules are a bit different - it can only serialize primitive types and objects that implement the CSLA IMobileObject interface. "

Does that mean that not only type object not supported but type byte[] also not supported?

**Comment by michaelcsikos** [comment]
More information in the exception would be very helpful. This is extremely hard to debug in version 4.11.2.
