### ISSUE TITLE
I found no posts in the old forum...

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslaforum#59]
I went to http://forums.lhotka.net/forums/
saw no posts and read a label saying "There are no posts to show. This could be because there are no posts in this forum or due to a filter."

Is it something to do with my browser's cache?

**Comment by rockfordlhotka** [comment]
The forum apparently filters by time, and all the posts are outside the date range. You need to change the filter to see the (now) old posts.

![snip_20150917161708](https://cloud.githubusercontent.com/assets/2333134/9946255/b7ea4ac2-5d57-11e5-9336-7c5c23a90b98.png)

**Comment by tfreitasleal** [comment]
Thanks Rocky. I changed the filter and saved it, Is there a way you - as administrator - can change the default filter?

**Comment by rockfordlhotka** [comment]
I don't see any way to do that, no.
