### ISSUE TITLE
Override Save()

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#590]
**Question**
I found out that I couldn't override Save() but could do so with SaveAsycn() as suggested in #104 ,
I know #104 is a little old so is it still the current practice? Since we will be calling Save() from UI, will Save() call SaveAsync() ?

kind regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by michaelcsikos** [comment]
Yes, `SaveAsync()` is called by `Save()`

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos

**Comment by Chicagoan2016** [comment]
@michaelcsikos , when did we stopped allowing overrides of Save() method?, if memory serves it could be done in Csla 1.xx, 2.xx ....

**Comment by michaelcsikos** [comment]
I think it was 4.x when `async` was added to .NET.

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos
