### ISSUE TITLE
DynamicBindingListBase

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#592]
**Question**
I know DynamicBindingListBase implements IBindingList but does it implement IBindingListView too?

regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms.

**Comment by rockfordlhotka** [comment]
iirc, `IBindingListView` is specific to Windows Forms and is designed for creating views over collections, so it isn't something a model would ever implement.

`DynamicBindingListBase` is a subclass of `BindingList`
https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Shared/Core/MobileBindingList.cs#L29

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka
