### ISSUE TITLE
Default value of a property and CommonRules.Required

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#596]
**Question**
I want CommonRules.Required to fail at default values of the properties. Is it possible?
kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
I would think that's a different (custom) rule.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka
