### ISSUE TITLE
Close WinForm using control box's "X" button

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#597]
**Question**
Could we use ActionExtender to detect the 'FormClosing' event caused by 'X' button in control box (winforms)?

regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms

**Comment by rockfordlhotka** [comment]
Maybe Tiago knows? He's done a lot more recent WinForms work than anyone I think.

**Comment by tfreitasleal** [comment]
If you handle all buttons click events that can make a form close, say by setting a flag, if the flag isn't set on the FormClosing event, then it was caused by the Form Close button.

**Comment by Chicagoan2016** [comment]
Thank you @tfreitasleal
