### ISSUE TITLE
My understanding of 'dirty' object

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#598]
**Question**
When we create a new csla object, csla marks it as dirty, but  from a user's perspective who has just opened a form to enter new address, demographic etc. and hasn't done anything yet and wants to close  the form shouldn't get any prompt of 'unsaved' work.
In our project we can't seem to find a solution for this scenario, we would like to have our new objects marked as 'clean'. we tried MarkClean() but it doesn't work.
Is there a way we could mark an object as dirty only when one of its property's SetProperty method is called?
or if possible we could override base.DataPortal_Create()?

Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by hurcane** [comment]
The CSLA default is to always return True for IsDirty when the object is new. If you are following the standard advice and have your own base business class that inherits from CSLA's base business class, you can override IsDirty. To do what you have proposed for the behavior, you want to have two states (New without changes and New with changes) that don't exist in the base CLSA implementation. You'll need a new variable to track with/without changes. An override of MarkDirty could update the state variable when the object is new.

I envision pseudo-logic like this in IsDirty:
if (IsNew()) {return CustomIsDirtyMethod();} else {return base.IsDirty();}

For MarkDirty:
if (IsNew()) {_newHasChanges = true;}
base.MarkDirty();

**Comment by Chicagoan2016** [comment]
@fujiiface , we tried that but there are cases where the user do change the 'new' object.
I think our ( or just mine)  confusion is the concept of 'dirty' object. One 'dirty' is the framework's 'dirty' --> whenever a new object is created its immediately marked as dirty, the other 'dirty' is  when a user actually modifies something

**Comment by Chicagoan2016** [comment]
hurcane, I think you just hit the nail on the head : )

**Comment by Chicagoan2016** [comment]
hurcane, I think if we can just override the standard behavior and mark new objects as clean, that will solve our current use cases. I really don't want to have another state variable inside my objects.
Any suggestion about overriding the default behavior? or not calling MarkDirty?

Regards

**Comment by hurcane** [comment]
If you do not override IsDirty, then new objects will _always_ be dirty. There is absolutely no way to work around that situation without overriding IsDirty. If you look at the CSLA source code for IsDirty, you'll see the new object handling has no conditions other than the object being new.

Why are you concerned about adding a simple boolean variable? It is only going to be inside your custom base class. And it will only be referenced in your overrides of MarkDirty and IsDirty. It doesn't seem to me to be terribly complicated scenario.

**Comment by fujiiface** [comment]
@Chicagoan2016 Yeah sorry about that. I was reading and writing while I was on the road during lunch so it seems like I misunderstood your requirement.

**Comment by rockfordlhotka** [comment]
I'm puzzled - is this thread a duplicate of https://github.com/MarimerLLC/cslaforum/issues/595?

**Comment by Chicagoan2016** [comment]
Yes , I think it's a duplicate thread, let me close it :)
