### ISSUE TITLE
Conventions for this "forum?"

### ISSUE THREAD

**Issue by ajj3085** [MarimerLLC/cslaforum#6]
Just starting to use this new forum; in the previous we had a Verify Answer button.  Should we close issues that we feel are resolved here?  I ask because the default when clicking on the Issues link is to only show open issues, so closed ones might be missed.

**Comment by rockfordlhotka** [comment]
We could close them, or I can create a label to mark issues as closed.

I am curious, can you label issues, or is that an admin-only thing?

**Comment by ajj3085** [comment]
I couldn't find anywhere for me to add a label, I looked when I did my first post.

**Comment by rockfordlhotka** [comment]
That's unfortunate. I guess it makes sense, but I wish there was a setting to allow anyone to add labels in this repository.

**Comment by rockfordlhotka** [comment]
I've invited you to a group that might give you the ability to add/change labels. Can you let me know if that makes a difference?

**Comment by ajj3085** [comment]
I still don't see anything allowing me to set labels.

**Comment by ajj3085** [comment]
Sorry, I joined the group but still don't see anything.

**Comment by rockfordlhotka** [comment]
OK, apparently people have to be an admin to assign a label. Pretty high bar.

**Comment by rockfordlhotka** [comment]
In the end, I think closing answered posts is the way to go.
