### ISSUE TITLE
Using Autofac to resolve data access dependencies in business objects. Bad idea?

### ISSUE THREAD

**Issue by jmarquesh** [MarimerLLC/cslaforum#605]
I'm following the ideas in this article [Abstractions in CSLA](https://magenic.com/thinking/abstractions-in-csla) to use Autofac to resolve data access dependencies for my business objects. I think I would not need to use the DalFactory and DalManager.

This is how it was before:
```
		[Transactional(TransactionalTypes.TransactionScope)]
		protected override void DataPortal_Update()
		{
			using (var dalManager = Solution.Dal.DalFactory.GetManager())
			{
				var dal = dalManager.GetProvider<IPaymentTypeDal>();

				using (BypassPropertyChecks)
				{
					var dto = DtoFromThis();
					dal.Update(dto);
					TimeStamp = dto.LastChanged;
				}
			}
			FieldManager.UpdateChildren(this);
		}
```

This is after:

```
		[Transactional(TransactionalTypes.TransactionScope)]
		protected override void DataPortal_Update()
		{
			using (var dataScope = ((IBusinessScope)this).Scope.BeginLifetimeScope())
			{
				var dal = dataScope.Resolve<IContactEditDal>();

				using (BypassPropertyChecks)
				{
					var dto = DtoFromThis();
					dal.Update(dto);
				}
				FieldManager.UpdateChildren(this);
			}
		}
```
Is this a bad idea?

I'm concerned with performance and the reuse of an open DbContext by my data access code. Will it continue to work as expected?

On the other hand, I like how simple is to mock a Dal implementation now to test:

```
		[Fact]
		public void Fetch_from_Dal_implementation_is_called_on_DataPortal_Fetch()
		{
			var dal = new Mock<IContactEditDal>(MockBehavior.Strict);
			dal.Setup(_ => _.Fetch(It.IsAny<int>())).Returns(new ContactEditDto { });

			var builder = new ContainerBuilder();
			builder.Register<IContactEditDal>(_ => dal.Object);

			ApplicationContext.DataPortalActivator = new ObjectActivator(builder.Build());

			var contactEdit = DataPortal.Fetch<ContactEdit>(1);
			dal.VerifyAll();
		}
```

I'm re-reading "Using CSLA 4 - Data Access" and I have some questions, but I'll ask those in another post.

**Comment by jonnybee** [comment]
Have a look at https://github.com/MarimerLLC/cslacontrib/tree/master/trunk/samples/MEFSamples.
Altho this samle uses MEF for IOC it would easily be adapted for Autofoac or other IoC containers.

**Comment by Chicagoan2016** [comment]
@jmarquesh , I am very interested in this, I have discussed one possible limitation with DalManager class #498 .
@jonnybee , I couldn't see an example of resolving data access dependency in the sample you mentioned.

Thanks and regards

**Comment by rockfordlhotka** [comment]
This seems like a duplicate of this other thread?
https://github.com/MarimerLLC/cslaforum/issues/606

**Comment by jmarquesh** [comment]
@rockfordlhotka: They are related, but in #606 I had a question about why the ```DalManager``` needed to call ```GetManager``` on its constructor, when a business object will also do it in its data access code. You gave me answer yesterday: For a transaction to work, the entire object graph needs to use a reference to the same connection.

In this issue I was hoping to get feedback from people already using Autofac or any other IoC container to resolve data access dependencies. 

The code in the DalManager is pretty simple and it can be even simpler with a big switch  to resolve dependencies. However, I would like to use an IoC container, but is it worth it performance wise?

**Comment by jmarquesh** [comment]
One more thing: For what @rockfordlhotka explained in #606, now I know that I need to use the DalManager, even if I use an IoC container. Now the role of the DalManager is not going to be to resolve the dependency, but to make the first call to the ```GetManager``` method on its constructor, so that transactions can work properly. I still need to see how that looks in a test project. I guess I'll have to implement a DalManager that doesn't do anything.

**Comment by jmarquesh** [comment]
@Chicagoan2016 you can find the example in the solution inside the folder named **Repository**. Open the solution and look at the method ```MyClassInitialize``` in ```MEFSample.Respository.Business.Test.MyRootTest```.

Also the class MyRoot have a region called ```Injected properties - must have private field marked was NonSerialized and NotUndoable``` with the property to store the reference to the dependency.

**Comment by jonnybee** [comment]
You also need to take a look at the 
https://github.com/MarimerLLC/cslacontrib/tree/master/trunk/Source/CslaContrib.MEF.Net45 project. This contains the actual IoC container registry and custom base classes to do property injection into Business classes and a /server/CslaFactoryLoader.cs that is custom ObjectFactoryLoader to resolve IoC dependencies in ObjectFactory classes. 

The samples shows how to use these. 

> More importantly, you might also look at Csla.Server.IInterceptDataPortal, which has Initialize and Complete methods where you can create and tear down your DI scope without having to clutter your root objects with that bit of plumbing.

And an implementation of IInterceptDataPortal to define the Lifetimescope and teardown.

In my opinion - you should not call Autfac directly to resolve dependencies in your own business code. Autofac should not be visible to the business code so that you could switch to another IoC container if required.  So have a look at the custom base classes and how these implement the injection or look at Csla.Server.IDataPortalActivator and resolve dependencies there.

**Comment by jmarquesh** [comment]
Thanks @jonnybee  for your good suggestions. I'll modify my code accordingly and I'll put my updates here, just in case somebody is interested.

**Comment by jmarquesh** [comment]
I still have some questions related to this topic, but it's better to ask them in another issue (#608). I'll try to create a repository with sample code at the end of all this process. In the meantime, I'm closing this issue.
