### ISSUE TITLE
How to get the instance of the business object in my implementation of IInterceptDataPortal?

### ISSUE THREAD

**Issue by jmarquesh** [MarimerLLC/cslaforum#608]
**Short question:**

Can I have access to my business object (BO) in ALL calls to ```Initialize``` and ```Complete``` in my ```IInterceptDataPortal``` implementation? For instance, in the ```Initialize``` of the Fetch operation.

**Why do I need it:**

I'm using an IoC container to resolve implementations of my data access. All is based on this post ["Abstractions in CSLA"](https://magenic.com/thinking/abstractions-in-csla) by @JasonBock. 

Following the advice of @rockfordlhotka:

>More importantly, you might also look at Csla.Server.IInterceptDataPortal, which has Initialize and Complete methods where you can create and tear down your DI scope without having to clutter your root objects with that bit of plumbing.

Also in ["More data portal enhancements for CSLA 4.5"](http://www.lhotka.net/weblog/MoreDataPortalEnhancementsForCSLA45.aspx),  announcing ```IInterceptDataPortal```:

>I suspect most people will put the container instance in Csla.Application.LocalContext to ensure it is easily and consistently available to all code regardless of runtime environment...

Also from @jonnybee: 

>In my opinion - you should not call Autfac directly to resolve dependencies in your own business code. Autofac should not be visible to the business code so that you could switch to another IoC container if required.

So, I want to resolve data access dependencies right before the start of the DataPortal operation and dispose them right after. I don't want to do it in the BO (advice from @jonnybee). I also want to store the dependency in a property of my BO, so I can use it in my DataPortal_XYZ code.

I could use ```Initialize``` and ```Complete``` in my ```IInterceptDataPortal``` but there is not always an instance of the BO there. Sometimes the instance is available (in the ```Complete``` after a Fetch, etc.). But sometimes is not (in the ```Initialize``` right before the Fetch).

What can I do?

Thank you for the time you took to read my question and for any help you can provide.

**Version and Platform**
CSLA version: 4.7.100
OS: Windows
Platform: ASP.NET Core, MVC

**Comment by jonnybee** [comment]
Rocky has aleady described this: 

> To inject more into this thread (see what I did there 😄 ), you might look at the Csla.Server.IDataPortalActivator type, which allows you to use your IoC container to create the actual business object instance.

> More importantly, you might also look at Csla.Server.IInterceptDataPortal, which has Initialize and Complete methods where you can create and tear down your DI scope without having to clutter your root objects with that bit of plumbing.

> For example, you can create an autofac scope in Initialize, thus making it available until Complete is called, when you can tear it down.

So you need to implement both interfaces as described by Rocky.

**Comment by jmarquesh** [comment]
Rocky recommends:

>...Initialize and Complete methods where you can create and tear down your DI scope without having to clutter your root objects with that bit of plumbing.

If I do it, I'll have to use that scope and call Resolve from my business object. And you said:

>In my opinion - you should not call Autfac directly to resolve dependencies in your own business code. Autofac should not be visible to the business code so that you could switch to another IoC container if required.

So, I went back to the idea of the ```DalManager```: I modified the ```GetProvider``` method to use Autofac to return an implementation of the data access.

The bit that I still don't like is that, in my business objects, I have to pass the Autofac scope as a parameter to the ```DalFactory``` and ```DalManager```:

```
[Transactional(TransactionalTypes.TransactionScope)]
protected override void DataPortal_Update()
{
        //Here I have to pass the scope to the DalManager
	using (var dalManager = Contacto.Dal.Shared.DalFactory.GetManager(((IBusinessScope)this).Scope))
	{...
```
If I ever need to change IoC containers, I think it will be just a modification to the type of the Scope property where I store the scope and to the ```DalManager```. I can live with that.

I'm storing the scope in a property of my business base class instead of in the Local Context, because of what @JasonBock wrote in his article [Abstractions in CSLA](https://magenic.com/thinking/abstractions-in-csla)

>The reason we need a reference to an ILifetimeScope-based object on the BO is due to the fact that Autofac’s default behavior with resolved dependencies (see http://code.google.com/p/autofac/wiki/DeterministicDisposal for more details). Therefore, we need to keep track of the scope used to resolve dependencies on a specific BO.

Thanks @jonnybee for the time you spent to answer my question. I'll appreciate your feedback if you think there is something wrong with my approach.

**Comment by rockfordlhotka** [comment]
Don't forget `IDataPortalActivator`, which is the location you should use your container to create/initialize your objects. The container shouldn't be necessary within the DP_XYZ methods.
