### ISSUE TITLE
Constructor Injection

### ISSUE THREAD

**Issue by kcabral817** [MarimerLLC/cslaforum#610]
**Question**
I'm working on using Unity to inject an object via an interface.   I get an error that the factory class needs a parameterless constructor.  I need to provide the interface and have Unity resolve and inject the object.  Such as this:

public ClaimFactory(IClaimRepository repository
                              , IEntityFactory entityFactory)
        {
            _repository = repository;
            EntityFactory = entityFactory;
        }

Does any one have an example on how to do this with CSLA?

thanks,
**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
You can not use constructor injection with CSLA, you need to use property injection.

**Comment by GreggThelen** [comment]
Rocky,
Have you written an article on DI/IoC patterns vs. distributed environments?
I don't want to bother you with questions you've already exhaustively answered.

I'm attempting to utilize good coding practices (new to MVC CORE) and I'm running up against instances where patterns morph from being good practice to being a pain in the backside.

As an example: 
In .NET the ideal is to use the configuration environment of the main project to inject things like connection strings into any library projects.  On one level I understand how that is a very pure pattern, however, injecting the connection string into every model object _seems_ to be more of a problem then any likely benefit.

**Comment by ajj7060** [comment]
This might be of help to you:  https://magenic.com/thinking/abstractions-in-csla

IMO the pain DI imposes ends up being worth it in the end; fast, focused unit tests are worth it, and pretty much everything you inject will always have two implementations.  The real one, and a mocked one for testing.
