### ISSUE TITLE
Public Constructors Required?

### ISSUE THREAD

**Issue by GreggThelen** [MarimerLLC/cslaforum#613]
For a long time now I've been getting mixed messages on private vs. public constructors.
For example, the template produces this code:

   private MyObject()
        { /* Note: Require use of factory methods */ }

However, I get an error that indicates that a public constructor is required
The error message says: "CSLA Business objects require a public constructor."

So is the error message wrong, the template, or am I confused?

**Comment by Chicagoan2016** [comment]
You can suppress that message if you want, that's what we did.
if memory serves, public constructors were required for SilverLight, not sure about Xamarin.
may be the experts will chime in : )

**Comment by ajj7060** [comment]
I'd suggest making a public default ctor; this was a requirement for Silverlight and I'm pretty sure XF and/or the MobileFormatter might require it.. 

In any event, if you use a private default ctor you'll run into issues if you need to support, or eventually need to support, platforms which restrict reflection to public members (like SL).  If you just make a public default ctor, its one less thing you could possibly run into if/when you port your code.

When in doubt, go with what the analyzers say.  They are being actively maintained.

**Comment by tfreitasleal** [comment]
Hi Gregg,
What templates generate a prvate constructor?

**Comment by rockfordlhotka** [comment]
We are looking at creating an analyzer to flag use of the `new` keyword to create an instance of a CSLA class. It is best to have a public default ctor, but people shouldn't actually _use_ it 😄 

https://github.com/MarimerLLC/csla/issues/925

**Comment by JasonBock** [comment]
And now that 925 is done, we could close this out :)
