### ISSUE TITLE
New___Async() problem in iOS

### ISSUE THREAD

**Issue by gem4511** [MarimerLLC/cslaforum#616]
My application runs great on Windows and Android.  But on iOS any attempt to create an object fails on

return await DataPortal.CreateAsync<xxx>( );

I get System.MissingMethodException and Default constructor not found for type Csla.Server.DataPortal+NullAuthorizer.

Also, I have protected override void DataPortal_Create( )

If I stuff the code from DataPortal_Create into New___Async, it works OK, but who wants to do THAT??
Any ideas would be welcome.

I'm using Csla v4.6.500.0

**Comment by ajj7060** [comment]
Can you post the full code for the business class you're having trouble with?

**Comment by ajj7060** [comment]
Without the data portal you lose any hope of using a remote application server, if you end up ever needing it.  Using the DP also ensures that MarkOld, MarkChild, etc. are called for you and invokes some other methods that you might need, so removing it isn't a great solution.

I thought I remember a similar issue on ios, but I can't seem to locate it.  In any event, it looks like nothing is actually async, and your data portal is running locally.  If that's the case, try using just Fetch and making the DP_F method just be void, not async Task.  

If that works (or even if it doesn't) would it be possible to update to the latest version of Csla?  Its possible there is a bug but its been fixed.  You'll need to use Nuget to remove the `Csla-Core` package from your iOS project and re-add *`Csla-Core-NS`* (as you'll need to use the NetStandard version for Xamarin).

**Comment by rockfordlhotka** [comment]
I have several projects that work fine using the data portal in iOS. Here's a public example:
https://github.com/HTBox/MobileKidsIdApp

Also ProjectTracker works fine on iOS:
https://github.com/MarimerLLC/csla/tree/master/Samples/ProjectTracker

**Comment by gem4511** [comment]
Thanks Rocky and ajj7060!

The (painful??) realization has hit me that it's probably time for me to redevelop my application.  The code base stems from code as old as the origin of Csla.Net, when Windows was the "only" real game in town.  It would probably take less time than to keep playing "Whack-the-mole" as technology marches forward.

Starting with Csla 4.7.2, I plan to rebuild.  The problem I'm having with iOS will surely evaporate as all efforts will be to keep multi-platforms in mind from the beginning.

Any suggestions or comments would be welcome.
