### ISSUE TITLE
Hosting Layers (BL, DL) on Different Servers

### ISSUE THREAD

**Issue by skeeler88** [MarimerLLC/cslaforum#619]
I wanted to see if there's a generic server that exposes Business Objects to Web Services or so forth in order to say put the Business Layer on a separate host from the UI.

Does CSLA have a generic hosting option or do you need to write the server specifically for scaling this way?

Thanks,

Sky

**Comment by rockfordlhotka** [comment]
In a way the answer is yes, but maybe not the way you mean.

The _Using CSLA 4_ ebook covers this pretty thoroughly, but here's a summary.

CSLA includes a component called the data portal. The data portal allows a CSLA client (often running in the presentation tier) to communicate with a CSLA server (often running on an app server) through a single endpoint. The data portal manages routing communication between the various domain objects on the client and the various domain objects and/or factories on the server through that single (generic) endpoint.

This is NOT a way of exposing public API style services. The data portal manages communication between _your_ client and _your_ server in a very rich and powerful way, including information/data that you'd never expose to random clients via a service-oriented scenario.

If your goal is general _public API_ generation then the answer is no, CSLA doesn't do that.
