### ISSUE TITLE
.NET 4.0 support - still needed?

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#623]
Does anyone still target .NET 4.0 (not 4.5 or 4.6, but actual 4.0)?

And if so, do you use CSLA 4.7?

I'm wondering if I still need to include the .NET 4.0 assembly (along with the async/await filler assemblies) in the `CSLA-Core` package.

**Comment by MarceloJGaray** [comment]
No, not using it at all.

**Comment by fujiiface** [comment]
Same as @MarceloJGaray.  My projects are 4.5+

**Comment by chatzikk** [comment]
I have a project (winforms) that targets .NET 4.0 as it is installed in some Windows XP pcs. 
I use CSLA 4.7

**Comment by rockfordlhotka** [comment]
From feedback here and twitter, **I plan to continue shipping the .NET 4.0 assembly via NuGet**.

I appreciate the feedback.

**Comment by tfreitasleal** [comment]
.NET 4.5 is the absolute minimum for me. Planning on moving everything to 4.6.1 (.NetStandard 2.0 compatible).

**Comment by kcabral817** [comment]
No.  I'm working with 4.7.

**Comment by michaelcsikos** [comment]
Late comment, but our software works with AutoCAD 2012-2019, and it's the AutoCAD version which dictates the .NET version.
```
AutoCAD 2012-2014: 4.0
AutoCAD 2015-2017: 4.5
AutoCAD 2018:      4.6
AutoCAD 2019:      4.7
```
Since Autodesk moved AutoCAD to subscription-only, some companies are sticking with their existing perpetual licenses for old versions.

**Comment by rockfordlhotka** [comment]
To close this out, I'm not dropping support for 4.0 until I am forced by some tech change. Which will eventually happen of course, but as long as the code continues to build for 4.0 I'll keep it in the NuGet package.
