### ISSUE TITLE
Custom Authentication

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#625]
**Question**
Hi All,
we are using Custom authentication with CSLA in a project, we have to implement features such as users approval, denial etc plus showing list of users to Admin and letting users change their profile.
I am thinking of putting  all this in a separate class and not in CustomIdentity (and CustomPrincipal), is this the right way to go?  I have to confess I am tired  : )

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows
Platform: WinForms, WPF, ASP.NET

**Comment by rockfordlhotka** [comment]
I think you are combining two totally separate use cases here: the use of an identity object for app authorization rules, and an application that allows someone to manage the user/role database.

There's exactly one case where the principal/identity objects should be involved in the user/role admin app, and that is for the purpose of implementing authentication rules - just like in your business app(s).

You need to build domain types for your user/role admin app just like you would any other app. Most of those types will be editable lists or editable objects, and you'll build a UI on top of those types.

**Comment by Chicagoan2016** [comment]
@rockfordlhotka , thank you, sir

kind regards
