### ISSUE TITLE
Analyzer Proposal: Catch When Save() is Called on Itself

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/cslaforum#63]
Doing something like this:

    public class x : BusinessBase<x>
    {
      public void Foo()
      {
        Save();
      }
    }

Doesn't seem right. If you try to save yourself, how can you assign the return value to `this`?

So I'm wondering if this should be flagged by an analyzer. Also, should this be a warning or an error?

**Comment by rockfordlhotka** [comment]
An error I think.

Unless the result of save is returned as the result of the method it makes no sense.

**Comment by JasonBock** [comment]
Now handled by this: https://github.com/MarimerLLC/csla/issues/458
