### ISSUE TITLE
DataPortal_Fetch() overloads

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#630]
Hi All,
its more like a design question, I have a readonlylist that has numerous factory methods.
All of them will need to call different stored procs but return similar data hence I placed them in the same ReadOnlylist object.
The issue I am facing is none of the factory methods needs any 'criteria' so the decision to call different 
DataPortal_Fetch methods is dependent upon factory methods' names.

Kind Regards

**Comment by kcabral817** [comment]
I'm trying to understand the question.  Are you asking about the factory method names?

**Comment by hurcane** [comment]
I can think of a couple different ways to tackle this scenario...

Option A:
Create separate criteria classes. They will all have no fields, and only differ by name. In the factory method, instantiate the appropriate criteria class. The DataPortal_Fetch methods use the appropriate criteria as a parameter.

Option B:
Create a criteria class with a "DataSource" property. In the factory methods, instantiate it with the appropriate value. A single DataPortal_Fetch method can use the DataSource property's value to execute the appropriate data retrieval calls.

**Comment by rockfordlhotka** [comment]
I like the way @hurcane is thinking.

I'd make sure to maintain some level of abstraction around the _intent_ of each variation in the data being returned, so whoever reads the client code can intuitively understand what's being returned.

You could do that via option A, or you could define an enum with the various intents and pass that value as criteria (somewhat like option B).

**Comment by fujiiface** [comment]
I agree with @rockfordlhotka and @hurcane.  I’ve done similar to both implementations minus Rocky’s enum suggestion (which I like).

My implementation uses multiple factory methods to populate different values on a shared criteria class.  That is passed into a single DataPortal_Fetch that uses a switch statement to determine which procedure to run.

**Comment by Chicagoan2016** [comment]
Thank you @hurcane , Thank you @rockfordlhotka
