### ISSUE TITLE
Analyzer Proposal: Warning When Calling A Constructor Directly on a BO

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/cslaforum#64]
Seems like you should always go through the `DataPortal` to create/fetch a BO. An exception to this may be commands that you create directly. Also, the object factory approach may require devs to use ctors on BOs (don't know offhand, don't ever use object factory.... @rockfordlhotka, @jonnybee?)

**Comment by jonnybee** [comment]
@JasonBock: Yes, the ObjectFactory is responsible for creating the BO object. This is typically done by Activator.CreateInstance or MethodCaller.CreateInstance but code may also call constructor directly.

**Comment by rockfordlhotka** [comment]
That sort of code will almost certainly be in an object factory, which would inherit from `Csla.Server.ObjectFactory` to gain access to all the helper methods that allow the factory to break encapsulation.

**Comment by JasonBock** [comment]
I'd have to look at the context of where the constructor is called from, and that may end up being quite difficult. I still think it's worth looking into, though.

**Comment by rockfordlhotka** [comment]
I do too - if you could suppress the warning if the containing class inherits from `ObjectFactory` that'd be sufficient I think.

**Comment by ajj3085** [comment]
I'm looking forward this, the previous dev in our codebase used the ctors on Csla objects alot, and not on OF.  Grumble...

**Comment by JasonBock** [comment]
I think this is done now :)
