### ISSUE TITLE
Not Getting Far in .Net Core

### ISSUE THREAD

**Issue by GreggThelen** [MarimerLLC/cslaforum#640]
I'm trying to use the Csla Model Binder.
#1: I've the following defined in Startup.cs, ConfigureServices
    services.AddMvc(config => config.ModelBinderProviders.Insert(0, new     Csla.Web.Mvc.CslaModelBinderProvider()));

#2: I've added the IModelCreator interface to my Controller
    [Area("Options")]
    public class AlertsController : MyController, IModelCreator

and the implementation
       public object CreateModel(Type modelType)
        {
            if (modelType == typeof(AlertEdit))
                return AlertEdit.NewAlertEdit();
            else
                return Activator.CreateInstance(modelType);
        }

#3: In the controller, when this code is called the CreateModel is never hit:
        [HttpPost]
        public IActionResult New(Guid id, AlertEdit child)

My understanding is that if ModelBinder is in place and that if the Controller implements IModelCreator that on each action that has the object as a parameter that IModelCreator will be called to create the object.   Instead, it appears the base ModelBinder is still in use.

**Comment by rockfordlhotka** [comment]
Does this blog post help?

http://www.lhotka.net/weblog/InPlaceListEditingInRazorPages.aspx

**Comment by GreggThelen** [comment]
Yes, it appears I was mixing MVC (traditional) and flat out Razor Pages.
That is what happens when you get into too many solutions.
Thank you again, I absolutely love the framework and I'm really looking forward to web assembly.
