### ISSUE TITLE
Lazy Load Child collection

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#641]
**Question**
Hi All,
We are trying to follow the example of AssignmentsProperty in ResourceEdit.cs to implement lazy loading of a child collection. I noticed that in DataPortal_Fetch method in ResourceEdit.cs there is a line
 Assignments = DataPortal.FetchChild<ResourceAssignments>(id);

I was wondering if for true "lazy load" we should omit the above line in our parent object?

Kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows
Platform: WinForms, WPF, ASP.NET Core

**Comment by jonnybee** [comment]
Yes, for true lazy loading you will not load any datafor that object when the "root"/parent object is loaded. 

A Lazy Load child object is like most child objects except that it implements DataPortal_Fetch as a "root" object to allow a standalone fetch to be called. 

You should use the LazyGetProperty/LazyReadProperty in your property getter to initialize and handle the lazy loading.

**Comment by tfreitasleal** [comment]
There is a full working sample of lazyloading at https://github.com/MarimerLLC/csla/tree/master/Samples/NET/cs/CslaLazyProperties

**Comment by Chicagoan2016** [comment]
Thank you @jonnybee
