### ISSUE TITLE
Multiple (concrete) data access layers

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#645]
I have a project where some of the objects are populated from excel sheets uploaded by users but the same objects will be saved to a SQL database. My solution structure in VS has a project MyProject.DataAccess.sql ( the concrete data access layer). I thought of creating a separate data access layer for objects that use excel for 'fetch' operation and call that project MyProject.DataAccess.Excel.
I am not sure if we could simultaneously use two concrete data access layers in our business objects.
Any suggestions/thoughts please?

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
You can absolutely do this.

1. If you are using a provider pattern like I do in the book, the factory that returns the DAL object for each type can return a DAL type from different concrete DAL implementations on a per-type basis
1. If you are using dependency injection, the DI container can return a DAL type from different concrete DAL implementations on a per-type basis

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka ,
Expanding on the same question, where should I write the code to make sure Excel sheet has the header row, correct header text etc.?
I couldn't seem to find a way to put this logic in business layer so I started coding it in the data access layer and pass data layer exception to the business layer? 

kind regards

**Comment by rockfordlhotka** [comment]
That totally sounds like a DAL level detail. What does the business logic care about how the spreadsheet is formatted? So yeah, 100% agree that this should be handled in the DAL.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka
