### ISSUE TITLE
MobileFormatter vs BinaryFormatter

### ISSUE THREAD

**Issue by JacoJordaan** [MarimerLLC/cslaforum#646]
**Question**
I am currently using the default BinaryFormatter for serialization on my CSLA WPF project. According to the CSLA books it is better to use the default BinaryFormatter. Is this still the case?

My object size is quite big and I am looking at ways to reduce it. According to initial tests it looks like the Mobile formatter serialize size is much smaller. 

I have some MobileFormatter serialization errors to sort out (probably using incompatible types) and I need to know if it worthwhile changing this.

Related to this will be plans to use WebAssembly in the future and also like to know if both serialization will be supported on .net core?

**Version and Platform**
CSLA version: 4.7.200
OS: Windows
Platform: WPF

**Comment by rockfordlhotka** [comment]
Over time the MobileFormatter has improved and is often better than the default BinaryFormatter.

**Comment by tfreitasleal** [comment]
I can subscribe to what @rockfordlhotka says.

I did some tests a few years ago (Silverlight was still around) and concluded MobileFormatter is faster than BinaryFormatter,

Later on the MobileFormatter was improved again, so I guess it's unbeatable.

**Comment by JacoJordaan** [comment]
Thanks for the feedback.

I have managed to change my objects to use the MobileFormatter.

Amazing results. According to fiddler size of my objects between 10-20% of the original size. Adding IIS compression makes it a fraction of the original size.

**Comment by ajj7060** [comment]
The mobile formatter required everything implement IMobileObject, or be a "simple" type, correct?

**Comment by rockfordlhotka** [comment]
Adding this FAQ link for future reference:
https://github.com/MarimerLLC/csla/blob/master/docs/serialization.md
