### ISSUE TITLE
Enhance DataPortal to use different endpoint per business type

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#647]
**As per https://github.com/MarimerLLC/csla/issues/959, I am looking for input on a feature enhancement to the data portal.**

In a service-oriented model there may be value in having different data portal server endpoints for different subsets of business domain types. The reasoning behind this is that some server-side code might:

* be a "hot spot" that needs different scaling from other parts of the app
* need to run on specialized hardware
* need to run in specific geographical data centers (GPDR, etc.)
* need to version more rapidly than other parts of the app

Now I'm not saying that the data portal will support true service-oriented modeling, it is an n-tier technology after all. However, the goals listed here fit within the realm of n-tier and yet provide a number of benefits also provided by a service-oriented model.

## Possible solutions

One way to do this is literally on a per-type basis.

* The existing data portal configuration would be the default
* For specific types the data portal proxy type and URL could be provided via configuration
* The per-type configuration would override the default

Another way to do this would be via some sort of "resource descriptor".

* The existing data portal configuration would be the default
* A business type could be attributed with a "resource descriptor" name (an arbitrary string)
* Via configuration we'd provide the data portal proxy type and URL for each resource descriptor
* The data portal would use the appropriate proxy/URL based on the resource descriptor attribute on a root type, and would fall back to default otherwise

**Comment by kcabral817** [comment]
I like the enum solution.

**Comment by rockfordlhotka** [comment]
Assuming you've set up 3 data portal servers, so they have 3 different URL endpoints, you should be able to do this in config:

```c#
      // set up default data portal for most types
      ApplicationContext.DataPortalProxy = typeof(Csla.DataPortalClient.HttpProxy).AssemblyQualifiedName;
      ApplicationContext.DataPortalUrlString = "https://default.example.com/dataportal";

      // add mapping to specialized hardware
      Csla.DataPortalClient.DataPortalProxyFactory.AddDescriptor(
        (int)ServerResources.SpecializedAlgorithm,
        new Csla.DataPortalClient.DataPortalProxyDescriptor
        { ProxyTypeName = typeof(Csla.DataPortalClient.HttpProxy).AssemblyQualifiedName, DataPortalUrl = "https://specialized.example.com/dataportal" });

      // add mapping for specific business type
      Csla.DataPortalClient.DataPortalProxyFactory.AddDescriptor(
        typeof(MyImportantType),
        new Csla.DataPortalClient.DataPortalProxyDescriptor
        { ProxyTypeName = typeof(Csla.DataPortalClient.HttpProxy).AssemblyQualifiedName, DataPortalUrl = "https://important.example.com/dataportal" });
```

Most of your business domain types will be unaffected - they'll use the same default proxy behavior as they always have.

That `MyImportantType` class though, will be routed to its own data portal proxy, and therefore all server-side calls for that type will run on the server specified for the type.

The `ServerResources` enum is something your app defines, or you can just use raw integers - but I think the enums should be easier to maintain and read. In this example the enum has a `SpecializedAlgorithm` option and types can indicate that they need that resource. For example

```c#
  [Serializable]
  [DataPortalServerResource((int)ServerResources.SpecializedAlgorithm)]
  public class ResourceType : BusinessBase<ResourceType>
  {

  }
```
The `DataPortalServerResource` attribute indicates that this business type needs a type of server from the enum, and the data portal will use the previous configuration to route all data portal calls for any type with the attribute to the appropriate server URL using the appropriate proxy type.

**Comment by ajj7060** [comment]
How would this work for WCF?  Specifically, what if there are multiple WCF proxies and they have different endpoint configurations?

I asked because we had to deal with this same issue with a custom data portal proxy we wrote.  The goal of our proxy was to try a list of URLs for automatic failover (if URL one doesn't respond, it tries the next one in this list).  

Also this sounds like it'd be very close to having a fallback URL capability :-)

**Comment by rockfordlhotka** [comment]
Supporting a fallback scenario is not in the scope of what I'm doing right now.

**Comment by rockfordlhotka** [comment]
Oh @ajj7060 - are you asking whether the proxy descriptor should include a proxy factory type so you have the opportunity to create the proxy via a factory?

Either way, that's a good point, and something I had overlooked in my design.

So how would that work I wonder? Hmm.

Something like this?

```c#
new DataPortalClient.DataPortalProxyDescriptor 
  { ProxyTypeName = "MyProject.MyProxy, MyProject", DataPortalUrl = "https://example.com/dataportal" });

new DataPortalClient.DataPortalProxyDescriptor 
  { ProxyFactoryTypeName = "MyProject.MyFactory, MyProject", 
    UserState = "some value you supply to indicate the nature of the proxy" });
    DataPortalUrl = "https://example.com/dataportal" });
```
