### ISSUE TITLE
custom properties in Exception classes

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#649]
Hi,
I have always written my exception classes following the pattern in ProjectTracker (ConcurrencyException.cs, UpdateFailureException.cs etc). I have to admit the reason behind writing numerous exception classes was  to identity the type and nature of error in a 'strongly typed' way : ).

In one of my exception classes I have to write a few custom properties. I wasn't sure how to do this, In DataAccess book Rocky has mentioned to add custom deserialization code in constructor and serialization code in GetObjectData() method.
I wonder if we have an example somewhere on how to do this?

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by Chicagoan2016** [comment]
Any help with this will be much appreciated : )

kind regards

**Comment by rockfordlhotka** [comment]
I suspect the [Csla.DataPortalException ](https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Shared/DataPortalException.cs)class has what you need.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka , I have implemented a property, I am assuming we  have to use non-Csla properties here. Please take a look when you have some down time. 

` [Serializable]
    public class ExcelHeaderMissingException : Exception
    {

        public int LineNumber { get; set; }
        public ExcelHeaderMissingException(string message, int lineNumber)
          : base(message)
        {
            LineNumber = lineNumber;
        }

        public ExcelHeaderMissingException(string message, Exception innerException, int lineNumber)
          : base(message, innerException)
        {
            LineNumber = lineNumber;
        }

        protected ExcelHeaderMissingException(
          System.Runtime.Serialization.SerializationInfo info,
          System.Runtime.Serialization.StreamingContext context)
          : base(info, context)
        {
            LineNumber = info.GetInt32("LineNumber");
        }

        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.SerializationFormatter)]
        [SecurityPermission(SecurityAction.Demand, Flags = SecurityPermissionFlag.SerializationFormatter)]
        public override void GetObjectData(
          System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
        {
            base.GetObjectData(info, context);
            info.AddValue("LineNumber", LineNumber);
        }
    }`

**Comment by rockfordlhotka** [comment]
I think that's right.

**Comment by Chicagoan2016** [comment]
@rockfordlhotka , thank you, appreciate your generous help.

Kind regards
