### ISSUE TITLE
Data Portal health endpoint?

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#653]
As per: https://github.com/MarimerLLC/csla/issues/961

The server-side data portal has long had hooks where it would be possible for people to add instrumentation or logging to monitor the health of the app server (at least the data portal). By "long" I mean since day 1 actually, so back in 2001 😄 

I am thinking that it might be wise to leverage that within CSLA itself, to provide an (optional) health endpoint that could be easily exposed via controller from a web API host - specifically the HttpProxy/HttpPortal as implemented in ASP.NET Core (Csla.Web.Mvc).

The data portal could keep a list of the last n (n=100?) server-side operations, including how long each took, which root object type was used, whether there were exceptions - that sort of thing. That data could be returned as JSON for use by the caller in presenting to an admin/IT Pro user via a dashboard or something.

1. Would this be useful to you?
1. Would you actually use this functionality?
1. If yes to those, then what exactly would you like to see?

**Comment by ajj7060** [comment]
I think this sounds interesting; it could allow us to plug into to the monitoring software we used to keep an eye on our systems.  

It might be useful too to allow some custom code to be plugged into this as well; for example if people also wanted to do a quick DB query to verify that the app server is still talking to the DB server correct as part of this, that might be useful.

**Comment by rockfordlhotka** [comment]
fwiw, if you are using the Http host you can do that db query idea already, because the endpoint is just an ASP.NET controller.

If you are using WCF you can accomplish the db query idea by adding another `svc` endpoint to your server that does the query.

**Comment by Chicagoan2016** [comment]
This part does sound interesting, 

> The data portal could keep a list of the last n (n=100?) server-side operations, including how long each took, which root object type was used, whether there were exceptions - that sort of thing. That data could be returned as JSON for use by the caller in presenting to an admin/IT Pro user via a dashboard or something.

> 

right now I am using one of the 'logging' frameworks to accomplish something similar

**Comment by rockfordlhotka** [comment]
My focus right now is on the following:

1. How long as the current server instance been online?
1. When was the server last invoked?
1. How many times has the server been invoked?
1. How many successful/failed operations have occurred?
1. Get me a list of the last n actions, each action includes
   1. The root object type
   1. The data portal operation
   1. Any exception that occurred
   1. The elapsed runtime of the operation
