### ISSUE TITLE
Move from verion 4.3.13 to 4.6.100

### ISSUE THREAD

**Issue by chatzikk** [MarimerLLC/cslaforum#66]
I am developing a Windows Forms solution that targets to .NET framework 4.0 as many of my customers still use Windows XP PCs. I use CSLA version 4.3.13.
Can I move to version 4.6.100 or will I have problems?

**Comment by rockfordlhotka** [comment]
CSLA 4.6 (via NuGet) includes support for .NET 4, 4.5, and 4.6.

**Comment by chatzikk** [comment]
Thank you very much
