### ISSUE TITLE
Rdlc reports and Csla business objects

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#661]
I am creating an rdlc report (Reporting services local report) in an ASP.NET project. While trying to add 'DataSources' to the report in Visual Studio, some of my Csla objects ( from Business Layer) are not visible.
I do have a reference to Business Layer project in my ASP.NET project. The thing I don't understand is why are some business objects (collection stereotype) not available in DataSources window.
Any suggestions please?

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
I don't think that I've ever tried to do what you are doing. Maybe it just doesn't work?

**Comment by Chicagoan2016** [comment]
@rockfordlhotka , yes sir, you are right, I ended up creating typed datasets and filling those datasets with ObjectAdapter using existing business objects. 
Thanks for creating ObjectAdapter ( and the whole Csla)  among many other utilities.

Respect from a developer trying to earn a living.

Kind regards
