### ISSUE TITLE
Analyzer Proposal: Flag DP Operations That Have Non-Serializable Arguments

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/cslaforum#67]
If an argument to a DP operation isn't serializable, it cause an error at runtime, saying "Type 'XYZ' cannot be serialized.". Would be better to know that when I type it in VS :). I'm thinking this analyzer would mark it as an error, not a warning.

No code fix would be created for this analyzer (at least I can't think of one that would be effective).

Thoughts?

**Comment by JasonBock** [comment]
A related issue is that there's no way to enforce that the type passed into a managed backing field must be serializable (at least I think it should be). So doing:

    public static readonly PropertyInfo<string> UserNameProperty = ...

Is OK, but this:

    public static readonly PropertyInfo<MyNonSerializableType> XYZProperty = ...

Would not be. Having an analyzer would be pretty sweet in this case (again, assuming that the types given to PropertyInfo MUST be serializable).

**Comment by rockfordlhotka** [comment]
They do have to be serializable (or primitive), otherwise n-level undo would fail, along with data portal serialization.

So yes, I think this would be a good rule to implement.

**Comment by JasonBock** [comment]
OK, I'll move this to the CSLA issues list and self-assign. I'll create two analyzers from this.

**Comment by mark-goles** [comment]
This (meaning flagging of arguments passed to DP methods) appears to have been added as promised. However, in the most recent version of CSLA-Core, v. 4.6.401, strings are flagged by this system as non-serializable -- which makes no sense, they are serialiable and marked (per Microsoft) with the Serializable attribute. Here is my code:

        private void DataPortal_Fetch(string fec) {

The string argument is flagged with: 

Severity	Code	Description	
Warning	CSLA0010	Operation argument types should be serializable.	

Was this just done incorrectly, or is there something I'm missing?

**Comment by jonnybee** [comment]
Hi, 

Please open a new issue. When an issue has status **closed** it should be viewed as "readonly"/history. 
And you could always link the new issue to the old "closed" issue.

**Comment by JasonBock** [comment]
I don't see this as an issue with the latest bits. Here's an example:

![image](https://cloud.githubusercontent.com/assets/904213/18748777/70b88be4-8099-11e6-95a0-f0ce1f93f53b.png)

Notice that the only warning I get is for the non-serializable type `NonSerializableObject`. The DP operation with a `string` argument isn't flagged.
