### ISSUE TITLE
CSLA .NET Core MVC Authentication/Authorization

### ISSUE THREAD

**Issue by skeeler88** [MarimerLLC/cslaforum#677]
I have created conventional MVC projects in CSLA.NET and have been able to call for exmaple

 [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.CreateObject, typeof(CustomerEdit))]

Is this the same syntax and or design as CSLA.NET MVC Core? If not is there an example of how to achieve this in samples?

Thanks!

Skyler

**Comment by rockfordlhotka** [comment]
I haven't brought those helpers forward to .NET Core yet.

I've been so focused on Xamarin and WebAssembly and Docker/Kubernetes that I haven't had the time to really dig into ASP.NET Core deeply.

There are _some_ new features for ASP.NET Core coming in 4.9, but I don't expect to have time to review the `HasPermission` attribute

**Comment by skeeler88** [comment]
I see OK thank you for letting me know!
