### ISSUE TITLE
Authentication With AspnetCore

### ISSUE THREAD

**Issue by coding786** [MarimerLLC/cslaforum#679]
Looking for a sample to implement Windows Authentication with ASPNET Core App Server.
How is the configuration to be done at the server portal side ? Please call out differences in doing configuration from a WCF based App Server. Also what configuration should be done at the client side ?

**Comment by rockfordlhotka** [comment]
This docs page looks like it contains most of what you'd need.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2

**Comment by coding786** [comment]
Rocky - Many Thanks. My question is more towards doing the same with CSLA core library. You have mentioned Windows auth with wcf based app server in your books n samples. Do you have some pointers/samples doing the same with ASPNET core based app server ? What config changes should be done on Dataportal client & Dataportal Server ?
