### ISSUE TITLE
Planning for CSLA .NET 5.0

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#684]
Hello all!

As 2018 comes to a close I'm preparing to release version 4.9.0 - the last release for this year.

I'm also starting to [plan for version 5.0.0](https://github.com/MarimerLLC/csla/projects/5). Not that this is a BIG RELEASE, but I'm now following the semver concept and I've been accumulating breaking changes, because any breaking change needs to be signaled by a change in the major version number (according to semver).

If you click the link above you'll see that all the proposed 5.0 changes are breaking changes, and mostly bug fixes.

I am starting this thread to get your collective input on areas you'd like to see enhanced.

More Xamarin? More ASP.NET Core? More data portal stuff like in 4.9?

**Comment by kcabral817** [comment]
I know this is the worst to ask, but updated documentation would be nice.  Even if the current documentation had the Silverlight and Async Callback removed and updated would be a real help.

**Comment by kcabral817** [comment]
I like it.  Now it’s burdened by the version and really, the books are somewhat independent of versions.  I know that I use GitHub a lot to solve problems and find the latest and greatest.

Have a nice day.

Kevin

________________________________

**Comment by rockfordlhotka** [comment]
I'm monitoring Blazor (and Uno) fairly closely and keeping CSLA working on those platforms. I think Blazor (server-side) is becoming stable enough to think about really investing - up to now they've been moving the cheese so often it has been hard to keep up.

What specifically would you (@MarkOverstreet ) like to see for Xamarin Forms features? At the moment there are four [open Xamarin issues in the backlog](https://github.com/MarimerLLC/csla/issues?utf8=%E2%9C%93&q=is:issue+is:open+xamarin). 

1. I for sure intend on the bug being addressed in 5.0
1. I'm not so sure about WcfProxy, and whether that continues to have value in the modern world?
1. The MacUI for ProjectTracker would be pretty cool 😄 
1. There's the SqlClient warning, which might be fixed as I externalize that dependency to address an issue where it isn't compatible with UWP for certified store apps 😞 https://github.com/MarimerLLC/csla/issues/981

**Comment by Chicagoan2016** [comment]
@rockfordlhotka , I would like to see if DI could be easily integrated with Csla, we have looked at the approached Jason followed in an article a couple years ago.
kind regards
