### ISSUE TITLE
property change notification

### ISSUE THREAD

**Issue by kcabral817** [MarimerLLC/cslaforum#687]
How do I get property change notification to fire on complex object?

I have an CompanyAddress class that has an address object as a property (is this a relationship.Child type?):

     public class CompanyAddressInfoPersist : InjectableBusinessBase<CompanyAddressInfoPersist>, ICompanyAddressInfoPersist
     {
     .
     .
     .
        public static readonly PropertyInfo<AddressInfoPersist> AddressProperty = RegisterProperty<AddressInfoPersist>(p => p.Address);
        public AddressInfoPersist Address
        {
            get => GetProperty(AddressProperty);
            set => SetProperty(AddressProperty, value);
        }
     }
When I do this:

     var obj = DataPortal.Create<CompanyAddressInfoPersist>();
     obj.Address.StreetName = "Washington";

The Address.StreetName property never fires the notification.

       [Serializable]
       [Csla.Server.ObjectFactory(typeof(AddressFactory), "Create", "GetAsync", "UpdateAsync", "DeleteAsync")]
       public class AddressInfoPersist : InjectableBusinessBase<AddressInfoPersist>, IAddressInfoPersist
       {
        public static readonly PropertyInfo<string> StreetNameProperty = RegisterProperty<string>(p => p.StreetName);
        public string StreetName
        {
            get => GetProperty(StreetNameProperty);
            set => SetProperty(StreetNameProperty, value);
        }
}

I have these two overrides in the CompanyAddress Class:

        protected override void OnChildChanged(ChildChangedEventArgs e)
        {
            base.OnChildChanged(e);
            BusinessRules.CheckRules();
        }
         
        protected override void PropertyHasChanged(IPropertyInfo property)
        {
            base.PropertyHasChanged(property);
            BusinessRules.CheckObjectRules();
        }

But neither of them get fired. So consequentially, the business rules never fire.   Is there something else that I need to do when using a complex object?  

**Version and Platform**
CSLA version:   Latest release
OS: Windows 
Platform: WPF

**Comment by rockfordlhotka** [comment]
Are you saying that `obj.Address.PropertyChanged` isn't raised? Or that `obj.PropertyChanged` isn't raised?

The first should occur, but the second should not.

**Comment by kcabral817** [comment]
I see, said the blind man!
