### ISSUE TITLE
Integrate AutoFac with CSLA ASPNet Core

### ISSUE THREAD

**Issue by coding786** [MarimerLLC/cslaforum#689]
Wish to use Autofac with ASPNetCore. In AddCSLA method in 4.6.9 version, you have used inbuilt ASPNetCore DI to resolve IDataPortal Factory. How can I use Autofac instead there for the same ? 

Also, I need one Autofac LifeTimeScope for single controller httprequest to register & resolve all my dependencies. How can I achieve that ? 

**Version and Platform**
CSLA version: 4.6.9
OS: Windows
Platform: ASP.NET Core

**Comment by rockfordlhotka** [comment]
My understanding is that autofac, along with most major IoC frameworks, support the .NET Core dependency injection abstraction.

CSLA is just using the .NET Core abstraction, and so my understanding is that you can replace the IoC provider within .NET Core via some mechanism, and CSLA won't care at all, because it just relies on those abstract interfaces.

**Comment by itgoran** [comment]
@coding786 

You can use the following code, to make all services registered in Microsoft container available in Autofac container

```
public Autofac.IContainer ApplicationContainer { get; private set; }

public IServiceProvider ConfigureServices(IServiceCollection services)
{
	var builder = new ContainerBuilder();
	builder.Populate(services);
        this.ApplicationContainer = builder.Build();
        return new AutofacServiceProvider(this.ApplicationContainer);
}
```
If you have any particular 'issue' regarding integration CSLA with autofac don't hesitate to ask.
Maybe I can help you in the process.

**Comment by coding786** [comment]
> @coding786
> 
> You can use the following code, to make all services registered in Microsoft container available in Autofac container
> 
> ```
> public Autofac.IContainer ApplicationContainer { get; private set; }
> 
> public IServiceProvider ConfigureServices(IServiceCollection services)
> {
> 	var builder = new ContainerBuilder();
> 	builder.Populate(services);
>         this.ApplicationContainer = builder.Build();
>         return new AutofacServiceProvider(this.ApplicationContainer);
> }
> ```
> If you have any particular 'issue' regarding integration CSLA with autofac don't hesitate to ask.
> Maybe I can help you in the process.

thanks a bunch
