### ISSUE TITLE
Integrate asp.net core config with csla configuration

### ISSUE THREAD

**Issue by coding786** [MarimerLLC/cslaforum#691]
How do we write csla configuration values to load in asp.net core configuration so that the app can read n use csla configuration settings ? I used to do the same thing in web.config in a wcf based data portal  but now i am using asp.net core data portal. Any resources/samples ?

**Version and Platform**
CSLA version: 4.6.9
OS: Windows,.
Platform: ASP.NET Core

**Comment by itgoran** [comment]
@coding786 

* Create appsettings.json (usually it's already created)

* Use one of the following configurations:

```
{  
   "csla":{  
      "propertyChangedMode":"Windows",
      "propertyInfoFactory":"test1,test2",
      "reader":"testReader",
      "serializationFormatter":"testSerializationFormatter",
      "isInRoleProvider":"testIsInRoleProvider",
      "mobileFactoryLoader":"csla.netcore.test.Configuration.TestMobileFactoryLoader, csla.netcore.test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "PrincipalCacheSize":10,
      "defaultTransactionIsolationLevel":"RepeatableRead",
      "mobileWriter":"csla.netcore.test.Configuration.TestCslaWriter, csla.netcore.test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "defaultTransactionTimeoutInSeconds":60,
      "dbProvider":"testDbProvider"
   }
}
```

Add this into your Startup.cs file

```
var config = new ConfigurationBuilder()
             .AddJsonFile("appsettings.coresettings.test.json")
             .Build()
             .ConfigureCsla();
```

Additionally, maybe [this link](https://github.com/MarimerLLC/csla/blob/master/Source/csla.netcore.test/Configuration/ReadConfigFromDotnetCoreSubsystemTests.cs) can help you.

If you need additional help don't hesitate to ask :)

**Comment by coding786** [comment]
I am not sure how to load CslaAuthorization Provider , is below sysntax correct ?

"csla": {
    "AuthenticationType": "Windows",
    "CslaAuthorizationProvider": "Namespace.ClassName,AssemblyName"
  }

Assembly I am using for CslaAuthorizationProvider is .Net Standard, so it does not have culture & version info, pls suggest how to load a type from .Net Standard assembly
