### ISSUE TITLE
CSLA naming

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#692]
Every few years I go through this phase where I think I should rename CSLA to something … cooler. And more pronounceable. 

I'm in one of those phases again. Any suggestions?

* Must not be already taken as a NuGet package name
* Ideally not already taken as a domain name (.net, .com, .io, _something_ needs to be available)
* More memorable
* More pronounceable
* Cool

**Comment by keithdv** [comment]
Rocoso - Spanish for Rocky
OOBehave - as in Object Oriented Behavioral Modeling

**Comment by rockfordlhotka** [comment]
Eridu - Sumarian/Akadian for Home (Home for business logic)

**Comment by CrossSlide** [comment]
@rockfordlhotka Hi, I sent you an email a 'rocky@lhotka.net' a few weeks ago on this. No big deal, I just wanted to check if you got it. Thanks

**Comment by ajj7060** [comment]
I'd vote for keeping Csla.  I know it may not be considered cool or modern, but it's been the name for so long that you'd have to know to include Csla when doing searches or you might not find what you're looking for under a new name.

Also what would that do to the Nuget packages?  New names for them as well (and thus transition work)?  Loss of the history (like # of downloads)?  

It just seems like a lot of work / source of confusion for not very much gain.

**Comment by fujiiface** [comment]
I don’t necessarily have a name to add to these but I just wanted to ask what happened to Ystari?

**Comment by rockfordlhotka** [comment]
A number of good ideas came out of the Ystari discussions, most of which are now in the CSLA backlog.

In the end my feeling was that the most important updates/enhancements could be made within the context of the existing framework, and that'd provide a roadmap forward for existing CSLA users. If we created a new framework from scratch there'd be no direct/easy roadmap forward.

On the other hand, creating a framework from scratch would be kind of cool, and would allow for a level of freedom I haven't enjoyed since 2001-20002 when I first created CSLA 😄

**Comment by rockfordlhotka** [comment]
@CrossSlide I did get your email, and I appreciate your thoughtful comments on the naming topic.

**Comment by Chicagoan2016** [comment]
@rockfordlhotka , I would love to know the idea(s) behind creating a new framework from scratch : ) ,I also volunteer to be a part of the team, I am excited to learn a lot from you and other talented members of Csla community.

I will take the liberty of suggesting a few enhancements.
1) We can use a 'professional' MVVM framework instead of Bxf, I am old school so I have looked at Prism up until recently, although not with Csla :(
2) Use one of the 'famous' DI containers for pluggable DAL, something like Autofac etc.
3) For some reason I still think we could probably use some code generation in addition to snippets and VS templates :)

kind regards

**Comment by Chicagoan2016** [comment]
and yes please don't change the name from Csla to 'something' else.
The name Csla reminds of the good old days when people would see you write code and thought you were intelligent hehe
Take a look at this pic


![turbopascal](https://user-images.githubusercontent.com/19640475/53276113-60ad3f00-36c3-11e9-8acc-f3f8e53dcd5b.png)

**Comment by brinawebb** [comment]
I vote to keep the name as-is, I've always liked it.

**Comment by CrossSlide** [comment]
I don’t think it’s a question of if you/we personally like the old name. The question is can a new name help entice more developers to take a look and perhaps join our community. CSLA is a great business framework and I wish we could attract a broader audience. I don’t believe the current name has helped and has possibly hurt the evangelism efforts.

**Comment by Chicagoan2016** [comment]
My observation about 'adopting' or using a framework like Csla is not the name but rather something strange : ). I have had pretty much no success in convincing developers with no CS/Engineering background to learn a Csla. We as Csla community know that Csla does use some advanced .NET features plus OO concepts. The above mentioned group of developers have told me it's too much for them to handle, they would rather write procedural code calling stored procs from 'code behind'.

To reiterate the above statements are just my observation : ) :)

kind regards

**Comment by CrossSlide** [comment]
I agree that a new name will not overcome some of the adoption hurdles but history shows us that the naming of a product or business can have a significant impact on its success. Rocky’s not wrong in thinking a new name would be a good move, IMHO.

**Comment by MarceloJGaray** [comment]
I also vote to keep the name as-is.

**Comment by j055** [comment]
bizobo.net
bizobs.net

**Comment by j055** [comment]
bizoop.net

**Comment by rockfordlhotka** [comment]
I am choosing to not rename CSLA for this release.
