### ISSUE TITLE
Best practice for working with multiple rulesets

### ISSUE THREAD

**Issue by jasonabi** [MarimerLLC/cslaforum#693]
**Question**
When working with multiple rulesets within a single BusinessBase<T> object, are there any recommended methods or examples of how RuleSets should be switched? I'm assuming a RuleSet should only be changed from within the object based on some Parent state or some criteria passed to a factory method.  Can anybody offer their experience or advice in regards to this? Thanks.

**Version and Platform**
CSLA version: 4.6.100
OS: Windows
Platform: WPF

**Comment by rockfordlhotka** [comment]
The intent behind RuleSets is to support multi-tenant server scenarios. So the RuleSet is per-request and is usually set as soon as you've established the identity and tenant for the user making the request.

So it isn't normally set in an object at all, but rather in the ASP.NET pipeline at the point where you set the current principal/identity/user for the request.

**Comment by jasonabi** [comment]
We use multiple rulesets to vary validation behavior of an object for different scenarios. Maybe this is the wrong approach? It currently requires some messy cascading method calls through the object hierarchy.  I'm trying to clean it up, but sounds like perhaps the entire approach should be reworked.

**Comment by jasonabi** [comment]
Should we be using that ChainedContext concept instead with a master rule that delegates to other rules depending on some initial state?
