### ISSUE TITLE
One or more errors occured on DataPortal call exception

### ISSUE THREAD

**Issue by JacoJordaan** [MarimerLLC/cslaforum#697]
**Question**
After I switched from using the WcfPortal to the MobilePortal my exceptions does not come through correctly. Where it used return the exception in the Csla.DataPortalException.BusinessException, it now only returns the "One or more errors occured" exception.

I understand that this has to do with the Async calls where multiple errors can occur, but I need help to get the correct exception that was thrown.

My ViewModel catches the exception with this code at the moment:

protected override void OnError(Exception error)
        {
            string message = null;
            var be = error as Csla.DataPortalException;
            if (be != null)
            {
                try
                {
                    if (be.BusinessException != null)
                        message = be.BusinessException.Message;
                    else
                        message = be.Message;
                }
                catch
                {
                    message = error.ToString();
                }
            }
            else
                message = error.Message;

            MessageBox.Show(message, "Error", MessageBoxButton.OK, MessageBoxImage.Error); 
            base.OnError(error);
        }

Any help will be appreciated.

**Version and Platform**
CSLA version: 4.7.200
OS: Windows
Platform: WPF

**Comment by rockfordlhotka** [comment]
iirc, the InnerException should be what amounts to a collection of exceptions - that's what comes back from an async call, and the top level "collection" is an exception itself, which says that multiple exceptions have occurred.
