### ISSUE TITLE
What IsDirty

### ISSUE THREAD

**Issue by jasonabi** [MarimerLLC/cslaforum#698]
**Question**
Is there an easy way to dump to the console every dirty managed property from the root all the way down the tree?  

**Version and Platform**
CSLA version: 4.6
OS: Windows
Platform: WPF

**Comment by rockfordlhotka** [comment]
If by easy you mean pre-built code, no.

If by easy you mean could you write an iterator using a visitor pattern to walk an object graph, then sort-of-yes, I think that is probably possible. But I wouldn't use the term 'easy'.

The trick is that by default CSLA doesn't track whether individual fields have been changed. It tracks `IsSelfDirty` only at the object level. You _can_ track individual fields by creating your own `IPropertyInfo` implementation and coming up with a strategy around what it means for a field to be dirty.

The reason it isn't the default, is that the most obvious strategy would be to maintain the original property value at all times, along with the current value, so you can compare. But that would double the size of every object in memory - and _far more importantly_ when serialized over the network.

Another strategy, though not foolproof, would be to maintain a hashcode of the original property value. Hashcodes aren't guaranteed to be unique, but they are fairly good. So there's some risk. And this still means ferrying around an Int32 for every field - again increasing the size of the serialized stream in n-tier scenarios.

**Comment by jasonabi** [comment]
I think I understand. So IsDirty is flipped like a switch on PropertyChanged events without tracking specifically what triggered it. Is that right?  And the FieldDataManager is only tracking previous states when the Begin/Apply/Cancel Edit methods are called, not every time PropertyChanged is called. 

Each IFieldData object, though, implements ITrackStatus, so I could iterate through the tree and maybe use reflection to access the private FieldDataManager instance and interrogate it?

**Comment by hurcane** [comment]
This just a thought, but what if base business object maintained a collection to track changed properties? The collection could be initialized with no elements. As properties change, they could insert the original value. If the property changes back to the original value, the property could be removed from the collection.

I also assume this behavior really only needs to be done when dealing with an existing object.

Possible pros and cons:
- You don't pay a transport penalty when nothing is being changed.
- You do pay a transport penalty if many properties are being changed. 
- IsSelfDirty would be cheap to implement. It only needs to check the count of the collection.

**Comment by rockfordlhotka** [comment]
@hurcane you could implement that strategy in a custom `IPropertyInfo` as well, absolutely. Some of the plumbing for that is already in CSLA in fact, just not the choice about flipping the per-property IsDirty flag (because this is one of several possible strategies).

**Comment by rockfordlhotka** [comment]
Yes @jasonabi - if you create a custom field tracking implementation so the per-field implementation of ITrackStatus actually does something, then you can do exactly what you propose.

The default implementation doesn't track whether individual fields have been changed.

**Comment by jasonabi** [comment]
@rockfordlhotka Okay, so I was just hacking together some bits to use reflection to yank out the _fieldManager instance from the root object and then iterate with calls to IsFieldDirty - but are you saying this isn't going to work anyway, because the individual fields - even though FieldInfo implements ITrackStatus - are not actually setting the IsDirty flag right now?

**Comment by jasonabi** [comment]
![tenor](https://user-images.githubusercontent.com/506731/51711428-19675c00-1ffa-11e9-9ef3-7bf18d7e5492.gif)

**Comment by rockfordlhotka** [comment]
Correct, that's why I said (with too many words) in my first reply - the default behavior of CSLA is that it tracks whether an _object_ is changed, not whether a _field_ is changed.

The hooks are there to track at the field level, and you can provide a custom implementation to make those hooks come alive, but the tracking isn't enabled by default.

**Comment by jasonabi** [comment]
Got it.  Alright, at least now I know.  It seems the function is somewhat useful even if it only identifies the objects with IsSelfDirty or IsDirty - narrows down the search a bit when debugging.  Don't think I want to go playing with customized FieldInfo definitions at this point.
