### ISSUE TITLE
Stronly typed configuration in asp.net core

### ISSUE THREAD

**Issue by coding786** [MarimerLLC/cslaforum#699]
How to load CslaAuthorizationProvider in asp.net core appsettings file ? Below syntax does not work, my provider is in a .net standard library

"csla": {
"AuthenticationType": "Windows",
"CslaAuthorizationProvider": "Namespace.ProviderClassName, AssemblyName"
}

In earlier wcf based application server, we used to do it in web.config like this : 

 <appSettings>
    <add key="CslaAuthentication" value="Windows" />
    <add key="CslaAuthorizationProvider" value="Namespace.ProviderClassName, AssemblyName" />

  </appSettings>

**Version and Platform**
CSLA version: 4.6.9
OS: Windows
Platform: WinForms, WPF, ASP.NET Core

**Comment by rockfordlhotka** [comment]
Your post cut off - but what you are showing should be correct.

**Comment by coding786** [comment]
thanks it worked
