### ISSUE TITLE
BusinessBase class subclassing 

### ISSUE THREAD

**Issue by lmsantin** [MarimerLLC/cslaforum#7]
Hello:
From this thread http://forums.lhotka.net/forums/p/1250/6529.aspx

Will this work?

public abstract class OwnBusinessBase<T> : Csla.BusinessBase<OwnBusinessBase<T>> where T : OwnBusinessBase<T>

**Comment by rockfordlhotka** [comment]
Yes, that is how you create a custom base class.

**Comment by lmsantin** [comment]
And what about this? Will this work?

[Serializable]
public abstract class OwnBusinessBase< T > : Csla.BusinessBase< OwnBusinessBase< T >> where T : OwnBusinessBase< T >
{}

[Serializable]
public class Category : OwnBusinessBase< Category >
{

public static readonly PropertyInfo< int > AccountIdProperty = RegisterProperty< int >(p => ((Category)p).AccountId);

public int AccountId
{
 get { return GetProperty(AccountIdProperty); }
 set { SetProperty(AccountIdProperty, value); }
}

}

**Comment by ajj3085** [comment]
Yes, that works as well.

**Comment by lmsantin** [comment]
Thanks Lhotka and Ajj3085. I'll close this discussion.
