### ISSUE TITLE
CSLA 4.9.0 Command Object failing on ASP.NET Core

### ISSUE THREAD

**Issue by al1979** [MarimerLLC/cslaforum#702]
**Preamble**
I have the following projects tiers in my application.
```
BusinessLibrary		.Net Standard 2.1    
Dal			.Net Standard 2.1
WebApi			.Net Framework 4.7.1
WebApi.Core		.Net Core 2.1
```
I have implemented a CSLA CommandBase object named Person,  in BusinessLibrary project. 
```
    [Serializable()]
    [Csla.Server.ObjectFactory(FactoryNames.PersonFactoryName)]
    public class Person : CommandBase<Person>
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public static string GetName ( int id)
        {
            Person cmd = new Person (id);
            cmd=DataPortal.Execute<Person>(cmd);
            return cmd.Name;
        }
        private Person (int id)
        {
            Id = id;
        }
        public Person (int id , string name   )
        {
            Id = id;
            Name = name;
        }
        public Person()
        {
        }
    }

```
And the command object factory implementation in the Dal project.
```
    class PersonFactory : ObjectFactory
    {
        public Person Execute (Person item)
        {
            if (item.Id == 1) return new Person (1, "Frederick Austin" );
            if (item.Id == 2) return new Person(2, "Zac Stevens");
            if (item.Id == 3) return new Person(3, "Jackson Mitchell");
            return new Person { Id = item.Id, Name = "Not Found" };
        }
    }
```
In the WebApi project, i have the following implementation
```
using BusinessLibrary;
namespace WebApi.Controllers
{
    public class PersonController : ApiController
    {
        // GET api/values/5
        public string Get(int id)
        {
            return Person.GetName(id);
        }

    }
}
```
Everything works fine,  the request:
`GET api/person/3`
is giving the right response 
`Jackson Mitchell`

**Issue**

When trying to implement the same on WebApi.Core project:
```
using BusinessLibrary;
namespace WebApi.Core.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PersonController : ControllerBase
    {
        // GET api/person/3
        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            return Person.GetName(id);
        }
    }
}
```
 the request:
`GET api/person/3`
is giving the wrong response. 
`Not Found`. 
After analyzing, it seems that on DataPortal.Execute of the command object, the default public constructor is called and the property `Id` of the command object is set to 0. Can you please advise me how to avoid this issue.

**Version and Platform**
CSLA version: 4.9.000
OS: Windows.
Platform: ASP.NET Core.

**Comment by rockfordlhotka** [comment]
I may have time Wed. Traveling today, all day workshop Tues, meetings Wed, traveling Thursday. Busy week for me.

**Comment by naumandnapuce** [comment]
Hello @rockfordlhotka. Please. If you can find the time. Still waiting for this one as it seems not yet resolved.

**Comment by rockfordlhotka** [comment]
It looks like you are creating your own API service instead of using the data portal. That's not a supported scenario. CSLA types are not designed to be exposed directly to a consumer (user or other app), they are designed to be used by your interface layer (GUI, web page, web API, etc.).

**Comment by rockfordlhotka** [comment]
OK, so you are saying that a `0` is being passed into the `GetName` method from your `Get` method?

Are you sure the `id` parameter is not `0` when the `Get` method is called?

**Comment by rockfordlhotka** [comment]
Oh WAIT - I believe I see the issue.

You are declaring the `Id` property in your command object as a standard property, not a CSLA property. So CSLA isn't helping to manage the property at all, and in .NET Core the default serializer is `MobileFormatter`.

MobileFormatter only knows how to serialize properties with managed backing fields by default. The easiest fix will be to use a managed property. But if you don't want to do that for some reason you'll need to override the `OnGetState`/`OnSetState` methods and manually get/set your private field values to the serialization stream.

Another option is to reconfigure CSLA to use `BinaryFormatter` instead. That isn't as efficient over the network, but would give you the same behavior as with .NET Framework.

**Comment by naumandnapuce** [comment]
We are passing the nr 3 as parameter and the Get method and also GetName method are receiving it as 3.

We see that the values of the public properties of the commandBase (in this case the Id field ) is lost just after Dataportal.Execute

So when in data layer the Id has a value 0. Thats why it is just returning "Not found"

**Comment by naumandnapuce** [comment]
It is working with manged backing fields

  
```
public static readonly PropertyInfo<System.Int32> _Id = RegisterProperty<System.Int32>(p => p.Id, "Id", (System.Int32)0);
        public System.Int32 Id
        {
            get { return ReadProperty(_Id); }
            set { LoadProperty(_Id, value); }
        }

public static readonly PropertyInfo<System.String> _Name = RegisterProperty<System.String>(p => p.Name, "Id", "");
        public System.String Name
        {
            get { return ReadProperty(_Name); }
            set { LoadProperty(_Name, value); }
        }

```

thanks a lot
