### ISSUE TITLE
ApplicationContext.ClientContext loses HttpContext during async call with LocalProxy

### ISSUE THREAD

**Issue by kellyethridge** [MarimerLLC/cslaforum#704]
I've seen some of the previous threads addressing issues similar to mine, but none of the resolutions seem satisfactory. 

During an async call in ASP.NET the ApplicationContext.ClientContext loses the HttpContext backing with LocalProxy presumably because the HttpContext doesn't flow for some reason. This causes the ClientContext in the Logical Server to fallback to using the default thread storage backing, losing the original ContextDictionary. In the Server.DataPortal the contexts are restored through deserialization if the server is remote, otherwise it is assumed the original contexts are still available, leaving us with a new empty ContextDictionary.

**Version and Platform**
CSLA version: <=4.9
OS: Windows 10
Platform: ASP.NET

I have a small ASP.NET application that demonstrates the issue I am experiencing, however I seem to not be able to attach the zip.

**Comment by jonnybee** [comment]
I believe this is the behavior of ASP.NET in that HttpContext does not flow into async calls. 
CSLA.NET has had this behavior for a long time.

**Comment by kellyethridge** [comment]
According to my research, the `HttpContext` will flow into async call just fine. From looking through the `LocalProxy` source code it came down to this line (only changed the one factory method):
`return await await _taskFactory.StartNew(() => this._portal.Create(objectType, criteria, context, isSync));`

I changed the code to the following and recompiled it:
```
    return await await this._taskFactory.StartNew(() => this._portal.Create(objectType, criteria, context, isSync),
    CancellationToken.None,
    TaskCreationOptions.None,
    TaskScheduler.FromCurrentSynchronizationContext());
```
using the modified csla.dll, my ASP.NET sample app worked as expected. I'm unsure of any issues using the `TaskScheduler.FromCurrentSynchronizationContext()` method versus the default behavior, however.

**Comment by rockfordlhotka** [comment]
That's excellent @kellyethridge!

I think we need to test that change in a console app (where there is no synchronization context), but otherwise that seems like a perfectly valid change.

**Comment by rockfordlhotka** [comment]
@kellyethridge do you want to submit a PR with this change?

**Comment by kellyethridge** [comment]
@rockfordlhotka sure thing.

**Comment by ajj7060** [comment]
@rockfordlhotka Would it be possible to get this fix backported to a 4.X version?  I believe we're hitting this now, where an Asp.net app running in local DP mode is losing the HttpContext when trying to do Async operations on the BO.

**Comment by rockfordlhotka** [comment]
@ajj7060 I'm happy to work with you on a back-port. I probably don't have time in the near term, but if you are willing to do a PR I'll create a 4.9.1 branch for you to target.

**Comment by rockfordlhotka** [comment]
@ajj7060 and @kellyethridge I have pushed a preview of 4.10.0 to NuGet that should have this fix backported. Can you please confirm?

**Comment by kellyethridge** [comment]
It does work for me using the four DataPortal methods.

**Comment by rockfordlhotka** [comment]
btw @kellyethridge, creating a branch against a released version of the code wasn't too difficult - after some research on git of course 😄 

1. An admin needs to create the new long-term maintenance branch
   1. fetch latest from MarimerLLC/master
   1. create v4.x branch from the tag `git checkout -b v4.x v4.9.0`
   1. push back to MarimerLLC `git push MarimerLLC/v4.x`
1. Now anyone can work against that branch
   1. `git fetch MarimerLLC` (which pulls the branch too)
   1. `git checkout -b 123-mybranch MarimerLLC/v4.x`
   1. do work in the feature branch
   1. `git push origin`
   1. use the GitHub web UI to create a PR _making sure the target is MarimerLLC/v4.x and not master_

Need to file this away for the future. Again, not hard, but took a little digging to figure out that first part to create the maintenance branch.

**Comment by rockfordlhotka** [comment]
@ajj7060 this has been backported and is now in v4.10.0
