### ISSUE TITLE
ReadOnlyList generalization pros and cons

### ISSUE THREAD

**Issue by lmsantin** [MarimerLLC/cslaforum#71]
Hello:
I am trying to generalize the ReadOnlyList to write less code whenever I need a readonly list.
The following is my superclass:

 [Serializable]
    public class MyReadOnlyListBase<TList, TDalInterface, TObject, TDto, TCriteria>
        : ReadOnlyListBase<TList, TObject>
        where TList : ReadOnlyListBase<TList, TObject>
        where TDalInterface : class, IOwnReadOnlyListBaseDal<TDto>
        where TObject : ReadOnlyBase<TObject>
        where TDto : class
        where TCriteria : ApplicationCriteriaBase, new()
    {
        #region Factory

```
    public static TList Get(TCriteria criteria)
    {
        return DataPortal.Fetch<TList>(criteria);
    }

    #endregion

    #region DataPortal

    private void DataPortal_Fetch(TCriteria criteria)
    {
        using (var dalManager = DalFactory.GetManager())
        {
            var dal = dalManager.GetProvider<TDalInterface>();
            int totalItems = 0;

            var data = dal.FetchList(criteria.QueryExpression(),
                    criteria.CurrentPage,
                    criteria.ItemsPerPage,
                    out totalItems,
                    criteria.CriteriaValues);

            IsReadOnly = false;
            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;

            foreach (var item in data)
                Add(DataPortal.FetchChild<TObject>(item));

            RaiseListChangedEvents = true;
            IsReadOnly = true;
        }
    }

    #endregion
}
```

And the following is all I have to write when I need a readonly list:

```
[Serializable]
public class LocationList : MyReadOnlyListBase<LocationList, ILocationDal,LocationInfo,LocationInfoDto,LocationListCriteria>
{
}
```

For this to work I need a reference to the Dal in the UI project and that is the point where I need your opinion.

Thanks a lot.

Lazaro

**Comment by rockfordlhotka** [comment]
If your Dal project is 100% interfaces then I don't see a problem with that being referenced. As long as the concrete implementation is only deployed to your app server it isn't like someone could get access to it on a client device.

**Comment by lmsantin** [comment]
Thank you Rocky.
My Dal project has the DTOs also.
I found another way to do the generic read only list without referencing the Dal project in the UI.
