### ISSUE TITLE
Data portal Child Fetch Failed

### ISSUE THREAD

**Issue by Jayamanickam** [MarimerLLC/cslaforum#711]
**Question**
DataPortal.Fetch failed(Dataportal.Fetch faild(ChildDataPortal.fetch failed on the server))
Csla.Relection.Ca;;MethodException:Child_fetch method call failed ->System.IndexOutOfrangeException: TaxUnitTotalAmount
at System Data.providerBase.FieldNameLookuo.GetOrdinal(String fieldname)
at Systme.Data.SqlClient.SqlDataReader.GetOrdinal(String name)

**Version and Platform**
CSLA version: 3.8.3
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

[CSAL.docx](https://github.com/MarimerLLC/cslaforum/files/2934695/CSAL.docx)

Kindly Find the attachement also

Thanks and Regards,
D.Jayamanickam

**Comment by hurcane** [comment]
Double check the results of the database call. This error message means that the database result does not include a column called TaxUnitTotalAmount. Perhaps the column is there, but with a slightly different name?

**Comment by Jayamanickam** [comment]
Thanks Issue Resolved. I miss that column to add in Stored procedure.
