### ISSUE TITLE
BusinessRule "override void Execute" is not working in 4.9.0 version

### ISSUE THREAD

**Issue by arunc700** [MarimerLLC/cslaforum#712]
Hi, I am using CSLA framework for my application and running since very long time. Now I am migrating 4.5 to 4.9 but getting lot of error while enabling new dlls.

public class DecimalPrecisionRule : BusinessRule
    {
        private readonly int _precision;

        public DecimalPrecisionRule(PropertyInfo<decimal> primaryProperty, int precision)
            : base(primaryProperty)
        {
            _precision = precision;
            InputProperties = new List<IPropertyInfo> { primaryProperty };
            RuleUri.AddQueryParameter("Precision", precision.ToString());
        }

        protected override void Execute(RuleContext context)
        {
            var primaryValue = (decimal)context.InputPropertyValues[PrimaryProperty];
            var roundedValue = decimal.Round(primaryValue, _precision);

            if (Utils.IsDefined(primaryValue) && roundedValue != primaryValue)
            {
                context.AddErrorResult(ValidationMessages.GetTooManyDecimalsMessage(PrimaryProperty.FriendlyName, _precision));
            }
        }
    }

Above code showing me error that working earlier with 4.5.

On "Execute" showing "No suitable method found to override".
Please help

**Comment by itgoran** [comment]
@arunc700 
Have you tried
` protected override void Execute(IRuleContext context)
  {
  }
`

**Comment by jonnybee** [comment]
@itgoran @arunc700 Yes, this is the correct solution. 

See also: https://github.com/MarimerLLC/csla/issues/827

**Comment by sylum** [comment]
Thx a lot.  just saved my day.
