### ISSUE TITLE
RegExPatterns in Csla 3.xx

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#714]
**Question**
Hi,
while looking at an older project I saw an enum RegExPatterns in CommonRules.cs.
Did we remove it in later versions of Csla?

kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
It is called [RegExMatch](https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Shared/Rules/CommonRules.cs#L489)

**Comment by Chicagoan2016** [comment]
@rockfordlhotka  thank you,
I thought in 3.xx a few regular expressions like Date, SSN etc were provided by Csla.
Not a big deal :), just wondering.

kind regards

**Comment by rockfordlhotka** [comment]
Ahh, yes, I do think I removed those, as they were a maintenance issue for me - very hard to find the "right" regex for any given purpose...
