### ISSUE TITLE
CommandBase and Authorization rules

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#716]
I was rereading Creating business objects books (second book in Using Csla 4.0 series) and on p-25 it says how commandBase doesn't support business and authorization rules but ProjectClose.cs  in Project tracker has AddObjectAuthorizationRules method.
I was wondering if its just a typo in the book.

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
I suspect it is a misunderstanding and I could improve the wording in the book. 

The data portal enforces authz rules, but `CommandBase` has no mechanism to enforce per-property or per-method rules within an instance.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka
