### ISSUE TITLE
4.8.0 string default value PropertyInfo change should be listed as Breaking Change as it is not backwards compatible

### ISSUE THREAD

**Issue by oatsoda** [MarimerLLC/cslaforum#723]
**Describe the bug**
String Properties Registered with a default value of null now have a default value of string.Empty forced upon them.

This should be noted as a breaking change on the Release: https://github.com/MarimerLLC/cslaforum/issues/637

https://github.com/MarimerLLC/csla/commit/953bfdce7e75585514f40eb288ea2c152c8a9f6e#diff-39ba1d2e9f63b430404df3072128c806R122

**Comment by oatsoda** [comment]
Was this definitely by design?  In my case we are explicitly Registering the property with a `defaultValue` of null...

     [Serializable]
     public class ProveObject : BusinessBase<ProveObject>
     {
         private ProveObject()
         {
         }
     
         private static readonly PropertyInfo<string> s_ReasonProperty = RegisterProperty<string>(cp => cp.Reason, nameof(Reason), null);
         public string Reason => GetProperty(s_ReasonProperty);
              
         private static readonly PropertyInfo<string> s_Reason2Property = RegisterProperty<string>(cp => cp.Reason2, defaultValue: null);
         public string Reason2 => GetProperty(s_Reason2Property);
     
         public static ProveObject CreateProveObject()
         {
             return DataPortal.Create<ProveObject>();
         }
     }
     
     [TestFixture]
     public class ProveObjectTests
     {
         [Test]
         public void CreateProveObjectHasNullReason()
         {
             var po = ProveObject.CreateProveObject();
     
             Assert.Multiple(() => 
                 {
                     Assert.That(po.Reason, Is.Null); // Fail
                     Assert.That(po.Reason2, Is.Null); // Fail
                 });
         }
     }

**Comment by rockfordlhotka** [comment]
It was by design. In fact I'm not sure how the non-null default ever happened, because CSLA originally always defaulted to a non-null value to prevent various data binding errors.

**Comment by rockfordlhotka** [comment]
I have updated the official release notes for version 4.8.1
https://github.com/MarimerLLC/csla/releases/tag/v4.8.1.1

**Comment by rockfordlhotka** [comment]
All that said, I'm open to suggestions on how to allow your scenario while still making the default default be `String.Empty`.

**Comment by oatsoda** [comment]
@rockfordlhotka I think I would just do something like this - ensure that default defaults are `string.Empty` but allow explicit defaults to bypass this check:

https://github.com/oatsoda/csla/commit/45abe01943e6e0542339fd305a768478b0b41c42

I am struggling quite a lot because of this. I have many places that use `null` for a string value to mean "not loaded" in the case of Business Rules and Child properties.

**Comment by oatsoda** [comment]
@rockfordlhotka Roughly what sort of timescales are you looking at for releasing the next version with this in?

**Comment by rockfordlhotka** [comment]
I expect to release 5.0 when Microsoft releases .NET Core 3 - so sometime later this year.

If you need the change sooner you can submit a PR against the v4.x branch and I'll do a 4.10.1 release.

**Comment by oatsoda** [comment]
@rockfordlhotka "make sure the target of your PR is , not master"

I assume there is supposed to be a branch name before the comma?
