### ISSUE TITLE
Outer rule's Input Properties -- rule chaining

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#730]
Morning,
I am using rule chaining, where an outer rule can potentially call three different inner rules, lets call them InnerRule1, InnerRule2 and InnerRule3. To make sure the OuterRule's InputProperties contains any property required by the inner rules, I suppose I have to write code like this in OuterRule's constructor for every single inner rule?

`if (InnerRule1.InputProperties != null) 
      InputProperties.AddRange(InnerRule.InputProperties);

if (InnerRule2.InputProperties != null) 
      InputProperties.AddRange(InnerRule.InputProperties);`

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by jonnybee** [comment]
Yes, that is true. The same also for AffectedProperties.

**Comment by Chicagoan2016** [comment]
Thank you @jonnybee , I didnt know about AffectedProperties until you mentioned.
Kind Regards
