### ISSUE TITLE
BusinessListBase DataPortal_Fetch

### ISSUE THREAD

**Issue by GreatBarrier86** [MarimerLLC/cslaforum#733]
**Question**
We're slowly porting our current WinForms app to something that is capable of sharing base classes with Xamarin and i noticed something. `BusinessListBase` does not contain a `DataPortal_Fetch` method. It has `DataPortal_Create` and `DataPortal_Update`, but no `DataPortal_Fetch`. Is this because we're expected to use an `IDataPortalProxy` here? Things are working as I expect with my custom proxy class, but in `BusinessBindingListBase`, we have a `DataPortal_Fetch`, so i was just more curious if I was doing something wrong.

According to this [link](https://github.com/MarimerLLC/cslaforum/issues/347), `BusinessListBase` is the proper one to use when working with XAML, so i assume i'm on the right track.

**Version and Platform**
CSLA version: 4.10
OS: Windows
Platform: Xamarin

**Comment by Chicagoan2016** [comment]
@GreatBarrier86 , When you say BusinessListBase, do you mean your collection derived from this class or the Csla framework code?
I have used BusinessListBase for Child collection as well as root collection and in both case I have a DataPortal_Fetch method.

kind regards

**Comment by rockfordlhotka** [comment]
There's no `DataPortal_Fetch` to override because we can't know what parameter type you'll be passing to your method(s).

There is a default `DataPortal_Create` because the _normal_ case is no parameter. You can, of course, ignore that overload and just create overloads that do have a parameter if needed.

There is a base `DataPortal_Update` because in no case does this method accept a parameter.

**Comment by GreatBarrier86** [comment]
Rocky, thanks for the info. That makes sense.

Now, those methods are considered the `RunLocal` implementation, yes? When i add my own `IDataPortalProxy` , the base `DataPortal_Update` is ignored. It seems like that's to be expected, yes?

**Comment by rockfordlhotka** [comment]
`IDataPortalProxy` only applies to the logical client-side aspects of the data portal, not the logical server-side aspects.

Invocation of the DP_XYZ methods is a logical server-side behavior and has nothing to do with any client-side proxy implementations.

**Comment by GreatBarrier86** [comment]
Thanks for your insight. Much appreciated
