### ISSUE TITLE
Csla.ApplicationContext.User and CustomPrincipal

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#737]
We are using CustomPrincipal class in our project which is derived from CslaPrincipal and we are also using CustomIdenity derived from CslaIdentityBase.
Our CustomIdentity has one extra property 'UserID', every time we need that property we have to cast Csla.ApplicationContext.User.Identity to our  'CustomIdentity'.
Is there a way we could possibly get rid of this casting?

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
I'm not aware of an easy way to avoid that cast. It is .NET itself that uses the `IPrincipal` and `IIdentity` interfaces - CSLA just follows their lead.

I suppose you could implement a static property on your custom principal type like:

```c#
public class CustomPrincipal : CslaPrincipal
{
...
  public static CustomIdentity CurrentIdentity
  {
    get { return (CustomIdentity)Csla.ApplicationContext.User; }
  }
...
}
```

Then access the current identity via that property everywhere in your code?

**Comment by jonnybee** [comment]
Or you could create an extension method GetUserId() that return the user id.
