### ISSUE TITLE
Command Object inside BusinessRule

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#739]
We have a use case similar to example below.
An Employee business object lets a user enter an EmployeeID but makes sure the user cannot assign an existing EmployeeID to a new Employee.
We have implemented a business rule that calls a command object inside the Execute method.
Is this the right approach ? wanted to make sure since the business rule is shared across object instances.

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by jonnybee** [comment]
Yes, this is the right approach.

**Comment by Chicagoan2016** [comment]
Thank you @jonnybee
