### ISSUE TITLE
Authorization Rule Problem

### ISSUE THREAD

**Issue by chatzikk** [MarimerLLC/cslaforum#74]
I am working on a Windows Form Project targeting Framework 4.0 and I have recently moved to version 4.6.100. I have implemented an authorization rule that checks whether the user trying to edit the instance is the creator of that instance or not. If the user is the creator of the instance (or belongs to administartor roles) can edit that instance otherwise can only view it. My custom authorization rule is:
//-------------------------------------------------------------------------------------------------------
        private class SCCanEditObject : Csla.Rules.AuthorizationRule
        {
            public string[] AllowedRoles { get; private set; }

            public SCCanEditObject(Csla.Rules.AuthorizationActions action, params string[] allowedRoles)
                : base(action)
            {
                AllowedRoles = allowedRoles;
            }
            protected override void Execute(Csla.Rules.AuthorizationContext context)
            {
                var sc = context.Target as CSaleContact;
                bool allowOwner=true;
                if (sc != null)
                {
                    if (User.IsInRole(AllowedRoles))
                    {
                        context.HasPermission = true;
                        return;
                    }
                    if (allowOwner)
                    {
                        context.HasPermission = sc.OwnerId == Atlantis.Library.Common.CUtils.GetUserId();
                    }
                        else
                            context.HasPermission = false;
                }
//-------------------------------------------------------------------

With CSLA 4.3.13 this rule was working as expected. Since I moved to version 4.6.100 during the fetch operation in the AddBusinessRules I get the error:
----------------------------------------------------------------------------------------------------------
System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=rule
  Source=Csla
  StackTrace:
       at Csla.Rules.BusinessRules.EnsureUniqueRule(AuthorizationRuleManager mgr, IAuthorizationRule rule)
       at Csla.Rules.BusinessRules.AddRule(IAuthorizationRule rule)
       at Atlantis.Library.SalesManager.CSaleContact.AddBusinessRules() in c:\Users\Konstantinos\OneDrive\Workbench\AtlantisSM--c# 3Tier\Atlantis.Library\SalesManager\CSaleContact.cs:line 597
       at Csla.Core.BusinessBase.InitializeBusinessRules()
  InnerException: 
-----------------------------------------------------------------------------------------

Thanks

**Comment by jonnybee** [comment]
The method EnsureUniqueRule is throwing an exception as it would seem the Authorization rule has already been added for that Element and Action. So that is a logical error in your AddBusinessRules method. 

It is only allowed to have one-1 AutorizationRule per Element and Action. AddRule may have worked in previous versions but the code would only ever use the first instance when executing Authz rules. 

You should also make sure to set CacheResult to false in the constructor so that the result will not be cached. Typically AutorixationRules only check roles and the result will be cached to speed up execution.

**Comment by chatzikk** [comment]
I used the Action AuthorizationActions.EditObject both in AddBusinessRules() and in static AddObjectAuthorizationRules(). I removed the line from AddObjectAuthorizationRules() and now works fine.
Thank you very much for your help.
