### ISSUE TITLE
INPUT NEEDED: NuGet package rename

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#745]
I am considering a fairly major change to CSLA 5.0 that'll affect upgrades.

Specifically, I want to "fix" the NuGet package names so they match modern naming conventions. 

When we first created the NuGet packages it was kind of the "wild west" with no set conventions. So we just ran with something. Specifically things like `CSLA-Core` and `CSLA-ASP.NET`.

It turns out that wasn't where the industry settled. Really things should be named like `Csla` and `Csla.Data.EntityFramework6` and `Csla.WindowsForms` and `Csla.Xaml`.

Obviously this would mean fixing NuGet references when migrating from 4.10 to 5.0. There wouldn't be _code changes_, but still.

What do people think about this change?

**Comment by fujiiface** [comment]
I’m for this as long as there’s a basic mapping we can follow to translate old to new.

Probably goes without saying but I’ll throw it out there anyway; samples/demos should also be updated to use the new packages at the same time.

**Comment by rockfordlhotka** [comment]
I've created a backlog item for this (see above) and have listed proposed new package names in that item.

If you have any suggestions on better package naming, please comment on the work item and let me know - **I value your input on this!!**
