### ISSUE TITLE
Default value in dropdownlists and Read only collections

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#752]
Hi,
We mainly use Read only collections to populate dropdownlists (combbox) in our applications.
For the default value of,  say, '[Select]' we had been adding a row in database tables (lookup tables).
I was wondering if we could add this default value (read only object) to the collection in the Business Layer.

Kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
Of course. Nothing stops you from adding a regular property to a collection. Considerations:

1. You'll need to override GetState/SetState to support serialization
1. The property should be read-only, just like the collection
1. Windows Forms won't be able to bind to this property (nor will Web Forms I think?)
1. There are no rules or change tracking or anything for properties in a collection

**Comment by GillesBer** [comment]
@Chicagoan2016 
do I understand correctly that you mean that you want a default item of your collection (the first one probably?)
in our case, in the DataPortal_Fetch, we 
* we add the default item 
* then we add the other items (your database rows)
Thus, we don't store the 'default' item as a database row.
Gilles

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka  and @GillesBer ,
I apologize for not explaining my question well, I want to add a default value in combbox something like '[None Selected]', Since I use Readonly collection, I thought of  adding a readonly object to the collection in DataFortal_Fecth ( like @GillesBer  recommended).
I think I can set 'string' property of the readonly object to '[None Selected]' and 'ID' property as -1 and assign dummy value to other properties of the readonly object.
Does it sound right?

Best Regards

**Comment by brinawebb** [comment]
We do this in the dataportal by passing in a bool and an ID to the criteria.

1. If bool == false then load the items. Most of our lists have an active/inactive concept so in this case we only add the active items.

2. If bool == true it's used for a selection list (combobox), so add a" (select item)" with an empty guid (or whatever you need for 'no ID'). Note the space before the "(", this keeps it at the top when sorting.

3. If bool == true and the ID isn't an empty Guid, then check to see if the ID has been added to the list and add it if not. This would be the case for something inactive.

4. Sort

**Comment by michaelcsikos** [comment]
I often do what you're describing. I pass in a parameter to the collection's factory method `bool includeNone` which, if `true`, adds a special object, usually with a known Id like `Guid.Empty` and a `ToString()` of _(None)_. You can combine this with a rule for an editable biz object if the value is required, but it gives your UI a nice way to show that no value has been selected yet, and it doesn't automatically default to the first real value in the list, which could easily be overlooked by the user.

**Comment by fujiiface** [comment]
I’m glad this conversation is happening.  I’ve usually loaded the “Select” default value from the Controller/Code-behind file using a helper function but loading from the object layer has me rethinking some older objects now.  Good stuff!

**Comment by fujiiface** [comment]
Curious if anyone is using the NameValueList object for things like this?  I’m using it for a couple different DropDownLists but if I recall correctly, this is an old CSLA pattern now?

**Comment by michaelcsikos** [comment]
I usually use a `ReadOnlyBindingListBase` of `ReadOnlyBase` objects as I sometimes want to display more than one column in a custom, lightweight grid drop-down.

**Comment by Chicagoan2016** [comment]
@michaelcsikos , I usually do the same but before this conversation go in a different direction : ) I would just open another thread about BusinessListBase and BusinessBindingListBase : ).

Kind regards

**Comment by Chicagoan2016** [comment]
if we go about as suggested how should we modify the code `below? I took this piece of code from Project Tracker application, class RoleEditList.cs

`    private void DataPortal_Fetch()
      {
        var rlce = RaiseListChangedEvents;
        RaiseListChangedEvents = false;
        using (var ctx = ProjectTracker.Dal.DalFactory.GetManager())
        {
          var dal = ctx.GetProvider<ProjectTracker.Dal.IRoleDal>();
          List<ProjectTracker.Dal.RoleDto> list = null;
          list = dal.Fetch();
          foreach (var item in list)
            Add(DataPortal.FetchChild<RoleEdit>(item));
        }
        RaiseListChangedEvents = rlce;
      }`


Regards

**Comment by michaelcsikos** [comment]
Firstly, you normally wouldn't databind a list of editable business objects to a drop-down.

You want something like the following:

``` csharp
[Serializable]
private class Criteria
    : CriteriaBase<Criteria>
{
    public static readonly PropertyInfo<bool> IncludeArchivedProperty
                     = RegisterProperty<bool>(p => p.IncludeArchived);
    public bool IncludeArchived
    {
        get { return ReadProperty(IncludeArchivedProperty); }
        set { LoadProperty(IncludeArchivedProperty, value); }
    }

    public static readonly PropertyInfo<bool> IncludeNoneProperty
                     = RegisterProperty<bool>(p => p.IncludeNone);
    public bool IncludeNone
    {
        get { return ReadProperty(IncludeNoneProperty); }
        set { LoadProperty(IncludeNoneProperty, value); }
    }

    public Criteria(bool includeArchived, bool includeNone)
    {
        IncludeArchived = includeArchived;
        IncludeNone     = includeNone;
    }

    public Criteria()
    {
    }
}

private void DataPortal_Fetch(Criteria criteria)
{
    RaiseListChangedEvents = false;

    using (var ctx = DalFactory.GetManager())
    {
        var dal    = ctx.GetProvider<ICompanyDal>();
        var list   = dal.FetchList(criteria.IncludeArchived);

        IsReadOnly = false;

        if (criteria.IncludeNone)
            Add(CompanyInfo.NewCompanyInfoNone());

        foreach (var dto in list)
        {
            var item = DataPortal.FetchChild<CompanyInfo>(dto);

            Add(item);
        }

        IsReadOnly = true;
    }

    RaiseListChangedEvents = true;
}
```

**Comment by GillesBer** [comment]
I think the short answer to @Chicagoan2016  for

> Does it sound right?

was **Yes**  !

**Comment by rockfordlhotka** [comment]
@fujiiface I don't see why people _wouldn't_ use `NameValueList` - this is its purpose. If you create a `ReadOnlyList` with two fields you've basically recreated NVL for nothing 😮

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos , Now I think I am overthinking it but its Friday night and I am not going out lol.
The method you mentioned above ```csharp CompanyInfo.NewCompanyInfoNone() ```.
I can think of two ways to implement it.
**First method**
   Use the private constructor in child object CompanyInfo as follows
   ```csharp
     internal static CompanyInfo NewCompanyInfoNone()
        {
            CompanyInfo obj = new CompanyInfo 
            {
                CompanyID = -1;
                CompanyName = "[None Selected]"
            };
            return obj;
        }
```

**Second Method**
    Call dataportal from static method and overlaod child_Fetch as follows
    ```csharp
      internal static CompanyInfo NewCompanyInfoNone()
       {
          return DataPortal.FetchChild<CompanyInfo>();
        }

       private void Child_Fetch()
        {
            CompanyID = -1;
            CompanyName = "[None Selected]"
        }
```

any ideas? anyone please : )

Kind regards

**Comment by michaelcsikos** [comment]
Just use the default constructor; there's no need to use the `DataPortal`.
