### ISSUE TITLE
csla 4.6 using WCF in IIS 7.0 with client WPF  (.NET 4.62)

### ISSUE THREAD

**Issue by arquisoft1956** [MarimerLLC/cslaforum#754]
I am using csla 4.6 using WCF with IIS7.0 get error message server "authentication failed". this happens when the server is remote. when use a server in the same pc run without problems. 
thanks you very much

**Comment by rockfordlhotka** [comment]
The easiest way to troubleshoot this sort of problem is to add an aspx page to your web server and then access it through the browser. Or you can try to just navigate to your svc endpoint in the browser.

Either way, you'll probably encounter the authentication issue and can change your server's settings to fix it.

**Comment by arquisoft1956** [comment]
Thanks very much

**Comment by arquisoft1956** [comment]
Thanks for the answer. One cuestion more. In WCF they say that
the client and server must be the same endpoint etc....
In CSLA would be not a must?.
Thanks.
Best regards
Alejandro Román

**Comment by arquisoft1956** [comment]
when put http://10.10.10.4/WcfPortal.svc
recibe
[image: image.png]

and This is the message that say when run against the server iis with
 http://10.10.10.4/WcfPortal.svc

[image: image.png]

my app.setting of my client wpf
is
 <appSettings>

    <add key="CslaDataPortalProxy" value="Csla.DataPortalClient.WcfProxy,
Csla"/>
    <add key="CslaDataPortalUrl" value="http://10.10.10.4/WcfPortal.svc"/>

    <add key="DalManagerTesorType"
value="Tesoreria.DalEf.DalManager,Tesoreria.DalEf"/>
    <add key="DalManagerSRType" value="SR.DalEf.DalManager,SR.DalEf"/>

  </appSettings>

the other hand when run against my iis local (in my pc )
it run with problems :

 <appSettings>


   <add key="CslaDataPortalProxy" value="Csla.DataPortalClient.WcfProxy,
Csla"/>
    <add key="CslaDataPortalUrl" value="http://localhost:82/WcfPortal.svc
"/>
    <add key="DalManagerTesorType"
value="Tesoreria.DalEf.DalManager,Tesoreria.DalEf"/>
    <add key="DalManagerSRType" value="SR.DalEf.DalManager,SR.DalEf"/>


  </appSettings>

thank you very much

**Comment by rockfordlhotka** [comment]
Your images did not appear.

Have you looked at the [Using CSLA 4: Data Portal Configuration](https://store.lhotka.net/using-csla-4-data-portal-configuration) book? It has a lot of information about configuring the data portal and WCF.

**Comment by arquisoft1956** [comment]
Please Help Me

**Comment by arquisoft1956** [comment]
the server  say this :

An account failed to log on.

Subject:
Security ID: NULL SID
Account Name: -
Account Domain: -
Logon ID: 0x0

Logon Type: 3

Account For Which Logon Failed:
Security ID: NULL SID
Account Name: Alejandro
Account Domain: ARQUISOFT21

Failure Information:
Failure Reason: Unknown user name or bad password.
Status: 0xc000006d
Sub Status: 0xc000006a

Process Information:
Caller Process ID: 0x0
Caller Process Name: -

Network Information:
Workstation Name: ARQUISOFT21
Source Network Address: -
Source Port: -

Detailed Authentication Information:
Logon Process: NtLmSsp
Authentication Package: NTLM
Transited Services: -
Package Name (NTLM only): -
Key Length: 0

This event is generated when a logon request fails. It is generated on the
computer where access was attempted.

The Subject fields indicate the account on the local system which requested
the logon. This is most commonly a service such as the Server service, or a
local process such as Winlogon.exe or Services.exe.

The Logon Type field indicates the kind of logon that was requested. The
most common types are 2 (interactive) and 3 (network).

The Process Information fields indicate which account and process on the
system requested the logon.

The Network Information fields indicate where a remote logon request
originated. Workstation name is not always available and may be left blank
in some cases.

The authentication information fields provide detailed information about
this specific logon request.
- Transited services indicate which intermediate services have participated
in this logon request.
- Package name indicates which sub-protocol was used among the NTLM
protocols.
- Key length indicates the length of the generated session key. This will
be 0 if no session key was requested.

Thank you very much for your help.
Alejandro Román

**Comment by arquisoft1956** [comment]
What can I do?.
Raise the csla version?
To use remoting?
Really I need help?
I use csla since 2000 but
Is first time that use wcf as channel
Because I allways have used Remoting
Thanks very much
Alejandro Roman

**Comment by arquisoft1956** [comment]
Rockford :
I have all your books (about 8) inclusive  “using csla 4.0”  5 books.
But l dont have your brain😔.
Perhaps the clients WPF must be in the domain.
I think Could be a problem in the impersonation process 
I am using custom authentication but
The call to wcf server must be authenticated by the server.?
I could pay for the Help
Best regards
Alejandro Román
From Chile




Enviado desde mi iPad

**Comment by arquisoft1956** [comment]
Yes. I buy in 2012 😊.

**Comment by arquisoft1956** [comment]
This is the error message  when
run against http://10.10.10.4 ( web server) :

System.ServiceModel.Security.SecurityNegotiationException
  HResult=0x80131501
  Mensaje = El servicio no autenticó al autor de la llamada.
  Origen = Csla
  Seguimiento de la pila:
   en Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   en Csla.DataPortal`1.Fetch(Object criteria)
   en Csla.DataPortal.Fetch[T](Object criteria)
   en Tesoreria.Library.Security.PTIdentity.GetPTIdentity(String username,
String password) en
E:\GitLocal\CM-Tesoreria\Tesoreria.Library\Security\PTIdentity.cs: línea 31
   en Tesoreria.Library.Security.PTPrincipal.Login(String username, String
password) en
E:\GitLocal\CM-Tesoreria\Tesoreria.Library\Security\PTPrincipal.cs: línea 35
   en WPFUITesor.ViewModels.Login.LoginUser() en
E:\GitLocal\CM-Tesoreria\WPFUITesor\ViewModels\Login.cs: línea 38

Excepción interna 1:
FaultException: The request for security token could not be satisfied
because authentication failed.

thanks you very much
alejandro Roman

**Comment by rockfordlhotka** [comment]
This is why I asked about the _Data Portal Configuration_ book. The problem you are facing is due to the way your server, or IIS, or WCF is configured.

It sounds like your server is requiring domain login. And that is fine, but the client needs to provide domain credentials.

This can be done by having the client machine be part of the domain to start with, so the user's identity automatically flows to the server. It sounds like this is not your scenario.

The other way to do this is to provide the user's domain credentials to WCF on the client so the credentials flow to the server. To do this you need to create a subclass of `WcfProxy` and provide the credentials as the underlying WCF proxy object is created and initialized.

**Comment by arquisoft1956** [comment]
Thanks very much.
I lost the sample customProxy.
Please  can you tell me how can I get it?
I need it for build a proxy subclass.
Thanks.

Best Regards
Alejandro Román

**Comment by rockfordlhotka** [comment]
Here's the sample from the book:
```c#
  public class WcfProxy : Csla.DataPortalClient.WcfProxy
  {
    public WcfProxy(string serverUrl)
    {
      _serverUrl = serverUrl;
    }
 
    private string _serverUrl;
 
    protected override System.ServiceModel.ChannelFactory<Csla.Server.Hosts.IWcfPortal> 
      GetChannelFactory()
    {
      var binding = new WSHttpBinding()
      { 
        MaxReceivedMessageSize = int.MaxValue, 
        ReaderQuotas = new System.Xml.XmlDictionaryReaderQuotas() 
        {
          MaxBytesPerRead = int.MaxValue,
          MaxDepth = int.MaxValue,
          MaxArrayLength = int.MaxValue,
          MaxStringContentLength = int.MaxValue,
          MaxNameTableCharCount = int.MaxValue
        }
      };
      return new ChannelFactory<IWcfPortal>(binding, _serverUrl);
    }
  }
```
I don't know that I have a sample showing how to add credentials to the WCF proxy, and it isn't something I've looked at for many years. There's nothing about it that is specific to CSLA though, so any good book or online source about WCF should show you how to do that.

You can override the `GetChannelFactory` method as shown here if the credentials go on the factory. Otherwise you can override the `GetProxy` method if you need to set the credentials as the proxy is created by using the factory.

**Comment by arquisoft1956** [comment]
Thank you very much

**Comment by arquisoft1956** [comment]
Dear Mr Lhotka :

The Method GetChannelfactory dont permit
override when using csla 4.61.
I cant see a way to override GetChannelFactory.
Do you could give me a hand?
Thanks
Best Regards
Alejandro Román

**Comment by rockfordlhotka** [comment]
It should be virtual. Here is the code from 4.6.100 showing that the method is virtual:
https://github.com/MarimerLLC/csla/blob/v4.6.100/Source/Csla.Shared/DataPortalClient/WcfProxy.cs#L122

If it really isn't virtual in your version of the code you should look at upgrading to a more current NuGet package.

**Comment by arquisoft1956** [comment]
[image: image.png]

Dear Mr. Lhotka:
when change the version of clsa to 4.6663 in customProxy
I get an error.
I cant resolve it.
Thanks.
Best regards
Alejandro Román

**Comment by rockfordlhotka** [comment]
Your images are not coming through so I can't see whatever you are trying to show me.

**Comment by rockfordlhotka** [comment]
Here's some code I just created in VS 2017 using the CSLA-Core 4.6.603 package reference (and a reference to `System.ServiceModel` of course):

```c#
using Csla.DataPortalClient;
using System.ServiceModel;

namespace ClassLibrary1
{
    public class CustomProxy : WcfProxy
    {
        protected override System.ServiceModel.ChannelFactory<IWcfPortal> GetChannelFactory()
        {
            return base.GetChannelFactory();
        }

        protected override IWcfPortal GetProxy(ChannelFactory<IWcfPortal> cf)
        {
            return base.GetProxy(cf);
        }
    }
}
```

**Comment by arquisoft1956** [comment]
Thanks very much.
In the customProxy of sample  had reference to csla.server.host.IWcfPortal but you
In your mail use csla.dataPortalClient.IWcfPortal. That was the problem. Thanks very much

Enviado desde mi iPad

**Comment by arquisoft1956** [comment]
Csla.Server.Hosts

Enviado desde mi iPad

**Comment by arquisoft1956** [comment]
Dear Mr. Lhotka :
I make the modification in subclass of wcfproxy (in Red color) :

 protected override ChannelFactory<IWcfPortal> GetChannelFactory()
    {
      // set up WSHttpBinding with
      var binding = new WSHttpBinding()
      {
        //MaxBufferPoolSize = int.MaxValue,       // default is 524288 and
kept to default value
        MaxReceivedMessageSize = int.MaxValue,    // default is 65536
        ReaderQuotas = new System.Xml.XmlDictionaryReaderQuotas
        {
          MaxArrayLength = int.MaxValue,          // default is 16384
          MaxStringContentLength = int.MaxValue,  // default is 8192
        }


        };
           * binding.Security.Mode = SecurityMode.Transport;
binding.Security.Transport.ClientCredentialType =
HttpClientCredentialType.None;*

            return new  ChannelFactory<IWcfPortal>(binding, _serverUrl);

    }

 and get the error :

  Mensaje = El esquema de URI proporcionado 'http' no es válido; se
esperaba 'https'.
(The URI schema  send is not valid. is neccesary 'https'.)

Nombre del parámetro: via
  Origen = Csla
  Seguimiento de la pila:
   en Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   en Csla.DataPortal`1.Fetch(Object criteria)
   en Csla.DataPortal.Fetch[T](Object criteria)
   en Tesoreria.Library.Security.PTIdentity.GetPTIdentity(String username,
String password) en
E:\GitLocal\CM-Tesoreria\Tesoreria.Library\Security\PTIdentity.cs: línea 31
   en Tesoreria.Library.Security.PTPrincipal.Login(String username, String
password) en
E:\GitLocal\CM-Tesoreria\Tesoreria.Library\Security\PTPrincipal.cs: línea 35
   en WPFUITesor.ViewModels.Login.LoginUser() en
E:\GitLocal\CM-Tesoreria\WPFUITesor\ViewModels\Login.cs: línea 38

Coud you give a indicaction?
Thanks
AR

**Comment by arquisoft1956** [comment]
Dear Mr. Lhotka :
I make the modification in subclass of wcfproxy (in Red color) :

 protected override ChannelFactory<IWcfPortal> GetChannelFactory()
    {
      // set up WSHttpBinding with
      var binding = new WSHttpBinding()
      {
        //MaxBufferPoolSize = int.MaxValue,       // default is 524288 and
kept to default value
        MaxReceivedMessageSize = int.MaxValue,    // default is 65536
        ReaderQuotas = new System.Xml.XmlDictionaryReaderQuotas
        {
          MaxArrayLength = int.MaxValue,          // default is 16384
          MaxStringContentLength = int.MaxValue,  // default is 8192
        }


        };
            binding.Security.Mode = SecurityMode.None;
binding.Security.Transport.ClientCredentialType =
HttpClientCredentialType.None;

            return new  ChannelFactory<IWcfPortal>(binding, _serverUrl);

    }

 and get the error :

System.ServiceModel.ServiceActivationException
  HResult=0x80131501
  Mensaje = No se pudo activar el servicio solicitado, (the server asked
cant active)
 'http://10.10.10.4/WcfFullPortal.svc'. Consulte los registros de
seguimiento de diagnóstico del servidor para obtener más información.
  Origen = Csla
  Seguimiento de la pila:
   en Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   en Csla.DataPortal`1.Fetch(Object criteria)
   en Csla.DataPortal.Fetch[T](Object criteria)
   en Tesoreria.Library.Security.PTIdentity.GetPTIdentity(String username,
String password) en
E:\GitLocal\CM-Tesoreria\Tesoreria.Library\Security\PTIdentity.cs: línea 31
   en Tesoreria.Library.Security.PTPrincipal.Login(String username, String
password) en
E:\GitLocal\CM-Tesoreria\Tesoreria.Library\Security\PTPrincipal.cs: línea 35
   en WPFUITesor.ViewModels.Login.LoginUser() en
E:\GitLocal\CM-Tesoreria\WPFUITesor\ViewModels\Login.cs: línea 38


when see the server error registre I get :

System.ServiceModel.ServiceActivationException: The service
'/WcfFullPortal.svc' cannot be activated due to an exception during
compilation. The exception message is: Could not find a base address that
matches scheme https for the endpoint with binding WSHttpBinding.
Registered base address schemes are [http].. --->
System.InvalidOperationException: Could not find a base address that
matches scheme https for the endpoint with binding WSHttpBinding.
Registered base address schemes are [http]. at
System.ServiceModel.ServiceHostBase.MakeAbsoluteUri(Uri
relativeOrAbsoluteUri, Binding binding, UriSchemeKeyedCollection
baseAddresses) at
System.ServiceModel.Description.ConfigLoader.LoadServiceDescription(ServiceHostBase
host, ServiceDescription description, ServiceElement serviceElement,
Action`1 addBaseAddress, Boolean skipHost) at
System.ServiceModel.ServiceHostBase.LoadConfigurationSectionInternal(ConfigLoader
configLoader, ServiceDescription description, ServiceElement
serviceSection) at System.ServiceModel.ServiceHostBase.ApplyConfiguration()
at
System.ServiceModel.ServiceHostBase.InitializeDescription(UriSchemeKeyedCollection
baseAddresses) at System.ServiceModel.ServiceHost..ctor(Type serviceType,
Uri[] baseAddresses) at
System.ServiceModel.Activation.ServiceHostFactory.CreateServiceHost(Type
serviceType, Uri[] baseAddresses) at
System.ServiceModel.ServiceHostingEnvironment.HostingManager.CreateService(String
normalizedVirtualPath, EventTraceActivity eventTraceActivity) at
System.ServiceModel.ServiceHostingEnvironment.HostingManager.ActivateService(ServiceActivationInfo
serviceActivationInfo, EventTraceActivity eventTraceActivity) at
System.ServiceModel.ServiceHostingEnvironment.HostingManager.EnsureServiceAvailable(String
normalizedVirtualPath, EventTraceActivity eventTraceActivity) --- End of
inner exception stack trace --- at
System.ServiceModel.ServiceHostingEnvironment.HostingManager.EnsureServiceAvailable(String
normalizedVirtualPath, EventTraceActivity eventTraceActivity) at
System.ServiceModel.ServiceHostingEnvironment.EnsureServiceAvailableFast(String
relativeVirtualPath, EventTraceActivity eventTraceActivity)
w3wp
2452
I know tha is WCF technology. but I prefer ask you
because I have safe with your wise.
Thanks
AR

**Comment by rockfordlhotka** [comment]
It sounds like you might be using an http address when the protocol is configured to require https?

>Could not find a base address that
matches scheme https for the endpoint with binding WSHttpBinding.
Registered base address schemes are [http]..

**Comment by arquisoft1956** [comment]
Problem solved. Thanks
Best regards
Alejandro Roman
