### ISSUE TITLE
Add option to allow FieldManager.UpdateChildren to ignore IsDirty

### ISSUE THREAD

**Issue by j055** [MarimerLLC/cslaforum#755]
**Is your feature request related to a problem? Please describe.**
I sometimes need to get all child data and save it to the database in the parent DataPortal_Update. I need to get all the children objects even if they are not dirty.

**Describe the solution you'd like**
I would like another overload of ```FieldManager.UpdateChildren``` which will ignore whether the child object is dirty or not. The child can then update the reference  object passed into it. e.g.

```
var entity = new SomeEntity();
FieldManager.UpdateChildren(entity, includeNotDirty);
```

**Describe alternatives you've considered**
Create an internal method which marks the child as dirty and call it in the parent ```DataPortal_Update``` method. That's a pain!

**Additional context**
Thanks for your consideration.

**Comment by rockfordlhotka** [comment]
The behavior to properly handle new/dirty/deleted child objects isn't actually in `UpdateChildren`, it is in the `Update` method of the `ChildDataPortal` itself.

What I'm hearing is that you don't really want the child data portal at all, because you want to ignore the metastate of the child objects.

You might consider looping through the child objects yourself, and calling your own method on those objects?

```c#
  var children = FieldManager.GetChildren();
  foreach (var child in children)
    child.UpdateChild(entity);
```

**Comment by j055** [comment]
Hi Rocky

I'm being lazy I know but I think a little mod here would help:
https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Shared/Server/ChildDataPortal.cs#L228

If the method could accept a flag to ignore the ```IsDirty``` check and bubble it up to the calling code I think that would give me what I wanted.

**Comment by rockfordlhotka** [comment]
I'm open to the idea if you'd like to do a PR.

I'd think, following your idea about `UpdateAllChildren` that we'd want to

1. Add public `UpdateAll` methods to `ChildDataPortal` to match the existing public `Update` methods
1. Add a parameter to the private `Update` method in `ChildDataPortal` to override the `IsDirty` check as you suggest
1. Add an `UpdateAllChildren` method to `FieldManager` that calls the new `UpdateAll` method in the data portal

**Comment by j055** [comment]
Cool. I'll create a PR. Thanks

**Comment by GillesBer** [comment]
Hi, why don't you override IsDirty in you child object?
ex:
	        public override bool IsDirty => true;

we have a couple of situation in which we have ovveride like this.
Is our usage a bad practice?

**Comment by j055** [comment]
Because that would make the root or parent dirty and it might not be.

**Comment by rockfordlhotka** [comment]
No @GillesBer, not a bad practice at all.

But I can see where @j055 has a point too, wanting the normal `IsDirty` behavior for UI interactions, etc. and also needing to do a full data update into the data store.

(btw @j055 - what you describe is why the parent has `IsDirty` and `IsSelfDirty`)

**Comment by GillesBer** [comment]
Thanks!
