### ISSUE TITLE
Dataportal call issue

### ISSUE THREAD

**Issue by Brannos1970** [MarimerLLC/cslaforum#756]
**Describe the bug**
In my ProjectIdentity file when calling DataPortal method I get an error telling me it could not load my project library or one of its files. I checked all references and they are there. This was working yesterday and started after I updated to the latest version. Any ideas. I have included the error details in the attached file
[Untitled 1.txt](https://github.com/MarimerLLC/csla/files/3239122/Untitled.1.txt)
.

**Version and Platform**
CSLA version: 10.1
OS: Windows
Platform: ASp.NET, MVC 5

**Code that Fails**
 public static TifsaIdentity GetTifsaIdentity(string username, string password)
        {
            return DataPortal.Fetch<Security.TifsaIdentity>(new UsernameCriteria(username, password));
        }

**Comment by rockfordlhotka** [comment]
The most likely cause is that you didn't update the CSLA assemblies on either the client or server. The version of the CSLA assemblies need to match on client and server, and so do the versions of your business assemblies.

**Comment by Brannos1970** [comment]
I found the issue. I had to add my database dal into the user interface I was working on. Strange that they were not there even though they had been. Thanks for the help.
