### ISSUE TITLE
Was there a change to Dataportal FetchAsync so it would not call void Dataportal_Fetch?

### ISSUE THREAD

**Issue by Brannos1970** [MarimerLLC/cslaforum#759]
I notice that when I call an async DataPortal.Fetch the DataPortal_Fetch method is not accessed. Was there a change somewhere or am I missing something? I don't get any errors, just hangs up. Was wondering if I need to create a DataPortal_FetchAsync.

**Comment by michaelcsikos** [comment]
Can you post your code? Calling either `DataPortal.Fetch<ClassName>(...)` or `await DataPortal.FetchAsync<ClassName>(...)` should call `private void DataPortal_Fetch(...)` as long as the parameters match.

**Comment by michaelcsikos** [comment]
OK, so we've just experienced this exact behaviour with a client. We were doing an `async` fetch during `OnLoad` in a form. The `DataPortal_Fetch` never gets hit.

I think it may have something to do with [this bug](https://github.com/MarimerLLC/csla/issues/1164#event-2380099683) that I reported last week.

In my case, it seems the UI thread isn't pumping so the fetch never gets a chance to run. When I hit the refresh button on this particular form after it has been shown, it fetches correctly. Moving the fetch from `OnLoad` to `OnShown` fixes the problem, but this is pretty scary stuff. We could potentially have lots of `async` calls in `OnLoad` which could be broken.

**Comment by rockfordlhotka** [comment]
I expect to release 4.11.0 with that fix tomorrow.

**Comment by Brannos1970** [comment]
I am building a website. While I can expose the methods we keep under the Full DotNet directives and get things to work while I am testing, I am needing to make asynchronous calls.

I just tested the calls with the new update and the fetch methods are still not being made.

**Comment by Brannos1970** [comment]
I spoke too soon. Just tried to call NewBusinessObjectAsync and nothing happened.

My code was called but Csla did not return with a new object. Here is my calling code:

public async static System.Threading.Tasks.Task<AccountEdit> NewAccountAsync()
        {
            return await DataPortal.CreateAsync<AccountEdit>();
        }
 [RunLocal]
        protected override void DataPortal_Create()
        {
            base.DataPortal_Create();
        }

**Comment by michaelcsikos** [comment]
`Task` is the `async` equivalent of `void`. You need to use a generic `Task` and `CreateAsync`:

``` csharp
public static async Task<Account> NewAccountAsync()
 {
     return await DataPortal.CreateAsync<Account>();
 }

 public Account()
 {
 }

 [RunLocal]
 protected override void DataPortal_Create()
 {
     base.DataPortal_Create();
 }
```

**Comment by Brannos1970** [comment]
I did not even think to put in Public Account(). Added it and it is working now. 

Thank you for the help.
