### ISSUE TITLE
Friendly name not supplied for a property

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#762]
I have noticed that if I don't supply a friendly name for a property, Csla takes the name of the property which is fine, no complaints : ), for instance, if I have a Phone property and I don't assign a friendly name and I add 'Required' business rule to this property, I still get 'Phone' inside the business rule message.
I wonder how does Csla get the property name?

Kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
Today it gets the name from your lambda expression in the `RegisterProperty` call.

In 5.0 it will get the name from your `nameof` expression in the `RegisterProperty` call.

**Comment by Chicagoan2016** [comment]
@rockfordlhotka , thank you sir
