### ISSUE TITLE
Dynamic CSLA properties for Custom Attributes 

### ISSUE THREAD

**Issue by damianrafferty** [MarimerLLC/cslaforum#764]
**Question**

Is it possible to dynamically create/add Properties to a CSLA Business Object at runtime? I have a standard CSLA Business Object that has standard get/set properties, and it also has a child collection of Custom Attributes where end users can add their own Property Names and Values. Currently we show a list of the Business Objects in a datagrid and show the Custom Properties in a Property Grid as each row in the datagrid is selected. However, I would like to show the Custom Properties as columns in the datagrid along side the "normal" properties of the Business Object. To that end, is it possible that in the data portal fetch when we have the object and child collection data for the custom properties, to add the Custom Properties dynamically to the Business Object as additional Properties so that the datagrid binds to them?  

**Version and Platform**
CSLA version: 4.7.100
OS: Windows
Platform: WPF
Data: Entity Framework (or ADO.NET if required)

**Comment by michaelcsikos** [comment]
Hi Damo

I have implemented a similar thing. The way I allowed the custom properties to be shown in the grid was by declaring 50 numbered properties in the parent class which return the value from the appropriate object in the child collection. (You could do more than 50, of course. It just depends on how many custom properties you expect users to add.) You can set up the column headers with the correct custom property name. I used `object` as the data type for the number properties with `DataGridViewTextBoxColumn` in the grid, and relied on `ToString()` to format values. And you only add the number of columns that you know have been defined by the user.

``` csharp
public static readonly PropertyInfo<object> Property00Property
                 = RegisterProperty<object>(p => p.Property00);
public object Property00
{
    get { return GetValue(Property00Property); }
    set { SetValue(Property00Property, value); }
}

// Rinse and repeat for the maximum number of columns of you want to support

private object GetValue(IPropertyInfo propertyInfo)
{
    var property = GetCustomProperty(propertyInfo);

    if (property == null)
        return null;

    // You could potentially do some switching or formatting here

    return property.GetValue();
}

private GenericObjectProperty GetCustomProperty(IPropertyInfo propertyInfo)
{
    var name = propertyInfo.Name;

    if (!name.StartsWith(PROPERTY))
        return null;

    var number     = name.Substring(PROPERTY.Length);
    int index      = int.Parse(number);
    var properties = CustomProperties;

    if (properties.Count <= index)
        return null;

    return properties[index];
}
```

**Comment by damianrafferty** [comment]
Thanks for that Michael. I will give that a spin and see how it goes.

**Comment by michaelcsikos** [comment]
No worries. If you run into any issues let me know, because I probably faced the same things.
