### ISSUE TITLE
Refactoring question related to combobox in winforms

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#766]
I have a winforms Application and we have combboxes populated from Csla readonly collections.
For instance if you have a combobox for displaying current employees, we set DisplayMember to "EmployeeName" and ValueMember to "EmployeeID".
Nothing wrong with it but I was thinking, since EmployeeName and EmployeeID are both properties of readonly objects contained within the read only collection which is the datasource for this combobox, is there a way to avoid the hard coded strings and use the property names instead?

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms

**Comment by ajj7060** [comment]
I don't think you can do it via the Properties window.  You could in your forms ctor set `DisplayMember/ValueMember = nameof(EmployeeInfo.EmployeeId)`  That will work exactly as typed BTW... even though EmployeeID is an instance member, you can use it in the nameof via the class name.

I think I'd still prefer the properties window method though; that's what I think most other developers would expect.

**Comment by michaelcsikos** [comment]
WinForms hardcodes strings for a lot of these things, including databinding, which is really terrible and can easily cause runtime exceptions when refactoring. With all of our new work, we **don't bind controls through the designer**. We can set up databinding faster and more reliably with code than we can through the properties grid. We have written extension methods for databinding that use CSLA `IPropertyInfo`. For `ComboBox` `Display` and `Value` we also use CSLA property infos whenever possible, e.g.

``` csharp
cboCompany.Display = CompanyInfo.NameProperty.Name;
cboCompany.Value   = CompanyInfo.IdProperty  .Name;
```

**Comment by Chicagoan2016** [comment]
Thanks @ajj7060  (Andy) and @michaelcsikos , you guys are the best.
Kind  Regards
