### ISSUE TITLE
Readonly objects and BusinessRules

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#771]
Although i have never used it but I noticed that in Readonly ojbects we could override AddBusinessRules(), I was wonderinng how could we use Business rules in Readonly objects?

Kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
`ReadOnlyBase` supports authorization rules, specifically for reading properties.

**Comment by Chicagoan2016** [comment]
@rockfordlhotka , Thank you Sir.
Kind regards
