### ISSUE TITLE
Follow-up issue related to #1197 - Undoing a failed save

### ISSUE THREAD

**Issue by GreatBarrier86** [MarimerLLC/cslaforum#773]
In [#1197](https://github.com/MarimerLLC/csla/issues/1197), I described how a failed `ViewModelBase.SaveAsync` caused the Model to be returned with a bad EditLevel. I've run into related problem. If `ViewModelBase.SaveAsync` fails, then the changes have already been committed as part of the `undoable.ApplyEdit`, so `ViewModelBase.DoCancel` does not return it to its prior state. If a `SaveAsync` call fails, and the user decides, for whatever reason, to Cancel and not bother retrying, the object is still in a bad state with its changed values.

Example
1. User has a WidgetsPage, which has a WidgetsViewModel, containing a BusinessListBase of WidgetModels, which are BusinessBase objects.
1. User opens an existing `WidgetModel` inside a `WidgetViewModel`, which is a `ViewModelBase`
2. User changes `WidgetModel.StringValue` from `ABC` to `DEF`
3. User calls the parent list's `WidgetsViewModel.SaveAsync`, which calls the web service.
4. Web service is down, so the user's request times out.
4. User receives a `DataPortalException` back.
5. User decides not to bother editing the object and calls the parent list's `WidgetsViewModel.DoCancel`
6. `WidgetModel` still has a value of `DEF` because ApplyEdit has already been called in `BaseViewModel.SaveAsync`

How would I undo those committed changes so `WidgetModel.StringValue` will be `ABC` again since the save failed and the user wanted to cancel and not bother trying again.

CSLA version: 4.9
OS: iOS, Android
Platform: Xamarin

**Comment by rockfordlhotka** [comment]
Thanks @GreatBarrier86 - sounds like a potential issue, though I wonder if fixing the `SaveAsync` implementation will change this behavior?

In any case, what we need is a failing test added here:
https://github.com/MarimerLLC/csla/blob/master/Source/Csla.test/ViewModelTests/ViewModelTests.cs

**Comment by GreatBarrier86** [comment]
@rockfordlhotka, i honestly don't know what would be best. My thinking is that if `SaveAsync` is responsible for calling `ApplyEdit`, it should be responsible for undoing it. 

My bigger concern is if someone can be undone after `ApplyEdit` is called. Doesn't `UndoEdit` only work as long as nothing has been "commited" with `ApplyEdit`?

**Comment by GreatBarrier86** [comment]
@rockfordlhotka, I've come to the conclusion that this issue and [#1197](https://github.com/MarimerLLC/csla/issues/1197) are issues only if the object being saved does not implement `ICloneable`. If it DOES implement it, then changing the `EditLevel` will occur on the clone and the object that we called `SaveAsync` on will not be affected.

I realized both of these were because of the temporary workaround I did for [#1191](https://github.com/MarimerLLC/csla/issues/1191), which is shown below.
```
        object ICloneable.Clone()
        {
            return this;
        }
```

**Comment by ajj7060** [comment]
@GreatBarrier86 I read your comments in https://github.com/MarimerLLC/csla/issues/1197.  If you're saving the Diary object directly, it seems that your list page should be a ReadOnlyListBase, containing DiaryInfos, which are ReadOnlyBase.  This should resolve the issue with the list being updated even though the save failed.  You can include a method on your DiaryInfo to Refresh from the editable business object instance, and only call it in the even the Diary saves successfully.  The Refresh method can update the DiaryInfo's properties as well as raise appropriate PropertyChanged events, which should be detected by the list view.  

This was the approach we took on a few of our list & edit detail screens, and it seems to work well.

**Comment by GreatBarrier86** [comment]
@ajj7060, can you explain a little more what you mean? I'm slightly lost by your explanation.

**Comment by ajj7060** [comment]
@GreatBarrier86 Basically for your list page I don't think you should be using a BusinessListBase sublcass, especially since you're saving the child BusinessBase object directly (the Diary class).  Make the list page work with a ReadOnlyListBase/ReadOnlyBase, and on the edit page fetch the editable Diary object.  

On the DiaryInfo (the ReadOnlyBase subclass), include a method `public void Refresh(Diary diary)` which will copy the properties from Diary into the DiaryInfo, and then fire OnPropertyChanged events for all the propertys in DiaryInfo which you updated from diary.  

This will resolve your problem where an unsuccessful save still shows the new values the user typed on the Diary edit page b/c of the BeginEdit/ApplyEdit not working correctly, because the list will only get updated when you tell it to.

**Comment by GreatBarrier86** [comment]
@ajj7060, i probably didn't explain it well. I'm not saving children directly. CSLA wouldn't let you do that anyway since they are children of a CSLA list. Basically, when the user presses Save on the detail page, the `DiaryDetailViewModel` calls back to the BusinessListBase (`DiaryList`) to `SaveAsync`.

So, i'm a little lost with what's going on right now. Basically, i was thinking THIS problem was erroneous because of the temporary workaround I mentioned above, which can go away when [#1191](https://github.com/MarimerLLC/csla/issues/1191) is released. But now, according to his most recent response on that one, I'm not confident anymore.

**Comment by ajj7060** [comment]
@GreatBarrier86 Ah, I misunderstood, I didn't catch that you were calling save on the list, not the individual BO, so my suggestion won't work for you.

**Comment by ajj7060** [comment]
@GreatBarrier86 Actually I've been thinking; if you're saving the entire list every time the click Save on a page where they are only editing a single diary, then I think my suggestion would work for you fine.  

The reason to have a root list of editable objects is if you want to enable multiple child objects to be edited and then saved as a batch.  But with your workflow as it is now, the entire list is saved (and thus serialized and deserialized) even though only one object is ever capable of being edited at a time.  That is, you never have two dirty child objects in the list.  And you haven't indicated there's any way to change the state of any objects in the list screen, nor does it seem to be a requirement that two or more diaries must save in a single transaction / unit of work, so the list screen can (probably should be) a readonlylistbase, and the Diary a root editable object, not a child.  

That is the design i would go with for your use case at least, and it would avoid the issue you're having with n-level undo.

**Comment by GreatBarrier86** [comment]
@ajj7060, i think you might be right here. All your assumptions are correct. But in your scenario, what do you suggest I do? Have a ReadOnlyListBase with child ReadOnlyBase objects? I don't like the idea of having to have a ReadOnlyBase Diary and a BusinessBase Diary type. Or are you just suggesting that the BusinessBase diaries live inside the ReadOnlyListBase Diary list?

**Comment by GreatBarrier86** [comment]
@ajj7060 , I've updated to 4.1.11 and it APPEARS that everything is working as i expected it to. I'm going to close this comment since i think we're good to go.

**Comment by ajj7060** [comment]
@GreatBarrier86 For your reference, normally read only objects have Info as the last part of their name, so the RO subclass is DiaryInfo (and the containing read-only list DiaryList), and the editable is Diary, all separate classes in your namespace.  That's the typical naming convention Rocky uses in his books.
