### ISSUE TITLE
Selector business rule

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#781]
I had implemented a selector business rule that called two inner business rule based on
if....else statement.
Now the business process has changed, I need to call the first inner business rule and if it can't verify the business process then call the second inner business rule, so sort of looking at the 'return' value of the inner business rule but we know that the Execute method is a void.

Any suggestions please?
kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by GillesBer** [comment]
Business rule chaining?
http://www.lhotka.net/weblog/CSLA4BusinessRuleChaining.aspx

Gilles


-------- Message d'origine --------
De : Chicagoan2016 <notifications@github.com>
Date : 29/07/2019 18:34 (GMT+01:00)
À : MarimerLLC/cslaforum <cslaforum@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [MarimerLLC/cslaforum] Selector business rule (#781)


I had implemented a selector business rule that called two inner business rule based on
if....else statement.
Now the business process has changed, I need to call the first inner business rule and if it can't verify the business process then call the second inner business rule, so sort of looking at the 'return' value of the inner business rule but we know that the Execute method is a void.

Any suggestions please?
kind regards

Version and Platform
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by Chicagoan2016** [comment]
@GillesBer , I am using Rulechaining but I am not sure if I could somehow use the result return from the first inner rule.

**Comment by jonnybee** [comment]
It is a little special but you could inspect the RuleContext.Result that contains all the added RuleResult for this rule. IE the chaining rule could f.ex check whether the first rule added a RuleResult with severity Error.

**Comment by Chicagoan2016** [comment]
@jonnybee  thank you, I was wondering if the 'Success' property of RuleResult class will help.
after calling (executing) the first inner rule, I can check for 
` if (context.Results.Any(p => p.Success))
                    return;`

in the Selector rule (main outer rule), does 'Success' property indicate the Validation rule validated the property and is not **broken** ?

[https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Shared/Rules/RuleResult.cs](url)

**Comment by jonnybee** [comment]
Won't help. Only the outermost rule should add a Success result (it is optional for sync rules).  The success result indicates that the outermost rule has finished.

**Comment by jonnybee** [comment]
The inner rules - when broken must add RuleResult with either Information, Warning or Error level.

**Comment by Chicagoan2016** [comment]
Thank you @jonnybee , I changed it to
`if (context.Results.Any(p => p.Severity != RuleSeverity.Success))
                    return;`

That way it will capture anything other than Success?

kind regards
