### ISSUE TITLE
Check Business Rules Before Deletion

### ISSUE THREAD

**Issue by fujiiface** [MarimerLLC/cslaforum#782]
**Question**
I don't think I've ever gotten this to work properly.  I'm basically loading up a `BusinessBase` object with data that will always be considered valid.  I want to, upon calling `obj.Delete()`, call business rules that check for other related data to make sure the user is allowed to delete the object.  So if `obj` is being using anywhere in my application, I want the business rule to come back with something like "This record is currently in use.  You are not allowed to delete it."

It appears the problem is that this is only run once and since I am not setting properties on the object, it can never actually be called again.  Any advice on how this should be written?

Here is the old code (not sure it has ever worked as expected)
```
protected override void AddBusinessRules()
{
      //Custom Rules
      BusinessRules.AddRule(new CanDelete());
}

private class CanDelete : BusinessRule
{
      protected override void Execute(IRuleContext context)
      {
          var target = (MyBusinessType)context.Target;

          //This rule will only be applied when the object is set to be deleted.
          if (target.IsDeleted)
          {
              bool isAssigned = true;

              using (var ctx = ContextManager<MyDataContext>.GetManager(Database.DatabaseName))
              {
                  isAssigned = 1; //sql omitted to check if record count is greater than 0
              }

              if (isAssigned)
                  context.AddInformationResult("This record cannot be deleted because it is assigned to one or more departments.  Please see the administrator.");
          }

          context.Complete();
      }
}

//calling code
try
{
    obj.Delete();
    if (SaveObject(obj, true))
    {
        TempData["Success"] = "Obj deleted successfully!";
        return RedirectToAction("Index");    
    }
    
    TempData["Error"] = "An error occurred while deleting the object.  Please try again.";
    ViewData.Model = obj;
    return View();
}
catch (Exception ex)
{
    ModelState.AddModelError("", ex.Message);
    TempData["Error"] = "An error occurred while deleting the object.  System Administrators have been notified.";

    ViewData.Model = obj;
    return View();
}
```

Thanks in advance.

**Version and Platform**
CSLA version: 4.11.1.0 (currently upgrading from 4.7.200)
OS: Windows
Platform: ASP.NET MVC

**Comment by Chicagoan2016** [comment]
@fujiiface , It appears you want to implement concurrency control, if so, I would consider @rockfordlhotka's approach of implementing concurrency, if you look at the Csla samples, its a timestamp field in sql table.

**Comment by fujiiface** [comment]
Thanks @Chicagoan2016.  Off the bat that doesn't seem like it will work for my situation but I'll check out the sample.

**Comment by michaelcsikos** [comment]
The delete will generally be prevented by a foreign key constraint, so the issue is really about how to check and inform the user before attempting the save, thus preventing an ugly error message about violating a foreign key constraint, which means nothing to the user.

For me, deletes are often done via a list of read-only info objects, so implementing a business rule doesn't help. One solution is a simple `Command` which returns the `Count` of the references. In your UI, before attempting to process the delete request, check the count and report if greater than 0: "This widget is used by X other records and can not be deleted." You can use this approach with read-only or editable business objects in a child collection.

**Comment by fujiiface** [comment]
@michaelcsikos You’re absolutely correct about the constraint and check.  There may be parts of the database that still require constraints (original developer didn’t believe in putting them in and I had to put them in on the main objects a few years ago).

I’ll probably end up putting your suggestion into place but I’m curious how I can get the rule to run if a property isn’t explicitly changed.  This code was originally written in a way that overrides IsValid to explicitly call BusinessRules.CheckRules();.  Then, before the delete operation, instead of using SaveObject(obj,true) we would just check obj.IsValid and the rules would be checked again.  This has never felt right to me because it felt (and still feels) like a hack from when the code was originally written but maybe I’m wrong about that.

**Comment by michaelcsikos** [comment]
The other side of the coin is if an object is marked for deletion, you could argue that it doesn't matter if there are broken rules.

I would probably approach this by defining a property like `CanBeDeleted` and override `Delete()`. If `!CanBeDeleted` then return without calling `base.Delete()`. In the UI you can make this neater by disabling the option to delete an object that is already in use (or display a message, etc), but at least you know the business layer will prevent it in any case.

**Comment by ChristopherFujii-ISD** [comment]
Thanks for the suggestions @michaelcsikos.  I ended up just using the foreign key for now.  Turns out there was one missing so adding it resolved the issue.

**Comment by fujiiface** [comment]
Thanks for the suggestions @michaelcsikos. I ended up just using the foreign key for now. Turns out there was one missing so adding it resolved the issue.
