### ISSUE TITLE
HttpProxy sync calls

### ISSUE THREAD

**Issue by JacoJordaan** [MarimerLLC/cslaforum#784]
**Question**
Is the HttpProxy supporting sync calls included in the last stable release of 4.11.1 or do we need wait for release 5.0?

**Version and Platform**
CSLA version: 4.11.100
OS: Windows, Linux
Platform:  WPF, ASP.NET Core

**Comment by rockfordlhotka** [comment]
I only applied the changes to the v5 codebase.
