### ISSUE TITLE
What to use since BusinessListBase does not have RegisterProperty

### ISSUE THREAD

**Issue by GreatBarrier86** [MarimerLLC/cslaforum#787]
**Question**
I have a backing field in my `BusinessListBase` that is of type `MobileList<MyClass>`, where `MyClass` is `BusinessBase<MyClass>`. I want to be able to send this data over during serialization/deserialization, but `BusinessListBase` does not offer a `RegisterProperty` function like `BusinessBase` does.

Given this, what is the recommended solution for serializing this since this backing field is a `MobileList<MyClass>` and not a primitive type. Would using `OnGetChildren/OnSetChildren` be the most appropriate? Is there some sort of `BusinessListBase` equivalent to `RegisterProperty`?

Rocky's link about [CSLA Light serialization implementation](http://www.lhotka.net/weblog/CSLALightSerializationImplementation.aspx) indicates he considers this an "edge-case" scenario, so i was curious about the most appropriate design.

Thanks,
Jason

**Version and Platform**
CSLA version: 4.11.2
OS: Windows
Platform: ASP.NET Core

**Comment by rockfordlhotka** [comment]
Having properties in a list is still considered an edge case in my mind.

The solution is as you suggest: override the `OnGetChildren` and `OnSetChildren` methods to put/get the child value(s) in the serialization stream.

For example, in `OnGetChildren` the code looks like:

```c#
            SerializationInfo childInfo = formatter.SerializeObject(childObject);
            info.AddChild("ChildName", childInfo.ReferenceId, data.IsDirty);
```
And in `OnSetChildren` the code looks like:

```c#
          SerializationInfo.ChildData childData = info.Children["ChildName"];
          childObject = formatter.GetObject(childData.ReferenceId);
```

**Comment by GreatBarrier86** [comment]
Great. As long as that's the right method, I'm good! Thanks, @rockfordlhotka.

**Comment by GreatBarrier86** [comment]
Here's my abstract implementation of it since i'll need to use it in multiple list classes. Any reason why this would be a poor idea?


        IEnumerable<MemberInfo> GetAdditionalSerialzationStreamMembers()
        {
            Type type = GetType();
            BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.FlattenHierarchy;

            MemberInfo[] properties = type.GetProperties(flags);
            MemberInfo[] fields = type.GetFields(flags);

            return properties.Union(fields).Where(p => p.GetCustomAttribute<IncludeInGetSetChildrenAttribute>() != null);
        }

        protected override void OnGetChildren(SerializationInfo info, MobileFormatter formatter)
        {
            Type type = GetType();

            foreach (MemberInfo member in GetAdditionalSerialzationStreamMembers())
            {
                object objToGet = null;

                if (member is PropertyInfo pi)
                {
                    objToGet = pi.GetValue(this, null);
                }
                else
                {
                    objToGet = ((FieldInfo)member).GetValue(this);
                }

                SerializationInfo objInfo = formatter.SerializeObject(objToGet);
                info.AddChild(member.Name, objInfo.ReferenceId);
            }

            base.OnGetChildren(info, formatter);
        }

        protected override void OnSetChildren(SerializationInfo info, MobileFormatter formatter)
        {
            foreach (MemberInfo member in GetAdditionalSerialzationStreamMembers())
            {
                string name = member.Name;
                if (info.Children.ContainsKey(name))
                {
                    int referenceId = info.Children[name].ReferenceId;
                    object val = formatter.GetObject(referenceId);

                    if (member is PropertyInfo pi)
                    {
                        pi.SetValue(this, val);
                    }
                    else
                    {
                        ((FieldInfo)member).SetValue(this, val);
                    }
                }
            }

            base.OnSetChildren(info, formatter);
        }
