### ISSUE TITLE
Design Question

### ISSUE THREAD

**Issue by bashinamwila** [MarimerLLC/cslaforum#793]
We have a simple object with properties  Id (string),Name (string) and Amount (double).However the complexity arises from the value of Amount Property is determined by other properties which for now I will call Variables(a,b,c,d) all of type double.These Variables are known in advance but what is not known is is the combination in which the user will use at runtime

One user might define the value of the amount property to be (a+b)*c,another user might define the value of amount property as a+b and other user might define the value of the amount property as b*d
We has explored the following
1)Dynamic Properties for the properties a,b,c and d (though there is little guidance on how to implement these in CSLA.NET)
2)Create a child list object for the object and add child of objects for a,b,c,d depending on how the user defines the formulae of the amount property on creation object add the child objects (similar to SmartDate Object in CSLA.NET) defined
Another complication arises from the fact some objects will use the value of the amount of another object in the object graph. 

Are we on the right track in our line of thought or is there a better way we can solve this problem in CSLA.NET

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by michaelcsikos** [comment]
If the `Amount` property is calculated, it only needs a `get` and doesn't require a managed backing field. It doesn't matter how complicated the formula is, or how it's derived. "Don't store what you can calculate" is a pretty common guideline in software and databases.

**Comment by Chicagoan2016** [comment]
@bashinamwila , I am assuming two things here.
1) Variables a, b, c, ,d  are entered by the user and the number of a,b, c, d are fixed, in this example four.
2) 'Definition' of 'amount' such as 'a+b', 'bd' is also entered the by user. 
  I would implement this  as business rule.

If the number of a, b, c, d is not fixed, you might want to look into a  child collection for a,b,c........


regards

**Comment by bashinamwila** [comment]
@Chicagoan2016 thanks for your response.Could kindly give us an  example on how  we could implement this business rule.Your assumption that the variables are fixed is true and they are entered by the user but what is not certain in what combination the user will enter/use the variable.Many thanks

**Comment by Chicagoan2016** [comment]
@bashinamwila , I was busy and just saw this.
Based on the example you have given,
1) There are four variables i.e, a, b, c and d.
2) The 'definition' of the amount expressed in terms of a, b, c and d is also provided by the user.
    so you could have something like the following
       Amount = a+b  or
       Amount = bd  or 
      Amount = (a+b)c 
      etc.

It appears you need at least two variables to calculate Amount, I would make two variables to the method calculating Amount required and the other two variables optional.
  
look at the example in 'Creating business objects' book and also the business rule tutorial available with csla download.

**Comment by bashinamwila** [comment]
@Chicagoan2016 thanks again for you response I know how to write business rules in CSLA.NET but my question how do variables are assigned to the object.Should we use child objects or dynamic properties.We would be appreciate if you can resolve on how we should design our object many thanks

**Comment by rockfordlhotka** [comment]
So values a, b, c, and d may or may not exist at all? The user adds these values at runtime through some sort of UI?

If there are 4 and only ever 4 then I'd implement them as nullable properties (`double?`) - otherwise I'd create a child list for them.

**Comment by bashinamwila** [comment]
Thanks @rockfordlhotka  and @Chicagoan2016  for your answers
