### ISSUE TITLE
OnChildChanged with ListChangedType.ItemDeleted in Parent

### ISSUE THREAD

**Issue by lupanmarian** [MarimerLLC/cslaforum#796]
**Question**
Dear Rocky And all members

**I started to update my business objecs with csla 3.6 from 3.0.5. I was very excited about  overriding OnChildChanged in editable parent in order to change a parent property when an item is added or removed in my child collection:**

  Private Shared AmbulatoriuConsultatiiServiciiProperty As PropertyInfo(Of Ambulatoriu_ConsultatieServiciu___S) = RegisterProperty(New PropertyInfo(Of Ambulatoriu_ConsultatieServiciu___S)("AmbulatoriuConsultatiiServicii"))
  Public ReadOnly Property AmbulatoriuConsultatiiServicii() As Ambulatoriu_ConsultatieServiciu___S
    Get
      If Not (FieldManager.FieldExists(AmbulatoriuConsultatiiServiciiProperty)) Then
        LoadProperty(AmbulatoriuConsultatiiServiciiProperty, Ambulatoriu_ConsultatieServiciu___S.NewChildren())
      End If
      Return GetProperty(AmbulatoriuConsultatiiServiciiProperty)
    End Get
  End Property 

**All is nice about item adding.**

**BUT:**

**When I removed an item from Telerik grid I'm receiving an error if i keep PropertyHasChanged call:**
  Protected Overrides Sub OnChildChanged(e As ChildChangedEventArgs)
    If TypeOf (e.ChildObject) Is Ambulatoriu_ConsultatieServiciu___S Then
      If e.ListChangedArgs.ListChangedType = ComponentModel.ListChangedType.ItemAdded OrElse e.ListChangedArgs.ListChangedType = ComponentModel.ListChangedType.ItemDeleted Then
        PropertyHasChanged("NuExistaConsultatiiServicii")
      End If
    End If
    MyBase.OnChildChanged(e)
  End Sub

Error is: 
"Index was out of range. Must be non-negative and less than the size of the collection." & vbCrLf & "Parameter name: index"

Stack trace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Telerik.WinControls.Data.RadListSource`1.get_Item(Int32 index)
   at Telerik.WinControls.Data.RadListSource`1.RemoveItem(Int32 index)
   at Telerik.WinControls.Data.RadListSource`1.currencyManager_ListChanged(Object sender, ListChangedEventArgs e)
   at System.Windows.Forms.CurrencyManager.OnListChanged(ListChangedEventArgs e)
   at System.Windows.Forms.CurrencyManager.List_ListChanged(Object sender, ListChangedEventArgs e)
   at System.Windows.Forms.BindingSource.OnListChanged(ListChangedEventArgs e)
   at System.Windows.Forms.BindingSource.InnerList_ListChanged(Object sender, ListChangedEventArgs e)
   at System.ComponentModel.ListChangedEventHandler.Invoke(Object sender, ListChangedEventArgs e)
   at System.ComponentModel.BindingList`1.OnListChanged(ListChangedEventArgs e)
   at Csla.BusinessListBase`2.RemoveItem(Int32 index) in C:\Marian\eLogin\eLogin_Spital2020\CSLA3.6\cslacs\Csla\BusinessListBase.cs:line 512
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at System.Collections.ObjectModel.Collection`1.System.Collections.IList.Remove(Object value)
   at System.Windows.Forms.BindingSource.Remove(Object value)
   at Telerik.WinControls.Data.RadListSource`1.RemoveAt(Int32 index)
   at Telerik.WinControls.UI.GridViewRowCollection.RemoveAt(Int32 index, Boolean selectCurrentRow)
   at Telerik.WinControls.UI.GridViewRowCollection.Remove(GridViewRowInfo item, Boolean selectCurrentRow)
   at Telerik.WinControls.UI.GridViewRowCollection.Remove(GridViewRowInfo item)
   at Telerik.WinControls.UI.BaseGridNavigator.DeleteSelectedRows()
   at Telerik.WinControls.UI.GridDataRowElement.ItemDelete_Click(Object sender, EventArgs e)
   at Telerik.WinControls.RadElement.OnClick(EventArgs e)
   at Telerik.WinControls.UI.RadButtonItem.OnClick(EventArgs e)
   at Telerik.WinControls.UI.RadMenuItem.OnClick(EventArgs e)
   at Telerik.WinControls.RadElement.DoClick(EventArgs e)
   at Telerik.WinControls.RadElement.RaiseBubbleEvent(RadElement sender, RoutedEventArgs args)
   at Telerik.WinControls.RadItem.RaiseBubbleEvent(RadElement sender, RoutedEventArgs args)
   at Telerik.WinControls.RadElement.RaiseRoutedEvent(RadElement sender, RoutedEventArgs args)
   at Telerik.WinControls.RadElement.DoMouseUp(MouseEventArgs e)
   at Telerik.WinControls.RadElement.CallDoMouseUp(MouseEventArgs e)
   at Telerik.WinControls.ComponentInputBehavior.OnMouseUp(MouseEventArgs e)
   at Telerik.WinControls.RadControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at Telerik.WinControls.RadControl.WndProc(Message& m)
   at Telerik.WinControls.UI.RadPopupControlBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at eLoginHospital2020.modMain.Main() in C:\Marian\eLogin\eLogin_Spital2020\eLoginHospital2020_UI\modMain.vb:line 386

Error apears for any item from my collection,

I'm trying for 2 days to find the reason: my business objects, telerik grid or csla bug.

Can someone help me, please?

**Version and Platform**
CSLA version: 3.6
OS: Windows
Platform: WinForms

**Comment by lupanmarian** [comment]
Still I didn't have an answer.
I added parts of root object, editable collection and child object:

**root object**
<Serializable()> _
Public Class Ambulatoriu
  Inherits BusinessBase(Of Ambulatoriu)
........,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

  Public ReadOnly Property NuExistaConsultatiiServicii() As Boolean
    Get
      Return (ReadProperty(AmbulatoriuConsultatiiServiciiProperty).Count = 0)
    End Get
  End Property

  Private Shared AmbulatoriuConsultatiiServiciiProperty As PropertyInfo(Of Ambulatoriu_ConsultatieServiciu___S) = RegisterProperty(New PropertyInfo(Of Ambulatoriu_ConsultatieServiciu___S)("AmbulatoriuConsultatiiServicii"))
  Public ReadOnly Property AmbulatoriuConsultatiiServicii() As Ambulatoriu_ConsultatieServiciu___S
    Get
      If Not (FieldManager.FieldExists(AmbulatoriuConsultatiiServiciiProperty)) Then
        LoadProperty(AmbulatoriuConsultatiiServiciiProperty, Ambulatoriu_ConsultatieServiciu___S.NewChildren())
      End If
      Return GetProperty(AmbulatoriuConsultatiiServiciiProperty)
    End Get
  End Property

  Protected Overrides Sub OnChildChanged(e As ChildChangedEventArgs)
    MyBase.OnChildChanged(e)
    If TypeOf (e.ChildObject) Is Ambulatoriu_ConsultatieServiciu___S Then
      If e.ListChangedArgs.ListChangedType = ComponentModel.ListChangedType.ItemAdded OrElse e.ListChangedArgs.ListChangedType = ComponentModel.ListChangedType.ItemDeleted Then
        PropertyHasChanged("NuExistaConsultatiiServicii")
      End If
    End If
  End Sub

**editable collection**:
<Serializable()> _
Public Class Ambulatoriu_ConsultatieServiciu___S
  Inherits BusinessListBase(Of Ambulatoriu_ConsultatieServiciu___S, Ambulatoriu_ConsultatieServiciu)

#Region " Business Methods "
  Protected Overrides Function AddNewCore() As Object
    Dim item As Ambulatoriu_ConsultatieServiciu = Ambulatoriu_ConsultatieServiciu.NewChild
    Add(item)
    Return item
  End Function

  Public Function GetItem(ByVal pIdLinie As Integer) As Ambulatoriu_ConsultatieServiciu
    For Each item As Ambulatoriu_ConsultatieServiciu In Me
      If item.IdLinie = pIdLinie Then
        Return item
      End If
    Next
    Return Nothing
  End Function

  Public Overloads Sub Remove(ByVal pIdLinie As Integer)
    For Each item As Ambulatoriu_ConsultatieServiciu In Me
      If item.IdLinie = pIdLinie Then
        Remove(item)
        Exit For
      End If
    Next
  End Sub

  Public Overloads Function Contains(ByVal pIdLinie As Integer) As Boolean
    For Each item As Ambulatoriu_ConsultatieServiciu In Me
      If item.IdLinie = pIdLinie Then
        Return True
      End If
    Next
    Return False
  End Function

  Public Overloads Function ContainsDeleted(ByVal pIdLinie As Integer) As Boolean
    For Each item As Ambulatoriu_ConsultatieServiciu In DeletedList
      If item.IdLinie = pIdLinie Then
        Return True
      End If
    Next
    Return False
  End Function
#End Region

#Region " Factory methods "
  Friend Shared Function NewChildren() As Ambulatoriu_ConsultatieServiciu___S
    Return DataPortal.CreateChild(Of Ambulatoriu_ConsultatieServiciu___S)() 
  End Function

  Friend Shared Function GetChildren(ByVal dr As SafeDataReader) As Ambulatoriu_ConsultatieServiciu___S
    Return DataPortal.FetchChild(Of Ambulatoriu_ConsultatieServiciu___S)(dr) 
  End Function

  Private Sub New()
    'require use of factory methods
    AllowNew = True
  End Sub
#End Region

#Region " Data Access "
  Private Sub Child_Fetch(ByVal dr As SafeDataReader)
    Me.RaiseListChangedEvents = False
    While dr.Read()
      Me.Add(Ambulatoriu_ConsultatieServiciu.GetChild(dr))
    End While
    Me.RaiseListChangedEvents = True
  End Sub
#End Region
End Class

**child object**:
<Serializable()>
Public Class Ambulatoriu_ConsultatieServiciu
  Inherits BusinessBase(Of Ambulatoriu_ConsultatieServiciu)

  Private Shared mLastId As Integer

#Region " Business methods "
  Private Shared IdLinieProperty As PropertyInfo(Of Integer) = RegisterProperty(New PropertyInfo(Of Integer)("IdLinie"))
  <System.ComponentModel.DataObjectField(True, True)>
  Public ReadOnly Property IdLinie() As Integer
    Get
      Return GetProperty(IdLinieProperty)
    End Get
  End Property

  Private Shared IdAmbulatoriuProperty As PropertyInfo(Of Integer) = RegisterProperty(New PropertyInfo(Of Integer)("IdAmbulatoriu"))
  Public Property IdAmbulatoriu() As Integer
    Get
      Return GetProperty(IdAmbulatoriuProperty)
    End Get
    Set(ByVal Value As Integer)
      SetProperty(IdAmbulatoriuProperty, Value)
    End Set
  End Property

  Private Shared IdConsultatieServiciuProperty As PropertyInfo(Of Integer) = RegisterProperty(New PropertyInfo(Of Integer)("IdConsultatieServiciu"))
  Public Property IdConsultatieServiciu() As Integer
    Get
      Return GetProperty(IdConsultatieServiciuProperty)
    End Get
    Set(ByVal Value As Integer)
      SetProperty(IdConsultatieServiciuProperty, Value)
    End Set
  End Property

  Private Shared CodProperty As PropertyInfo(Of String) = RegisterProperty(New PropertyInfo(Of String)("Cod"))
  Public Property Cod() As String
    Get
      Return GetProperty(CodProperty)
    End Get
    Set(ByVal value As String)
      SetProperty(CodProperty, value)
    End Set
  End Property

  Private Shared DenumireProperty As PropertyInfo(Of String) = RegisterProperty(New PropertyInfo(Of String)("Denumire"))
  Public Property Denumire() As String
    Get
      Return GetProperty(DenumireProperty)
    End Get
    Set(ByVal value As String)
      SetProperty(DenumireProperty, value)
    End Set
  End Property
#End Region

#Region " Validation Rules"
  Protected Overrides Sub AddBusinessRules()
    ValidationRules.AddRule(Of Ambulatoriu_ConsultatieServiciu)(AddressOf IdConsultatieServiciu_Corect(Of Ambulatoriu_ConsultatieServiciu), "Cod")
  End Sub

  Private Shared Function IdConsultatieServiciu_Corect(Of T As Ambulatoriu_ConsultatieServiciu)(ByVal target As T, ByVal e As Validation.RuleArgs) As Boolean
    If target.IdConsultatieServiciu = 0 Then
      e.Description = "Consultatie | serviciu nespecificata."
      Return False
    Else
      Return True
    End If
  End Function
#End Region

#Region " Factory methods "
  Friend Shared Function NewChild() As Ambulatoriu_ConsultatieServiciu
    Return DataPortal.CreateChild(Of Ambulatoriu_ConsultatieServiciu)()
  End Function

  Friend Shared Function GetChild(ByVal dr As SafeDataReader) As Ambulatoriu_ConsultatieServiciu
    Return DataPortal.FetchChild(Of Ambulatoriu_ConsultatieServiciu)(dr)
  End Function

  Private Sub New()
    ' require use of factory methods
    MyBase.DisableIEditableObject = True
  End Sub
#End Region

#Region " Data access "
  Protected Overrides Sub Child_Create()
    LoadProperty(IdLinieProperty, mLastId - 1)
    mLastId = ReadProperty(IdLinieProperty)

    LoadProperty(CantitateProperty, 1)
    LoadProperty(IdStareRecordProperty, 1)

    MyBase.Child_Create()
  End Sub

  Private Sub Child_Fetch(ByVal dr As SafeDataReader)
    With dr
      LoadProperty(IdLinieProperty, .GetInt32("IdLinie"))
      LoadProperty(IdAmbulatoriuProperty, .GetInt32("IdAmbulatoriu"))
      LoadProperty(IdConsultatieServiciuProperty, .GetInt32("IdConsultatieServiciu"))
      LoadProperty(CodProperty, .GetString("Cod"))
      LoadProperty(DenumireProperty, .GetString("Denumire"))
    End With
  End Sub

  Private Sub Child_Insert(ByVal pAmbulatoriu As Ambulatoriu)
    Dim cn As SqlConnection = DirectCast(ApplicationContext.LocalContext("cn"), SqlConnection)

    Using cm As SqlCommand = cn.CreateCommand
      cm.CommandText = "Ambulatoriu_ConsultatiiServicii_Insert"
      LoadProperty(IdAmbulatoriuProperty, pAmbulatoriu.IdAmbulatoriu)
      cm.Parameters.AddWithValue("@IdUtilizator", pAmbulatoriu.IdUtilizator)
      DoInsertUpdate(cm)
    End Using
  End Sub

  Private Sub Child_Update(ByVal pAmbulatoriu As Ambulatoriu)
    Dim cn As SqlConnection = DirectCast(ApplicationContext.LocalContext("cn"), SqlConnection)

    Using cm As SqlCommand = cn.CreateCommand
      cm.CommandText = "Ambulatoriu_ConsultatiiServicii_Update"
      LoadProperty(IdAmbulatoriuProperty, pAmbulatoriu.IdAmbulatoriu)
      cm.Parameters.AddWithValue("@IdUtilizator", pAmbulatoriu.IdUtilizator)
      DoInsertUpdate(cm)
      If ReadProperty(ActiuneDocumentePentruValidareProperty) Then
        TransferInDocumentePentruValidare(ReadProperty(InDocumentePentruValidareProperty))
        LoadProperty(ActiuneDocumentePentruValidareProperty, False)
      End If
    End Using
  End Sub

  Private Sub Child_DeleteSelf(ByVal pAmbulatoriu As Ambulatoriu)
    Dim cn As SqlConnection = DirectCast(ApplicationContext.LocalContext("cn"), SqlConnection)

    Using cm As SqlCommand = cn.CreateCommand
      cm.CommandText = "Ambulatoriu_ConsultatiiServicii_Delete"
      cm.CommandType = CommandType.StoredProcedure
      cm.Parameters.AddWithValue("@IdAmbulatoriuConsultatieServiciu", ReadProperty(IdLinieProperty))
      cm.Parameters.AddWithValue("@IdUtilizator", pAmbulatoriu.IdUtilizator)
      cm.ExecuteNonQuery()
    End Using
  End Sub

  Private Sub DoInsertUpdate(ByVal cm As SqlCommand)
    With cm
      .CommandType = CommandType.StoredProcedure

      If Me.IsNew Then
        Dim paramIdLinie As New SqlParameter("@IdAmbulatoriuConsultatieServiciu", SqlDbType.Int)
        paramIdLinie.Direction = ParameterDirection.Output
        .Parameters.Add(paramIdLinie)
      Else
        .Parameters.AddWithValue("@IdAmbulatoriuConsultatieServiciu", ReadProperty(IdLinieProperty))
      End If

      .Parameters.AddWithValue("@IdAmbulatoriu", ReadProperty(IdAmbulatoriuProperty))
      .Parameters.AddWithValue("@IdConsultatieServiciu", ReadProperty(IdConsultatieServiciuProperty))

      .ExecuteNonQuery()

      If Me.IsNew Then
        LoadProperty(IdLinieProperty, CType(.Parameters("@IdAmbulatoriuConsultatieServiciu").Value, Integer))
      End If
    End With
  End Sub
#End Region

End Class

**Comment by lupanmarian** [comment]
The problem seems to be **PropertyHasChanged("NuExistaConsultatiiServicii")**. Without this line of code there is not any error.

But still I need to know when collection remains without items, in order to use this property on databinding on enable property for some controls.

If it will be any help it will be fantastic.

Thanks to all,

Marian

**Comment by michaelcsikos** [comment]
I would start by do a test using a standard `DataGridView` and `BindingSource` to rule out the Telerik grid as the problem.

**Comment by michaelcsikos** [comment]
Actually, try changing `PropertyHasChanged("NuExistaConsultatiiServicii")` to `OnPropertyChanged("NuExistaConsultatiiServicii")` You should only need `OnPropertyChanged` to notify bound controls to re-read the value of the property.

**Comment by lupanmarian** [comment]
Thanks Michael,

I tried imediatelly after the error. Is the same error. Without PropertyHasChanged | On PropertyChanged all is fine, but i' cant disable with binding on enanled property some ui controls. 
Stil nice If i'm checking ValidationRules.CheckRules(propertyName), but this doesn't help me.

Marian

**Comment by michaelcsikos** [comment]
It still throws with only `OnPropertyChanged`?

**Comment by lupanmarian** [comment]
with any of them:
- PropertyHasChanged
or 
- On PropertyChanged

Tkanks for your implication.

Marian

**Comment by lupanmarian** [comment]
I'm tired,

Still the same error!. 

I started a new project with CSLA0 4.0, I checked Rocky books for csla 4.0, once again, I've made a lot of changes regarding business validation etc. and... NOTHING.

Even worst! Ading rows directly in grid raised a new error. I changed base class in collection to BusinessBindingListBase and i addeed new child using Bindingsource.AdingNew event in UI, because AddNewCore was dead.

How can I find a solution for deleting row and call PropertyHasChanged? I don't know yet.

So.....tomorrow is another day for debugging.

Any advice is welcome!

Thanks,
Marian

**Comment by lupanmarian** [comment]
whai i found it today:

OnChildChanged in parent is executed successfully:

  Protected Overrides Sub OnChildChanged(e As ChildChangedEventArgs)
    If TypeOf (e.ChildObject) Is Ambulatoriu_ConsultatieServiciu___S Then
      If e.ListChangedArgs.ListChangedType = ComponentModel.ListChangedType.ItemAdded OrElse e.ListChangedArgs.ListChangedType = ComponentModel.ListChangedType.ItemDeleted Then
        PropertyHasChanged("NuExistaConsultatiiServicii")
      End If
    End If
    MyBase.OnChildChanged(e)
  End Sub
After that execution continues in businessbase,cs:

    /// <summary>
    /// Creates a ChildChangedEventArgs and raises the event.
    /// </summary>
    private void RaiseChildChanged(
      object childObject, PropertyChangedEventArgs propertyArgs, ListChangedEventArgs listArgs)
    {
      ChildChangedEventArgs args = new ChildChangedEventArgs(childObject, propertyArgs, listArgs);
      **OnChildChanged**(args);
    }
....
    /// <summary>
    /// Handles any ListChanged event from 
    /// a child list and echoes it up as
    /// a ChildChanged event.
    /// </summary>
    private void Child_ListChanged(object sender, ListChangedEventArgs e)
    {
      if(e.ListChangedType != ListChangedType.ItemChanged)
        **RaiseChildChanged**(sender, null, e);
    }

And here is stopped.

**Comment by lupanmarian** [comment]
Dear Rocky,

I missed you!

1. One thing that's important (and you may already have seen this) is that you must use BusinessBindingListBase instead of BusinessListBase when working with Windows Forms.

I created a new project using CSLA4.0 and replace BusinessListBase with BusinessBindingListBase. The same error on removing items from grid, with delete key. I need to do this because adding new row directly in grid. CSLA 3.6 doesn't implement BusinessBindingListBase.

I want to use CSLA 3.6, that version of csla that starts to implement OnChildChanged.

2. Also, you need to make sure to set the CSLA property changed mode to Windows as your app starts up, otherwise CSLA uses the newer way of raising PropertyChanged events, which is not ideal for WinForms.

Do you means to CslaAuthentication in app.config, appSettings?
Im using now <add key="CslaAuthentication" value="CSLA" />.

Best regards!
O started to use csla with comexpress, janus ui and VB.6. Only CSLA grows these years! Fantastic job.

Marian

**Comment by lupanmarian** [comment]
"Also, you need to make sure to set the CSLA property changed mode to Windows as your app starts up, otherwise CSLA uses the newer way of raising PropertyChanged events, which is not ideal for WinForms."
Sory for my previously message. I didn't catch your sugestion.

I will add Csla.ApplicationContext.PropertyChangedMode =
Csla.ApplicationContext.PropertyChangedModes.Windows at the begining of application. 
I can't run the project now but I will do it asap.

Thank you

**Comment by lupanmarian** [comment]
It;s wotking perfect with Janus grid, Evem with BusinessListBase! It's not working with Microsoft datagridview and telerik gridview.
