### ISSUE TITLE
BusinessRules not executed.

### ISSUE THREAD

**Issue by jchabot1979** [MarimerLLC/cslaforum#8]
Here's my code. In my BusinessObject, I set the Door propertie. It loads my 2 default color and then their BaseUnitPriceProperties with businessRules. My Glazing property is set by a businessRule when the Door is changes and then the GlazingBaseUnitPrice. The Glass property is changed by the Glazing 
with another Rules, but the Rules that changes the GlassBaseUnitPrice is never called when setting the Door property. Only when I manually call the Setter of the Glazing property. Why?? It seems that only 2 layers of Rules are executed. Here's my code.

using Csla;
using Csla.Core;
using Csla.Rules;
using Csla.Rules.CommonRules;
using PortesDecko.BusinessObjects.MF_MasterFile;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace PortesDecko.BusinessObjects.SO_SalesOrder
{
    [Serializable]
    public class DoorDetail : Base.CORE.BusinessObjects.CustomBusinessBase<DoorDetail>
    {
        public DoorDetail() : base() { /* Require use of factory methods */ }

        #region Properties

        #region Root Properties

        public static readonly PropertyInfo<MF_Product.LightBusinessObjects.viewProductDoor> DoorProperty = RegisterProperty<MF_Product.LightBusinessObjects.viewProductDoor>(c => c.Door);
        public MF_Product.LightBusinessObjects.viewProductDoor Door
        {
            get { return GetProperty(DoorProperty); }
            set { SetProperty(DoorProperty, value); }
        }

        public static readonly PropertyInfo<decimal?> DoorBaseUnitPriceProperty = RegisterProperty<decimal?>(c => c.DoorBaseUnitPrice);
        public decimal? DoorBaseUnitPrice
        {
            get { return GetProperty(DoorBaseUnitPriceProperty); }
            set { SetProperty(DoorBaseUnitPriceProperty, value); }
        }

        public static readonly PropertyInfo<MF_MasterFile.LightBusinessObjects.Dimension> DoorHeightDimensionProperty = RegisterProperty<MF_MasterFile.LightBusinessObjects.Dimension>(c => c.DoorHeightDimension);
        public MF_MasterFile.LightBusinessObjects.Dimension DoorHeightDimension
        {
            get { return GetProperty(DoorHeightDimensionProperty); }
            set { SetProperty(DoorHeightDimensionProperty, value); }
        }

        public static readonly PropertyInfo<MF_MasterFile.LightBusinessObjects.Dimension> DoorWidthDimensionProperty = RegisterProperty<MF_MasterFile.LightBusinessObjects.Dimension>(c => c.DoorWidthDimension);
        public MF_MasterFile.LightBusinessObjects.Dimension DoorWidthDimension
        {
            get { return GetProperty(DoorWidthDimensionProperty); }
            set { SetProperty(DoorWidthDimensionProperty, value); }
        }

        public static readonly PropertyInfo<MF_Product.LightBusinessObjects.viewProductColor> OutdoorColorProperty = RegisterProperty<MF_Product.LightBusinessObjects.viewProductColor>(c => c.OutdoorColor);
        public MF_Product.LightBusinessObjects.viewProductColor OutdoorColor
        {
            get { return GetProperty(OutdoorColorProperty); }
            set { SetProperty(OutdoorColorProperty, value); }
        }

        public static readonly PropertyInfo<decimal?> OutdoorColorBaseUnitPriceProperty = RegisterProperty<decimal?>(c => c.OutdoorColorBaseUnitPrice);
        public decimal? OutdoorColorBaseUnitPrice
        {
            get { return GetProperty(OutdoorColorBaseUnitPriceProperty); }
            set { SetProperty(OutdoorColorBaseUnitPriceProperty, value); }
        }

        public static readonly PropertyInfo<MF_Product.LightBusinessObjects.viewProductColor> IndoorColorProperty = RegisterProperty<MF_Product.LightBusinessObjects.viewProductColor>(c => c.IndoorColor);
        public MF_Product.LightBusinessObjects.viewProductColor IndoorColor
        {
            get { return GetProperty(IndoorColorProperty); }
            set { SetProperty(IndoorColorProperty, value); }
        }

        public static readonly PropertyInfo<decimal?> IndoorColorBaseUnitPriceProperty = RegisterProperty<decimal?>(c => c.IndoorColorBaseUnitPrice);
        public decimal? IndoorColorBaseUnitPrice
        {
            get { return GetProperty(IndoorColorBaseUnitPriceProperty); }
            set { SetProperty(IndoorColorBaseUnitPriceProperty, value); }
        }

        public static readonly PropertyInfo<MF_Product.LightBusinessObjects.viewProductGlazing> GlazingProperty = RegisterProperty<MF_Product.LightBusinessObjects.viewProductGlazing>(c => c.Glazing);
        public MF_Product.LightBusinessObjects.viewProductGlazing Glazing
        {
            get { return GetProperty(GlazingProperty); }
            set { SetProperty(GlazingProperty, value); }
        }

        public static readonly PropertyInfo<decimal?> GlazingBaseUnitPriceProperty = RegisterProperty<decimal?>(c => c.GlazingBaseUnitPrice);
        public decimal? GlazingBaseUnitPrice
        {
            get { return GetProperty(GlazingBaseUnitPriceProperty); }
            set { SetProperty(GlazingBaseUnitPriceProperty, value); }
        }

        public static readonly PropertyInfo<MF_Product.LightBusinessObjects.viewProductGlass> GlassProperty = RegisterProperty<MF_Product.LightBusinessObjects.viewProductGlass>(c => c.Glass);
        public MF_Product.LightBusinessObjects.viewProductGlass Glass
        {
            get { return GetProperty(GlassProperty); }
            set { SetProperty(GlassProperty, value); }
        }

        public static readonly PropertyInfo<decimal?> GlassBaseUnitPriceProperty = RegisterProperty<decimal?>(c => c.GlassBaseUnitPrice);
        public decimal? GlassBaseUnitPrice
        {
            get { return GetProperty(GlassBaseUnitPriceProperty); }
            set { SetProperty(GlassBaseUnitPriceProperty, value); }
        }

        #endregion

        #region Localized Properties

        private long _CustomerID;
        public long CustomerID
        {
            get { return _CustomerID; }
            set { _CustomerID = value; }
        }

        #endregion

        #endregion

        #region Search Functions

        #endregion

        #region DataPortal Functions

        internal class DataPortal_FetchArgs
        {
            public string DefaultCollection { get; set; }
            public Models.MF_Product.Height Model { get; set; }
        }
        internal interface ISearchCriteria
        {
            string Collation { get; set; }
            Expression<Func<Models.MF_Product.Height, bool>> GetWhereExpression();
        }
        internal static Base.CORE.DataLayer.IDbContextBase DomainDrivenDesignBoundedContext
        {
            get { return new DataLayer.EnterpriseResourcePlanning.ProductContext(); }
        }

        protected override void DataPortal_Create()
        {
            CreateObject();
        }
        protected override void Child_Create()
        {
            base.Child_Create();
            CreateObject();
        }
        private void CreateObject()
        {

        }

        #endregion

        #region Validation

        protected override void AddBusinessRules()
        {
            
            base.AddBusinessRules();
            
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(DoorProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_Door_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(OutdoorColorProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_OutdoorColor_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(IndoorColorProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_IndoorColor_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(GlazingProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_Glazing_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(GlassProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_Glass_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(DoorBaseUnitPriceProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_DoorBaseUnitPrice_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(DoorHeightDimensionProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_DoorHeightDimension_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(DoorWidthDimensionProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_DoorWidthDimension_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(OutdoorColorBaseUnitPriceProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_OutdoorColorBaseUnitPrice_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(IndoorColorBaseUnitPriceProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_IndoorColorBaseUnitPrice_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(GlazingBaseUnitPriceProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_GlazingBaseUnitPrice_RequiredRule; } });
            BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(GlassBaseUnitPriceProperty) { Priority = 0, MessageDelegate = () => { return Resources.DoorBuilder_GlassBaseUnitPrice_RequiredRule; } });

            BusinessRules.AddRule(new LoadDimensions(DoorProperty, DoorHeightDimensionProperty, DoorWidthDimensionProperty) { Priority = -1 });
            BusinessRules.AddRule(new LoadDefaultOptions(DoorProperty, OutdoorColorProperty, IndoorColorProperty, DoorBaseUnitPriceProperty) { Priority = -1 });
            BusinessRules.AddRule(new LoadOutdoorColorBaseUnitPrice(OutdoorColorProperty, OutdoorColorBaseUnitPriceProperty) { Priority = -1 });
            BusinessRules.AddRule(new LoadIndoorColorBaseUnitPrice(IndoorColorProperty, IndoorColorBaseUnitPriceProperty) { Priority = -1 });
            BusinessRules.AddRule(new LoadDefaultGlazingOption(DoorProperty, GlazingProperty) { Priority = -1 });
            BusinessRules.AddRule(new LoadGlazingBaseUnitPrice(GlazingProperty, GlazingBaseUnitPriceProperty) { Priority = -1 });
            BusinessRules.AddRule(new LoadDefaultGlassOption(GlazingProperty, GlassProperty) { Priority = -1 });
            BusinessRules.AddRule(new LoadGlassBaseUnitPrice(GlassProperty, GlassBaseUnitPriceProperty) { Priority = -1 });
        }

        private class LoadDefaultOptions : Csla.Rules.BusinessRule
        {
            public IPropertyInfo OutdoorColor { get; set; }
            public IPropertyInfo IndoorColor { get; set; }
            public IPropertyInfo DoorBaseUnitPrice { get; set; }

            public LoadDefaultOptions(IPropertyInfo doorProperty, IPropertyInfo outdoorColorProperty, IPropertyInfo indoorColorProperty, IPropertyInfo doorBaseUnitPriceProperty)
                : base(doorProperty)
            {
                OutdoorColor = outdoorColorProperty;
                IndoorColor = indoorColorProperty;
                DoorBaseUnitPrice = doorBaseUnitPriceProperty;
                InputProperties = new List<IPropertyInfo> { doorProperty };
                AffectedProperties.Add(OutdoorColor);
                AffectedProperties.Add(IndoorColor);
                AffectedProperties.Add(DoorBaseUnitPrice);
            }

            protected override void Execute(RuleContext context)
            {
                var customerID = ((DoorDetail)context.Target).CustomerID;
                var collation = ((DoorDetail)context.Target).DefaultCollation;
                var door = ((BusinessObjects.MF_Product.LightBusinessObjects.viewProductDoor)context.InputPropertyValues[PrimaryProperty]);
                var outdoorColor = door != null ? BusinessObjects.MF_Product.LightBusinessObjects.viewProductColor.GetDefaultOutdoorColor(door.ID, customerID, collation) : null;
                var indoorColor = door != null ? BusinessObjects.MF_Product.LightBusinessObjects.viewProductColor.GetDefaultIndoorColor(door.ID, customerID, collation) : null;

                context.AddOutValue(OutdoorColor, outdoorColor);
                context.AddOutValue(IndoorColor, indoorColor);
                context.AddOutValue(DoorBaseUnitPrice, door != null ? door.BaseUnitPrice : null);
            }
        }

        private class LoadDefaultGlazingOption : Csla.Rules.BusinessRule
        {
            public IPropertyInfo Glazing { get; set; }

            public LoadDefaultGlazingOption(IPropertyInfo doorProperty, IPropertyInfo glazingProperty)
                : base(doorProperty)
            {
                Glazing = glazingProperty;
                InputProperties = new List<IPropertyInfo> { doorProperty };
                AffectedProperties.Add(Glazing);
            }

            protected override void Execute(RuleContext context)
            {
                var customerID = ((DoorDetail)context.Target).CustomerID;
                var collation = ((DoorDetail)context.Target).DefaultCollation;
                var door = ((BusinessObjects.MF_Product.LightBusinessObjects.viewProductDoor)context.InputPropertyValues[PrimaryProperty]);
                var glazing = door != null ? BusinessObjects.MF_Product.LightBusinessObjects.viewProductGlazing.GetDefaultGlazing(door.ID, customerID, collation) : null;
                context.AddOutValue(Glazing, glazing);
            }
        }

        private class LoadDefaultGlassOption : Csla.Rules.BusinessRule
        {
            public IPropertyInfo Glass { get; set; }

            public LoadDefaultGlassOption(IPropertyInfo glazingProperty, IPropertyInfo glassProperty)
                : base(glazingProperty)
            {
                Glass = glassProperty;
                InputProperties = new List<IPropertyInfo> { glazingProperty };
                AffectedProperties.Add(Glass);
            }

            protected override void Execute(RuleContext context)
            {
                var customerID = ((DoorDetail)context.Target).CustomerID;
                var collation = ((DoorDetail)context.Target).DefaultCollation;
                var doorID = ((DoorDetail)context.Target).Door.ID;
                var glazing = ((BusinessObjects.MF_Product.LightBusinessObjects.viewProductGlazing)context.InputPropertyValues[PrimaryProperty]);
                var glass = glazing != null ? BusinessObjects.MF_Product.LightBusinessObjects.viewProductGlass.GetDefaultGlass(doorID, customerID, glazing.ProductID, collation) : null;
                context.AddOutValue(Glass, glass);
            }
        }

        private class LoadDimensions : Csla.Rules.BusinessRule
        {
            public IPropertyInfo HeightDimension { get; set; }
            public IPropertyInfo WidthDimension { get; set; }

            public LoadDimensions(IPropertyInfo doorProperty, IPropertyInfo heightDimensionProperty, IPropertyInfo widthDimensionProperty)
                : base(doorProperty)
            {

                HeightDimension = heightDimensionProperty;
                WidthDimension = widthDimensionProperty;
                InputProperties = new List<IPropertyInfo> { doorProperty };
                AffectedProperties.Add(HeightDimension);
                AffectedProperties.Add(WidthDimension);
            }

            protected override void Execute(RuleContext context)
            {
                var door = ((BusinessObjects.MF_Product.LightBusinessObjects.viewProductDoor)context.InputPropertyValues[PrimaryProperty]);
                context.AddOutValue(HeightDimension, door != null ? door.HeightDimension : null);
                context.AddOutValue(WidthDimension, door != null ? door.WidthDimension : null);
            }
        }

        private class LoadOutdoorColorBaseUnitPrice : Csla.Rules.BusinessRule
        {
            public IPropertyInfo OutdoorColorBaseUnitPrice { get; set; }

            public LoadOutdoorColorBaseUnitPrice(IPropertyInfo outdoorColorProperty, IPropertyInfo outdoorColorBaseUnitPriceProperty)
                : base(outdoorColorProperty)
            {

                OutdoorColorBaseUnitPrice = outdoorColorBaseUnitPriceProperty;
                InputProperties = new List<IPropertyInfo> { outdoorColorProperty };
                AffectedProperties.Add(OutdoorColorBaseUnitPrice);
            }

            protected override void Execute(RuleContext context)
            {
                var customerID = ((DoorDetail)context.Target).CustomerID;
                var collation = ((DoorDetail)context.Target).DefaultCollation;
                var outdoorColor = ((BusinessObjects.MF_Product.LightBusinessObjects.viewProductColor)context.InputPropertyValues[PrimaryProperty]);

                context.AddOutValue(OutdoorColorBaseUnitPrice, outdoorColor != null ? outdoorColor.BaseUnitPrice : null);
            }
        }

        private class LoadIndoorColorBaseUnitPrice : Csla.Rules.BusinessRule
        {
            public IPropertyInfo IndoorColorBaseUnitPrice { get; set; }

            public LoadIndoorColorBaseUnitPrice(IPropertyInfo IndoorColorProperty, IPropertyInfo IndoorColorBaseUnitPriceProperty)
                : base(IndoorColorProperty)
            {

                IndoorColorBaseUnitPrice = IndoorColorBaseUnitPriceProperty;
                InputProperties = new List<IPropertyInfo> { IndoorColorProperty };
                AffectedProperties.Add(IndoorColorBaseUnitPrice);
            }

            protected override void Execute(RuleContext context)
            {
                var customerID = ((DoorDetail)context.Target).CustomerID;
                var collation = ((DoorDetail)context.Target).DefaultCollation;
                var indoorColor = ((BusinessObjects.MF_Product.LightBusinessObjects.viewProductColor)context.InputPropertyValues[PrimaryProperty]);

                context.AddOutValue(IndoorColorBaseUnitPrice, indoorColor != null ? indoorColor.BaseUnitPrice : null);
            }
        }

        private class LoadGlazingBaseUnitPrice : Csla.Rules.BusinessRule
        {
            public IPropertyInfo GlazingBaseUnitPrice { get; set; }

            public LoadGlazingBaseUnitPrice(IPropertyInfo glazingProperty, IPropertyInfo glazingBaseUnitPriceProperty)
                : base(glazingProperty)
            {

                GlazingBaseUnitPrice = glazingBaseUnitPriceProperty;
                InputProperties = new List<IPropertyInfo> { glazingProperty };
                AffectedProperties.Add(GlazingBaseUnitPrice);
            }

            protected override void Execute(RuleContext context)
            {
                var customerID = ((DoorDetail)context.Target).CustomerID;
                var collation = ((DoorDetail)context.Target).DefaultCollation;
                var glazing = ((BusinessObjects.MF_Product.LightBusinessObjects.viewProductGlazing)context.InputPropertyValues[PrimaryProperty]);

                context.AddOutValue(GlazingBaseUnitPrice, glazing != null ? glazing.BaseUnitPrice : null);
            }
        }

        private class LoadGlassBaseUnitPrice : Csla.Rules.BusinessRule
        {
            public IPropertyInfo GlassBaseUnitPrice { get; set; }

            public LoadGlassBaseUnitPrice(IPropertyInfo glassProperty, IPropertyInfo glassBaseUnitPriceProperty)
                : base(glassProperty)
            {

                GlassBaseUnitPrice = glassBaseUnitPriceProperty;
                InputProperties = new List<IPropertyInfo> { glassProperty };
                AffectedProperties.Add(GlassBaseUnitPrice);
            }

            protected override void Execute(RuleContext context)
            {
                var customerID = ((DoorDetail)context.Target).CustomerID;
                var collation = ((DoorDetail)context.Target).DefaultCollation;
                var glass = ((BusinessObjects.MF_Product.LightBusinessObjects.viewProductGlass)context.InputPropertyValues[PrimaryProperty]);
                context.AddOutValue(GlassBaseUnitPrice, glass != null ? glass.BaseUnitPrice : null);
            }
        }

        #endregion
    }
}

Thanks a lot.

**Comment by jonnybee** [comment]
Yes rules is only executed 2 levels down (default). 

You may set the 

     BusinessRules.CascadeOnDirtyProperties = true;

in the CTOR or DataPortal_Create/DatePortal_Fetch method to enable the rule engine to cascade further down on dirty properties - assuming that you load new values by ruleContext.AddOutValue
You could end up in an eternal loop and get "out of stack space" - so this is only available as an override/advanced mode.

**Comment by jchabot1979** [comment]
Thanks alot, it works now...
