### ISSUE TITLE
Using MobileFormatter on non-CSLA classes

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslaforum#80]
I'm under the impression that this question wasn't discussed before.
As far as I understand, MobileFormatter performs better than standard .NET formatters:
- it minimizing the use of reflection
- it takes less bytes and so uses less bandwidth

How about using it outside the CSLA .NET ecosystem? How can one do it?

**Comment by rockfordlhotka** [comment]
One way MF achieves those goals is that it has active participation of the objects being serialized - thereby avoiding the use of reflection or serializing unnecessary information.

When you get right down to it, MF can serialize anything that implements `IMobileObject` - or that inherits from the set of basic `IMobileObject` implementations that exist in `Csla.Core` (`MobileObject`, `MobileList`, etc.).
