### ISSUE TITLE
Extra parameter Value and RuleUri

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#801]
Hi All,
I encountered a problem but first  let me share a recommendation from p-99 of Creating business objects. "Whenever we pass extra parameter to a business rule in addition to primary property, 
we are required to add the additional parameter to RuleUri inside the constructor of the business rule"(my words, not Rocky's : ) ).

I have two business rule that takes two parameters,one is  the primary property which is different for the two business rules but the second property (i,e extra parameter) is the same. Will I get some runtime errors if I add the same extra parameters to RuleUri in two business rules?

Kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by michaelcsikos** [comment]
That should not be a problem.

**Comment by rockfordlhotka** [comment]
iirc, the whole point is to make the URI unique so we have a "key" to identify each broken rule. CSLA automatically uses the rule name and primary property to create that URI, but if you have other properties on the rule then those would also be necessary to create a unique value.

**Comment by Chicagoan2016** [comment]
Thank you @michaelcsikos , @rockfordlhotka , I worried because the recommendation was to add only extra parameter to RuleUri and the two business rules were so similar, each requiring two properties (primary and extra parameter) and then both rules were using the same extra parameter although the primary property they use is different.

Kind regards
