### ISSUE TITLE
CSLA 5 prerelease online - with Blazor support

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#802]
I've put a prerelease of CSLA 5 online (5.0.0-R19090201) that now includes a new `Csla.Blazor` NuGet package with some basic UI helper functionality for [building Blazor client-side apps with CSLA](http://www.lhotka.net/weblog/BlazorSupportInCSLAV5.aspx).

This release also squashes quite a number of bugs with the new data portal and DI functionality. 

I've also made some good progress updating the ProjectTracker sample - specifically in WinForms, WPF, UWP, and Xamarin. I'm not done yet, but much of the code now demonstrates the new capabilities in CSLA 5.

One really nice thing is that, thanks to `HttpProxy` now supporting sync calls, I was able to update _all_ UI projects to use `HttpProxy`. That makes everything easier to understand, and also reduces my maintenance burden quite a bit. I was able to drop the .NET Framework data portal server and entirely rely on a modern .NET Core server, which is excellent!

**Comment by JasonBock** [comment]
When I read you added sync calls to `HttpProxy`, I started to wonder why that was done. Shouldn't *all* root `DataPortal` operations be asynchronous? Any time I would invoke a root operation, I'm talking to a service, or a database, or files, and all of that can be done with async I/O at this point. Even if a developer would say, "well, I have a case where the members I call are all async," you can still return `Task.CompletedTask` from a method that returns a `Task`, and if that is awaited (IIRC), the async state machine has a fast path to check for tasks that have already completed.

I get that only have async `DataPortal` support would be a breaking change, but it also seems like it's something that we should be moving towards anyway. Of course, I could be missing something very obvious here :).

**Comment by GillesBer** [comment]
Hi @JasonBock , I think that 
>  breaking change
is the key here. We would love to move to an async only DataPortal, but this is not the highest priority of our backlog. So implementing new DataPortal calls with async while keeping our existing code base "as is" (=sync), is really a great thing for us!
Also, most of our calls to DataPortal_Create are sync... and do not have interaction to the DB.
Even if we can use the Task.CompletedTask, this would make the code more complex.
This is my point of view.

**Comment by rockfordlhotka** [comment]
@JasonBock the big issue is the vast amount of legacy Windows Forms (and some WPF) apps out there that were written before the async shift.

Especially now that Windows Forms works in .NET Core 3, but WCF does not, it is critical that Windows Forms apps have an upgrade path without rethinking the entire UI approach - switching from sync to async means reworking the entire UI, which is just not realistic.

Given that HttpProxy is essentially the replacement for remoting/asmx/WCF in the modern world, it needs to support that WinForms sync scenario.

**Comment by JasonBock** [comment]
I get the points about legacy code. At the same time, is it possible to see if there's a way to push (or just nudge) people over time to use async I/O when possible? If I'm creating new code, I'd *want* to do async I/O as much as possible, I don't want to do blocking sync calls, and it's hard to do that if they don't exist at all. Maybe there's a way to have two separate `DataPortal` implementations where one is sync and one is async and there's a `DataPortal` that is a composition of these two. This is complete "what-if?" off-the-cuff thinking, which means it's probably not thought out very well at all.

To be fair, this can be simply managed by code reviews or something like that.

**Comment by rockfordlhotka** [comment]
I think it is more of a code review thing, personally.

Given that the Silverlight-style async methods are now marked as obsolete, there are only two valid ways to use the data portal:

1. Sync (e.g. `Create`, `Fetch`, etc.)
1. Async (e.g. `CreateAsync`, `FetchAsync`, etc.)

But, for example, in the `Csla.Xaml` viewmodel base, and the new Blazor viewmodel base, there are only async options.

In my mind, leaving the sync methods is necessary for older code, but newer code will almost certainly be using modern UI helpers (like the viewmodel types) and they only support async. So the nudge is happening.

**Comment by michaelcsikos** [comment]
There are situations where `async` isn't possible. We use CSLA inside AutoCAD, which is still single threaded in some cases. Using `async` calls to access an external database from a Windows Form is fine, but reading or writing data inside a DWG is strictly sync. And this is still true in AutoCAD 2020. For all new WinForms UI we use `async` almost exclusively, of course.
