### ISSUE TITLE
Getway rule using Rule chaining

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#806]
In one of my objects I have around 20 properties and almost all properties have multiple rules associated with them, ranging from priority 0 to priority 5.
I will give the example of Person object with one property as SSN, this property is required for 'employee' Person object but optional for 'client' Person objects.
When SSN is required we have rules like 'FormatSSN', NotAlreadyAssignedSSN, SSNReportedbyHR etc. with varying priorities.
However when the data entry staff member picks 'client' for the person object SSN is not required so none of the above rules for SSN are needed.
I am implementing  a gateway rule 'SSNNotRequired' using Rule Chaining where I am calling all the rules for SSN inside the 'Execute' method of SSNNotRequired.
I feel like there should be an 'easy' way to do this  : ), not trying to find shortcuts , just have a feeling.

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by GillesBer** [comment]
In our code, we use Rule Sets for this scenario.
See http://www.lhotka.net/weblog/CSLA4BusinessRulesSubsystem.aspx
This works well.
Just ensure that your re-perform a CheckRules, if you change the rule set of your object afterwards.


-------- Message d'origine --------
De : Chicagoan2016 <notifications@github.com>
Date : 06/09/2019 18:36 (GMT+01:00)
À : MarimerLLC/cslaforum <cslaforum@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [MarimerLLC/cslaforum] Getway rule using Rule chaining (#806)


In one of my objects I have around 20 properties and almost all properties have multiple rules associated with them, ranging from priority 0 to priority 5.
I will give the example of Person object with one property as SSN, this property is required for 'employee' Person object but optional for 'client' Person objects.
When SSN is required we have rules like 'FormatSSN', NotAlreadyAssignedSSN, SSNReportedbyHR etc. with varying priorities.
However when the data entry staff member picks 'client' for the person object SSN is not required so none of the above rules for SSN are needed.
I am implementing a gateway rule 'SSNNotRequired' using Rule Chaining where I am calling all the rules for SSN inside the 'Execute' method of SSNNotRequired.
I feel like there should be an 'easy' way to do this : ), not trying to find shortcuts , just have a feeling.

Kind Regards

Version and Platform
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by Chicagoan2016** [comment]
Thank you @GillesBer , I also found another solution
if someone else has the same use case, there is an easy solution on p-86,87 of 'Creating Business objects' book (part of the Using Csla 4 book series)

Kind Regards
