### ISSUE TITLE
Develop android apps,use HttpProxy and ObjectFactoryAttribute

### ISSUE THREAD

**Issue by dojason** [MarimerLLC/cslaforum#807]
I use xamarin to develop Android application, and data portal used HttpProxy. In my business objects, I use the ObjectFactoryAttribute, but it doesn't work.

**Comment by rockfordlhotka** [comment]
Thank you - what exception do you get?

**Comment by dojason** [comment]
System.MissingMethodException: 'ProjectTracker.BusinessLibrary.TestEdit.[Create].()'
Thank you!

**Comment by rockfordlhotka** [comment]
It is possible that you are encountering an issue that will be fixed in the next preview release. I can not duplicate this problem with the latest CSLA code.

I hope to push a new prerelease within the next 24 hours.

**Comment by dojason** [comment]
OK，I am waiting csla5.0。Thank you，best wish for you！

**Comment by rockfordlhotka** [comment]
@dojason I found the problem, and am fixing it in the next prerelease.

**Comment by rockfordlhotka** [comment]
@dojason the fix should be available now in 5.0.0-R19091005

**Comment by dojason** [comment]
I see,Thank you.
