### ISSUE TITLE
CSLA prerelease 5.0.0-R19091005 online

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#808]
**UPDATE**
I just pushed a new prerelease of CSLA to NuGet - 5.0.0-R19091005.

**YES!! A double update in one day! I fixed a few bugs as I got all the samples updated.**

This should be the last batch of new functionality in any meaningful way. From now to the end of September the focus is on updating samples, identifying and squishing bugs, and anything else necessary to get out a final release shortly after Microsoft officially releases .NET Core 3 on Sept 23.

[Full change log](https://github.com/MarimerLLC/csla/issues?q=is%3Aissue+is%3Aclosed+project%3AMarimerLLC%2Fcsla%2F5+sort%3Aupdated-desc) is on GitHub. You can also checkout the [releasenotes document](https://github.com/MarimerLLC/csla/blob/master/releasenotes.md).

Highlights of this prerelease:

* A _lot_ of bug fixes and improved stability
* New support for Blazor validation
* New samples: Blazor, Uno, ASP.NET Core MVC, Data portal factory
* New permissions handler for ASP.NET Core
* New validation message support for ASP.NET Core MVC
* New `ObjectAuthorizationRules` attribute so `AddObjectAuthorizationRules` method name is no longer hard-coded
* New support for Windows Forms in .NET Core 3
* New support for WPF in .NET Core 3
* Improved support for .NET Core dependency injection
* Updates to the ProjectTracker sample
* Updates to the C# and VB snippets for CSLA 5
* Updates to the `Support/Templates` code for CSLA 5
* Updates to the fluent config API to simplify use

**Comment by rockfordlhotka** [comment]
Lots of great activity in the last 30 days!!

![image](https://user-images.githubusercontent.com/2333134/64670047-6123e200-d429-11e9-95bf-842a55a4b63d.png)

**Comment by iherwald** [comment]
That is really great to see!

Thanks to you Rocky and all contributors for keeping this outstanding framework up-to-date and for adding even more value to it!
