### ISSUE TITLE
"magic strings" and Csla

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#811]
Hi all,
I have asked similar question in the past about "magic strings" ( I couldn't up with a better term : )) and Csla, since static classes can't be serialized we can't use properties of static classes to replace magic strings in a Csla projects. We have used 'Resources' in Visual studio and 'enum's ToString() method but I still feel like there should be a 'better' way to handle this.

thoughts please?

Kind regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
A global static array?

**Comment by Chicagoan2016** [comment]
@rockfordlhotka , thank you sir, I will continue using Resource files.
kind regards
