### ISSUE TITLE
Detected Razor language version downgrade

### ISSUE THREAD

**Issue by skeeler88** [MarimerLLC/cslaforum#823]
**Question**
I am using Visual Studio 2019 and create a new .NET Core 3.0 ASP .NET project.

When I add Csla.AspNetCore package I receive this warning:

RAZORSDK1006 Detected Razor language version downgrade. This is typically caused by a reference to the Microsoft.AspNetCore.Razor.Design package. Consider removing this package reference.	WebApplication1

I think the reason is because MS added Framework References and it automatically adds these references into the csproj. What would be the suggested approach to this issue?

(I can duplicate in .Samples/MvcExample as well)

Thank you!

**Version and Platform**
CSLA version: 5.0.1
OS: Windows, Linux, iOS, Android, etc.
Platform: ASP.NET Core

**Comment by rockfordlhotka** [comment]
As far as I've been able to determine, there's no actual negative impact from this warning.

I have been discussing this with the .NET product team at Microsoft, and a "solution" seems like it might be very complex - for me and all users of CSLA.

So for right now I'd recommend ignoring the warning. If you encounter tangible problems please do let me know.

**Comment by rockfordlhotka** [comment]
HA!!

I got the warning resolved (https://github.com/MarimerLLC/csla/issues/1367) and the fix will be in version 5.1.0 in the near future.

**Comment by skeeler88** [comment]
Great good to hear thank you!

**Comment by jeraldjamescapao** [comment]
> HA!!
> 
> I got the warning resolved ([MarimerLLC/csla#1367](https://github.com/MarimerLLC/csla/issues/1367)) and the fix will be in version 5.1.0 in the near future.

Thank God, there will be a solution. So I will ignore this warning message for now.
