### ISSUE TITLE
CSLA 5 - DAL with ADO.NET issues

### ISSUE THREAD

**Issue by liborpolansky** [MarimerLLC/cslaforum#824]
After a long time I use CSLA again and work on a new project in CSLA5 (.NET Core 3) and set up DAL using ADO.NET.

I have two questions:

1) SafeDatareader - HasRows
Cannot find HasRows method in SafeDataReader. Is there any reason for this?

2) Using SQLConnectionString
I load SQLConnectionString from the application configuration file and insert it into ConfigurationManager.ConnectionStrings. Subsequently, I wanted to use a saved connectionstring in ConnectionManager but I cannot use the code below. 

public DalManager
     {
       ConnectionManager = ConnectionManager <SqlConnection> .GetManager ("dbName");
     }
It returns a System.NotSupportedException: 'isDatabaseName == true'

I must use the following code instead:

public DalManager
     {
       ConnectionManager = ConnectionManager <SqlConnection> .GetManager (ConfigurationManager.ConnectionStrings ["dbName"]. ConnectionString, false);
     }

**Version and Platform**
CSLA version: 5.0.1
OS: Windows
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
> SafeDatareader - HasRows - Cannot find HasRows method in SafeDataReader. Is there any reason for this?

Yes, `HasRows` is not part of the `IDataReader` interface, it is exclusive to `SqlDataReader`. 

This thread has more info: https://github.com/MarimerLLC/cslaforum/issues/715

**Comment by rockfordlhotka** [comment]
> I load SQLConnectionString from the application configuration file and insert it into ConfigurationManager.ConnectionStrings. Subsequently, I wanted to use a saved connectionstring in ConnectionManager but I cannot use the code below.

This change is due to the new .NET Core configuration subsystem. It is no longer possible to know how or where connection strings will be loaded by the configuration subsystem, so we're now requiring that the connection string be provided to the constructor instead of a connection name.

**Comment by rockfordlhotka** [comment]
Actually @liborpolansky I take it back. Regarding `HasRows` CSLA 5 does now include a `SqlSafeDataReader` that is in the `Csla.Data.SqlClient` package (pick Fx for .NET Framework):

![image](https://user-images.githubusercontent.com/2333134/66250251-d53e6680-e705-11e9-8929-e9492de67734.png)

**Comment by liborpolansky** [comment]
Rocky, thank you for prompt information.
