### ISSUE TITLE
Could not load type 'HttpProxy' from assembly 'Csla'...

### ISSUE THREAD

**Issue by BlagoCuljak** [MarimerLLC/cslaforum#834]
Hi, I'm try to implement CSLA config subsystem so that my WPF app would use dataportal URL from my appsettings.json file.

I have done it in this way:
1. Added this to Configure() in Startup.cs:
`   var config = new ConfigurationBuilder()
      .AddJsonFile("appsettings.json")
      .Build()
      .ConfigureCsla();`
2. Add appsettings.json:
`{
  "csla": {
    "dataPortal": {
      "proxy": "HttpProxy",
      "portalUrl": "http://localhost:8040/api/dataportal"
    }
  }
}`

When starting an application I get this error: 
Could not load type 'HttpProxy' from assembly 'Csla, .... What am I doing wrong, I don't get it, wasted entire day on this.

Also, one question, is it better to stick with http proxy or move to grpc, performance-wise? Can we use grpc with WPF and Blazor client at same time?

**Version and Platform**
CSLA version: 5.0.0
Platform:  WPF, ASP.NET Core

**Comment by BlagoCuljak** [comment]
Well, silly me...
`"proxy": "Csla.DataPortalClient.HttpProxy",`

gRPC question still stands though...

**Comment by rockfordlhotka** [comment]
I think the `.Build()` needs to be the last operation performed, because that's what actually builds the config object.

**Comment by rockfordlhotka** [comment]
I don't know whether gRPC performs better than Http, as I haven't done direct perf testing to compare.

The way CSLA uses both transports is just as a _transport_. In other words, in both scenarios CSLA just passes a byte array over the transport. So I doubt there'll be much performance difference between the two.

However, my understanding is that there are some built-in options with gRPC for compression, and that might be helpful.

There should be no problem with multiple client types using the same server endpoint. The protocol is the same regardless of client platform. So yes, you should be able to use the same endpoint from WPF and Blazor (and Xamarin, and Windows Forms, and ... ).

**Comment by BlagoCuljak** [comment]
I don't get, can we also use dynamic/static compression on httpproxy? If we can, no need to use gRPC, there's no real use cases that benefits us that much.

**Comment by rockfordlhotka** [comment]
I agree, given how CSLA uses these transports there's no big difference between them imo.
