### ISSUE TITLE
CSLA.NET Business Rules And SaaS

### ISSUE THREAD

**Issue by bashinamwila** [MarimerLLC/cslaforum#847]
CSLA.NET Business Rule System has concept of RuleSets for different tenants for the SaaS Application.In a SaaS Application tenant provisioning may be done programmatic ally which makes impossible to hard code tenant specific business rules.How would one solve such an Issue?Storing tenant specific Business Rules in the db?Dynamic Business Rules?Pointers to resources to helping to solve this issue in CSLA.NET would be highly appreciated.Many Thanks

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
Keep in mind that each rule is a type, and so an instance can be created dynamically using `Activator.CreateInstance` if you have the assembly qualified type name. Or you can use MEF (I don't remember the namespace right now), which is a .NET framework for discovering and loading dynamic types (a built-in framework, it is part of .NET).

So it is totally realistic to load the type names and constructor parameters from a database (via a `ReadOnlyBase` type) such that `AddBusinessRules` is not hard-coded.

**Comment by bashinamwila** [comment]
Thanks Rocky
