### ISSUE TITLE
Validation of query parameters

### ISSUE THREAD

**Issue by TheCakeMonster** [MarimerLLC/cslaforum#850]
Blazor is making me have to rethink some of our existing architectural patterns. I'm sure I won't be alone in that, but that is another discussion ...

We have a number of search screens in our system that allow the entry of parameters in filter fields, which displays a paged list of records that match the parameters entered. That input data needs validation, especially as it is a web system that someone might try to abuse. In the bad old days, I had to rewrite my validation logic in the UI layer - most web technologies of old didn't fully respect CSLA rules in the object layer and expose them on the client-side - so I didn't worry so much about any validation in the object layer. What we ended up with was rules in the UI layer, and a read-only object graph used to call to the database and return the matching results of the query operation. We used a read-only root (to expose the total number of results, the number of pages of results and so on) and a read-only child list of matching results on the current page, with a read-only child at the bottom containing the fields to show on the screen. All was good with the world.

Along comes Blazor, and in a rewrite, my validation can be done differently - it can be done by an object that is intended to capture the parameter values of the query. CSLA has a great validation (business rules) engine, so that's what I reach for in these scenarios ... but I find myself in an odd position. For years, I've found it easy to identify the use of the stereotypes, but here I find myself suddenly in a quandary.

In order to get validation on an object, I think it has to be editable. However, that doesn't feel right here; what we're going to do is get a set of results - a fetch operation - and nothing else. What I want is a read-only object with read-write parameters that have validation applied (and re-applied on the server, if we use client-side Blazor, and don't trust the data from the client.)

How have people modeled this in the past in other UI technologies? This must also have happened in Silverlight, not to mention WinForms and WPF (but with lesser security concerns, perhaps.) What stereotype would you use for the object that accepts the parameter values from the UI?

It would be possible to do most of the required validation on this object with Data Annotations, so you could say I could do without CSLA here. However, Data Annotations doesn't enable validation across parameters ("at least one of these x number of fields must be provided" for example.) Once the data has been entered, there is also a data access job to perform, so it seems reasonable that this be enabled through a CSLA object model, somehow.

It almost feels like this is a new stereotype - a query object, or something - but after all these years with a fixed number of stereotypes that completely fulfilled our requirements, that seems very unlikely!

Any details of how others have approached this in the past would be greatly received.

**Comment by rockfordlhotka** [comment]
This is absolutely a scenario where `BusinessBase` is a valid choice. As you note, this scenario isn't new - it is exactly the same as WinForms/WPF/SL/UWP folks have worked with forever.

Stereotypes are a useful thought model. But it is also useful to just look at the base classes, see what features they offer, and match those features against your needs.

You need

1. Public read-write properties
1. Rules attached to those properties
1. The ability to transfer the object's state to the server

`BusinessBase` provides all those capabilities. Yes, it provides _more_ capabilities, but you can use it just for these features.

Much like EF provides tons and tons of features, but we still use it if all we're doing is pulling a single value from a database query.

**Comment by hurcane** [comment]
I'm not in the web. I deal with a rich desktop client. However, your scenario is not unlike what we deal with.

Our solution is to have a "criteria" class that is an editable root stereotype. The criteria are never saved to the database, so we don't implement save methods. However, we have lots of business rules on these criteria classes.

The results of the query are designed as a read-only stereotype. It takes the criteria class as a parameter and returns the relevant results.

**Comment by TheCakeMonster** [comment]
OK, thanks both.

I'm slightly unused to exposing a lot of functionality that is not required on my object's external interface. These days this might seem a bit old-fashioned, but I used to imagine that the person who created the object and the person who consumed the object might be different. In our department, that's not really true, so maybe this is a carry over from reading one of the very first books, in the days when maybe developers were pigeon-holed in this way.

The bit of the interface that feels particularly out of place when using an editable root for this purpose is the Save method. It works, but it feels slightly unusual.

I presume the business rules are not reapplied automatically on a root object during the interaction you describe; this is something that I need to write code for. With an editable object, it is calling the Save method that reapplies this on our behalf, catching us if we miss the existence of a broken rule in our handling of the object. In this scenario, calling Save doesn't feel right, so I have to do that check manually.

**Comment by rockfordlhotka** [comment]
I don't call `Save` on a criteria object - I just bind the object to the UI, let the user fill in the values, then I can easily see if the object `IsValid` before passing it as the criteria parameter through the data portal to fetch the object I'm trying to retrieve.

**Comment by Chicagoan2016** [comment]
@TheCakeMonster , I am glad you asked this question. To add to what @rockfordlhotka  mentioned.
If you use BusinessBase as criteria and use public read-write properties, you don't have to call the Save method. In the 'PropertySet' your business rule(s) will be called (at least for the that property-- and dependent properties) and mark your object Valid/InValid.
Regards

**Comment by TheCakeMonster** [comment]
OK, thanks for the replies everyone. It feels like the question is answered, so closing it seems appropriate. Thanks for your help.
