### ISSUE TITLE
Guidance on the Csla.Blazor ViewModel - Not as friendly as static factories

### ISSUE THREAD

**Issue by drakeforte5** [MarimerLLC/cslaforum#853]
I've been using the new Csla.Blazor library and I noticed that this is now using syntax such as:

await vm.RefreshAsync(param1, param2, param3);

which translates to the DataPortal server call of:

[Fetch]
private void FetchByParams(int32 param1, int32 param2, int32 param3, [Inject] somelib)

In my BO I also have or different parameter requirements depending the need:
[Fetch]
private void FetchAll([Inject] somelib]

It works in my new project by the way but just takes more time to troubleshoot errors because the UI developer has to really know which Fetch to target in cases where the [Fetch] has multiple signatures.

I suppose I can still use the static factories just like in the old WinForms apps?

Would there still be enhancements/changes on this since I am now creating a project using Csla.Blazor.

Thank you.

**Comment by rockfordlhotka** [comment]
Yes, you can still use static factories and directly set the `Model` property with the result.

Alternately, you can subclass `ViewModel` and add methods that provide strongly typed parameters. Probably name the methods `CreateAsync` and `FetchAsync` - and have them invoke `RefreshAsync` internally.

**Comment by rockfordlhotka** [comment]
Yes, you can still use static factories and directly set the `Model` property with the result.

Alternately, you can subclass `ViewModel` and add methods that provide strongly typed parameters. Probably name the methods `CreateAsync` and `FetchAsync` - and have them invoke `RefreshAsync` internally.

**Comment by drakeforte5** [comment]
OK Thank you.
