### ISSUE TITLE
Always encrypted causes Operand type clash: varchar(8000) encrypted with (encryption_type = 'DETERMINISTIC'...

### ISSUE THREAD

**Issue by kwuh97** [MarimerLLC/cslaforum#864]
**Question**
I am trying to use the Always Encrypted feature in SQL Server 2017. I wanting to update a table using CSLA .NET MVC5. The column that I am trying to update has a datatype of varchar(15). I would rather not write a custom SP to do this update and have CSLA process my CRUD operations. I keeping getting this error when I try to update the table using my application:

Operand type clash: varchar(8000) encrypted with (encryption_type = 'DETERMINISTIC',

I ran a trace on the table and found the UPDATE statement was setting my column parameters to varchar(8000) when the column should be varchar(100). I'm not sure why this is happening. I just wanted to know if anyone else has face this problem and found a solution.

Just a side note: I did get it to work successfully but I had to change the size to varchar(8000) however that is a very large size when I am only storing 15 characters in the column and I will have to encrypt additional columns in the future of varchar(15).

Thanks In Advance for any assistance.

**Version and Platform**
CSLA version: 4.7.101
OS: Windows
Platform: ASP.Net MVC

**Comment by rockfordlhotka** [comment]
CSLA does not talk to the database, it calls your data access layer and your code talks to the database. What does your DAL code look like?

**Comment by hurcane** [comment]
If you're using ADO.NET parameters, you  should explicitly set the size of the parameter. If you do not set the size, the provider will use a default value, which happens to be the maximum length for the data type of the column. 

You can see the examples [in the Mirosoft Docs](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/develop-using-always-encrypted-with-net-framework-data-provider?view=sql-server-2017).

**Comment by kwuh97** [comment]
rockfordlhotka forgive me if some of my terms are not totally accurate but I wasn't sure how to present the DAL Code to you and I wasn't sure if you were asking for the DBML file or the Table Object. I have attached the Table Object that we generate from our CodeGen Tool and it has the CRUD operations within it. Hopefully this will be of some substance to you.
[RoomSchedule.txt](https://github.com/MarimerLLC/cslaforum/files/4059511/RoomSchedule.txt)

hurcane This xsd file is the only thing that I found in our project that comes close to ADO.Net parameters that your link references. Hopefully this will helps.
   
[NCI_COMMONDataSet.txt](https://github.com/MarimerLLC/cslaforum/files/4059722/NCI_COMMONDataSet.txt)

Again Thanks In Advance for any assistance.

**Comment by kwuh97** [comment]
I forgot to add that the column that I have encrypted is Subject on the RoomSchedule Table.

Thanks Again

**Comment by hurcane** [comment]
It appears that you are using the Linq-to-SQL technology to update your database.

https://stackoverflow.com/questions/44812514/update-insert-rows-in-sql-table-with-encrypted-columns-using-linqtosql-always
https://stackoverflow.com/questions/45551782/cannot-insert-into-sql-server-alwaysencrypted-table-with-linq

You might consider using a different client-side technology for the table with the encrypted column. Microsoft has [examples for different platforms](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-client-development?view=sql-server-ver15), but none of them are for Linq to SQL.

**Comment by kwuh97** [comment]
Ok thanks for everything. We may just have to go with changing the column to varchar(8000).

**Comment by rockfordlhotka** [comment]
One thing to consider is that LINQ to SQL will come to end of life in the near future. I don’t remember exactly when, but it is a discontinued product.
