### ISSUE TITLE
Client Side Blazor 3.2 Move startup .cs code to program.cs

### ISSUE THREAD

**Issue by uwefms** [MarimerLLC/cslaforum#872]
Could some one please show me how to transfer

`      app.UseCsla((c) =>
        c.DataPortal().DefaultProxy(typeof(Csla.DataPortalClient.HttpProxy), "/api/DataPortal"));
`

from the obsolete configure(IComponentsApplicationBuilder app) method in Startup.cs to Main(string[] args) in Program.cs ?

**Version and Platform**
Csla.Blazor Version= 5.1.0-R20012201
OS: Windows
Platform: ASP.NET Core 3.1 (2)

   Thanks
  
        Uwe

**Comment by rockfordlhotka** [comment]
I don't think that `startup.cs` is obsolete, unless it is in the latest VS 2019 16.5..0 Preview 1.0? 

That'd be a MAJOR change on Microsoft's part, and would completely diverge from their strategy around Blazor client-side configuration.

I am sure you aren't talking about server-side Blazor, because Microsoft isn't about to abandon `startup.cs` for ASP.NET Core after all this time.

**Comment by uwefms** [comment]
Rocky,

   you are right - sorry for being so unclear. I am referring to Client Side Blazor and the newest 3-2-0-preview-1 version.

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/

Trying to update to the newest changes I got stuck in ProjectTracker.Ui.Blazor.Client. If I got the release notes correctly startup.cs is no longer necessary in CSB.

This can easily be reproduced by creating a CSB hosted project with the newest templates after upgrading.

    regards

       Uwe

**Comment by rockfordlhotka** [comment]
I think, until I make this a little cleaner, you can use the following to get running.

```c#
  public class Program
  {
    public static async Task Main(string[] args)
    {
      var builder = WebAssemblyHostBuilder.CreateDefault(args);
      builder.RootComponents.Add<App>("app");

      builder.Services.AddCsla();
      CslaConfiguration.Configure().
        ContextManager(typeof(Csla.Blazor.ApplicationContextManager));

      await builder.Build().RunAsync();
    }
  }
```

**Comment by uwefms** [comment]
Rocky,

   thank you for your answer. Could solve my problem by adding

`
CslaConfiguration.Configure().
  DataPortal().
    DefaultProxy(typeof(Csla.DataPortalClient.HttpProxy), "/api/DataPortal");
`
   
   Uwe

**Comment by rockfordlhotka** [comment]
I just pushed a 5.1 preview to NuGet that includes a good answer to this change.

https://blog.lhotka.net/2020/02/05/Updated-Blazor-WebAssembly-app-initialization

**Comment by uwefms** [comment]
Did the update - works as it should.

   Thank you

**Comment by Brannos1970** [comment]
@rockfordlhotka 
Not sure if anyone is aware but the UseCsla is not recognized with the latest preview.

**Comment by rockfordlhotka** [comment]
Thank you @Brannos1970 - tracking the changes here: https://github.com/MarimerLLC/csla/issues/1514

Though already there's been _another_ preview release on top of the one referenced in that issue, so I need to update the version number in the issue...

If they are going to release Blazor WebAssembly in May they need to stop changing key types pretty soon!! 😄
