### ISSUE TITLE
CSLA 4.6 Analyzer Questions

### ISSUE THREAD

**Issue by acgritt** [MarimerLLC/cslaforum#88]
I have been using CSLA on several projects for many years and have been using the framework heavily since version 3.  However, I have a question about the analyzers that are included in the CSLA 4.6 release.

PublicNoArgumentConstructorIsMissingRule - In the past the standard has been to use a **private** class constructor.  Has the reasoning for this changed?  I know that in the books for CSLA version 4.1 it is stated that for Silverlight you must supply a default public constructor for the serialization to work.  However, I have always used just CSLA Core and the business objects exist only on the server side logic.  Is the **correct** standard to now use a public constructor instead of a private one?

**Comment by JasonBock** [comment]
Yes, you're correct. The original idiom was to make them `private` but that's changed over time.

**Comment by ajj3085** [comment]
I didn't know this had changed.  Does the analyzer also warn to not have client code actually calling the ctor though?  Seems dangerous, but I guess this is also related to runtimes where reflection has to be against public members.

**Comment by rockfordlhotka** [comment]
There's also the positive side-effect that you don't actually need to manually implement the ctor at all - in most cases you can just allow the compiler to auto-gen the default ctor and be happy. Less code to write/maintain is good.

**Comment by acgritt** [comment]
The reason I had asked was that we had implemented all of our business objects such that there was the `private` empty constructor and a `public` constructor that took a `IDisableConstructor`.  The second constructor would always throw and exception.  This was to prevent Unity from constructing an instance of the business object through the constructor since Unity always goes for the constructor with the most parameters.  We use Unity on the business objects to call BuildUp() to inject the Data Context instance at runtime.  The two new Constructor Analyzers have caused some discussion within the team as to whether we should just disable them or refactor the code so that they are valid.  However, in refactoring we do open up potential risk with using Unity.

**Comment by clodewyks** [comment]
Hi All,

Is there an way to update this without having to go into each file class? We are using CSLA in all of our projects spanning 1000s of files and updating each constructor from private to public would take a considerable amount of time.
