### ISSUE TITLE
GetPropertyInfo Method in Blazor

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#890]
Hi,
On p-132 (Blazor book) I am reading about GetPropertyInfo method and it seems like a very useful tool. Do we have that in other UI frameworks when using Csla? We have a couple of projects in WPF and WinForms (using Csla) where we could utilize GetPropertyInfo method.

Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
In the `Csla.Xaml` namespace there's the `PropertyInfo` type/control that fills much the same niche, fitting into the way XAML controls are composed.

There's nothing comparable for Windows Forms.

**Comment by Chicagoan2016** [comment]
Thanks @rockfordlhotka
