### ISSUE TITLE
Sample besides Projecttracker which uses Asp.Net Mvc and csla .4.5

### ISSUE THREAD

**Issue by ashishsinha24** [MarimerLLC/cslaforum#9]
Hi everyone,

I have developed and successfully deployed several apps for CSLA 3.8 and winforms.

Now, I have started csla 4.5 but it is very confusing.

Q: Is it necessary to use Async operations for MVC?
Q: Is a sample app available for new users which shows a Order--->LineItems--->LineItem type app which uses all the new features of CSLA 4.5.

regards

pat cash

**Comment by lmsantin** [comment]
For your first question and from the 02-Using CSLA 4 Creating Business Objects book:
"I typically always implement async factory methods in my classes, and implement synchronous factory methods only for the .NET platform. To do this, I use a compiler directive so the synchronous code doesn’t compile for Silverlight. For example:
#if !SILVERLIGHT 
// .NET-only code goes here
 #endif"

For your second question, download CSLA from https://github.com/MarimerLLC/csla/archive/V4.3.14.zip
and in this path (csla-4.3.14.zip\csla-4.3.14\Samples\NET\cs\CslaMVC) there is a sample I think it can help you.

**Comment by rockfordlhotka** [comment]
Regarding the MVC and async question - it depends on whether you are using the MVC async controller capabilities or not.

If you use an async controller then you should probably use async data portal calls.

If you use sync controllers then you _must_ use sync data portal calls or things get really complex.

**Comment by ashishsinha24** [comment]
Thanks a lot for all the help. I could run the ProjectTracker sample.

But, have a small glitch which prevents from logging in. The error i am getting is:

The provided anti-forgery token was meant for user "manager", but the current user is ""

I have tried all i the remedies i could find out the web. Any ideas ?

pat
