### ISSUE TITLE
Purpose of OnMetaPropertyChanged

### ISSUE THREAD

**Issue by Marjon80** [MarimerLLC/cslaforum#904]
**Question**
We are building a WinForm application and because of the heavy refresh cost when a PropertyHasChangedEvent is fired was looking at the events that are fired when a property changes.

I've noticed that the IsSaved, IsValid, etc events fire very regularly and discovered the OnMetaPropertyChanged method. What is the purpose of this method and what ramifications would there be to not having it raise events for the IsXYZ methods? The thought is that if a user makes a change to property then a PropertyHasChanged event would have been fired already and knowing that IsDirty, IsValid is not relevant. 

I can see some real value to this method when using WPF, however, that isn't something we are exploring at this time.

Thanks in advance

Marjon

**Version and Platform**
CSLA version: 5.0.1
OS: Windows
Platform: WinForms

**Comment by rockfordlhotka** [comment]
There's a config setting to tell CSLA to optimize events for Windows Forms. Do you have that set as your app loads?

**Comment by Marjon80** [comment]
Rocky,

I was not aware of this setting, can you advise what it is?

**Comment by rockfordlhotka** [comment]
https://github.com/MarimerLLC/csla/blob/master/Samples/ProjectTracker/ProjectTracker.Ui.WinForms/Startup.cs#L51

**Comment by Marjon80** [comment]
That information is amazing and why I love working with this framework still after 12 years!
Thanks very much
