### ISSUE TITLE
Changing properties within an aysnc rule

### ISSUE THREAD

**Issue by Marjon80** [MarimerLLC/cslaforum#917]
**Question**
Is it possible to change a property other than the primary property within an async rule, 
I've taken the example of an async rule published by Rocky [here](https://github.com/MarimerLLC/cslaforum/issues/903) and was able to change the name property but when I added a secondary property was unable to get any result out. I assume this is a limitation of async rules, which I can understand just want to make sure I'm not missing something obvious.

**Version and Platform**
CSLA version: 5.1.0
OS: Windows, iOS, Android.
Platform: WinForms, Xamarin

**Comment by Chicagoan2016** [comment]
@Marjon80 , it would be helpful if you could share your code.

**Comment by Marjon80** [comment]
I found the cause of my problem, sorry for bothering the forum.
