### ISSUE TITLE
PropertyChanged not fired from ObjectRule

### ISSUE THREAD

**Issue by tsvideo** [MarimerLLC/cslaforum#919]
Hi!
I have an ObjectRule in witch i check some dependencies and calculate some Values for the whole Object. I use AddErrorResult and AddOutValue for the Messages and Values.
The Propertys of the Object are changing correct.
But there are no Property Changed Events to the WPF UI.
If i write one separate BusinessRule to Change values it Works, but i must have an ObjectRule.
CSLA Version 4.11.2
Thank You for helping!

**Comment by rockfordlhotka** [comment]
@jonnybee is the best one to answer this if he's online.

**Comment by tsvideo** [comment]
@Chicagoan2016  No, It's based on BindableBase from PRISM

@jonnybee Info: If i use context.target.PropertyName it works, but not for the ErrorMessages

**Comment by jonnybee** [comment]
Can you provide som small sample to show the issue? 

I assume that you are using PropertyChangedModes.Xaml and call BusinessBase.CheckObjectRules?

The code is very similar for CheckObjectRules and CheckPropertyRules 

    protected virtual void CheckPropertyRules(IPropertyInfo property)
    {
      var propertyNames = BusinessRules.CheckRules(property);
      if (ApplicationContext.PropertyChangedMode == ApplicationContext.PropertyChangedModes.Windows)
        OnPropertyChanged(property);
      else
        foreach (var name in propertyNames)
          OnPropertyChanged(name);
    }

    /// <summary>
    /// Check object rules and notifies UI of properties that may have changed. 
    /// </summary>
    protected virtual void CheckObjectRules()
    {
      var propertyNames = BusinessRules.CheckObjectRules();
      if (ApplicationContext.PropertyChangedMode == ApplicationContext.PropertyChangedModes.Windows)
      {
        OnUnknownPropertyChanged();
      }
      else
        foreach (var name in propertyNames)
          OnPropertyChanged(name);
    }

so the behavior should be the same to notify the UI when PropertyChangedMode is set to Xaml.

**Comment by tsvideo** [comment]
Hello Jonny,
yes, here some code:

       protected override void AddBusinessRules()
        {
            base.AddBusinessRules();

            //Some other BusinessRules.AddRule

            BusinessRules.AddRule(new ObjectInputRule());
            BusinessRules.AddRule(new RunObjectRulesOnPropertyChange(ArmlaengeProperty) { RunMode = RunModes.DenyAsAffectedProperty });
        }

        private class ObjectInputRule : Csla.Rules.ObjectRule
        {

            public ObjectInputRule() : base()
            {
                AffectedProperties.Add(ArmlaengeProperty);
                AffectedProperties.Add(LastschwerpunktProperty);
                AffectedProperties.Add(FusslaengeProperty);
            }

            protected override void Execute(IRuleContext context)
            {
                var target = (KragarmregalFischer)context.Target;

                //Some other checks and calculations with AddOutValues and AddErrorResult

                #region Arme Fuesse

                var armlaengemax = target.Armlaenge;
                var fusslaenge = target.Fusslaenge;

                if (armlaengemax > fusslaenge)
                {
                    context.AddErrorResult(FusslaengeProperty, "Fuß darf nicht kürzer als längster Arm sein.");
                }
                if (armlaengemax == 0)
                {
                    context.AddErrorResult(ArmlaengeProperty, "Mindestens ein Arm muss angelegt sein.");
                }
                if (armlaengemax > 0)
                {
                    //Works not:
                    context.AddOutValue(FusslaengeProperty, armlaengemax);
                    context.AddOutValue(LastschwerpunktProperty, armlaengemax);

                    //Works:
                    //target.Fusslaenge = armlaengemax;
                    //target.Lastschwerpunkt = armlaengemax;
                }

                #endregion
            }
        }

        private class RunObjectRulesOnPropertyChange : Csla.Rules.BusinessRule
        {
            public RunObjectRulesOnPropertyChange(IPropertyInfo primaryProperty) : base(primaryProperty)
            {
                InputProperties = new List<IPropertyInfo>();
                InputProperties.Add(primaryProperty);
                PrimaryProperty = primaryProperty;
            }

            protected override void Execute(IRuleContext context)
            {
                var target = (KragarmregalFischer)context.Target;

                target.BusinessRules.CheckObjectRules();
            }
        }

Where can i set or check the PropertyChangedMode? (Please with sample)
Only the 'Armlaenge' property changed event reaches in my ViewModel the _model_Property_Changed eventhandler

**Comment by Chicagoan2016** [comment]
> @Chicagoan2016 No, It's based on BindableBase from PRISM
> 
> @jonnybee Info: If i use context.target.PropertyName it works, but not for the ErrorMessages

I am so glad you mentioned Prism, I have a couple of quick questions. 
1) Since Prism have Modules, do you use them? I am wondering how should we structure our projects in the solution, Do you have a Shell project and Modules project? please share
2) Do have a public property in your ViewModels something to the effect of 'Model' which holds a Csla object?

Kind Regards

**Comment by tsvideo** [comment]
> > @Chicagoan2016 No, It's based on BindableBase from PRISM
> > @jonnybee Info: If i use context.target.PropertyName it works, but not for the ErrorMessages
> 
> I am so glad you mentioned Prism, I have a couple of quick questions.
> 
> 1. Since Prism have Modules, do you use them? I am wondering how should we structure our projects in the solution, Do you have a Shell project and Modules project? please share
> 2. Do have a public property in your ViewModels something to the effect of 'Model' which holds a Csla object?
> 
> Kind Regards

1) Yes, we use Modules and a Shell project with a ModuleCatalog each as Project in one Solution
Our Solution Structure:
Solution
- Folder BusinessLayer
   - Business Assembly 1 (Project)
   - Business Assembly 2 (Project)
- Folder DataLayer
   - DataLayer SQL Server (Project)
   - DataLayer Firebird (Project)
- Folder Modules
   - Modules.Article (Project)
   - Modules.OfferOrder (Project)

2) Yes, in every ViewModel we have a Property 'Model' which is a CSLA Business object and the WPF Xaml is bound to Model.Property

**Comment by Chicagoan2016** [comment]
@tsvideo , thank you Sir.
 In your Folder Business Layer, do you have two Csla based business projects? Business Assembly 1 and Business Assembly 2?
In your Folder Modules, do you have only Views and View Models?

Also why more than one Business Assembly projects?

Kind Regards

**Comment by tsvideo** [comment]
> @tsvideo , thank you Sir.
> In your Folder Business Layer, do you have two Csla based business projects? Business Assembly 1 and Business Assembly 2?
> In your Folder Modules, do you have only Views and View Models?
> 
> Also why more than one Business Assembly projects?
> 
> Kind Regards

Yes, more Business Projects to part new and legacy in the hope to get rid the legacy in some years
Important is that In the Business Layer no UI Code or References exist to run on WCF Service Server
And Yes, in Modules Only Views and View Model.

**Comment by jonnybee** [comment]
So you run the ObjectRules from within a PropertyRule? That pretty much explains the issue as we never planned for that execution path. 

It is the implementation inside BusinessBase that raises PropertyChanged - not the BusinessRules engine itself. 


        protected override void Execute(IRuleContext context)
        {
            var target = (KragarmregalFischer)context.Target;
             
            // you could call CheckObjectRules on the target object 
            // see code from my first reply 
            target.CheckObjectRules();
        }

my recommended solution would rather be to override the CheckPropertyRules method in the BusinessBase: 

    protected virtual void CheckPropertyRules(IPropertyInfo property)
    {
      var propertyNames = BusinessRules.CheckRules(property);
      if (property == ArmlaengeProperty || property == LastschwerpunktProperty 
                 || property == FusslaengeProperty)
      {
          // get affected properties from object rules 
          objectPropertyNames = BusinessRules.CheckObjectRules();
          // add to affected propertyNames from property rules 
          propertyNames = propertyNames.AddRange(objectPropertyNames).Distinct(); 
      }
      // Notify UI about property changed. 
      if (ApplicationContext.PropertyChangedMode == ApplicationContext.PropertyChangedModes.Windows)
        OnPropertyChanged(property);
      else
        foreach (var name in propertyNames)
          OnPropertyChanged(name);
    }

**Comment by jonnybee** [comment]
My preferred solution would probable be to create one PropertyRule and assign that rule to each of the actual InputProperties - rather than having is as an ObjectRule.

**Comment by Chicagoan2016** [comment]
@jonnybee , I don't if the concept of 'chained context' would apply here but I have always used it when I had to call a business rule from inside another business rule.
@tsvideo , if that's the path (Inner rule and chained context) you want to take , Rocky has discussed 
 it in detail in 'Creating business objects' book.
@tsvideo , also I love the fact that at least one other fellow csla developer is using Prism with Csla

Kind Regards

**Comment by jonnybee** [comment]
@Chicagoan2016 'chained context/inner rules' might be applicable here - in fact it might be the easiest way to implement this in the property rule. But we do not know if there are other requirements for still keeping it as both a Object Rule and a Property Rule. An object rule is essentially a PropertyRule where PrimaryProperty is null. 

I would typically have som logic in the outermost rule to select which inner rules to execute or test for som condition, f.ex CanWrite as a gateway rule to check if user is allowed to edit the field before executing a validation rule. 

You should be able to use this rule to wrap an inner object rule: 

    public class CallObjectRule : PropertyRule
    {
      private IBusinessRule InnerRule { get; }
      
      public CallObjectRule(IPropertyInfo primaryProperty, ObjectRule innerRule) : base(primaryProperty)
      {
        InnerRule = innerRule;
        AffectedProperties.AddRange(innerRule.AffectedProperties);
        RuleUri.AddQueryParameter("rule", System.Uri.EscapeUriString(innerRule.RuleName));
        if (true == innerRule.InputProperties?.Any())
        {
          InputProperties = new List<IPropertyInfo>();
          InputProperties.AddRange(innerRule.InputProperties);
        }
      }

      protected override void Execute(IRuleContext context)
      {
        var target = (Csla.Core.BusinessBase)context.Target;
        var chainedContext = context.GetChainedContext(InnerRule);
        InnerRule.Execute(chainedContext);
      }
    }

**Comment by tsvideo** [comment]
@jonnybee Good Morning!
We will discuss and try your suggestions.
Thank You!

**Comment by Chicagoan2016** [comment]
Good morning from the US, @tsvideo please share if it works, very interesting scenario.
@jonnybee, thank you, your business rules knowledge has helped me immensely.
Regards

**Comment by tsvideo** [comment]
After had a lot of Work to change all our CSLA Business Classes (285) from Entity Framework 4 to 6 with changing to a seperate DataLayer i want to Report our Solution to this issue:
For Messages (Errors, Warnings) about broken Rules we have now one Objectrule and for dependent Data manipulation we use for each Propertie a single Rule. This works for us.

**Comment by rockfordlhotka** [comment]
Thank you for the update on your progress and solution.
