### ISSUE TITLE
Blazor Server Side & ApplicationContext

### ISSUE THREAD

**Issue by clodewyks** [MarimerLLC/cslaforum#931]
**Describe the bug**
Currently the ApplicationContext is static within the client. However when running a blazor server side application the static implementation does not work as the user changes after each login.

Scenario 1:

- User 1 (michael) logs in successfully, ApplicationContext.User is set to the Authenticated Principal
- User 2 (chrisjan) visits the site and does not need to login and the current Authenticated Principal is User 1 (michael) 

Scenario 2:

- User 1 (michael) logs in successfully, ApplicationContext.User is set to the Authenticated Principal
- User 2 (chrisjan) was already on the login screen and then logs in, ApplicationContext.User is set to the Authenticated Principal
- User 1 (michael) navigates around and ApplicationContext.User is now User 2 (chrisjan)

After user 1 (michael)  login, before user 2 (chrisjan) login
![image](https://user-images.githubusercontent.com/5906783/79259414-f63dfc00-7e8c-11ea-8347-473d609d06d8.png)

After user 2 (chrisjan) login, ApplicationContext.User changes on user 1 (michael) machine
![image](https://user-images.githubusercontent.com/5906783/79259470-0e158000-7e8d-11ea-9a8f-fc090e493cf8.png)

**Version and Platform**
CSLA version: 5.1.0
OS: Windows and Linux
Platform: Blazor Server Side

**Code that Fails**
![image](https://user-images.githubusercontent.com/5906783/79258936-2e910a80-7e8c-11ea-855d-e9adbdd0d052.png)

or anywhere where Application.Context is used.

I am using a very similar setup to the one in the [BlazorAuthClient](https://github.com/rockfordlhotka/BlazorAuthClient/tree/master/BlazorAuthClient/Client), however the fact that the `CurrentUserService` is Singleton would most likely mean the same problem as Singleton would provide the same instance for all requests?

Am I missing something in the setup or is this a bug?

I can provide a repro if required.

**Comment by rockfordlhotka** [comment]
Did you reference the `Csla.AspnetCore` package as well as `Csla.Blazor`?

It is necessary to reference `Csla.AspnetCore` because that's the package that contains the `ApplicationContext` provider based on `HttpContext`.

**Comment by clodewyks** [comment]
Hi Rocky,

Thank you for the quick response. Even after adding the reference to `Csla.Aspnetcore` the issue persists. 

The below screenshot is as explained in Scenario 2.

![image](https://user-images.githubusercontent.com/5906783/79264159-6308c480-7e94-11ea-9dcc-ae136c8025bc.png)


![image](https://user-images.githubusercontent.com/5906783/79264017-2046ec80-7e94-11ea-8e02-fe5048190087.png)

**Comment by rockfordlhotka** [comment]
And your `Startup.cs` is calling `services.AddCsla();` and `app.UseCsla();` as appropriate?

**Comment by clodewyks** [comment]
That was the ticket!

Thank you very much for the help Rocky. 

![image](https://user-images.githubusercontent.com/5906783/79266108-5df94480-7e97-11ea-8411-012d713c9234.png)
