### ISSUE TITLE
Add virtual to Parent

### ISSUE THREAD

**Issue by Cuiqs76** [MarimerLLC/cslaforum#937]
**
I use a third party control in my blazor webassembly project, the control use newtonsoft to serialize object. after vm.refreshaync(ID), throw a error  Self referencing loop detected for property ‘Parent’ with type ”. Path ‘Descendants[0]’. 
so i down load CSLA code add [JsonIgnore] to Parent. 
the control no privde options as asp.net netcore to config the newtonsoft.
I try to add  ShouldSerializePrarent in the child according to newtonsoft instruction, but no success.  

**Describe the solution you'd like**
change the Parent property to virtual

**Describe alternatives you've considered**
I change the csla code add virtual to Parent, and in my child class to overide it with [JsonIgnore].  and no need add newtonsoft to csla.

**Comment by rockfordlhotka** [comment]
Hi @Cuiqs76 - you should read through the [serialization doc](https://github.com/MarimerLLC/csla/blob/master/docs/JSON-Services.md) in the /docs directory.

Also read about [serializers that do work](https://github.com/MarimerLLC/csla/blob/master/docs/serialization.md).
