### ISSUE TITLE
Blazor Server Side. Authorization not work when deploy on Azure WebSite with SignalR

### ISSUE THREAD

**Issue by RolandoTonin** [MarimerLLC/cslaforum#949]
**Describe the bug**
MyApp.csproj:
.........
<PackageReference Include="Microsoft.Azure.SignalR" Version="1.4.3" />
<PackageReference Include="Csla.AspNetCore" Version="5.2.0-R20050802" />
 <PackageReference Include="Csla.Blazor" Version="5.2.0-R20050802" />
........

Startup.cs:
public void ConfigureServices(IServiceCollection services)
{
...
services.AddSignalR().AddAzureSignalR("Endpoint=https:/..............");
....
}
If I comment above line in IISExpress publish configuration all work fine but if I publish on My Azure WebSite, without SignalR config some Blazor components don't responds and don't works as expected. 
If I remove above comment  in both IISExpress and Azure publish configuration, Csla.ApplicationContext.User.Identity.IsAuthenticated return always false even I force it to claim principal (login page) and consequently all <AuthorizeView Policy="@(CslaPolicy.GetPolicy(......) are always <NotAuthorized>.

**Version and Platform**
CSLA version: 5.2.0-R20050802
OS: Windows
Platform: Blazor Server Side on Azure Web Site

**Comment by rockfordlhotka** [comment]
This sounds like a Blazor issue, not a CSLA issue.

Server-side Blazor sets up its own SignalR circuit to manage communication between the browser and the server. My guess is that you need to do something special to set up your own SignalR to keep it separate from what Blazor does automatically.

I suggest asking in a Blazor forum, or in the Blazor gitter channel.

**Comment by RolandoTonin** [comment]
Thanks Rocky,
I have removed nuget SignalR reference and deployed the App on Azure web site and it all seems to work ...
