### ISSUE TITLE
How to update an ObservableCollection after editing child name 

### ISSUE THREAD

**Issue by coolgrim** [MarimerLLC/cslaforum#95]
Hello,
I have a scenario very close to the ProjectTracker sample project (ProjectEdit / ProjectResourceEdit scenario): 
A root object 
- contains an observable collection 
  - which contains child objects

When you add/delete a child to/from the observable collection, the root's list is updated and displayed accordingly (via OnModelChanged and OnPropertyChanged("observableCollection") in the view model). Everything is fine.

But when I edit the name of a collection child object (committing via Model.ApplyEdit()) the list of the root object still displays the old child's name.

In the collection object I can see that the new child's name is available (via  EditChildComplete). Nevertheless it seems that the collection does not "inform" its parent that the child's name has been changed. The collection should somehow tell it's parent root object that it has been changed. My solution in the root object looks like this:
OnPropertyChanged("observableCollection"); // updates the list of the root object
CanCancel = true; // on the root object for un-do button
CanSave = true; // on the root object for save button

But I wonder if there is a smarter / natural / standard way of doing this?

**Comment by rockfordlhotka** [comment]
Look at the ChildChanged event in the root.

**Comment by coolgrim** [comment]
The OnChildChanged in the root only executes when an item is added to or removed from the list (of type BusinessListBase), but not when the name of an existing child item has been edited.

This is the property definition in the root: 
public static readonly PropertyInfo<ProductSteps> StepsProperty = RegisterProperty<ProductSteps>(p => p.Steps);
        public ProductSteps Steps
        {  get  {
                if (!(FieldManager.FieldExists(StepsProperty)))
                    LoadProperty(StepsProperty, DataPortal.CreateChild<ProductSteps>());
                return GetProperty(StepsProperty);  }
            private set { LoadProperty(StepsProperty, value); }
        }

**Comment by rockfordlhotka** [comment]
That shouldn't be the case. The `ChildChanged` event cascades up through the object graph for every change within the graph. The event _looks different_ based on whether the change is due to a child object or a collection (the event args are different).

**Comment by coolgrim** [comment]
Strange that calling CancelEdit() on the child cascaded as expected, but ApplyEdit() did not.
And after hours and hours of debugging I found my error: the property in the child was set via LoadProperty(), after changing it to SetProperty() everything is fine now. Sorry, my fault. 
Thanks for your support and by the way: great framework, it's absolutely awesome!
